### ISSUE TITLE
Conside moving fatigue states above tabbed section

### ISSUE THREAD

**Issue by Lazytron** [sdenec/tidy5e-sheet#1]
Fatigue state feels like it is core character state information similar to HP and resources, and should be above the fold.

**Comment by sdenec** [comment]
Could you specify what you mean "obove the fold"? I feel exhaustion is a condition rarely used and as such can live at the bottom of the attributes tab. To put it in the header for example would be too space demanding. Anywhere between might be a bit of an inconvenience with the hover note.

**Comment by sdenec** [comment]
Thanks for your input. I found a solution to pull the exhaution bar to the top an still get it out of the way - in a positive way I think :)
