### ISSUE TITLE
Spell/Feature Line Spacing in Expanded View

### ISSUE THREAD

**Issue by DivertedCircle** [sdenec/tidy5e-sheet#102]
Line spacing when editing the Description of a spell/feature is not reflected in the expanded view on the character sheet. This make it harder to read because there isn't a distinct break between paragraphs. The first screenshot, in the spell editor, shows a distinct break between the two paragraphs. The second screenshot of the expended spell shows no such break.

![image](https://user-images.githubusercontent.com/26470570/94608514-bc09c080-025a-11eb-964a-af631bdcf78e.png)
![image](https://user-images.githubusercontent.com/26470570/94608600-d9d72580-025a-11eb-963a-0faaa961aff9.png)

**Comment by sdenec** [comment]
Should be fixed now!

**Comment by DivertedCircle** [comment]
Not sure if it was this change or something different but while the spacing now displays properly, the text color has changed to a light grey that is hard to read.
![image](https://user-images.githubusercontent.com/26470570/95491749-4aff9280-0957-11eb-82ed-3f287cb6ae29.png)

**Comment by sdenec** [comment]
That actually is either a css bug or strange styling decision made by Atropos in the 0.97 update. It is also visible in the default sheet. Non the less I can change it back in the next update.

**Comment by sdenec** [comment]
color should be back to normal at least for the tidy5e sheet. The core sheet still has this error until it gets fixed by atropos.
