### ISSUE TITLE
Text box for editing Background/Biography is not full size

### ISSUE THREAD

**Issue by feltz916** [sdenec/tidy5e-sheet#106]
This bug started with dnd5e 0.98, when they added traits/ideals/bonds/flaws to the biography tab.

Tindy5e sheet has a problem with the background / biography field when in edit mode, in that the edit field is not the full size of the window, making it very hard for edits. You are only able to see one line at a time.

![bug1](https://user-images.githubusercontent.com/7417818/95771145-688e6e00-0c6f-11eb-9556-d1b3e4b409cf.PNG) ![bug2](https://user-images.githubusercontent.com/7417818/95771149-6b895e80-0c6f-11eb-80a0-17336cd3dafb.PNG)

**Comment by sdenec** [comment]
ah, what a timing. Just fixed this!
