### ISSUE TITLE
Issue: Alternative Dark Sheet Text 

### ISSUE THREAD

**Issue by Matsozetex** [sdenec/tidy5e-sheet#108]
Foundry Version: 0.6.6
5e Version: 0.98
Tidy5e Sheet version: 0.2.27

Issue: The text on the alternative dark mode for both characters sheets and NPC sheets is black vs the previous white on earlier versions on the 5e game system, which is extremely hard to read on the dark grey background. The attributes menu seems to be unaffected but inventory, features, spellbook are affected by the issue.

How to Produce: Enable alternative dark mode via module settings.

**Comment by sdenec** [comment]
thanks for bringing this to my attention. should be fixed now!
