### ISSUE TITLE
Unable to change actor name from Tidy5e sheet

### ISSUE THREAD

**Issue by feltz916** [sdenec/tidy5e-sheet#114]
Attempting to save the new name gives an assert failed error:
Assertion failed: Input argument is not an HTMLInputElement

Switching to default character sheet allows it to work fine.

Foundry version 0.7.5
dnd5e version 0.98
tidy5e-sheet version 0.2.28

**Comment by sdenec** [comment]
Sorry, I can not replicate this. Changing names of PCs and NPCs works fine with Tidy5e and your posted version numbers.

**Comment by feltz916** [comment]
reloaded world, and i cannot reproduce anymore. Not sure what was wrong! thanks.
