### ISSUE TITLE
Update for 0.7.5?

### ISSUE THREAD

**Issue by Malmageddon** [sdenec/tidy5e-sheet#116]
Hi, great work so far. It seems the player character sheets are not working with the new Foundry 0.7.5 update. It's quite a big update and is pretty stable with most other modules. Any plans on updating for compatibility with 0.7.5?

**Comment by akrigline** [comment]
Tidy5e should be working in 0.7.5, what issues exactly are you seeing @Malmageddon? Also, verify that you don't have any modules which aren't marked compatible with 0.7.5 activated as they may be causing issues.

**Comment by sdenec** [comment]
Tidy5e works fine with the 0.7.x updates. If you experience any issues try to disable other modules first. Also I have the suspicion that Forge users may have general troubles with opening character sheets - if that is your issue aswell try to contact your foundry hoster.

**Comment by sdenec** [comment]
Any insights regarding you problems?
