### ISSUE TITLE
Show attack bonus and damage dice on weapons and attacks.

### ISSUE THREAD

**Issue by DipsoNOR** [sdenec/tidy5e-sheet#118]
When making quick decisions in combat i find it very useful to see what bonus i get to attack roll and what the damage roll is going to be. (see how it's displayed in dnd beyond for instance)

Would love an option to show this directly in the sheet instead of having to open the item sheet.

**Comment by sdenec** [comment]
I'd like to recommend the module Dice Tooltip. Should do what you want :) https://github.com/SteffanPoulsen/dice-tooltip
