### ISSUE TITLE
Equipped toggle is not properly displaying

### ISSUE THREAD

**Issue by Avitale34** [sdenec/tidy5e-sheet#119]
If I go into the details of an item and equipped it the toggle on the sheet does not change. Click on the sheet to equipped and unequppied is unreliable sometimes it works.

**Comment by sdenec** [comment]
Hi, that seems strange as the toggle state is directly related to the item data. If it has the "equipped" state the toggle can't be "unequipped" and vice versa. Furthermore I can't reproduce this issue. Have you tried disabling other modules, maybe there is a conflict.

**Comment by sdenec** [comment]
I won't lie, I thought this was impossible as the equipped state is directly related to the item but you are indeed right. I could reproduce this though the code is exaclty as before. Therefore i completely deactivated the module, did a refresh, reactivated the module and now I can't reproduce the issue. Would you be so kind an try that?

**Comment by sdenec** [comment]
Also this does only seem to happen with equipment. weapons worked fine. And since 0.98 it seems other item types no longer have the ability to be equipped from the item details, or lack a details tab altoghether (this is also true for core).
