### ISSUE TITLE
[Bug?] Roll Hit Dice - TypeError

### ISSUE THREAD

**Issue by Ghardyne** [sdenec/tidy5e-sheet#12]
Roll Hit Dice +@bonus in the roll formula comes up with an error message:

TypeError: Cannot read property "value" of undefined

![03j0Rcv](https://user-images.githubusercontent.com/66368456/83637979-b9e36e00-a5a8-11ea-80fb-2b32bfe051fa.png)

The error message appears with or without boni added in the "Situational Bonus?" field.

**Comment by sdenec** [comment]
Sorry, can not confirm the bug. I can roll Hit Dice fine with any added bonus. Also I didn't change any roll formulas, just changed the css of the sheet. Maybe another plugin? Did you try with the default sheet?

**Comment by Ghardyne** [comment]
The error comes with any sheet, could be a problem with how vtta imports characters. Gonna try it with a character that didn´t get imported

**Comment by Ghardyne** [comment]
Can be closed, was a glitch with the initial 0.6.1 version. A force update using the beta channel fixed my problem.
