### ISSUE TITLE
Request: Movable Favorites, or a Favorite Favorites section

### ISSUE THREAD

**Issue by ZBell** [sdenec/tidy5e-sheet#120]
Hello, I've been using TidySheet for some time now and think it's pretty great!  I had a thought regarding the Favorite section and was wondering if it might be possible.  Is there any way to add the ability to move the favorite categories around?  In case someone has lot of inventory items favorited, but they'd prefer to have easier access to their spells?

In a similar vein, would it be possible to have a more generic Favorite favorite sections that could have inventory items, feats, or spells all side by side in the same category?  This would be at the top of the favorites section, and I guess you'd probably just drag the favorites you want in there.  Not sure if this one is even possible, or any iteration of it.  Anyway, just wanted to suggest some stuff, thank you for all your hard work!

**Comment by sdenec** [comment]
Hi, happy to hear you like the sheet. Regarding your suggestions: I merely copied the favorites function from the original module and changed what I was comfortable with. Your wishes are an extensive change in the code, in a way I am not comfortable doing, skill wise and demand wise. So I'm very sorry but at this moment I won't do any further customization to the sheet. I still hope you find it useful, even without these features and that it will be of great use for your future games :)

**Comment by ZBell** [comment]
No problem, just thought it couldn't hurt to suggest!  It's still excellent and I'll definitely be using it going forward.
