### ISSUE TITLE
Can't read features text using the sheet with Alternate Dark Mode.

### ISSUE THREAD

**Issue by Sildamet** [sdenec/tidy5e-sheet#127]
Using Foundry 0.7.6, dnd 5e 0.99. When importing a class using Plutonium, the features get very hard to read on Alternate Dark Mode.

![image](https://user-images.githubusercontent.com/74163724/98493278-d26f4880-2218-11eb-9637-041434e966af.png)

**Comment by akrigline** [comment]
Does this happen with manually created items? Because if manually created items are fine, that module is to blame (and you should not be mentioning that module outside of its own dark little corner anyway)

**Comment by sdenec** [comment]
No, seems to be all item descriptions reverted back to black text somehow. I'll see that it gets fixed!

**Comment by Sildamet** [comment]
Apologies. I did not mean to offend. I was just trying to provide as much information as possible on the issue (exactly for the reason you mentioned - could be the *other* mod doing weird things).Thank you for your attention, reply and the time you invest in making the Tidy Sheet. :)Enviado do meu Samsung Mobile da Claro
-------- Original message --------From: Andrew Krigline <notifications@github.com> Date: 09/11/2020  11:30  (GMT-03:00) To: sdenec/tidy5e-sheet <tidy5e-sheet@noreply.github.com> Cc: Sildamet <sildamet@gmail.com>, Author <author@noreply.github.com> Subject: Re: [sdenec/tidy5e-sheet] Can't read features text using the sheet with Alternate Dark Mode. (#127) 
Does this happen with manually created items? Because if manually created items are fine, that module is to blame (and you should not be mentioning that module outside of its own dark little corner anyway)

**Comment by sdenec** [comment]
should be fixed now!
