### ISSUE TITLE
Style Settings

### ISSUE THREAD

**Issue by mstiller7** [sdenec/tidy5e-sheet#13]
Hey! Thanks for your work, it brings a good option to the (virtual) table.
One of my players likes the layout of the tidy sheet styling, but has asked about the possibility of alternate styling for some of the features so that it could better reflect their own preferences. Would you consider adding settings to toggle the styling of the following features?

- Font style in general; their comment on the rounded font of the tidy sheet is that it feels too modern.
- Shaded section backgrounds of the Biography and Journal sheet sections. My player prefers the absence of these shaded sections, which also contribute to the more modern feel.
- The icons that surround and partially obscure the character portrait. Is there perhaps another sheet location these could be presented?

Essentially they would like to have the presentation/functionality of the tidy styling, but also retain the 'weathered aesthetic' of the default Foundry styling.

**Comment by sdenec** [comment]
I'm happy you like the sheet but sadly I can't offer any costumization regarding your requests - BUT there might be already an option to at least partly achive what you are looking for:
Regarding the portrait icons - I consciously chose to put them there but also in the last update added an option to hide them until you hover over the portrait. Have a look in the Module Settings, you can toggle each icon on its own on a per player basis.
Regarding Biography/Journal backgrounds: Install the custom css module and add the following rule that will remove the dark backgrounds.

.tidy5e .tidy5e-sheet .note-entries article {background: none;}

Regarding the font: It is the same font used in the original sheet but a little less heavy on the Old-Style font. If you want to get a little bit of this font back you can add a few more rules to the custom css module:

.tidy5e.sheet.actor .tidy5e-sheet .inventory-list .inventory-header h3 {font-family: "Nodesto"; font-size:18px;font-weight:normal}

.tidy5e.sheet.actor .tidy5e-sheet .note-entries article .section-titles {font-family: "Nodesto"; font-size:18px;font-weight:normal}

.tidy5e.sheet.actor .tidy5e-sheet .note-entries article .section-titles input {font-weight:normal}

This will change the Headlines for items, spells and biography/journals.
That's all I can offer, hope it caters to your friends needs!

**Comment by mstiller7** [comment]
That's super great for now, thank you! I'll hope it suffices.
