### ISSUE TITLE
Suggestion: Attuned items count

### ISSUE THREAD

**Issue by ariakas2008** [sdenec/tidy5e-sheet#130]
Just my 2 cent suggestion: add a counter for the number of attuned items to the sheet (inventory tab? Favourite tab?)

**Comment by crymic-linith** [comment]
It should be adjustable in case of Artificer boost.

**Comment by sdenec** [comment]
You are not forgotten :) Thank you for your input guys. I'll put it on my list!

**Comment by sdenec** [comment]
it is now integrated into the latest update
