### ISSUE TITLE
Add Option to disable Wheel-Event on Inputs

### ISSUE THREAD

**Issue by Hydroxi** [sdenec/tidy5e-sheet#139]
Hi,
at first I thought this was a problem with default Foundry. 
My players very often have the problem that they accidentally change the stats or spellslots with the mouse wheel.

Could you add an option to disable the wheel event on the number input fields?

**Comment by sdenec** [comment]
That is neither a core nor a tidy feature. Do you use MESS? The module has a scroll numbers setting.

**Comment by Hydroxi** [comment]
Oh my god thank you! Damn I thought it was a browser feature that needs to be explicitly disabled.
