### ISSUE TITLE
Inspiration button affects first char sheet opened if multiple are open

### ISSUE THREAD

**Issue by RulyTafzil** [sdenec/tidy5e-sheet#14]
If you open multiple character sheets, then click on the "inspiration" button, it will affect the first sheet that was opened, regardless of which sheet you are clicking on. 

For example.

Open sheet for Billy the bard.
Open sheet for Sarah the sorcerror.
Click on inspiration button for Sarah. 
Billy gets inspiration.

**Comment by sdenec** [comment]
Thanks for pointing that out! Investigating the issue lead to a few more fields that were affecting the first opened actor sheet. Should be fixed in the current version!
