### ISSUE TITLE
Delete Disabled/Enabled missing from the Effects tab

### ISSUE THREAD

**Issue by InnilToo** [sdenec/tidy5e-sheet#142]
The **Delete Disabled/Enabled** button is missing from the Effects tab. IT would be a very helpful addition so players can't delete an effect by accident.

Tidy5e Sheet version 0.3.4
Foundry version 0.7.7
DnD 5e version 1.1.1

**Comment by sdenec** [comment]
Sorry for the late reply. The suggestion is noted and will find its way into the sheet at a later point in time! Tahk you for your patience

**Comment by sdenec** [comment]
It is integrated into the latest update
