### ISSUE TITLE
Modifing HP from token menu sometimes sets it to zero.

### ISSUE THREAD

**Issue by ExileofBrokenSky** [sdenec/tidy5e-sheet#143]
See the animated gif for an explanation much better than words could provide.
TidySheet5e is the only mod active and the error does not occur without it.

![tidysheeterror](https://user-images.githubusercontent.com/28786777/99994384-ee312d80-2d86-11eb-98d6-2cff197359e9.gif)

**Comment by sdenec** [comment]
Thanks for the detailed bug report. The just pushed update should fix the issue :)
