### ISSUE TITLE
Minor Dark Mode issue

### ISSUE THREAD

**Issue by saethone** [sdenec/tidy5e-sheet#145]
On dark mode, while editing Active Effects, the text is dark grey on dark grey, making it impossible to read the name of the effect

![image](https://user-images.githubusercontent.com/13894683/100497001-3a30f900-311e-11eb-9528-3f582b6ebe6d.png)

here's the relevant code and the source of the color setting

![image](https://user-images.githubusercontent.com/13894683/100497013-52087d00-311e-11eb-9a3e-a38d0a570deb.png)

I'm not aware of anywhere else that uses that color on the darkmode sheet so it can probably just be overridden with the same selector

**Comment by sdenec** [comment]
sorry for the long wait. will be fixed in the shortly released update.
