### ISSUE TITLE
Feature Request: Show quantity all the time (Possible Option)

### ISSUE THREAD

**Issue by megahead11** [sdenec/tidy5e-sheet#146]
Because better rolls handles consumable logic different in a way that makes BR usable with Midi Qol and DAE, sometimes it is necessary to keep the items on the sheet with a quantity of 0.
However, at the moment, the CSS hides the quantity at all times if it is not above 1. 
Because of this, it is impossible to tell if an item has a quantity of 1 or 0. 
It would be nice if there was an option to always show the quantity in these cases, in the same way the vanilla sheet shows quantity at all times (possibly as a GM option to save my players trouble or enabled by default).

**Comment by sdenec** [comment]
Sorry for the late reply! Your suggestion is noted. So just to clarify: You want quantity to always be visible (not just on hover) even if the quantity is 1 or 0? I just checked the default Sheet. Quantity of 1 is hidden, but 0 is visible. So would it be viable to also just show 1 on hover but keep 0 visible like numbers above 1?

**Comment by megahead11** [comment]
Yeah, that would more or less work! 
Not being able to see 0 quantity items can be a bit strange, it doesn't always happen but there are instances (like with betterrolls 5e) where it needs to be set to 0 and not destroyed from the sheet.

**Comment by sdenec** [comment]
Alright, I'll see what I can do - maybe default behavior but as suggested also an option to always show quantity not matter if 0, 1 or more :)

**Comment by sdenec** [comment]
It is integrated into the latest update :)
