### ISSUE TITLE
Buttons added to items by midi qol not rendering

### ISSUE THREAD

**Issue by dstein766** [sdenec/tidy5e-sheet#147]
FVTT 0.7.8
dnd5E 1.1.1
midiqol 0.3.33
Tidy5e Sheet 0.3.5

1. Configure midiqol settings: "Add attack/damage buttons to item inventory list" should be CHECKED.
2. Open character sheet, navigate to Inventory tab, and open up any random weapon (frankly, ANY item...but using a weapon for this example).

**Expected**: In addition to the boxed attribute tags (such as "Martial melee" and/or "Equipped" and/or etc...), I SHOULD also have buttons added by midiqol such as "Standard Roll", "Attack", "Damage", and "Info".  
**Actual**:  Currently, I do not see these.  Switching to any other character sheet (core default, Sky's Alternate, OGL5E Character Sheet, etc - have checked 5 others) and the buttons DO display as expected.

Worked in prior versions of Tidy5e, but do not know exactly when it broke...but broke NO EARLIER THAN the release date of midiqol 3.26 (which has a commit date of Nov 17 over on tposney's github).  I had reason to specifically confirm it worked at the time midiqol 0.3.26 released and all was good at that time.

**Comment by sdenec** [comment]
I can not confirm this. I'm seeing the buttons fine

**Comment by sdenec** [comment]
![working](https://user-images.githubusercontent.com/8881200/101276765-78c65380-37af-11eb-9289-3cbcdd3c0b62.jpg)

**Comment by sdenec** [comment]
![Uploading midiqol-settings.jpg…]()

**Comment by dstein766** [comment]
_I'm submitting this now while I've got the screencaps handy, but am then going to simply do a full system reboot to see if the problem persists.  Will edit this report in a few minutes if necessary._

Thanks for the quick verificiation.  Very strange, however.  My test config is literally just the module list shown in comment 1 (i.e. 2 modules enabled), and this problem persists following a server restart.  I used TidyUI to turn off EVERYTHING, then also turned off TidyUI before enabling ONLY midiqol + Tidy5e Sheet.        

Tried creating a new dummy PC and dragged a weapon over to it - same thing, so not tied to new PC vs old PC.  Tried deinstalling/reinstalling Tidy5E Sheet - same thing.  Any suggestions on anything else I might try on my side?  _(I note that de-install/re-install didn't appear to reset the Tidy5E config settings.  I turned on Dark Mode just prior to deinstall just to confirm and see that following re-install it didn't go back to the default of NOT Dark Mode.  Is there anything I could try on my side that more aggressively wipes all traces of Tidy5E on de-install before I once again re-install?  Or is there any CSS file and/or any transient file I can look at during runtime where I can see whether the proper settings for rendering the buttons are/aren't present?)_ 

I have seen a few strange errors in the console when trying to troubleshoot.  They sadly are NOT 100% consistent - and I have serious doubts they are related to the issue since I'd otherwise expect them to show up consistently - but they show up enough while working in the character sheet that I've quoted them here.  In general, they appear to be triggered by hitting the "I"nfo button next to an item...but it is also possible that these are unrelated messages belonging to some background process that just happen to show up when I'm looking.

![image](https://user-images.githubusercontent.com/24942951/101287098-1cf5cd80-37a3-11eb-9ce3-f995df41e933.png)
![image](https://user-images.githubusercontent.com/24942951/101287139-4282d700-37a3-11eb-804a-7d83dde4c961.png)

Finally, I'll note that during this AM's testing I have had two tests (steps unpredictable/unrepeatable, so far) involving some combo of switching to Default sheet, switching back to Tidy, and then some add'l random button mashing involving opening the Prototype Token dialog but doing nothing that resulted in Tidy showing the buttons again...but it didn't persist.  Have tried to find a sequence of actions with a consistent positive outcome but failed so far.  So clearly the capability is still present on my side, too....but somehow being blocked.

**Comment by dstein766** [comment]
OK - post reboot and still no joy...but also think I've got some kind of weird low-level corruption in my install.  Realized I should try testing in a new world...and getting strange console errors when clicking button to create world.  Also having troubles launching my non-default worlds.  So think I have a bigger issue here.  **My questions re: steps to COMPLETELY wipe prior traces of Tidy5E and/or files related to Tidy's rendering still of interest purely out of curiousity..but I believe that at this time Tidy5E is likely innocent of all charges** :-)

**Comment by sdenec** [comment]
Tidy sets a few custom flags for actors - e. g. when switching to dark mode - that will stay with the actor and in consequence will be active upon reinstalling the module. but that should in no way be the cause why the buttons don't show up. All your posted warnings to not refer directly to tidy but the core scripts for characters. So I'm clueless as to what the actual problem ist. Sorry. And since no one else has repoted any issues with this I do think it has to do something with your files. Ih have two independent servers running and both display better roll and midiqol buttons fine ...

**Comment by dstein766** [comment]
Understood.  Frustrating, but I'm clearly dealing with some weird edge case here and I guess for now the only thing to do would be to close the issue.  If I'm able to make any headway I'll re-open if appropriate.  

------ Original Message ------

**Comment by dstein766** [comment]
Hey - I just figured it out!

I had to make a manual change to your code, which seems to be referencing the wrong CSS element names.  In tidy5e-modules.css:

/* ------------------------------------ */
/*   Support Better Rolls / Minor QOL   */
/* ------------------------------------ */

.tidy5e.sheet.actor .items-list .item-summary .item-buttons {
    margin: 8px 0;
}

.tidy5e.sheet.actor .items-list .item-summary .item-buttons .tag {
    border: none;
    margin: 2px 4px 2px 0;
}

.tidy5e.sheet.actor .items-list .item-summary .item-buttons .tag button {
    border: 1px solid rgba(0,0,0,.2);
    background: rgba(0,0,0,.4);
    color: rgba(255,255,255,.8);
    padding: .25rem .5rem;
    box-shadow: none;
    cursor: pointer;
}

.tidy5e.sheet.actor .items-list .item-summary .item-buttons .tag button:hover {
    background: rgba(0,0,0,.6);
}


All of these are currently listed as ".item-summary".  I changed all 4 references of .item-summary to .item-properties based on how they appeared to be constructed in midi-qol/module/sheetQOL.js and now it works fine.  

I am NOT (stress on NOT) knowledgeable about CSS, so my steps are purely brute force and best guesses.  I have no idea if this is the entirety of what needs to be fixed, but so far working again for me.

------ Original Message ------

**Comment by dstein766** [comment]
Well, s#!&$@!!   It worked....until it didn't.  PC #1's sheet looked great after the above change, then I closed it and re-opened and again missing.  For reasons that escape me every other character sheet is rendering the midiqol stuff OK except for tidy. 

FROM OTHER CHARACTER SHEETS
===========================
<div class="item-properties">
    <div class="item-buttons">
        <span class="tag"><button data-action="basicRoll">Standard Roll</button></span>
        <span class="tag"><button data-action="attack">Attack</button></span>
		<span class="tag"><button data-action="damage">Damage</button></span>
		<span class="tag"><button data-action="info">Info</button></span>
		<br>
		<header style="margin-top:6px"></header>
	</div>
	<span class="tag">Martial Melee</span>
	<span class="tag">Equipped</span>
	<span class="tag">Proficient</span>
	<span class="tag">1 Action</span>
	<span class="tag">Feet</span>
</div>
	
	
FROM TIDY5E
===========================
<div class="item-properties">
	<span class="tag">Martial Melee</span>
	<span class="tag">Equipped</span>
	<span class="tag">Proficient</span>
	<span class="tag">1 Action</span>
	<span class="tag">Feet</span>
</div>
