### ISSUE TITLE
Feature Request: Show To Hit/DC/Damage on weapons and spells.

### ISSUE THREAD

**Issue by cs96and** [sdenec/tidy5e-sheet#148]
It would be nice if the row for a weapon or spell showed a summary of the To Hit/Save DC and damage.  The Compact DndBeyond 5e Sheet does this, an example screenshot is below.  It would also be nice if you showed the actual bonuses though instead of just "@mod".

![Compact DndBeyond 5e Sheet](https://raw.githubusercontent.com/ElfFriend-DnD/foundryvtt-compactBeyond5eSheet/master/readme-img/main-view.png)

**Comment by cs96and** [comment]
If it's too much to squeeze into a row, maybe you could just add it along side the other information in the expanded view?
![image](https://user-images.githubusercontent.com/898086/101338326-ba6d0200-3874-11eb-85eb-11e4f4ce42ee.png)

**Comment by akrigline** [comment]
I'm not 100% (haven't had a chance to look and make sure) but I think `item.getRollData()` will spit out a bunch of useful things that will make this easier to do than how I did it on my side (I believe it will fix the @mod thing). If you want, I can add this to my backlog and open a PR if you don't get to this first @sdenec .

**Comment by sdenec** [comment]
I took a look at "dice tooltip - dnd5e". That mod does all of this as a tooltip. It seems quite complicated to extract the exact attack roll and dmg roll data.

**Comment by cs96and** [comment]
I tried that module recently but it hasn't been updated in a while and was behaving strangely.

**Comment by akrigline** [comment]
This actually got more difficult in the 1.2.0 dnd5e version (my own sheets are still broken as I reevaluate how to do this).

**Comment by akrigline** [comment]
In 1.2.next as of right now, a new Item `label.toHit` will be present on items with attacks which will at least allow the To Hit bonus to more easily be displayed for items with attacks.

**Comment by cs96and** [comment]
It looks like some work is being done on the core foundry sheet for this

https://gitlab.com/foundrynet/dnd5e/-/issues/563
https://gitlab.com/foundrynet/dnd5e/-/issues/937

**Comment by sdenec** [comment]
great news! I'm a bit worried though regarding the "additional columns" thing. the default sheet and tidy is already pretty crowded and 2 more columns won't make it better. So if these values will become available I'll propably opt for an icon with a hover label so it's a) preserving some space and b) is uniform for items and spells. It wouldn't be instantly visible but just a mouse move away, not even a click.

**Comment by sdenec** [comment]
This is now partly solved with the character actions list that has Hit/DC and damage listed. While most likely not a perfect solution it should work for now. Though the future might bring further changes/optimisation in that regard to the sheet.
