### ISSUE TITLE
GM and Player View Disparity

### ISSUE THREAD

**Issue by Tarcion** [sdenec/tidy5e-sheet#150]
With tidysheet installed, I am able to view the sheets and configure settings fine. However, when my players view their sheets, it shows tidysheet but with none of the selected settings in use. This seems to happen regardless of other modules installed.

Configuration
![image](https://user-images.githubusercontent.com/29694463/101831789-74c66880-3b04-11eb-8d9e-c2ab251c63e7.png)
GM View
![image](https://user-images.githubusercontent.com/29694463/101831836-8445b180-3b04-11eb-9525-3bc30ecc840a.png)
Player View
![image](https://user-images.githubusercontent.com/29694463/101831917-9e7f8f80-3b04-11eb-8f41-b79a2a391ab9.png)

**Comment by sdenec** [comment]
That is easily explained but poorly worded on my part. Display settings like Darkmode, section placement and visibility of portrait buttons is a per user setting. I want to rework the already extensive settings into a better structure to show what is a global setting and what's per user. If your players prefer one over another setting they can set those in their sheet setting (and will only see what they can change for their sheet). Sorry for the confusion.

**Comment by Tarcion** [comment]
Ah, fantastic! I figured I just had to be missing something. Thank you for the quick response!
