### ISSUE TITLE
Error throw when trying to open up a character sheet

### ISSUE THREAD

**Issue by Rawrly85** [sdenec/tidy5e-sheet#156]
Foundry Version: 0.7.7
Tidy Sheet: 0.3.6

Getting the error when I'm trying to open tokens:
<img width="957" alt="Screen Shot 2020-12-11 at 3 19 53 PM" src="https://user-images.githubusercontent.com/53245027/101963845-9e46c900-3bc4-11eb-8f11-7ee0764b5f25.png">

**Comment by akrigline** [comment]
Hey @Rawrly85 can you try uninstalling tidy5e sheet and reinstalling?

**Comment by sdenec** [comment]
I can't confirm the issue. The mentioned helper was added to the sheets javascript file and gets called as expected. I would likte to suggest a new installation as well. Maybe update to 0.7.8, though that should not be the cause of this.

**Comment by Mist-Hunter** [comment]
Getting the same fault.
FVTT 0.7.8
DnD5e **v1.20**
Active Modules:
tidy5e-sheet--v0.3.6;
tidy-ui_game-settings--v0.1.21;

For me this started this morning when I updated to 5e v1.20
https://gitlab.com/foundrynet/dnd5e/-/releases

Thanks for your awesome modules, they are so clean, easy to use and well supported!

**Comment by Mist-Hunter** [comment]
This seemed to have resolved itself

![image](https://user-images.githubusercontent.com/6420684/101990013-021ad180-3c59-11eb-8d80-488dea177e4b.png)

The message above took far longer to pop up than normal (10+ minutes).
I can verify your module is working fine with all the same version in my prior post. Sorry for jumping the gun :)

**Comment by sdenec** [comment]
Happy to hear it works!
