### ISSUE TITLE
With new DnD5e 1.2.0 attunement change, the sheet seem to register attuned items incorrectly.

### ISSUE THREAD

**Issue by intemptesta** [sdenec/tidy5e-sheet#158]
Foundry 0.7.7
DnD5e 1.2.0
Tidy5e Sheet 0.3.6

I have an item that attuned while in DnD5e 1.1.1. After I update to 1.2.0 the attunement system changed, the attuned state stuck to the item and shown on Tidy5e Sheet.
The item will be highlighted as attuned even if I change it to 'no attunement required'. The fix is to re-create the item again in 1.2.0 and the problem is gone.

However new magic item created within DnD5e 1.2.0 will be highlighted in inventory when attuned, but not in the favorite.

**Comment by sdenec** [comment]
The attunement display should be fixed in the inventory. Favorite items at the moment aren't able to show the attuned state. Will work on that for a later update.
