### ISSUE TITLE
Unable to configure Movement Speed

### ISSUE THREAD

**Issue by SlippyTheToad** [sdenec/tidy5e-sheet#161]
When using Tidy5e Sheet version 0.3.7 you are unable to modify movement speed. When clicking on the gear icon no new windows pop up. This issue currently exists on Foundry release 0.7.8.

**Comment by sdenec** [comment]
It does work. Do you run dnd5e 1.2.0?

**Comment by SlippyTheToad** [comment]
> It does work. Do you run dnd5e 1.2.0?

It turns out I had been running 1.1.1 and didn't see there had been an update. I can confirm that it does work after updating the ruleset module. Thank you so much for pointing that out.
