### ISSUE TITLE
Suggestion: Redesign the "Toggle Effect" button to switch between a Cancel symbol (for inactivate) and a Checkmark (for activate)

### ISSUE THREAD

**Issue by eikgren** [sdenec/tidy5e-sheet#162]
The [1.2.0 release of Foundry VTT 5th Edition](https://gitlab.com/foundrynet/dnd5e/-/releases#release-1.2.0) included:
> - Redesign the "Toggle Effect" button for an Active Effect to switch between a Cancel symbol (for inactivate) and a Checkmark (For activate).

Which was addressing [this suggestion](https://gitlab.com/foundrynet/dnd5e/-/issues/807). As a result of that, the "Toggle Effect" buttons now look like this in the default sheet:
![image](https://user-images.githubusercontent.com/59783644/102781707-0ac58300-4390-11eb-8a94-3f3fb55598c8.png)

By contrast, the Tidy sheet uses a single icon for both:
![image](https://user-images.githubusercontent.com/59783644/102782124-bc64b400-4390-11eb-8a8b-b084b61fd522.png)

Would you please consider updating the Tidy sheet to similarly use two icons?

If you would prefer to keep one icon, a suitable middle-ground might be to colour the icon differently for active effects.

Thanks!

**Comment by sdenec** [comment]
Good point - I hadn't noticed the change! It will find its way in one of the next updates. Thanks for the hint :)

**Comment by sdenec** [comment]
implemented with the recent update!
