### ISSUE TITLE
feature request. add a lock button for active effects. 

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [sdenec/tidy5e-sheet#163]
please add a lock button for active effects. so that players cannot delete active effects that are built directly onto the effects tab of a a characters sheet.

**Comment by sdenec** [comment]
Hi. Just to clarify: Do you want to prevent Players from editing effects altogether or just have a safety measure that players can turn on/off to prevent accidential effect tempering?

**Comment by ThingsCouldGetDicey** [comment]
well i had the player error of accidentally deleting effects ive programmed mid game. id like the delete button removed for players but visible for gms.  or id like the way you do it with items on the active effects. with a delete disabled button. so they have to ask me first before they delete something.

**Comment by ThingsCouldGetDicey** [comment]
is there any news on this?

**Comment by sdenec** [comment]
Just a little more patience. I have a big upcoming update - if everything works out I'll release it tomorrow :)

**Comment by ThingsCouldGetDicey** [comment]
sweet thank you!

**Comment by sdenec** [comment]
Implemented in a way with the recent update!
