### ISSUE TITLE
Movement speed displayed as "DND5e.Movement"

### ISSUE THREAD

**Issue by Spectre-63** [sdenec/tidy5e-sheet#164]
See below:

![image](https://user-images.githubusercontent.com/65740836/102916718-da85ef00-4438-11eb-99e3-90d1f6580a95.png)

**Comment by akrigline** [comment]
@Spectre-63 I've a feeling you're on a pretty outdated version of dnd5e. Can you confirm your version? This should have been this way since 1.1.x at least

**Comment by Spectre-63** [comment]
Andrew -

apologies for the goose chase - I was on 1.1.1, but an update to the latest
version resolved the issue.
