### ISSUE TITLE
Size Issue?

### ISSUE THREAD

**Issue by NukeMaster0** [sdenec/tidy5e-sheet#165]
I've been trying to get them to be large size tokens, taking up 9 sq., but it just stays medium, also, I couldn't get the size scale to work as it just resets back to "1" instead of say "2". This is the only module in the world.

https://user-images.githubusercontent.com/68701755/103051741-87f62100-4565-11eb-9b7d-9ef19be463b0.mp4

**Comment by akrigline** [comment]
@NukeMaster0 Can you check that that default sheet does this? I am not certain but I think the Token Mold module is needed to cause this behavior to work how you're expecting it to.

**Comment by NukeMaster0** [comment]
> @NukeMaster0 Can you check that that default sheet does this? I am not certain but I think the Token Mold module is needed to cause this behavior to work how you're expecting it to.

Yes, I have done this test with and without this module, everytime I added this module it's the same issue, also, I added the token module and the same thing happened on the new world, what do you do with the Mold module? I also checked to see if the default sheet was doing this, on a new world with no modules the size changed on both scale and size, but when I added this sheet and retried again it was the same problem on both sheets.

**Comment by akrigline** [comment]
Gotchya, thanks for confirming. If it's something the default sheet manages to affect but not Tidy, might be something wrong with where Tidy maps its `size` attribute.

**Comment by NukeMaster0** [comment]
Ah, I manage to get it working now with mold.

![image](https://user-images.githubusercontent.com/68701755/103097753-48b3e880-45d6-11eb-96eb-8e4c50366090.png)

Thank you and sorry for the late reply!
