### ISSUE TITLE
Faulty speed tittle and options

### ISSUE THREAD

**Issue by smauricioj** [sdenec/tidy5e-sheet#166]
Hello!

I really like the character sheet provided by the module, but the speed section in the header seem to have some problem. The tittle is "DND5e.Movement", and the cog underneath does not allow me to change the value(s).

Thanks for your work, and good luck!

![image](https://user-images.githubusercontent.com/30733529/103177591-9f315900-485a-11eb-9bc8-e11ae84db69a.png)

**Comment by sdenec** [comment]
Most likely you are not up to date on your system version. Are you on dnd5e 1.2.0?

**Comment by smauricioj** [comment]
Ooops, that's it! So sorry for the inconvenience!

Thanks buddy

Em dom, 27 de dez de 2020 15:56, sdenec <notifications@github.com> escreveu:
