### ISSUE TITLE
Bug: Collapsing categories makes the left triangle disappear, making it impossible to expand again

### ISSUE THREAD

**Issue by weihanderz** [sdenec/tidy5e-sheet#167]
After collapsing the left hand triangle of a category, it disappears, making it impossible to expand.

**Comment by weihanderz** [comment]
Was another module that offered collapsing feature.

**Comment by sdenec** [comment]
Even though you have closed the issue: Inventory+ is working fine with tidy5e - the arrows don't disappear on closed or opened state. Just fyi.
