### ISSUE TITLE
BUG - Some error with the "Resource Plus module" for the new 0.4.X release

### ISSUE THREAD

**Issue by 4535992** [sdenec/tidy5e-sheet#169]
**Environment Details**

Foundry VTT Version: 0.7.9

Operating System: [Linux]

How Are You Using Foundry: [Linux,Native Application (Electron), Chrome]

Which Game System: Dungeons and Dragons 5th Edition, version 1.2.0

Modules Enabled?: yes

OS, Hosting, Browser (if applicable): Linux/Node/Chrome

Module Version : 0.4.1

**Description Details**

I starting from a already setted world with other modules installed.

I get the errors after update to the  new 0.4.1 release all it's seem to work fine with the latest 0.3.X release.

From what i see on the developer console it's seem some problem with "[Resources Plus module](https://github.com/ardittristan/5eSheet-resourcesPlus/tree/master)"?

![](https://i.imgur.com/XnPcNWV.png)
![](https://i.imgur.com/gL8JmRD.png)
![](https://i.imgur.com/eWaVUZT.png)

**Comment by sdenec** [comment]
As far as I have been following the discord chat it seems to be the latest libwrapper update that causes this error. Either because resources plus has to be updated or there is a bug in libwrapper. That's my best guess ...

**Comment by 4535992** [comment]
Yes i just tested with the version of libwrapper 1.1.4.0, no it's work .
