### ISSUE TITLE
Always roll two dice

### ISSUE THREAD

**Issue by ThoGri75** [sdenec/tidy5e-sheet#17]
In a attack it roll two dice

**Comment by ThoGri75** [comment]
Yes I do, use both of them. So can't use better rolls and / or  MinorQOL with tidy sheet?

btw I love this sheet :-)

**Comment by sdenec** [comment]
You can. But it depends on the settings in those modules if you roll twice or single!

**Comment by sdenec** [comment]
Since this issue most likely is better rolls/minorQOL related I guess this is resolved.
