### ISSUE TITLE
Manifest leads to 404

### ISSUE THREAD

**Issue by AtlasWasTaken** [sdenec/tidy5e-sheet#170]
The link, https://raw.githubusercontent.com/sdenec/tidy5e-sheet/master/module.json, + updating in Foundry gives a 404 error.

**Comment by sdenec** [comment]
Please try to uninstall and reinstall. The release workflow has changed. Sorry!

**Comment by sdenec** [comment]
If you haven't already reinstalled the module it should now be fixed.
