### ISSUE TITLE
Tidy5e Sheet v0.4.1 broke Crash's 5e Downtime Tracking

### ISSUE THREAD

**Issue by intemptesta** [sdenec/tidy5e-sheet#172]
Tidy5e Sheet v0.4.1
Crash's 5e Downtime Tracking v0.4.8
Foundry VTT 0.7.9
DnD5e 1.2.0

Crash's 5e Downtime Tracking's multiple buttons are missing.

![image](https://user-images.githubusercontent.com/13413266/103486179-7dbe0780-4e2e-11eb-81da-f3ad8b4faa92.png)

![image](https://user-images.githubusercontent.com/13413266/103486156-451e2e00-4e2e-11eb-9c5c-84ebba17cc3f.png)

**Comment by sdenec** [comment]
should be resolved with 0.4.2
