### ISSUE TITLE
Can't delete NPC spells

### ISSUE THREAD

**Issue by dccrain** [sdenec/tidy5e-sheet#174]
The Context menu to delete items for an NPC does not show when right clicking spells. As of right now I need to change the npc's sheet back to the default sheet in order to delete a spell from the character.

Edit.
This also means that spells cannot be edited once added to the NPC.

**Comment by sdenec** [comment]
Make sure you are on 0.4.1 - If auto update does not work please try to reinstall the module.

**Comment by dccrain** [comment]
Thanks, resolved.
