### ISSUE TITLE
Tidy Lootsheet

### ISSUE THREAD

**Issue by benbarbour** [sdenec/tidy5e-sheet#175]
Love the character, NPC, and vehicle sheets. Just wondering if you'd consider tidying the loot sheet (as in the module)?

**Comment by sdenec** [comment]
Thank you, happy to hear! Tidying that sheet would mean to either force the author to adopt my style or I would have to create my own module for the loot sheet. I'm comfortable with neither (unless the author would ask me to collaborate). To be honest I've got my hands full with tidy as is - so for the moment: No :)
