### ISSUE TITLE
Can't delete or edit spells in NPC sheets

### ISSUE THREAD

**Issue by barraakeno** [sdenec/tidy5e-sheet#176]
Just updated this module and I can't delete spells from NPC sheets or EDIT them.

When left clicking an item or features it works 
![image](https://user-images.githubusercontent.com/44577670/103571925-848a6000-4eaa-11eb-948b-6d52b0b0a732.png)

But not when clicking on a spell
![image](https://user-images.githubusercontent.com/44577670/103571991-9f5cd480-4eaa-11eb-8ff0-34565de95fb9.png)
(not really sure how to show that on a picture)

**Comment by sdenec** [comment]
Hi. Please make sure you are on 0.4.1 - try to update tehe module. If that shouldn't work please uninstall and reinstall.

**Comment by sdenec** [comment]
The newest version in 0.4.2 just to let you know.
