### ISSUE TITLE
Update Vehicle Speed to support new data model

### ISSUE THREAD

**Issue by akrigline** [sdenec/tidy5e-sheet#177]
Coming soon :tm: in the next dnd5e system update, vehicles will have the same data model for speed as other actors do.

Recommend you apply the same treatment to them in such a way that the rendering does not fail if the data doesn't exist in order to make ready for that update.

Something like this maybe:
```hbs
<section class="movement {{#unless (or movement actor.flags.tidy5e-sheet.legacy-speed)}} legacy-display{{/unless}}">
{{#if movement }}
  <ul class="speed-form">
    ...
  </ul>
{{/if}}

<ul class="speed-form-legacy">
  ...
</ul>

{{#if movement}}
  <span class="legacy-switch">
{{/if}}
</section>
```
Such that the legacy speed is visible when the `movement` data does not exist, or when the flag is set.

**Comment by sdenec** [comment]
hm, it seems something isn't working with that setup. Either movement already exists but without data or the condition is wrong. The "Speed" Title and toggle button shows up - neither new nor old data though. Also The console spits out an error.

![movement error](https://user-images.githubusercontent.com/8881200/103614580-349eae00-4f29-11eb-9ec0-e6d9cb581bbf.jpg)

**Comment by sdenec** [comment]
Ah, ideed. Even freshly created vehicles already have the movement object setup. Propably just the function to poluate is missing from the core class. So that won't work I'm afraid.

**Comment by akrigline** [comment]
Interesting. That's not expected I don't think. I'll take a closer look tonight and get back to you.

**Comment by akrigline** [comment]
Ok interesting. The ActorSheet's getData populates a `movement` object even though it is empty for vehicles in 1.2.0.

The `actor.data.attributes.movement` object is however missing as expected in 1.2.0, so you could use that instead of `movement` in your conditional.

**Comment by sdenec** [comment]
Next update will bring vehicles up to date with dnd5e 1.2.2. Thanks for all the info, though :)
