### ISSUE TITLE
Feature request: Filter/search item names

### ISSUE THREAD

**Issue by Fallayn** [sdenec/tidy5e-sheet#182]
It would be very handy for our group if there was a way to search/filter the full inventory list.

For example via a search field at the top of the inventory list, to the left of / next to the existing "filter" icon.
Once you enter something, the items in the inventory get filtered for that term and only matching items are shown.

Currently, the inventory gets somewhat unwieldy once you get past a certain number of items.

**Comment by sdenec** [comment]
Next update will include this feature! Thanks for the suggestion :)
