### ISSUE TITLE
Feature Request: Spellbook Features

### ISSUE THREAD

**Issue by DivertedCircle** [sdenec/tidy5e-sheet#185]
Couple features I'd love to see added to the spellbook tab.

Spellcasting Attack modifier: Currently the spellbook lists your save DC at the bottom of the tab but doesn't list your Spellcasting Attack modifier for spells that require an attack roll. This would be useful in situations where you're rolling for a spell that isn't on your sheet.

Number of Prepared Spells: [MESS](https://github.com/Moerill/mess) has an option to display a tracker for the number of prepared spells you have compared to a total number you can prepare. I'd love to see this added to the sheet, or support added for the MESS version so it lines up better. Currently the box for entering the total you should have drops down a line and spans the width of the tab.

**Comment by sdenec** [comment]
In the next update Spell Attack Modifier will be visible in the spells tab aswell as an Prepared Spells tracker!
