### ISSUE TITLE
Abbreviations don't match custom currency names

### ISSUE THREAD

**Issue by megahead11** [sdenec/tidy5e-sheet#187]
Minor UI issue and compatibility issue. 
When using custom denomination names (such as with the **custom currency module** or anything else that changes the currency configuration), the abbreviations are overridden using the name of the currency's internal abbreviation rather than one defined by the lang .json or other methods to re-define terms (such as CONFIG.DND5E.currencies).  The hover-over tooltip will display the appropriate  lang .json name, but the abbreviation will not match. The custom currency module appears to work by replacing the names of the core's currency, but does not completely remove their original  designation in CONFIG.DND5E.currencies (so they'll replace gp, pp, etc. rather than making new ones).

https://user-images.githubusercontent.com/21242682/103952031-87789100-50f4-11eb-950c-2e1acdb5c4dd.mp4

In the attached video, you'll see the tooltip is changed but the abbreviations are not (the abbreviations should be GC, GL, X, X, and X respectively.) I have a bespoke module that replaces these names in the same manner that custom currency does.

**Comment by sdenec** [comment]
The Problem with that is that the system doesn't offer abbreviations. I used the code references to create them and put the full names in the label. I do not know how to best handle this. The Full names clearly are to long to be put in the fields. Maybe in a future update atropos can add official abbreviations for coinage to the dnd5e system so modules can use that. At that point I'm happy to put those in and the custom currency mod author can use them aswell!

**Comment by sdenec** [comment]
Or, If I figure out how to get my own translations for denomination into the mix, the mod author could potentially create new settings to put custom abbreviations as well. This is a point on my agenda as currently those abbreviation won't translate at all.

**Comment by sdenec** [comment]
For the next update I have added translation strings for currency abbreviations. I don't know though if that is enough to fix the custom currency issue.

**Comment by ktrieun** [comment]
I added settings so that the user can enter their own currency abbreviations and added a function that will change the currency abbreviation text displayed shown on render so my module is now compatible with your current version.
