### ISSUE TITLE
Feature Request:  a UI option to change maximum attunement slots

### ISSUE THREAD

**Issue by itamarcu** [sdenec/tidy5e-sheet#189]
Classes like the Artificer can attune to more than 3 items.

You already created the basis for this - I looked at the code and found:

```
  	await actor.update({"data.details.attunedItemsMax": 3});
```

so it's already possible to do this through a macro for example, which is awesome 👍 

still, would be good to have a method to do it through the user interface.  I suggest making it happen when clicking the attuned items counter (create a small dialog window?).

**Comment by TheTercept** [comment]
Agreed.

Setting hard limits on values like this is terrible for homebrew support as well.

**Comment by sdenec** [comment]
It is not hard set. The GM can individually change players attunement maximum. Players cant change to prevent cheating (as I'm sure I would get the request to let only DMs change something like that)

**Comment by sdenec** [comment]
To clarify: The dm can go into each player's character sheet and simply type in the max value in the max attunement field. Should propably add that to the readme.

**Comment by sdenec** [comment]
Next update will reflect the mechanic in the module readme. Thanks for making me aware.
