### ISSUE TITLE
Update, Weapon Properties (Adamantine and Silvered) to Actor's sheets

### ISSUE THREAD

**Issue by NukeMaster0** [sdenec/tidy5e-sheet#193]
Wanted to know if you are adding these properties to the actor's sheets Vul., Resist., Immune. combined with Midi's QoL module would be helpful for automation, thank you!

![image](https://user-images.githubusercontent.com/68701755/104108142-4b7a3300-5290-11eb-88ba-24c09c2bc65f.png)

**Comment by sdenec** [comment]
Sorry, that's out of my hand and part of the dnd5e core mechanic. For that you should propably open an issue with atropos in the dnd5e repo! It's a good issue though and I agree that it should be added.

**Comment by NukeMaster0** [comment]
Forgive me, it was my fault entirely, I should have tested this with and without the modules on a new world like I usually do, but I got kind of lazy and assumed wrong.
