### ISSUE TITLE
Missing right click menu option to equip certain item categories

### ISSUE THREAD

**Issue by archeresky** [sdenec/tidy5e-sheet#195]
Currently, it's not possible to change the equipped status of certain item categories like tools or loot. Although, it may seem desirable to not have the option to equip those, in case they are equipped, the user is forced to change to default sheet (or a different one) to manipulate their equipped status. This is inconvenient and it would be nice to have the options of the right click menu uniform across all categories.

**Comment by sdenec** [comment]
next update will have those back in - was derived from the fact that these item types don't have support for being equipped/unequipped in the item sheet itself.
