### ISSUE TITLE
Feature Request - View Character/Token Artwork

### ISSUE THREAD

**Issue by btunnadine** [sdenec/tidy5e-sheet#196]
I think it would be a great addition to be able to right-click on the portrait to have a "View character artwork" and "View token artwork" button, the same as they work when doing so in the Actors Directory.

As a DM I like to use the artwork to show players what a creature looks like, but it can take quite a bit of time to search through the actors list to find the correct actor, doing it directly on the sheet would be a great addition.

**Comment by sdenec** [comment]
Interesting request! Next update will feature a right click option on portraits as suggested! I actually had situations myself when I wanted to share some character art and didn't because it was to much to search the actors. The possibility to add this feature never occured to me ...
