### ISSUE TITLE
[BUG] Searchbox Does Not Work In Grid View

### ISSUE THREAD

**Issue by JLtheking2** [sdenec/tidy5e-sheet#198]
The newly added searchbox works fine and well while in the default list view, but while in grid view it does not seem to work.

![image](https://user-images.githubusercontent.com/48344299/104133171-ce98a780-53bc-11eb-8e0d-b410fac8448d.png)
![image](https://user-images.githubusercontent.com/48344299/104133177-d6584c00-53bc-11eb-8dab-d6f02c11508d.png)

**Comment by sdenec** [comment]
Ups, didn't test there. Should be fixed now.
