### ISSUE TITLE
Feature Request: Hide left notes on biography tab for NPC sheets

### ISSUE THREAD

**Issue by Nildran** [sdenec/tidy5e-sheet#203]
For most NPCs, personality traits, ideals, bonds and flaws are useless. On the biography tab, these notes on the left take up half the page at the expense of the readability on the biography notes.

I propose to set up an option to hide the left notes for the NPC sheets.

![image](https://user-images.githubusercontent.com/59559563/104165594-dcb8e900-53f9-11eb-9d67-49f20a8553cd.png)

**Comment by sdenec** [comment]
can you give me a quick translation for "Toggle Personality Info"

**Comment by Nildran** [comment]
If the option allows to hide personality information, the translation will be: "Masquer les informations de personnalité". If the option allows to show the information, the translation will be: "Afficher les informations de personnalité".

(there is no French word that has exactly the same meaning as "Toggle".)

**Comment by sdenec** [comment]
What about "commuter les informations de personnalité" or perhaps "changer  les informations de personnalité" - or if none of these will fit just "les informations de personnalité" maybe?

That's where it will be visible as a label:
![solution_personlity jps](https://user-images.githubusercontent.com/8881200/104179438-26123400-540c-11eb-8370-80e24508b753.jpg)

**Comment by Nildran** [comment]
Very good feature integration. From what I see, the best would be "Informations de personnalité".

**Comment by sdenec** [comment]
Next update I push will have it integrated with the french translation updated accordingly. Thanks for the feature request. Good addition :)
