### ISSUE TITLE
Feature Request: Allow formula override for max prepared spells

### ISSUE THREAD

**Issue by eikgren** [sdenec/tidy5e-sheet#204]
The new prepared spells counter is a handy feature, thanks for adding that :)

I tried to use DAE to override the maximum with a formula by setting data.details.maxPreparedSpells but the sheet ends up with the formula displayed as text rather than interpreted:
![image](https://user-images.githubusercontent.com/59783644/104182652-ad5da880-5408-11eb-878c-515b7adc1656.png)

I suspect this is down to Tidy because I was able to override a resource maximum with the same formula - though please do let me know if this is a DAE issue and I'll go raise it with them instead.

Thanks!

**Comment by sdenec** [comment]
phew, good question. I have not the slightest clue how DAE operates. Tidy simply adds this value onto the actor, so this is nothing that's there by default. Could very well be that DAE can only alter values that are "known" to it?

**Comment by sdenec** [comment]
Actually it is working for me! Maybe your formula is wrong or you have to up your priority?
![override](https://user-images.githubusercontent.com/8881200/104185188-ed2a8d00-5414-11eb-9d8e-e9aca6e6354f.jpg)

**Comment by sdenec** [comment]
scratch that. as soon as any kind of formula is in there it won't work.

**Comment by eikgren** [comment]
> I have not the slightest clue how DAE operates.

Me neither! 😁 

> scratch that. as soon as any kind of formula is in there it won't work.

Exactly so, an integer is fine. I'm happy to raise it with DAE if that would make more sense (if only to find out more from them).

**Comment by sdenec** [comment]
I chatted wit tposney a bit. we're trying to find a solution. Might take a bit though :)

**Comment by eikgren** [comment]
Ah, cool, thank you! No worries, the feature is still very useful 😄

**Comment by sdenec** [comment]
Sorted it out. Next update you can set your costum equasion with DAE. You have to use "Custom" though. It will essentially work like an override - if you want anything else you can prepend the equasion with "-,+,*,/" for substract, add, multiply, divide

**Comment by eikgren** [comment]
Sounds great, thanks again!

**Comment by cs96and** [comment]
Unfortunately this still isn't working correctly.  If I set the formula to `@classes.druid.levels + @data.abilities.wis.mod`, then the following warning pops up...

![image](https://user-images.githubusercontent.com/898086/104445953-ae6e1180-5591-11eb-9f0d-b68e0d342a6e.png)

The max prepared spells is then set to 5 instead of 9 because the wis mod is not being added on.

**Comment by sdenec** [comment]
the correct formula should be `@classes.druid.levels + @abilities.wis.mod` leave out the "data" :)

**Comment by cs96and** [comment]
D'oh!  Sorry for the confusion!
