### ISSUE TITLE
[BUG] Needs checking if Spellcasting is none

### ISSUE THREAD

**Issue by 9ryex5** [sdenec/tidy5e-sheet#206]
![image](https://user-images.githubusercontent.com/43207603/104364127-111dc980-550e-11eb-8825-d77a1402a329.png)

When a character doesn't have a spellcasting ability, we get this errors because actor.data.data.abilities[spellAbility] is undefined.

**Comment by sdenec** [comment]
Yup, didn't check for that. Will fix it. Shouldn't break anything until the next update though.

**Comment by sdenec** [comment]
This has been fixed with the recent update.
