### ISSUE TITLE
[BUG] Incompatibility with Let's Trade 5E

### ISSUE THREAD

**Issue by 9ryex5** [sdenec/tidy5e-sheet#207]
I was getting that error, so I disabled all modules and enabled one by one, there seems to be some kind of incompatibility with [Loot Sheet NPC 5E](https://foundryvtt.com/packages/lootsheetnpc5e/).

![image](https://user-images.githubusercontent.com/43207603/104365134-88a02880-550f-11eb-8263-9b6f781a6e54.png)

**Comment by sdenec** [comment]
I can't reproduce this error - I have tidy5e and Loot Sheet active and I can view each sheet type without any error and can drag items from the loot character to any other actor. Anyway, that is propably something to address in the Loot Sheet 5e Repo.

**Comment by 9ryex5** [comment]
Sorry, I meant [Let's Trade 5e](https://foundryvtt.com/packages/lets-trade-5e/) and not Loot Sheet. I'll edit this issue's title so it makes sense.

**Comment by 9ryex5** [comment]
Anyway I posted this on [Let's Trade 5e](https://foundryvtt.com/packages/lets-trade-5e/) side. It's getting fixed  :)
