### ISSUE TITLE
Ability Checks and saves from sheet don't work

### ISSUE THREAD

**Issue by amcvfx** [sdenec/tidy5e-sheet#208]
There seems to be a problem with rolling saving throws and ability checks from NPC and PC sheets. The check and save fields bellow the ability scores don't do anything when clicked and give this error:

![image](https://user-images.githubusercontent.com/35099081/104439332-44ee0300-5591-11eb-8d20-4070b79b4836.png)

Using the Ability Score titles for the rolls gives this error.

![image](https://user-images.githubusercontent.com/35099081/104439151-14a66480-5591-11eb-8018-021127570ed7.png)

![image](https://user-images.githubusercontent.com/35099081/104438937-d9a43100-5590-11eb-8705-43edbdc8c44d.png)

**Comment by sdenec** [comment]
This just has been fixed :)
