### ISSUE TITLE
Bug: Bullet Point Text Formatting Issue

### ISSUE THREAD

**Issue by DivertedCircle** [sdenec/tidy5e-sheet#211]
Not sure if this is just a Firefox issue (haven't tested other browsers) but bullet points in description text aren't displaying in the expanded view.

![image](https://user-images.githubusercontent.com/26470570/104496549-5dace780-5596-11eb-8c7d-9d05e848d86c.png)
![image](https://user-images.githubusercontent.com/26470570/104496598-6c939a00-5596-11eb-8f63-1410cadb25f5.png)

**Comment by sdenec** [comment]
will be fixed!
