### ISSUE TITLE
[Feature Request] Character sheet lockdown

### ISSUE THREAD

**Issue by InnilToo** [sdenec/tidy5e-sheet#212]
Add and option to Enable/Disable button to lock down the character sheet for certain permission levels.

What I mean by that. When editing is disabled no one should be able to edit fields like AC or ability scores, toggle different proficiencies, or edit recourses. Additionally it should remove the "Edit Item" on right click. This could be an additional layer of the lock button that could modified in the setting.

My players and I as the DM click on the wrong part of the character sheet and add/remove a proficiency or change something. [Illandril's Character Sheet Lockdown (5e)](https://github.com/illandril/FoundryVTT-sheet5e-lockdown) has the right idea, but as a separate module it's quite messy.

**Comment by sdenec** [comment]
Do you want a complete lockdown - so no manual input can be made at all? No health adjustment, no resource management, no item quantity? That seems to be a little excessive and might hinder the flow of the game in some way. I can get behind certain things like Ability Stats, proficiency toggles, max health maybe.

**Comment by InnilToo** [comment]
Ability scores, proficiency toggles, max HP, AC, resources (preventing changing the maximum and when they are regained S/L rest), speed, max charges and uses of items and features, special traits.

Basically things and would mess up the character if change accidentally. These sort of things usually only change on level up. But allowing things like current HP, temp HP, quantity, current uses to be edited on the fly.

If it's possible maybe having options in the setting as what parts of the sheet will be locked would satisfy overzealous.

**Comment by sdenec** [comment]
Hm, specific options as to what to lock is a little much to build in. But I'll try to add the gm option to lock down the sheet's most "vulnerable" input fields when the sheet is in the "locked" state.

**Comment by sdenec** [comment]
While it is not a full lockdown there is now a new GM setting that you can enable to lock down sensible fields when the edit lock is active. Hope that makes life a little easier :)
