### ISSUE TITLE
[Feature Request] Global Classic Item Control

### ISSUE THREAD

**Issue by Kixao** [sdenec/tidy5e-sheet#213]
So, in an update a while ago. You changed it so the way to interact with items, features, spells etc. is through rightclicking them.

While I realize there is individual player options to return it to close to what it was before.
I'd propose a global DM setting to have this view be the default. I like the classic control better, and so does my players. I imagine there are others that like it aswell, and having the option for it to be default globally, would be nice 👍

**Comment by sdenec** [comment]
Well, one prefers it this way another one that way. With presenting each individual its own choice I think I covered all my bases. If you know you and your players prefer it the "classic" way, I'll let you jump the hoop to either instruct your players to take the steps to set it up themselves or do the work for them. At best you have 4-5 players and at worst 20 or more - even then it should be maybe 5 minutes to set it up. Plus anyone can decide at any point in time to switch settings. If you use the grid view for example you'll get used to right clicking pretty fast and a player who does that might prefer it for list view as well. Taking it away on a global level doesn't seem right to me.
