### ISSUE TITLE
Error: This is not a registered game setting

### ISSUE THREAD

**Issue by bimberman** [sdenec/tidy5e-sheet#215]
Line 454 in tidy5e-sheet/scripts/app/tidy5e-favorites.js is not commented.
After commenting this line the error was removed.

![image](https://user-images.githubusercontent.com/2808668/104695183-3141ba00-56c1-11eb-8b6e-d4fad9c797c3.png)

**Comment by sdenec** [comment]
you have errors with midiQol and the integrated favorite item module. that's very strange. Are you sure you are on tidy version 0.4.8?

**Comment by bimberman** [comment]
False alarm. The upgrade somehow downgraded me to 0.4.0 from 0.4.7 (not sure how). I deleted the module and reinstalled. Now I am on 0.4.8 and no issues.
