### ISSUE TITLE
Long rest sets spells to 0

### ISSUE THREAD

**Issue by amcvfx** [sdenec/tidy5e-sheet#216]
I'm having an issue that causes spell slots to be reset to 0 on a long rest for PC and NPCs. I confirmed that this still happens when Tidy is the only module activated.

Also as another issue, it seems that each time Tidy 5e Sheet is updated it resets a characters speed to zero? I can't be sure if this has happened only on the most recent updates.

**Comment by sdenec** [comment]
spell slots resetting to 0 on a long rest is a dnd systen bug introduced in 1.2.x and will also happen on the default sheet. I did notice the 0 speed as well but don't think it has to do with tidy either and might be a system bug as well

**Comment by akrigline** [comment]
I know about the long rest thing and there's a fix for that already merged waiting release. Haven't heard about the speed though. Would like some more details there.

**Comment by sdenec** [comment]
If updating the sheet module would cause actors to lose their speed values, uninstalling and reinstalling the sheet should cause the same issue, I guess - updating is just that, replacing the files. Upon updating no scripts in the module are executed, that will only happen once you open an actor sheet. Just for testing purposes I set up a few actors with speeds, uninstalled tidy and reinstalled. And of course all values are still there - the configurable ones as well as "legacy" ones. So my best guess is something happened during the 1.2.2 database update that deleted all movement settings as well as the old speed values. I noticed all creatures in the library that don't have a walking speed will have no speed at all. Creatures with a walking speed will have it translated into the new movement speed with everything else beeing lost both from settings and the legacy fields. Player characters seem to have their movement and speed erased altogether. That is somewhat problematic and of course can't be reverted. But I have 2 huge modules (homebrew Campaign and ToA) with a lot of NPCs and none of them have usable movements (apart from walking speed).

**Comment by cs96and** [comment]
This was fixed in [dnd5e v1.2.3](https://gitlab.com/foundrynet/dnd5e/-/releases/release-1.2.3)

**Comment by akrigline** [comment]
> If updating the sheet module would cause actors to lose their speed values, uninstalling and reinstalling the sheet should cause the same issue, I guess - updating is just that, replacing the files. Upon updating no scripts in the module are executed, that will only happen once you open an actor sheet. Just for testing purposes I set up a few actors with speeds, uninstalled tidy and reinstalled. And of course all values are still there - the configurable ones as well as "legacy" ones. So my best guess is something happened during the 1.2.2 database update that deleted all movement settings as well as the old speed values. I noticed all creatures in the library that don't have a walking speed will have no speed at all. Creatures with a walking speed will have it translated into the new movement speed with everything else beeing lost both from settings and the legacy fields. Player characters seem to have their movement and speed erased altogether. That is somewhat problematic and of course can't be reverted. I have two huge modules (homebrew campaign and ToA) with a lot of NPCs and none of them have usable movements (apart from walking speed) anymore.

Took some time tonight and investigated this issue. Your sheet's `legacy speed` toggle is doing something that the core migration scripts do not expect. After 0.99, it's not expected that `attributes.speed` exist on migrated actors. But since it does, when migration runs again things break.

See this for details:
https://gitlab.com/foundrynet/dnd5e/-/issues/965

**Comment by Fallayn** [comment]
I created this page summarizing the issue, the workarounds and providing a online tool to fix missing movement on actors if you've still got a previous backup somewhere: https://fallayn.com/foundry-movement-fix/

**Comment by sdenec** [comment]
the recent update disables legacy speed and thus eleminates the speed values from the sheet, preventing them to populate. The damage is done but further issues upon data migration shouldn't happen.
