### ISSUE TITLE
[Feature Request] Active Effect Toggle on Row

### ISSUE THREAD

**Issue by geilt** [sdenec/tidy5e-sheet#217]
Love this sheet for NPC's since no one elses works with Temp HP.

Any way for active effects you could have a quick toggle button on the effect row so we dont have to right click activate?

This is similar to how the baseline foundry sheet works.

Thanks!

**Comment by sdenec** [comment]
If the right click is too much and you prefer the "old" way you can chose to display the "classic" item controls. That will display the controls inline without the need to right click. That only applies for the list view though.
