### ISSUE TITLE
Localization issue

### ISSUE THREAD

**Issue by DarKDinDoN** [sdenec/tidy5e-sheet#22]
Hello,  

There is an issue for the french localization:
![image](https://user-images.githubusercontent.com/1687854/84605438-77ba0680-ae9d-11ea-8ab7-84d649eb29df.png)

The first title (first tab) is on two lines when there are items bookmarked.
Default DnD5 sheet doesn't have this issue.

**Comment by sdenec** [comment]
Thanks for telling me! Forgot to fix it with the last update. Will be fixed in the next version!
