### ISSUE TITLE
Observers of NPCs cannot see all features, attacks, actions etc.

### ISSUE THREAD

**Issue by cs96and** [sdenec/tidy5e-sheet#221]
An observer of an NPC is not able see all features, attacks, actions etc.

E.g. here is the GM view of the SRD Giant Boar...

![image](https://user-images.githubusercontent.com/898086/105102993-b228f900-5aa7-11eb-90bf-9609d29dab48.png)

Here is the same creature as seen by a "Trusted Player" with the "observer" permission...

![image](https://user-images.githubusercontent.com/898086/105103155-003dfc80-5aa8-11eb-9533-5442edcfa0e3.png)

Sometimes you can see some things, but not everything.  E.g, for a Bandit, you can see the attacks but not the inventory.  GM view...

![image](https://user-images.githubusercontent.com/898086/105103264-34b1b880-5aa8-11eb-9e2c-08f2446e3db6.png)

Observer view...

![image](https://user-images.githubusercontent.com/898086/105103327-59a62b80-5aa8-11eb-9a64-03888fe26287.png)

**Comment by sdenec** [comment]
Thanks for the report. Made me aware that there was a mistake in a condition. If only one item is in a category it gets hidden! Was affecting PC and Vehicle sheets as well. Should be fixed in the next update!
