### ISSUE TITLE
[Feature Request] Changable UI

### ISSUE THREAD

**Issue by emperorflame** [sdenec/tidy5e-sheet#223]
Could you be able to make the UI selectable? 
The latest UI is a little bit unpractical, but the previous one was awesome and we loved it.

Thank you for making this sheet and your work!

**Comment by sdenec** [comment]
What exactly do you want to change? The main difference is the right click menu. You can disable that in the settings on a per user basis - then an icon will appear that opens the context menu on a left click. If you want the "classic" inline controls you can set that as well on a per user basis in the settings. Other that that I can't offer any other changes in the UI.

**Comment by emperorflame** [comment]
Thanks for the quick answer! :) 
In the previous ui the ability bar was on the left side of the sheet and the HP, hit dice and a couple other things were where the ability bar is currently are. Other things that you are mentioned are cool.

**Comment by sdenec** [comment]
Yeah, no. That would be really impractical to change back. I'm afraid you have to live with the new layout. sorry!

**Comment by emperorflame** [comment]
Alright. :) Thank you for you answer. Have a nice day! :)
