### ISSUE TITLE
Senses for DnD5e 1.1.1 

### ISSUE THREAD

**Issue by alcobeard** [sdenec/tidy5e-sheet#226]
Hi, didn't want to bother you, but need your help to migrate Trait sense visibility to older version of system. At this moment when I'm using the latest version of your module, there is no information for senses (like darkvision) in characters sheet. I've tried many ways in changing this line in tidy5e-traits.html, but I couldn't achieve behavior like for other traits (but I could add like in previous versions - input).
```

  {{#unless isVehicle}}
  <div class="form-group">
    <article title="{{localize 'DND5E.Senses'}}">
      <label for="data.traits.senses">
        <i class="fas fa-eye"></i> <span>{{localize 'DND5E.Senses'}}</span>
      </label>
        <ul class="traits-list">
        {{#each senses as |v k|}}
            <li class="tag {{k}}">{{v}}</li>
        {{/each}}
        </ul>
    </article>
    <a class="trait-selector config-button" data-action="senses" title="{{localize 'DND5E.MovementConfig'}}"><i class="fas fa-pencil-alt"></i></a>
  </div>
```

If you have some free time, could you help to migrate this moment for old version please

**Comment by sdenec** [comment]
In the older version senses could only be entered via the input field, not with an options menu. The menu was not implemented in the dnd system, yet. So the only way for you to show senses on the sheet would be to use the input field - as the default sheet does as well. The html sheet can only display data that has already been generated by the dnd5e system. So I can't help you with that I'm afraid.

**Comment by akrigline** [comment]
Since you've updated this module but not updated your system, there's only so much compatibility that can be done... Short of rolling back the version of the module you have installed I think you're out of luck. Recommend updating your dnd5e system.
