### ISSUE TITLE
Minor visual error when used alongside another module.

### ISSUE THREAD

**Issue by Arx724** [sdenec/tidy5e-sheet#230]
Hey, I've been using Tidy5e sheet ever since I switched to foundry, and with the recent UI update, I've had a minor visual issue stemming from an interaction between this module and a different one.

When using both this module and [Forien's Unidentified Items](https://github.com/Forien/foundryvtt-forien-unidentified-items), the "Mechanics / Flavor Text" text seems to get doubled, as shown in this image:
![screenshot](https://i.imgur.com/f2Ek8F5.jpg)

It's a minor thing and fairly easily ignored, but I figured I might as well see if it's also easily fixable. The other module hasn't seen a release in half a year now, so I figured I'd mention the issue here as well.

Thanks for the module regardless, I'm really loving visual rework!

**Comment by sdenec** [comment]
I think you shouldn't use Forien's Unidentified items. It potentially messes up your database. At least that was the latest info I had on that!

**Comment by sdenec** [comment]
Ah, no. scratch that. Seems to be okay now. But the error causing the heading to be doubled should be on that modules side.

**Comment by akrigline** [comment]
The latest version (0.2.5) is safe to use.

**Comment by Arx724** [comment]
> The latest version (0.2.5) is safe to use.
Huh, my foundry must have been bugging out and wouldn't update it.
0.2.5 seems to not have the issue (mine was stuck in 0.2.3 and kept saying that's the latest version), so problem solved, I guess!

Thanks for the quick response, both of you!
