### ISSUE TITLE
[Feature Request] Custom Encumbrance

### ISSUE THREAD

**Issue by alexcooper97** [sdenec/tidy5e-sheet#231]
Hi! I'm aware of the "Powerful Build" on Special Traits tab that doubles your carry capacity. However, some players on my group use homebrew material on his PC's, that has "add your Constitution score to your Strength score when determining your carry capacity". I know it's much to ask to include something that complex but...it is possible to add a "custom" fillable space on the carry capacity in your inventory like the attunement maximum limit that lets you enter any number?

**Comment by sdenec** [comment]
Hi, why don't you add a custom effect? Something like "Strong Back" and change the "Attributes Encumbrance Max" value to "ADD" or "OVERRIDE" and put in the desired value? Way easier than me adding a new field with all the calculations. Would also work with mods like enhanced encumrance I guess :)
![custom_encumbrance_effect](https://user-images.githubusercontent.com/8881200/106140278-d8692b80-616e-11eb-9318-0afd661a3b1e.jpg)

**Comment by sdenec** [comment]
You could even do something fancy as to add the calculated bonus from your Con modifier * 15 or some arbitrary multiplier. What ever your homebrewing heart desires. Store it as a effect in a compendium and slap it onto a character. Auto updates the carry capacity if the core ability changes :)
![custom_formula](https://user-images.githubusercontent.com/8881200/106140772-7bba4080-616f-11eb-9de4-a86dc6691ae5.jpg)

**Comment by alexcooper97** [comment]
Oh, didn't know that effects included encumbrance. In that case, it's not necessary to add anything. Sorry for bothering you and thank you so much for the advice!
