### ISSUE TITLE
Suggestion: Tidy5e Loot-sheet

### ISSUE THREAD

**Issue by Ikabodo** [sdenec/tidy5e-sheet#232]
There have been several attempts to create sheets for looting in other modules, they work decently. But it might be worth making a simpler version with your great sheet.

Basically a simplified sheet of an actor, with all stats removed accept an inventory with the same look and feel as your sheet. This sheet can act as chests, party trunk's, npc loot or whatever you want it to be as a GM. Without the complications of loot distribution or other automations.

**Comment by sdenec** [comment]
Doesn't sound like a bad idea. Right now I need a little break of adding new things to the sheet and keep focusing on maintenance. But I'll definately keep it in mind when the encancement bug bites again :)

**Comment by Bryn1701** [comment]
Would love to see this also. I can see a cool sheet just for a bag of holding etc.

**Comment by CixrTyx** [comment]
Can you make the looting apart of the sheet?  Like instead of having to switch sheets, just add a loot feature to the sheet?

**Comment by sdenec** [comment]
I'm going to close this. I don't see myself working on this in the forseeable future. Right now I'll concentrate on keeping the sheet working as it is - you know work and life and stuff ;) Sorry!
