### ISSUE TITLE
Group favorites tab by action type

### ISSUE THREAD

**Issue by benbarbour** [sdenec/tidy5e-sheet#235]
I think it would be much more useful for players and GMs to have sections for:

- Actions
- Bonus Actions
- Reactions
- Legendary Actions
- Crew Actions
- Special (any other action type)
- Passive (no action type)

rather than knowing whether the item is a spell or a consumable or ammo. Although subsections for things like that and spell level could be explored.

**Comment by benbarbour** [comment]
I haven't looked too closely, but maybe this project could be leveraged? https://github.com/ElfFriend-DnD/foundryvtt-dnd5eCharacterActions

**Comment by sdenec** [comment]
The character actions list is now integrated into tidy5e but maybe there will be a rework in the future to combine actions list and favorites into one multi purpose module.
