### ISSUE TITLE
Request: "Enable Edit" locks attribute/skill features from being edited too. 

### ISSUE THREAD

**Issue by GambetTV** [sdenec/tidy5e-sheet#236]
Right now the Enable Edit feature only prevents you from accidentally deleting inventory items and spells and stuff. But it is all too easy to accidentally misclick your Proficiencies and give yourself bonuses you shouldn't have. It'd be nice if the Enable Edit feature locked much of this stuff down too. You could leave HP/Ability Score values, etc alone as if people are typing in those fields they're probably doing it on purpose, but Saving Throw proficiencies, Skill proficiencies, Inspiration, would be great if they could be locked down. Thanks!

**Comment by sdenec** [comment]
You now have a new GM setting to lock down sensible fields when the edit lock is active. Hope that suits your needs :)
