### ISSUE TITLE
Exhaustion is inaccessible with Token.getBarAttribute()

### ISSUE THREAD

**Issue by DJ4ddi** [sdenec/tidy5e-sheet#237]
Hi there.

I recently got a bug report on my module that the exhaustion attribute is not working with Tidy5e enabled (reference: https://gitlab.com/woodentavern/foundryvtt-bar-brawl/-/issues/8). I looked into this and found that this module breaks FoundryVTT's `Token.getBarAttribute` method because it stores the value as a string (while Foundry expects a number). For example, editing the exhaustion via the sheet results in `"5"` (string) rather than the expected `5` (number). It is checked using `Number.isFinite(data)`.

I have not checked whether this also happens for other values. It would be great to get this fixed and restore compatibility with the Foundry API.

**Comment by sdenec** [comment]
Should be fixed! Might be nessessary to switch exhaustion once if it wasn't 0.
