### ISSUE TITLE
Problem with Item Macro

### ISSUE THREAD

**Issue by 9ryex5** [sdenec/tidy5e-sheet#242]
Tidy5E works fine with [Item Macro](https://foundryvtt.com/packages/itemacro/) in Features Tab.
The issue is when you add a feature to favorites. Rolling it from the Attributes tab doesn't trigger [Item Macro](https://foundryvtt.com/packages/itemacro/) even though when editing the item in the Attributes tab the Item Macro is shown.

**Comment by sdenec** [comment]
Hm, that might be an issue more suited for the item macro module I guess. Propably doesn't recognize the items would be my guess. Totally possible because the favorites get loaded in fairly late by the script and thus might be ignored - though I don't know how item macro works exactly.

**Comment by 9ryex5** [comment]
I'll check with Item Macro dev then.
