### ISSUE TITLE
Long rest setting spell counts to zero

### ISSUE THREAD

**Issue by warfric** [sdenec/tidy5e-sheet#244]
- Foundry 0.7.9
- Tidy Sheet 0.4.14
- All other modules disabled

When I use the long-rest on a PC sheet, all available spell counts get set to zero. They should be set to max.

**Comment by sdenec** [comment]
Please update your dnd5e system. It's a system bug resolved in 1.2.2 I think. Current version is 0.1.4

**Comment by warfric** [comment]
Thanks that did it.
