### ISSUE TITLE
Ability UI Bug

### ISSUE THREAD

**Issue by GameCrazed** [sdenec/tidy5e-sheet#245]
Hi, created a new world with no other modules included except the tidy5e-sheet module. Upon opening a newly created actor all the attribute names, aswell as the Effects tab name, appear to be using their code names rather than their UI friendly names. I've made no changes to the settings aside from enabling the darkmode of the module and this issue seems to present itself regardless of that and across multiple worlds I've tested it against.

I reckon to have checked the issues list for this problem and haven't found any mention of it but I apologise if this is a duplicated issue. 

![Tidy5e Sheet UI Bug](https://user-images.githubusercontent.com/7393464/107545453-3c561000-6bc3-11eb-97ca-42c76568047c.PNG)

**Comment by sdenec** [comment]
Are you on dnd5e 1.2.4? This a rather curious bug, especially since there are no effects listed. My best guess is that you are on a very old 5e system.

**Comment by GameCrazed** [comment]
You are absolutely correct! It'd been a while since I dabbled in Foundry and I completely forgot you need to update the game system aswell! I was way back on v0.94. After updating to 1.2.4 it looks exactly like it should. Thanks for taking the time to respond.
