### ISSUE TITLE
[Feature request] Add "Always Prepared" to the Prepared/Unprepared menu

### ISSUE THREAD

**Issue by Juanfrank** [sdenec/tidy5e-sheet#247]
Greetings.-

Always prepared spells are one of the few things which have become really popular as class and subclass features in recent books. Therefore, I would like to ask for the possibility to add the "Always Prepared" option as one of the toggle options inside the right-click menu for spells, so as to quickly be able to configure those spells without the need to edit each one of them.

It wouldn't be a big priority, but a useful one nonetheless.

**Comment by sdenec** [comment]
Since always prepared spells are a one time setup I think the sheet can continue to omit that from the menu as to not clutter it too much. Besides "middle mouse click" to directly go to the editor exists if you want to streamline your setup process and save a few clicks.
