### ISSUE TITLE
Show Portrait / Show Token reveals hidden names when hidden with CUB

### ISSUE THREAD

**Issue by davidR1974** [sdenec/tidy5e-sheet#248]
"Show Players" option from Tidy5e Sheet reveals tokens name when option "Hide names Hostile NPC" is checked

![image](https://user-images.githubusercontent.com/77006061/107882230-73d8fb00-6ee8-11eb-9bfc-a10a1a54b4ea.png)

when switching to other NPC Sheets (monster blocks for example), the name is correctly hidden.

![image](https://user-images.githubusercontent.com/77006061/107882285-b4d10f80-6ee8-11eb-9041-35774ea20cac.png)

**Comment by sdenec** [comment]
Thanks, will be fixed!
