### ISSUE TITLE
dark mode drop down menus have white backgrounds making text hard to read.

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [sdenec/tidy5e-sheet#249]
dark mode drop down menus have white backgrounds with white text meaning that youd have to scroll with your mouse highlighted to see what the text actually says. the bacground of the drop down needs to fit the dark theme by being black behind it. if possible.

**Comment by sdenec** [comment]
I can't confirm this. I know that this was an issue a in the early 0.4 versions but was fixed. Shouldn't be an issue in 0.4.14 
![dropdown](https://user-images.githubusercontent.com/8881200/107892624-b4f00000-6f26-11eb-8307-6060ea90becc.jpg)
