### ISSUE TITLE
Empty action tab

### ISSUE THREAD

**Issue by DarKDinDoN** [sdenec/tidy5e-sheet#251]
Hello,

With the latest version, the action tab is showing up empty when the character action list module is not installed and activated.

**Comment by DivertedCircle** [comment]
Can confirm, also seeing this. Would prefer a toggle to enable it rather than it defaulting to a new page.

**Comment by sdenec** [comment]
This was an oversight on my part. Now the sheet checks if the module is enabled - otherwise the actions tab won't show up.
