### ISSUE TITLE
Item-Macro-enabled features don't fire their Item Macro workflows from the Favourites section

### ISSUE THREAD

**Issue by unsoluble** [sdenec/tidy5e-sheet#252]
Not sure if this is an [Item Macro](https://github.com/Kekilla0/Item-Macro/issues/9) or a Tidy issue, but here just in case: When items are configured with an Item Macro, they fire properly from the Inventory tab of a Tidy sheet, but not from the Favourites list. Something slightly different going on in there I imagine?

**Comment by Ikabodo** [comment]
I'm actually experiencing this on the feature tab as well. Macro's are not being fired from the feature tab. Pretty sure something happened in the last update, because it was working last friday (our last session). No messages in the console log.

**Comment by sdenec** [comment]
This is most likely a favorites issue. But I have to be honest - since I have tried to adapt the original Favorite Items module I don't understand fully whats going on in the code and how to change it so that item macros will fire from there. But Calego and I where thinking about a new module that combines features of actions list and favorites so there might be a good chance that this part of the sheet will be reworked and thus the item macro issue gets fixed along the way!

**Comment by Ikabodo** [comment]
I've done some more testing. And I've got it working, both with the favorites and the other tabs. Had to narrow it down. :)
On my end it was a missing setting in ItemMacro, the hooks were not set to true. (not sure why it was missing).

Not going to speak for @unsoluble though.

**Comment by unsoluble** [comment]
Sorry, didn't get a chance to test this again until now. I've got both the hook options enabled in Item Macro, but still don't get them called when rolling off Tidy's favs section.

**Comment by sdenec** [comment]
Honestly, I can't figure out why this isn't working. I'm prtty sure it has something to do with hirarchy and that the favorites get loaded in after the itemMacro script tries to get all the items but I have no idea how to fix that.

**Comment by kaelad02** [comment]
I just tested this and it worked for me too. I have the "Character Sheet Hook" and "Player access" settings for Item Macro enabled, and that's it.

Item Macro v1.5.7
Tidy5e Sheet v0.5.32

**Comment by sdenec** [comment]
Thanks for testing and providing a solution. I'll close this issue then :)
