### ISSUE TITLE
Actions Tab not showing everything

### ISSUE THREAD

**Issue by tagnullde** [sdenec/tidy5e-sheet#254]
Not sure if it's a tidy5e or actions module issue. But I'll start here.

For some reason not all available options are shown in the actions tab. 
Some Cantrips or Spells are shown. Some are not.

Actions visible:
![grafik](https://user-images.githubusercontent.com/44159008/108034701-2e2a4880-7036-11eb-8f80-0100c995b217.png)

Spells prepared / Always Prepared:
![grafik](https://user-images.githubusercontent.com/44159008/108034735-3da99180-7036-11eb-8611-94b6f296ca97.png)

As you can see, Mage Hand for example is present, but Prestidigitation is not. Although it's configured the same and both are 1 Action.

**Comment by sdenec** [comment]
I'm just leveraging the modules ability to integrate into a sheet, function issues should be addressed to @akrigline So currently I can't help with that, sorry!

**Comment by tagnullde** [comment]
No worries - will head over there then. ;)
Thanks!
