### ISSUE TITLE
Suggestion: Colour coded Spells (By Class)

### ISSUE THREAD

**Issue by theDinkus** [sdenec/tidy5e-sheet#255]
It would be nice to have alternative colouring options to match _which_ class has which spells prepared/always prepared.
Or even just for the sake of highlighting a spell so you don't forget to prep it if the idea comes across you mid session and you feel a long rest is a ways away.

I think something as simple as a HEX code input next to the prepared dropdown would be nice.

![Untitled-1](https://user-images.githubusercontent.com/72901444/108279597-1936dd80-713a-11eb-8daa-c05bd27189a2.png)

**Comment by akrigline** [comment]
Could DIY something like this, but I would advise waiting until this system issue is addressed:
https://gitlab.com/foundrynet/dnd5e/-/issues/1012

**Comment by Baffes** [comment]
+1 on this request. The feature request for the 5e system is not on a priority right now and a simple colour picker from here:
https://github.com/ardittristan/VTTColorSettings
would probably do the trick.

**Comment by sdenec** [comment]
I won't touch this request because of time issues. But If it becomes a core feature I'll do my best to intergrate it. Until then, sorry, no fancy spell colo coding.
