### ISSUE TITLE
CSS for NPC changes too

### ISSUE THREAD

**Issue by rinnocenti** [sdenec/tidy5e-sheet#26]
![image](https://user-images.githubusercontent.com/3178127/85214819-98bfa300-b346-11ea-955a-2ab519f4dfd6.png)
The CSS in NPC sheet change in highlights as Name, Attributes valor.. etc, for white in Dark version. making it difficult to read the npcs.

Could have a dark version for npc sheet too?

**Comment by sdenec** [comment]
Whoops! Bad css specificy. I will work on a fix for the next update! Thanks for reporting :)
