### ISSUE TITLE
Stats display

### ISSUE THREAD

**Issue by Grift3r777** [sdenec/tidy5e-sheet#260]
The display for Strength, Dex, Int, Cha, Con, and Wis read as DND5e.AbilityStrAbbr. Is it possible to change this so it just says Str

![Capture](https://user-images.githubusercontent.com/79666696/109213804-4b65c200-776e-11eb-8f74-4e43f79cd698.PNG)

**Comment by sdenec** [comment]
What dnd5e version are you running? Seems you are on a very old build and not up to date.

**Comment by Grift3r777** [comment]
Yeah that fixed it. I did not know i needed to update the game system. Thank you that will probably fix a few issues ive been having.
