### ISSUE TITLE
The senses trait is not hiding when empty

### ISSUE THREAD

**Issue by paulohdsc** [sdenec/tidy5e-sheet#261]
Even with the "PCs: Toggle empty character traits" option enabled and "hide empty traits" activated, the senses trait is not hiding when empty.

![image](https://user-images.githubusercontent.com/75817094/109576638-ea721d00-7ad2-11eb-8fc1-0fa67a78d951.png)

**Comment by sdenec** [comment]
Yeah, I know. Somehow the "senses" field is treated differently from the other fields and doesn't get an indicator if it is empty and thus can't be hidden like the rest. So while it is not a desired effect it is not per se a bug, just an oddity of the underlying original code of which the sheet is based on.
