### ISSUE TITLE
Incompatability with Better Rolls feature.

### ISSUE THREAD

**Issue by DivertedCircle** [sdenec/tidy5e-sheet#262]
The errors below are generated when logging into a game with both Better Rolls and Tidy5e enabled. The author of Better Rolls has indicated this is due to Tidy5e using a function that is deprecated in the current version of BR.

![image](https://user-images.githubusercontent.com/26470570/110050738-c6504f00-7d11-11eb-9977-521c95c997ab.png)

**Comment by sdenec** [comment]
The error messages should be gone. I have removed the deprecated BetterRoll Hooks.
