### ISSUE TITLE
[Feature Request] Adding Exhaustion applies the corresponding Exhaustion Condition

### ISSUE THREAD

**Issue by Nivrelin** [sdenec/tidy5e-sheet#264]
Hi,

I think it would be nice when you select the exhaustion level that the corresponding exhaustion condition (from e.g. Combat Utility Belt) would be applied/removed.

**Comment by sdenec** [comment]
it was originally my intend to apply the corresponding effects but that cause severe issues with the sheet. I'll continue to look into this though and hope I can figure out how to do it.

**Comment by sdenec** [comment]
The sheet now applies active effects for exhausion!
