### ISSUE TITLE
[Feature Request] Persistent Death Saves

### ISSUE THREAD

**Issue by danthemanb** [sdenec/tidy5e-sheet#267]
A very common homebrew change is to keep persistent death saves that go away upon a short or long rest.  The tidy5e sheet makes this impossible because it automatically removes all death saves upon coming back to consciousness. 

I attempted updating the Macros, death failures are checked before updating the CSS code.

This could be a pretty simple addition that allows for a very common house rule.

**Comment by akrigline** [comment]
I don't think this is within the scope of Tidy5e sheet as it is only a skin placed on top of the data provided by the dnd5e system. This kind of thing shouldn't be dependant on which sheet skin you choose to use.

**Comment by sdenec** [comment]
It seems the behavior of death saves in the default sheet has changed - or maybe it was always this way. I have implemented a function that will check if health is greater 0 and saves are not 0. It then will reset the saves to be 0. Well, removing this function  still has the same effect and so does the default sheet. My guess is Atropos changed the default behavior. And akrigline is correct, that's nothing I care to implement. The changes aren't quite as easy - you would have to somehow conditionally tap into the reset and rest mechanics. All that not regarding my layout choice to have the saving throws directly on the portrait.

There might be a way - but that might be equally complicated to achieve: While making death saving throws upon regaining health create a "Upon Death Door" passive effect that overrides death save failures/successes with the current value - depending on what the  house rule keeps - and let the effect be removed when taking a rest.

Sounds like it could be its own little module though.
