### ISSUE TITLE
Better Rolls 5e roll called from Inventory tab shows default roll chat card

### ISSUE THREAD

**Issue by struckyCZ** [sdenec/tidy5e-sheet#269]
So uhm, hello,
first time posting something here on GitHub.

Got to say I love this module and most of my players too.

But the last session we've encountered the problem described in the title. I've tried to replicate this with other sheets but to no avail and this lead me to thinking that it could be the Tidy Sheet's problem rather then Better Rolls' one, that's why I'm writing that here.

If the paladin wants to make an attack with a longsword and clicks that D20 button next to the item name in the Inventory panel, the result is the defaul FVTT attack card gets displayed in the chat, whereas when clicked from the Attributes panel then it shows the correct Better Rolls 5e chat card.

**Comment by sdenec** [comment]
Hey, thanks for the bug report. Though I think it might be a better rolls issue. I didn't change anything regarding item rolls. I even rolled back to my last sheet version and the issue is still there. Since better rolls was updated yesterday I figure the error occured then. I find it really strange that everywhere but in the inventory you can roll the items just fine - you'll even get the item roll buttons in the item description. Just clicking the item image in the inventory tab won't connect with better rolls ... I already contacted the author, maybe he can clear things up :)

**Comment by struckyCZ** [comment]
> Hey, thanks for the bug report. Though I think it might be a better rolls issue. I didn't change anything regarding item rolls. I even rolled back to my last sheet version and the issue is still there. Since better rolls was updated yesterday I figure the error occured then. I find it really strange that everywhere but in the inventory you can roll the items just fine - you'll even get the item roll buttons in the item description. Just clicking the item image in the inventory tab won't connect with better rolls ... I already contacted the author, maybe he can clear things up :)

Hah dude, you're the best for contacting him. I kinda struggle with writing in English and the idea of trying to explain the problem to somebody else once more was freaking me out. :-D

Thanks for looking into it.

**Comment by sdenec** [comment]
Hey, it's an item macro issue. If you have "character sheet hook" enabled it won't work with better rolls for some reason. There will be an update to betterRolls / libwrapper that might address this issue. In the meantime just deactivate that option in the item macro plugin :)

**Comment by struckyCZ** [comment]
Hi, I don't think I have such thing as this "hook", at least not intentionally. I haven't set any macros up also. I just run pure modules, since I've got no deeper knowledge of macro stuff etc. But I can still wait for an update, that's for sure. :-)

**Comment by struckyCZ** [comment]
Also, just noticed a funny thing. It does that only with the Paladin's longsword. It's not happening at other PC's so I guess I'll just try to delete that paladin's longsword and set the weapon up again from scratch lol.

Anyways, thanks sdenec for being helpul and bothering with replying to such petty issue. :-)
