### ISSUE TITLE
Issue in the skills column

### ISSUE THREAD

**Issue by DarKDinDoN** [sdenec/tidy5e-sheet#27]
Hi,

I have an issue in the skills column of the first tab. It's truncated and I can not scroll to reveal the bottom of this section. See screenshot:

![image](https://user-images.githubusercontent.com/1687854/85223345-c77b5f00-b3c2-11ea-9908-5e2fa6d6f97e.png)

FoundryVTT 0.6.3
DnD 0.9.3

**Comment by sdenec** [comment]
Hi, that is an 0.6.3 core issue. The font isn't rendering correctly and thus enlarging lines. I already informed Atropos of this and we are working on a fix. So for the moment I can't correct this, sorry!
