### ISSUE TITLE
Suggestion: Add modules with special support to README

### ISSUE THREAD

**Issue by Fallayn** [sdenec/tidy5e-sheet#270]
As a user of this module, it took me some time to notice the sheet has special support for things like *MidiQOL* or *Character Actions List dnd5e*. Having a section in the README to point out modules that add (supported/suggested, but optional) additional functionality to this sheet would be cool!

**Comment by sdenec** [comment]
Hm, I guess that list might get pretty extensive. I hope most modules are compatible. What exactly do you mean by the " (supported/suggested, but optional) additional functionality".
