### ISSUE TITLE
Currency Names Not Found

### ISSUE THREAD

**Issue by soundeffects** [sdenec/tidy5e-sheet#273]
There's an issue with the currency names as they appear in the sheet after the most recent update. Here's a quick screenshot I took:

<img width="684" alt="Screen Shot 2021-03-10 at 12 59 38" src="https://user-images.githubusercontent.com/6353447/110690096-bec0f800-81a0-11eb-9716-19b180cdff46.png">

**Comment by sdenec** [comment]
yeah, sorry for that. Fixed it!
