### ISSUE TITLE
Item info cards not visible for sheets using PopOut!

### ISSUE THREAD

**Issue by Stendarpaval** [sdenec/tidy5e-sheet#275]
The change in v0.4.18 to make item info cards stick out from the left side of actor sheets isn't ideal for users that use the [PopOut!](https://foundryvtt.com/packages/popout/) module. 

Before the change, the item cards were only visible in grid view and indeed took up quite a bit of space on the left side of the sheet, but since grid view is so compact this was an acceptable compromise. 

Now the item cards also show up in other tabs, which is very nice, but as mentioned before they don't show up at all for PopOut! users. Here's an example:
<img width="839" alt="tidy5e-popout-screenshot" src="https://user-images.githubusercontent.com/17188192/111031995-8fadbf00-840a-11eb-85ee-9deaf39ac4e5.png">
I'm considering going back to a version before this update, but also wanted to ask if it would be possible to add a setting to choose between showing the item card outside of the sheet, or within it. That would be amazing.

Also, I want to thank you for your phenomenal work on Tidy5e-sheet, it's a really popular upgrade among my players over the regular Foundry actor sheet. As a DM I also want to thank you for making it easier to track temporary hit points and short / long rests for NPCs.

**Comment by sdenec** [comment]
Thank you for the praise :)

Info Cards can now be set to float next to the cursor - this should be more suitable for the popOut-Sheet. Due to the nature of the PopOut mechanic it isn't possible to fix the card with the keboard though. Tried everything I could think of. Maybe I'll get it to work in a future update.

**Comment by Stendarpaval** [comment]
Being able to float item cards next to the cursor is amazing, and indeed solves this issue. Not being able to fix the card isn't too problematic; my players should be more than happy with it. Thank you!
