### ISSUE TITLE
Exhaustion Level 6 can't be deactivated!

### ISSUE THREAD

**Issue by Nargath** [sdenec/tidy5e-sheet#278]
One of my players decided to go clicking, and turned on Exhaustion Level 6 from the top left of his character portrait.
Now we can't turn it off, and his character is pretty much borked.

Any ideas?

**Comment by sdenec** [comment]
Well, that shouldn't happen. Did he try to set it to "0" and delete the lvl 6 effect if it still is active?

**Comment by Nargath** [comment]
When you take it to 6, it "kills" the character and the buttons around the portrait disappear, so you can't change it back.

I tried deleting the active effect, but it wouldn't delete at all. And couldn't disable it either

**Comment by sdenec** [comment]
Do you get any console errors? That somehow sounds like a different issue. 
This is how the sheet normally looks with lvl 6 exhaustion:
![exhaustion](https://user-images.githubusercontent.com/8881200/111455575-42856200-8716-11eb-8b2a-3da750203073.jpg)

If there isn't any exhaustion menu at all - did you maybe set the sheet option "Global: Disable exhaustion tracker"? That will hide the tracker completely and doesn't let you change the exhaustion lvl any longer. (This setting is only recommended when no actor has exhaution set and you don't want to use exhaution in your campaign.)

When you delete the effect it will reapply, that is correct but it seems the user interface not showing the exhaustion is your main issue here.

To get rid of the effect itself you could got once more into the setting and disable the exhaustion effects altoghether (Global: exhaustion effects) And the delete the lvl 6 effect on the actor. This way you should be able to "heal" your character and set exhaustion back to 0. If you reenable exhaution effects wihtout setting the actor to 0 is will reapply the effect though.

Anyway something else, not the effect, is set up wrong would be my guess ...

**Comment by Nargath** [comment]
Unfortunately we were mid session (this is our first using the 5e rules in Foundry), and I didn't think to jump into the console.

The Global option isn't set either.

I know he was randomly clicking on stuff in his character sheet and applying conditions, so it must of just been a combination of things that triggered the UI elements to not render. 

I have deleted the actor completely and resynced a new copy of it down from DNDBeyond, so its not an issue going forward.
And I tried setting it to level 6, and worked as you described above.
So not sure what he did!

I figured it was worth raising, just in case it turned out to be something more than my players acting like my 3 year old with a new toy!

**Comment by akrigline** [comment]
> I have deleted the actor completely and resynced a new copy of it down from DNDBeyond, so its not an issue going forward.
For the future if this or something similar happens again, you can avoid nuking and remaking the character by simply changing the sheet for the actor back to the default one, making changes, and then changing the sheet to Tidy agan.
