### ISSUE TITLE
[Feature Request] Use Combat Utility Belt for Exhaustion Status

### ISSUE THREAD

**Issue by Streyder** [sdenec/tidy5e-sheet#281]
It would be awesome if I could configure the player exhaustion tracker, to automatically set the relevant CUB condition (which uses DAE) instead of creating their own. In combination with this tutorial: https://www.foundryvtt-hub.com/guide/under-the-hood-enhancing-exhaustion-condition/ one would have perfectly synced exhaustion states, no matter where it is set.

**Comment by sdenec** [comment]
Setting the exhaustion condition won't affect the exhaustion tracker though as they are not linked. You can have the exhaustion 6 state set from the token conditions, the actor would still be on exhaustion 0. So I don't know if this suggestion will work the way you want it to.

**Comment by Streyder** [comment]
You can add this to the exhaustion effects:
![image](https://user-images.githubusercontent.com/18559266/111815580-229f9b00-88dc-11eb-86f5-f5b8b86bb5d3.png)
Maybe override is not the best case, but you get the idea

**Comment by sdenec** [comment]
You can now use custom effects created with CUB :)
I found override for the exhaustion value seems to be the best option, just fyi

If you want to adjust the macro from the tutorial to be configurable with the tidy5e settings you can use this

`
// Tidy5e CUB-Exhaustion macro
// requires Furnice and CUB

if (args[0] == "on") {
    // get custom exhaustion effect name and number of tiers from sheet settings
    // (this must be the same as set up in CUB!)
    const effectName = game.settings.get('tidy5e-sheet', 'exhaustionEffectCustom')
    const tiers = game.settings.get('tidy5e-sheet', 'exhaustionEffectCustomTiers')

    var exNew = args[1].efData.label
    
    // loop levels and remove if effect is active
    for(let i = 1; i <= tiers; i++){
        let ex = `${effectName} ${i}`
        if ((ex != exNew) && (game.cub.hasCondition(ex))){
            await game.cub.removeCondition(ex)
        }
    }
}
`
