### ISSUE TITLE
Feature Request - Named Containers in Features Tab

### ISSUE THREAD

**Issue by apoapostolov** [sdenec/tidy5e-sheet#282]
Rather than generic Passive and Active abilities, allow to create named container sections that player can use to bundle together several features that have similar source, function or effect.

For example, a user could create
- Container 'Human' to put all Human Features
- Container 'Class' to put all Class Features together
- Container 'Feats' to put all optionally selected Feats together
etc.

**Comment by akrigline** [comment]
This sounds like an "inventory+" but for features. IMO it would be better as a standalone module...

**Comment by sdenec** [comment]
Yeah, I don't think I will implement this. Apart from my lack of knowledge how to approach this, I think this might be a request actually well placed with the developer of inventory+ as akrigline suggested. I bet he has the basic structure or at least the knowledge down to build this. Though I don't know if this feature really is this high in demand to make it happen.

I'll close this request but thanks anyway for the suggestion!
