### ISSUE TITLE
[Feature Request] Item Value visible in List Layout

### ISSUE THREAD

**Issue by samgrieve** [sdenec/tidy5e-sheet#284]
My players are constantly looting NPCs and selling stuff and frequently request whether it would be possible to have values displayed on the list view for inventory.

**Comment by sdenec** [comment]
I chose a middle ground solution: Item value is now displayed in the item info card (next to quantity).
Also there is no calculated total value for item quantities, so it will be displayed as "X * X.XX GP".
I hope that is something your players can work with^^
