### ISSUE TITLE
[Feature Request] "Prepared" Cantrips

### ISSUE THREAD

**Issue by git-kor-av** [sdenec/tidy5e-sheet#287]
Currently when you choose the "Prepared" filter on the Spells tab it ignores Cantrips.  While I understand Cantrips are technically "Always Prepared", Tasha's Cauldron of Everything provided Wizards with an optional rule stating the following:

 _Cantrip Formulas TCE p75

3rd-level wizard optional feature

You have scribed a set of arcane formulas in your spellbook that you can use to formulate a cantrip in your mind. Whenever you finish a long rest and consult those formulas in your spellbook, you can replace one wizard cantrip you know with another cantrip from the wizard spell list._

From a functional perspective you theoretically could remove a cantrip and readd it, but if you are doing this with each long rest it can be tedious to manage.  I've been using Cantrips as "Prepared" Spells instead, which makes it easy to manage.  However this leads to two problems.

1)  As noted above, the Prepared Filter doesn't filter out Unprepared Cantrips.
2)  There are no context menu's or quick buttons to easily prepare/unprepare cantrips.

**Comment by sdenec** [comment]
This is something the 5e system should handle. Filters are provided by the core system, not the sheet. Your suggestion would most likely be better placed in the dnd5e repo.

**Comment by git-kor-av** [comment]
Thank you, I was unaware that this functionality was more part of the system.  I'll make the recommendation there.
