### ISSUE TITLE
 [Feature Request] Appearance Characteristics

### ISSUE THREAD

**Issue by Ghostdesu** [sdenec/tidy5e-sheet#288]
Since tidy5e already added personality traits missing in the default sheet, I think it would be cool if you could add something to replicate roll20's bio tab:
![image](https://user-images.githubusercontent.com/31375910/112755141-173d2580-8fe8-11eb-9dd3-e4c80392342f.png)

I always found it helpful for quick reference so I think it would be a great addition.

Maybe you could also implement adding custom fields, though I don't know how doable that would be with foundry structure.

**Comment by sdenec** [comment]
The next update will feature these details in the biography tab!
