### ISSUE TITLE
[Feature Request] - Print Character Sheet to pdf

### ISSUE THREAD

**Issue by Mushie1** [sdenec/tidy5e-sheet#289]
I would be great if it were possible to print the character sheets to pdf. (or just a printer).
The only way I have found to do it is to use "pop out" module and then print from the web browser, which is not formatted in the best way, and doing this way you have to print individual tabs within the sheet.
Thanks :)

**Comment by sdenec** [comment]
Yeah, I don't think this is a function I can add. It's really not in the scope of the digital sheet and foundry I'm afraid.

**Comment by Mushie1** [comment]
bummer, thanks for the feedback. Perhaps I'll put in the suggestions list on the Foundry Discord.
