### ISSUE TITLE
Exhaustion icon doesn't appear on avatar when using CUB

### ISSUE THREAD

**Issue by cs96and** [sdenec/tidy5e-sheet#291]
If you use option to use CUB exhaustion effects, then the dynamic effect is applied, however the icon on the avatar on the sheet doesn't update to show the sad face, and stays at at level 0.

**Comment by sdenec** [comment]
Hi, you have to set up your custom exhaustion effects with cub. Sinde the exhaustion menu is only used to trigger the effects you have to add an override for the actual exhaustion value into the effect. So Exhaustion 1 get an override to set the actor's exhaustion to 1 and so forth.
Here's an image for Exhaustion 3 example:
![111815580-229f9b00-88dc-11eb-86f5-f5b8b86bb5d3](https://user-images.githubusercontent.com/8881200/113017162-784b3180-917f-11eb-90e5-20ee0b124017.png)
You can use this guide to switch out the effects (higher tiers cancel out lower tiers) https://www.foundryvtt-hub.com/guide/under-the-hood-enhancing-exhaustion-condition/ you just have to midify the tutorial and add the exhaustion value override. Hope this helps?

**Comment by cs96and** [comment]
Ah OK, that makes sense, thanks.

However, I set up the exhaustion levels in CUB, but if you set your exhaustion level on a scene that does not have your token, you get an error "Can't find actor token to apply exhaustion effect to."

I think the CUB method is too fiddly and will probably just stick to the built in Tidy5e stuff.  The only reason I wanted to use CUB is so that a marker appears on your token.  Is there any way you could make your exhaustion effects do that by making them temporary instead of passive?

**Comment by sdenec** [comment]
The error is intentional as it is required to target a token to apply the CUB effect. To be honest, I don't know. So far I've only found ways to create passive effects. I'll investigate and see if it is a) possible b) has any disadvantaged over passive effects.

**Comment by sdenec** [comment]
Well, it seems is isn't as trivial as I thought to add an active effect to an actor. So for now the only options I can offer are the ones already made available. Sorry!
