### ISSUE TITLE
REQUEST: Player Name entry

### ISSUE THREAD

**Issue by GambetTV** [sdenec/tidy5e-sheet#293]
Just a QOL suggestion, but could you add a spot, maybe on the same row as Size/Race/Alignment for "Player Name"? I'm running a massive game with over 50 players, and keeping track of everyone is a bit of a pain, and something like this would be really cool!

**Comment by sdenec** [comment]
Next update will feature a new setting (in DM settings tab) to show an input field below the character name to enter the players name. Hope this helps :)
