### ISSUE TITLE
Feature Request: Option to sort spells (per level) alphabetically

### ISSUE THREAD

**Issue by spirritus** [sdenec/tidy5e-sheet#294]
Currently the list of spells is ordered by time of import. An option (maybe clicking on the spell level header) to sort alphabetically would greatly enhance usability. Especially for long spell lists, e.g. cleric.

**Comment by sdenec** [comment]
I don't know if I will implement this into the sheet. In the meantime you can try "Illandrils Inventory sorter (5e)". Though it seems it will sort your items permanently in an alphabetically order without the amility to manually sort until you deactivate the mod again.
