### ISSUE TITLE
Speed doesn't display

### ISSUE THREAD

**Issue by jayhide** [sdenec/tidy5e-sheet#297]
Experiencing an issue where, while the module is active, the speed section is always blank on sheets. Currently on Foundry 0.7.9. Mousing over it causes the wheel to appear but clicking it does nothing.

![image](https://user-images.githubusercontent.com/59358264/113975051-c7363e00-97f3-11eb-9172-8a93e69d6ee3.png)
![image](https://user-images.githubusercontent.com/59358264/113975628-a5898680-97f4-11eb-9605-d21add741c9a.png)

**Comment by sdenec** [comment]
Please check if you are up to date with the sheet (0.4.25) and dnd5e!

**Comment by jayhide** [comment]
Oh, looks like I just failed to realize that you need to update dnd5e as well! Thanks, closing this!
