### ISSUE TITLE
translation item card need

### ISSUE THREAD

**Issue by EternalRider** [sdenec/tidy5e-sheet#298]
```
<p><span class="key">X</span> hold key to interact with card.</p>
<p><i class="fas fa-mouse"></i> middle mouse to view/edit item.</p>
```

at the following html: 
templates/actors/tidy5e-npc.html
templates/actors/tidy5e-sheet.html
templates/actors/tidy5e-vehicle.html

translation support please.

**Comment by sdenec** [comment]
Missed that. Will be available in the next update!
