### ISSUE TITLE
Suggestion: Optional Ressource Field for NPC Sheets

### ISSUE THREAD

**Issue by Sekierer** [sdenec/tidy5e-sheet#299]
Basically what the title says. I assume it'd have to be toggleable in the module settings as a majority probably wouldn't use/need it? Like the Legendary Actions/Reistsnace/Lair ones, right below there for example

Sometimes I have NPCs that I would like to enter 1 or 2 more small things in a way it's easy to see, same as the ressources in the PC Sheet. Converting them to PC sheets is the workaround but doing all of that just to get that 1 ressource field, while losing the neatness of the NPC sheet is a bit of a bummer.

Obviously just a suggestion I would appreciate. Don't know how many others see it the same way

**Comment by sdenec** [comment]
I'm not really good in adding dynamic content to the sheet, sry. But maybe this would be a good addition to the "ressource +" module (if it isn't already a feature). Maybe have a look at that :) https://www.foundryvtt-hub.com/package/resourcesplus/
