### ISSUE TITLE
Info Button for NPCs?

### ISSUE THREAD

**Issue by callenlatz** [sdenec/tidy5e-sheet#303]
With Midi QOL for an NPC sheet the GM can click an item "Info" button to send the description to chat, however this doesn't seem to work with Tidy5e-sheet? With Midi QOL there is an option to add attack/damage buttons to items in sheets, and so this also adds the info button function to the slide out card on tidy5e-sheet but only works for players and not NPCs when clicked.

**Comment by sdenec** [comment]
Whoops. Just released a bug fix for the midiQol buttons on NPC item cards - this should now work (also for features on PCs). Thanks for the bug report.
