### ISSUE TITLE
Feature Request: Subtract Health button

### ISSUE THREAD

**Issue by Fallayn** [sdenec/tidy5e-sheet#308]
Could we have a simple minus button near the health on the sheet that opens a popup to enter damage to subtract? :)

Would be very useful for less automated games.

P.S. the new appearence section is cool, but localisation isn't applied to the labels :)

**Comment by sdenec** [comment]
Hi. You can simply type "+10" or "-10" into the health field and the sheet will calculate the result. Default behaviour ;)
Translation for Age, Height, etc. ist in place. Maybe check if you have the latest update (0.4.28). Was added in short succession as I indeed forgot to add the strings.

**Comment by Fallayn** [comment]
D'oh! Nevermind then :P
