### ISSUE TITLE
Possible Error when opening Vehicle Actor Sheet

### ISSUE THREAD

**Issue by shinkei13** [sdenec/tidy5e-sheet#309]
Foundry: v0.7.9
Tidy5e-Sheet: v0.4.28

Whenever I open a Vehicle actorsheet, I get the following error in the console: `Uncaught (in promise) TypeError: Failed to execute 'setProperty' on 'CSSStyleDeclaration': 2 arguments required, but only 1 present.`

The error exists on line 166 of tidy5e-vehicle.js: `$('.system-dnd5e').get(0).style.setProperty('--vehicle-border');`

I've attached a screenshot of exactly what appears. It does not prevent me from opening the sheet, however the constant output makes it difficult to troubleshoot other errors.

<img width="1661" alt="Screen Shot 2021-04-16 at 9 30 45 PM" src="https://user-images.githubusercontent.com/33383758/115099604-a610d400-9efc-11eb-999e-1ef964d976da.png">

**Comment by sdenec** [comment]
Thanks, your hint lead to another error on the vehicle sheet. Will be fixed in the next update!
