### ISSUE TITLE
[Feature Request] Include a range collumn in the spellbook

### ISSUE THREAD

**Issue by spirritus** [sdenec/tidy5e-sheet#310]
Currently the spellbook does not offer a quick way to see the ranges of you spells.
The target collumn is awesome but only half the picture.

**Comment by sdenec** [comment]
Range column for PCs spells is now included. On NPC sheets there is very little space. Though you will get the range if you place the curser for a few seconds over the target text and the item info card has the range in the bottom tags as well. If I find a solution to I'd might add it as a column at a later point.
