### ISSUE TITLE
[Feature Request] Visual marker for spell slots

### ISSUE THREAD

**Issue by Kudusch** [sdenec/tidy5e-sheet#312]
I'd be nice to have a visual spell slot tracker, like the ones used by D&D Beyond.

![spellslots](https://user-images.githubusercontent.com/1136612/115398828-d8198300-a1e7-11eb-8494-9a6b8506f843.jpg)

One way to do this would be adding this line to the spell book template (`src/templates/actors/parts/tidy5e-spellbook.html`) after `div.spell-detail.spell-slots` section and adding an image resource that are named appropriately (e.g. `3-2.png` for three spell slots with two uses, i.e. one unused spell slot).

`<img src='modules/tidy5e-sheet/images/spellslots/{{section.slots}}-{{section.uses}}.png' style='height: 15px;'>`

I'd be happy to create a pull request for that implementation, but I'm not sure that this approach is the smartest, as I am unfamiliar with the development of FVTT modules.

**Comment by sdenec** [comment]
Using images is pretty unflexible and unwieldy as each possible combination of spellslot totals and available slots would have to be created and references. I think I'd try to solve it with javascript and css. Having something like this also is a 100% guarantee that folks will try to click the boxes to set or spend spell slots which adds another layer of complexity. I'll think about this feature request but can't promise anything or give a timeline.

**Comment by Kudusch** [comment]
Thanks for responding so quickly! Yeah, the image based solution isn't great, I agree. It was just the easiest way to patch that feature in for my group :)

**Comment by NeV3rKilL** [comment]
> Using images is pretty unflexible and unwieldy as each possible combination of spellslot totals and available slots would have to be created and references. I think I'd try to solve it with javascript and css. Having something like this also is a 100% guarantee that folks will try to click the boxes to set or spend spell slots which adds another layer of complexity. I'll think about this feature request but can't promise anything or give a timeline.

You can take inspiration from: https://user-images.githubusercontent.com/9851733/115126329-9cf03780-9fce-11eb-953f-96cc54a097c4.png

used in: https://github.com/fvtt-fria-ligan/forbidden-lands-foundry-vtt

**Comment by Kudusch** [comment]
I build a little add-on using css for the spell slots using tidy5e-sheets hooks: https://github.com/Kudusch/better-spell-slots

They are still not clickable, tho.

**Comment by sdenec** [comment]
Cool! When I find the time I'll have a look. Maybe I can expand on it and integrate it into the sheet - if you don't mind. As alway no idea if and when this will happen. But I'm always happy if someone contriubtes :)

**Comment by Kudusch** [comment]
> Cool! When I find the time I'll have a look. Maybe I can expand on it and integrate it into the sheet - if you don't mind. 
Sure, you can use the code if you want to! 

I could try and implement this in tidy5e-sheet myself if you're open to pull requests :)

**Comment by sdenec** [comment]
never say never! Thanks to @p4535992 I was able to adapt and include his suggested addition. Finally :)
