### ISSUE TITLE
[Issue] Problems with layout toogle

### ISSUE THREAD

**Issue by miguel-pinto-prodmad** [sdenec/tidy5e-sheet#314]
There is an issue with the Grid/list layout toggle. When the layout is using "Grid layout" it's not possible to go to any other tab on the sheet other than Attributes and Inventory.

**Tidy5e Sheet:**  0.4.28
**DnD5e:** 1.2.4
**Core:** 0.7.9

**Comment by sdenec** [comment]
Works fine for me. Most likely a module conflict I would guess ...

**Comment by aprusik** [comment]
I am having the same issue. I've got a bunch of modules installed and haven't had the chance yet to go through them, but I thought I'd document I also have the issue here. I'll update this once I comb through the modules to see what might be causing the issue.

**Comment by sdenec** [comment]
Any insights on this? Did you figure out which module interferes with the sheet?

**Comment by PalaNolho** [comment]
Sorry for the delay.
Yes, I found the source. I already spoke with the other mod owner and it will be fixed on its next release.
I have msg you in discord with details.

**Comment by sdenec** [comment]
Thank you! I'll close this issue then :)
