### ISSUE TITLE
[ Feature Request ] Add characteristics to NPC sheet

### ISSUE THREAD

**Issue by MarceloCortezz** [sdenec/tidy5e-sheet#315]
The last updates we saw the addition of PC characteristics in their sheets:
![image](https://user-images.githubusercontent.com/79060716/115921282-a9064a00-a451-11eb-84dc-d7fc1bcd7e2f.png)

I'd like to know if it's possible to add them to NPC sheets as well, for me to track NPCs informations like players track theirs.

**Comment by sdenec** [comment]
Sure, can do! Next update will have the same fields on NPCs.
