### ISSUE TITLE
[Issue] Cannot find Enable Traits Label setting

### ISSUE THREAD

**Issue by hanhmchau** [sdenec/tidy5e-sheet#317]
Hello,

I am referring to the setting that shows the labels "Languages", "Weapon Proficiencies", "Damage Vulnerabilities" etc. in this section of the sheet:
![https://i.imgur.com/2InTsen.png](https://i.imgur.com/2InTsen.png)

After updating to 0.4.28 I cannot find this setting in the Tidy5e's setting configuration anymore. I have tried both as GM and player and still cannot find it. I've checked in the "Sheet Settings" popup as well.

A quick look at [this file](https://github.com/sdenec/tidy5e-sheet/blob/master/src/templates/settings.html) seems to show that there's no "traitLabelsEnabled" setting here and the relevant setting is set as `config: false` [here](https://github.com/sdenec/tidy5e-sheet/blob/master/src/scripts/app/settingsList.js#L96) too.

Please let me know if this is intentional and the setting should be hidden.

Thanks

**Tidy5e Sheet**: 0.4.28
**DnD5e**: 1.2.4
**Core**: 0.7.9

**Comment by sdenec** [comment]
Whoops. Must have dropped the actual switch when I built the custom menu! Next update it will again be available to players under the "Players" Tab. Thanks for the report!
