### ISSUE TITLE
[Issue] Spellcasting section for NPCs broken

### ISSUE THREAD

**Issue by apoapostolov** [sdenec/tidy5e-sheet#320]
![image](https://user-images.githubusercontent.com/4083812/116001308-819fb080-a5fc-11eb-9cb2-4f7ef97b32a5.png)

**Comment by apoapostolov** [comment]
It also looks bad for PCs, although not as critical

![image](https://user-images.githubusercontent.com/4083812/116001588-cbd56180-a5fd-11eb-924e-80f4cedd5056.png)

**Comment by sdenec** [comment]
I'd say you have mess installed. The sheet itself works fine.

**Comment by apoapostolov** [comment]
Thank you, I found the conflicting option and turned it off.

**Comment by sdenec** [comment]
👍🏻
