### ISSUE TITLE
Issue with "let's trade" module

### ISSUE THREAD

**Issue by Avitale34** [sdenec/tidy5e-sheet#322]
In the past I have used both of these modules without issue but it seems like something recently happened where the buttons for send money to players and the attunement tracker now overlap.
![image](https://user-images.githubusercontent.com/65961637/116188177-f0603500-a6f4-11eb-99b6-3ff1119774b8.png)

**Comment by sdenec** [comment]
Hm, ccan't say I can confirm this ... Maybe yet another module that screws up the layout?
![Screenshot 2021-04-27 083932](https://user-images.githubusercontent.com/8881200/116196703-1fe26200-a734-11eb-8165-b7580f21a410.jpg)

**Comment by Avitale34** [comment]
I tracked it down to the "Mobile Improvements" Module.

**Comment by sdenec** [comment]
Great to hear you found the culprit. I'd advise to open an issue with the mod developer and ask for a fix :)
