### ISSUE TITLE
Unable to remove spell from custom npc.

### ISSUE THREAD

**Issue by kuchrk24** [sdenec/tidy5e-sheet#325]
![image](https://user-images.githubusercontent.com/74018852/116955634-1770b680-ac61-11eb-9d0d-41aa9dc8a9c6.png)

Lock is disabled. Clicking on spells in the spellbook does not bring up the context menu where I can usually see edit/delete. Works for other npc features. I am forced to change the sheet back to default in order to delete spells.

FVTT 0.7.9
DND 5e 1.2.4
TidySheet 0.4.0

**Comment by sdenec** [comment]
Hi, you are waaaaay behind with the tidy5e version. current version is 0.4.29! Seems your module got stuck on the initial release. I'd suggest uninstalling and reinstalling the sheet. There was a lot of new stuff and bug fixes added since 0.4.0!

**Comment by kuchrk24** [comment]
Yes I am.... sorry about that. Now I'm wondering how many of my other modules are stuck...

**Comment by sdenec** [comment]
I think you should be good. I switched the method how my module was updated and somehow it got stuck for some. With the fresh install this shouldn't happen any longer!
