### ISSUE TITLE
[Feature Request] Implement a rounding feature for NPCs in the hit dice UI.

### ISSUE THREAD

**Issue by juliandeleonguerrero** [sdenec/tidy5e-sheet#326]
Both in the NPC Tidy Sheet, and in the default Foundry sheet, the hit dice UI does not support rounding the HP dice automatically, only rolling it randomly.  It is up to the user to do the math to determine the average HP of a monster from the hit dice they add.

I propose adding the ability to right-click on the hit dice icon on the sheet, which will automatically round the HP dice according to standard 5e rules.  This would greatly expedite homebrew and provide a lovely QoL improvement to the module, further enhancing it beyond the capabilities of the default sheet.

I will pay you $10 USD to implement this.  Hit up DestinyGrey#2890 on Discord for the money.

**Comment by sdenec** [comment]
This feature was just implemented :)
