### ISSUE TITLE
Bug: Players with "Observer" permission can trigger saving throw / ability check rolls

### ISSUE THREAD

**Issue by Merudo** [sdenec/tidy5e-sheet#328]
A player with "Observer" permission on an actor is not supposed to be able to launch a roll or edit that actor.

Yet, a player with "Observer" permission can click on the modifier right below the six attributes (str/dex/con/int/wis/cha) and trigger a roll that way

Here is an image where I have circled where a player can launch a roll they do not have the permission for:

![image](https://user-images.githubusercontent.com/7371085/117096640-5705d400-ad2f-11eb-84b4-c2ec7e61cf4a.png)

This bug affects Tidy 5e sheets for both PCs and NPCs.

**Comment by Merudo** [comment]
I think it might be due to a missing `rollable` around here: https://github.com/sdenec/tidy5e-sheet/blob/acc10459da76f46312017b18a7559a297f98a3dd/src/templates/actors/tidy5e-sheet.html#L240

**Comment by sdenec** [comment]
Fixed! It was a combination of a missing rollabe class and the class reference in the click function. Thanks for the hint and general bug report!
