### ISSUE TITLE
Not compatible with Skill Customization for 5E mod

### ISSUE THREAD

**Issue by apoapostolov** [sdenec/tidy5e-sheet#33]
Previous version was fully compatible with the wider skill table due to additional dropdown and value fields. 0.2.0 and onward causes the issue below:

![image](https://user-images.githubusercontent.com/4083812/85312715-e27fc900-b4bf-11ea-8d20-a856f09cb383.png)

**Comment by sdenec** [comment]
Talked to the module creator. It's better he adjusts the sheet for his module - so this should be fixed in his next update!
