### ISSUE TITLE
Doubled “Items” on Character Sheet

### ISSUE THREAD

**Issue by ratzofftyoya** [sdenec/tidy5e-sheet#330]
In my Forge instance (not outside of the Forge), character class is shown in duplicate rows below the character name. Also, the “add to favorites” option appears twice in the right click menu for all items, and whenever either of those options is clicked, the item is added to favorites twice.

**Comment by sdenec** [comment]
That sounds more like a forge specific issue. Also a little strange that this is the first time someone reports this issue. Maybe you have a module conflict? Could you check if it happens if only the sheet is active?

**Comment by ratzofftyoya** [comment]
I have disabled all other modules. Someone else on forge discord reported
having the same issue!

**Comment by sdenec** [comment]
I would like to ask you to address this issue with the forge dev. I know there have been issues in the past with the sheet and the forge that where fixed by them. Right now I do not know how I should address this as is it working fine outside the forge environment 🤷🏻‍♂️ Sorry!

**Comment by ratzofftyoya** [comment]
Thanks!

**Comment by JonDemand** [comment]
I had this same issue starting on friday,  i think i found what was causing it,  i installed a module called Tool Proficiency for dnd5e,  which doubled up a lot of things,  disabling the module removes the doubling up
