### ISSUE TITLE
Foundry 0.7.9 allows upgrading to tidy5e 0.5.0, even though it is no longer compatible

### ISSUE THREAD

**Issue by cs96and** [sdenec/tidy5e-sheet#333]
I am running Foundry 0.7.9.  When I check for updates for some modules (e.g. Token Auras), it says the upgrade is blocked because the latest version of the module requires Foundry  0.8.1.

I notice that the `module.json` in the latest version of tidy5e (0.5.0) says it has a minimum Foundry version of 0.8.2, however, Foundry does not block it and will still let me upgrade to that version.  I am reluctant to upgrade to 0.5.0 in case it breaks something.

**Comment by sdenec** [comment]
Hm, that is strange. I put the minimum version in the madule.json AND in the foundry repo ... I thought that would be enough to prevent older versions to pull an update ... I actually don't know any other way to prevent that

**Comment by sdenec** [comment]
I messed up my files and edited an old file. Caused me some confusion but now it shouldn't want to update anymore! Thanks for making me aware :)

**Comment by sdenec** [comment]
Oh, btw. it shouldn't have been a huge issue if you actually did the update. The main change was the "type" field for npcs that simply wouldn't show pre 0.8.3. At least that's the case for me because I noticed my current 0.7.9 install did the 0.5.0 update for the sheet. World is still standing^^
