### ISSUE TITLE
"Type" Missing from NPC Sheet

### ISSUE THREAD

**Issue by gabrieljtaylor** [sdenec/tidy5e-sheet#334]
The NPC sheet does not expose a field to set or view an NPC's Type (e.g., "Fey", "Beast", "Humanoid", etc.). This field is present and exposed on the default Foundry sheet, just not Tidy5E's sheet. I have looked in the settings for any options to enable the field, but have not found any.

Is there already a plan to expose this field, even optionally? If not, could there be? Thanks!

**Comment by sdenec** [comment]
Hi, you probalby updated the sheet to 0.5.0 while you are still on the 0.7.9 core. The version requirements got messed up and 0.5.0 was flagged to be compatible with the old version. If you want to get the type field back please uninstall tidy5e and reinstall it. It should automatically pull the 0.4.29 version!

**Comment by gabrieljtaylor** [comment]
Ah, yep, that's surely it. Good to know it's just a version issue! I'll revert back to 0.4.29 for now. Thanks!
