### ISSUE TITLE
[Feature Request]: Please add a Coinage area

### ISSUE THREAD

**Issue by CixrTyx** [sdenec/tidy5e-sheet#335]
Please add an area (maybe under spells) for coinage!
I'm playing 5E system.

**Comment by sdenec** [comment]
Sorry, I'm confused. What do you mean by coinage? Like a place to story copper, silver, electum, gold and platinum pieces?

**Comment by CixrTyx** [comment]
> Sorry, I'm confused. What do you mean by coinage? Like a place to store copper, silver, electum, gold and platinum pieces?

Yes please. This Ogre in the screenshot has 500gp on its persons, but I had to switch sheets to add that on there:
![image](https://user-images.githubusercontent.com/35784701/119212636-ad8d4500-ba87-11eb-9968-790b9da96da1.png)

**Comment by sdenec** [comment]
Ah, it's about NPC sheets! Hm, the default sheet doesn't offer coin management for NPCs. I'm not sure if can add this feature on my own. But I'll keep it in mind.

**Comment by SR5060** [comment]
Agree this would be super handy for loot sheet streamlining

**Comment by sdenec** [comment]
NPCs will have a currency section in the next update! Located between the inventory and the spellbook.
