### ISSUE TITLE
[Feature Request] : Option to Hide or Edit the "Mechanics/Flavor Text" Header

### ISSUE THREAD

**Issue by Krahnin** [sdenec/tidy5e-sheet#336]
I'd like to request an option to hide or edit the "Mechanics/Flavor Text" header on the top of certain sheets, specifically loot type items, Many of the things I am creating the header seems unnecessary/does not fit. e.g. creating a book as an item that a vendor might sell or to be found in a lootable container. The header throws some of my players off and I have at multiple times needed to explain it should be ignored.

**Comment by sdenec** [comment]
Hi, I don't see an issue with the headline but can understand if it doesn't fit your item texts.
It's a bit much to add a specific setting for this though.
I want to suggest another option: Use the custom css module to customize the sheet.
To remove the heading simply add the following as a rule in the css editor:

´´´css
.tidy5e .editor .details-headline {
		display: none;
}
´´´
You can only remove the heading for all item types, it's not possible to just remove it from loot.
Hope this helps!
