### ISSUE TITLE
Multiple journal fields can be opened at the same time for editing, but only one can be saved.

### ISSUE THREAD

**Issue by Dumbhuman** [sdenec/tidy5e-sheet#34]
If more than one field in the journal tab is open for editing, clicking save on any one of those fields will close/save that one, but also close all other open fields without saving (losing any changes).

**Comment by sdenec** [comment]
This is an ongoing issue. I still couldn't figure out how to change that behavior. If you have any insight coding wise I'd appreciate the help^^

**Comment by Dumbhuman** [comment]
I wish I could be more helpful than just pointing out a problem you had already seen, but I'm effectively a non-coder who only knows enough to make the most minor changes.

**Comment by sdenec** [comment]
Finally it is done! You now should be able to edit all fields at you hearts content and save all when one editor is saved!
