### ISSUE TITLE
Attunement for 0.8.X

### ISSUE THREAD

**Issue by ExileofBrokenSky** [sdenec/tidy5e-sheet#341]
Major updates sure are fun eh?

Anyways number of attuned slots being used no longer updates for Foundry 0.8.6

![image](https://user-images.githubusercontent.com/28786777/120523755-4b481480-c3a4-11eb-94ac-c2edf89da023.png)

**Comment by sdenec** [comment]
Uh, I'll have to look into that! Thanks for letting me know :)

**Comment by sdenec** [comment]
Fixed!
