### ISSUE TITLE
Localization alphabetical sorting: skills, languages...

### ISSUE THREAD

**Issue by LordJovanius** [sdenec/tidy5e-sheet#342]
If you use the sheet in any other language than Foundry's native tidy-5e sheet doesn't sort skills, languages and so on to adapt to localization language. I know they manage to do it in main 5e system, I don't know if it's possible to do here.

I've been using this awesome sheet in english for a long time, but in a new campaign my players ask me to change language and I realized this "issue".

Thanks for the good work!

**Comment by sdenec** [comment]
For sure! I didn't notice this was a change made with a recent update. Easy to implement. But it seems to only affects the skills list. Traits are always sorted the same. But I'll fix the skills for the next update!

**Comment by LordJovanius** [comment]
Thanks a lot! We're gonna love that

**Comment by sdenec** [comment]
It should work now :)
