### ISSUE TITLE
New NPCs Have No Creature Type

### ISSUE THREAD

**Issue by VoltCruelerz** [sdenec/tidy5e-sheet#343]
With the change to the sheet that made creature type a popup dialog, this does not appear to display on creatures that have not already been assigned one, forcing the user to switch back to the default 5e sheet to assign an initial one.

![image](https://user-images.githubusercontent.com/4068550/120816236-91c17e80-c51e-11eb-9bd1-8ff94810b29a.png)

**Comment by juliandeleonguerrero** [comment]
I have this issue as well, and I tested it with no modules except for Tidy Sheet enabled to double check.  Here's an existing sheet that had creature types before: 

![image](https://user-images.githubusercontent.com/78201899/120915545-3902fa80-c672-11eb-98fd-79df875e3a8b.png)

And here's a sheet that I made from scratch in 0.8.6: 

![image](https://user-images.githubusercontent.com/78201899/120915563-491ada00-c672-11eb-8859-84b40cd67002.png)

**Comment by sdenec** [comment]
Confirmed. Though I'd like to think that this is also a system fault. Every NPC should come with a default type, e.g. "humanoid" in my opinion. But I'll try to fix this :)

**Comment by sdenec** [comment]
I take it back. Even if there was a default tyoe it would be possible to unset the type and rendering the type attribute empty leading to a non selectable type configuration. In short: my mistake but an easy one to fix. Will be in the next update!

**Comment by sdenec** [comment]
Fixed!
