### ISSUE TITLE
[FEATURE REQUEST] Allow us to modify hit dice by double-clicking on the hit die field

### ISSUE THREAD

**Issue by ctbritt** [sdenec/tidy5e-sheet#344]
Just what it says. As a DM, I'd like to be able to unlock the sheet and double-click the HD field on the char portrait and update the HD. 

Thanks!
C

**Comment by sdenec** [comment]
Look at that! I wasn't even aware of this new feature. You now can simply click the round hit die display to open up the dialogue :) Thanks for the request!
