### ISSUE TITLE
Suggestion: Inverted filters on repeated clicks or right click

### ISSUE THREAD

**Issue by MathewBissonnette** [sdenec/tidy5e-sheet#350]
Currently, clicking a heading on the Spellbook tab like Concentration will show all spells that require concentration. When I'm concentration on a spell I frequently want to know all the spells that I can cast that will _not_ break concentration, so I'd like to be able to filter on (NOT)Concentration. Similar filters would be useful for action/bonus action/reaction.

**Comment by sdenec** [comment]
Hi. I didn't write the filters, they are from the default dnd5e system. Maybe this suggestion might be better suited over there :)
