### ISSUE TITLE
Respect injection settings of character actions list

### ISSUE THREAD

**Issue by benbarbour** [sdenec/tidy5e-sheet#352]
The Character Actions List module recently added toggles to control whether the Actions tab is injected into the sheet, but TidySheet doesn't seem to respect the settings.

See https://github.com/ElfFriend-DnD/foundryvtt-dnd5eCharacterActions/commit/0caed832374a830cbbe630319425edd3b4e6442b.

**Comment by akrigline** [comment]
This setting _does_ specifically mention that it is only for the default injection and states:
> Note that if you are using a sheet module which integrates the actions list on its own, this will not affect that sheet.

So this is "working as intended" and is up to tidysheet to determine if it wants this injection to be optional at all.

**Comment by benbarbour** [comment]
Yeah. Sorry if I wasn't clear. I'm hoping that this module can read the injection seeing from the Character Action List module, or add it's own seeing to turn off the injection.

... Oh... I'm not at my computer to check now... does Tidy already have that setting? I might not have checked. :/ :$

**Comment by sdenec** [comment]
Working on it! With @akriglines help I got it into the sheet and think it should work in the next update!

**Comment by benbarbour** [comment]
Thanks for the quick work on this! Just noticed that it doesn't appear to be working for NPC or Vehicle sheets though.

**Comment by sdenec** [comment]
Damn it. I put in all the variables but forgot to actually check for it in the noc/vehicle sheet ... Next update ... sorry!
