### ISSUE TITLE
Inspiration not toggle-able on some sheets

### ISSUE THREAD

**Issue by adacosta92** [sdenec/tidy5e-sheet#353]
A few select sheets (mostly when imported from dndbeyond) result in inspiration not being toggle-able. Other sheets (Compact D&DBeyond, Default) are still able to toggle inspiration.

**Comment by sdenec** [comment]
I can't replicate this issue. Toggling inspiration works fine for my imported test characters. Doesn't really make sense anyhow. It's just a value that is either true or false and I don't know how that could cause any issues ... If it can be toggled by the default sheet it can be toggled by the tidy sheet.
Do you get any errors in the console when you try to toggle inspiration on faulty actors?

**Comment by adacosta92** [comment]
Yeah doesn't really make sense to me either, but I used "Find the Culprit" and it turns out it was the GM Screen module that is breaking it. wild. Thanks anyways.
