### ISSUE TITLE
Error with Exhaustion.js "Uncaught (in promise) ReferenceError: ACTIVE_EFFECT_MODES is not defined"

### ISSUE THREAD

**Issue by SR5060** [sdenec/tidy5e-sheet#355]
error thrown when updating exhausion. Foundry 0.8.6 and Dnd5e 1.3.5

![image](https://user-images.githubusercontent.com/85184490/122438214-17521f00-cf60-11eb-8032-0c78b7d9383e.png)

**Comment by sdenec** [comment]
should be fixed! Thanks for the report :)
