### ISSUE TITLE
Limit area of fields other than "Bio"

### ISSUE THREAD

**Issue by adacosta92** [sdenec/tidy5e-sheet#363]
Just a feature request to improve the UI:

Currently, the sheet looks like this: 
![image](https://user-images.githubusercontent.com/67127175/122999248-04828480-d37c-11eb-963d-19ab0ea22dd8.png)

I think making the Traits, Ideals, Bonds, Flaws, and Appearance sections much smaller (or preventing them from scaling up when the sheet is expanded will be a benefit, as the Biography section is the most important one here. Just a thought! The sheet is great!

**Comment by tagnullde** [comment]
On my end I have a problem that it doesn't scale at all. I can barely hit the box to enter anything.

![image](https://user-images.githubusercontent.com/44159008/133286901-df9763dd-38ea-4714-9e83-e5a077863988.png)

**Comment by sdenec** [comment]
Indeed I can confirm. Somehow the biography tab does not expand to the right ...

**Comment by sdenec** [comment]
Should be fixed. Both.
