### ISSUE TITLE
Cannot enter creature type on NPC sheet

### ISSUE THREAD

**Issue by ZWinther** [sdenec/tidy5e-sheet#364]
The creature type (humanoid, beast, etc.) field is unavailable for me unless there was already something in the field in the first place.

Creating a new NPC will leave the field hidden/disabled (since there's no creature type entered yet).

Currently the only way for me to enter the creature type is to switch to the base 5e sheet, enter it there and then switch back.

This is how the field looks on a new NPC's sheet:
![FoundryVTT_hIV0xFFPNx](https://user-images.githubusercontent.com/82144909/123062337-b6699180-d40c-11eb-88ea-2bb47d43ae3a.png)

**Comment by sdenec** [comment]
Hm, thought I got that fixed but seems this was only true for existant NPCs not newly created ones! Should be fixed now :)

**Comment by ZWinther** [comment]
> Hm, thought I got that fixed but seems this was only true for existant NPCs not newly created ones! Should be fixed now :)

After updating, it now only says "Creature Type". I can click on it and set the type, but it still only says "Creature Type".

**Comment by sdenec** [comment]
damn it!

**Comment by sdenec** [comment]
Try it now ...

**Comment by ZWinther** [comment]
> Try it now ...

Works perfectly, thanks!
