### ISSUE TITLE
Cannot open NPC Sheet if "notes3" field contains a quest link generated by Forien's Quest Log

### ISSUE THREAD

**Issue by Nisimouse** [sdenec/tidy5e-sheet#365]
**Version**: 
0.8.6 and 0.8.7 (VTT/The Forge), Tidy5e Sheet 0.5.10, Forien's Quest Log 0.6.0

**Bug**: 
Cannot open NPC Sheet if "notes3" field contains a quest link generated by Forien's Quest Log.

**Description**: 
Before upgrading to 0.8.6 and later 0.8.7 I created a NPC sheets using Tidy5e. Added a link from Forien's Quest Log by drag and drop into the Quest field of tidy5e. Example string `"notes3": {"value": "<p>@Quest[zjlj2Zw8KvvbUzOD]{The Banshee&rsquo;s Bargain}</p>"},` Everything worked fine until the new update of VTT/Foundry. If I try to open the NPC Sheet by clicking on it, nothing happens. Console outputs this error message:

```
TypeError: An error occurred while rendering Tidy5eNPC 158: Cannot read property 'get' of undefined
    at _createContentLink (foundry.js:21115)
    at Function._replaceTextContent (foundry.js:21055)
    at Function.enrichHTML (foundry.js:20960)
    at Object.editor (foundry.js:3694)
    at Object.c (handlebars.min.js:27)
    at Object.eval [as main] (eval at createFunctionContext (handlebars.min.js:1), <anonymous>:381:145)
    at c (handlebars.min.js:27)
    at d (handlebars.min.js:27)
    at e (handlebars.min.js:28)
    at renderTemplate (foundry.js:3627)
```

I tried to export and reimport the json string of my broken charakter sheets and found out by removing the @Quest strings created by Forien's Quest Log the sheet works again. The default VTT Sheet works even if I use the @Quest tags. I added two example NPC json files. One is broken including the @Quest string mentioned before (Line 94 in fvtt-Actor-sister-garaele_broken.json) and one that works without the Quest string.

[fvtt-Actor-sister-garaele_broken.txt](https://github.com/sdenec/tidy5e-sheet/files/6714463/fvtt-Actor-sister-garaele_broken.txt)
[fvtt-Actor-sister-garaele_works.txt](https://github.com/sdenec/tidy5e-sheet/files/6714464/fvtt-Actor-sister-garaele_works.txt)

**Comment by sdenec** [comment]
Have you tried this with newly created npcs, more importantly with the default charactersheet and the "Biography" field? Those other fields essentially work the same. Means I didn't programm anything for this fields just told the sheet to display more if it. Foundry has implemented a new html sanitation process that might mess with editor fields if they contain unexpected strings ...

**Comment by Nisimouse** [comment]
Yes it won't work for other fields too.
Just created a blank new Non Player Sheet and dragged a Quest inside the Journal field. The sheet will show me at least the non working link. If I close the sheet and reopen it, I get the same error message.

![a](https://user-images.githubusercontent.com/86464259/123433856-2bcf9080-d5cc-11eb-946d-51a57491ccae.JPG)
![b](https://user-images.githubusercontent.com/86464259/123433863-2d995400-d5cc-11eb-89f2-c539dfbc54c7.JPG)

**Comment by Nisimouse** [comment]
Ah I missread your post. I tested again a new blank DEFAULT NPC sheet and I get the same error. So it is not related to tidy5e it seems. I'm sorry, I will close this issue.
