### ISSUE TITLE
Cannot set a skill to be proficient when Jack Of all Trades is enabled.

### ISSUE THREAD

**Issue by cs96and** [sdenec/tidy5e-sheet#366]
Once Jack Of All Trades is enabled on a PC, then it is impossible to set a skill to be proficient.  You can only set 1/2 proficient, or expertise.

**Comment by sdenec** [comment]
Seems to be default behaviour - it's the same in the basic foundry sheet. With some trial and error clicking it seems you have to right click to set a skill as proficient! ;) Hope this helps!
