### ISSUE TITLE
Polymorph / Wildshape doesn't work if the creature is dropped on top the favourites sections

### ISSUE THREAD

**Issue by cs96and** [sdenec/tidy5e-sheet#368]
Dragging a creature onto a sheet, in order to bring up the polymorph/wildshape dialog, doesn't work if the creature is dropped onto any of the favourites sections (Inventory, Features, Spells etc) on the main page of the sheet.

You should be able to drop the creature anywhere on the sheet to bring up the dialog.

**Comment by sdenec** [comment]
My somewhat dickish response to that is: don't drop it on the favorites section! But in all honesty: The favorites section needs a rewrite but I'm not skilled enough to do it. So I honestly can't fix this right now and I'm sorry for any inconvenience :(
