### ISSUE TITLE
Can't change Max HP for NPC Sheets

### ISSUE THREAD

**Issue by giogreymon** [sdenec/tidy5e-sheet#369]
I don't know if it's default behaviour or a bug, but I can't change/edit the Max Hp for NPC sheets. I can add max hp, but I want to just set the Hp to their max value.

![image](https://user-images.githubusercontent.com/77355668/123500812-b33df380-d60e-11eb-8dea-e8cd04c9486f.png)

**Comment by sdenec** [comment]
Hi, make sure you have the sheet unlocked (green/red lock icon in the tabs bar)!

**Comment by sdenec** [comment]
I take it this issue is resolved :)
