### ISSUE TITLE
Overlap in attributes panel

### ISSUE THREAD

**Issue by Nordiii** [sdenec/tidy5e-sheet#37]
![overlapp](https://user-images.githubusercontent.com/2118629/85333758-6b0b6300-b4da-11ea-8a42-e69ea6aff4b8.JPG)

I get this pretty ugly overlap between my skills and my traits.

Browser: Firefox
FoundryVTT: 0.6.2
D&D5e: 0.93
Resolution: Full HD
Tidy5e: https://github.com/sdenec/tidy5e-sheet/commit/2f5124c4cc940513cfe34ebc2976fcd4538d6437

**Comment by sdenec** [comment]
indeed. will be fixed! Thanks for reporting.
