### ISSUE TITLE
Long Rest doesnt reduce exhaustion level

### ISSUE THREAD

**Issue by Mushie1** [sdenec/tidy5e-sheet#370]
Pressing the "Long Rest" button doesnt reduce the exhaustion level by 1 automatically.
Not a major issue, but I thought I would let you know.

**Comment by sdenec** [comment]
Yeah, since long rest is a predefined function by foundry I'm not sure how I would trigger reduction in exhaustion - so for now you have to do it manually.

**Comment by sdenec** [comment]
Now it does. At least for the build in exhaustion effects and custom CUB exhaustion! Please tell me if it would be useful for the regular no effects attached basic variant as well. I forgot to implement it for the most basic case -.-
