### ISSUE TITLE
[Feature Request] Option to hide Currency Converter from Players

### ISSUE THREAD

**Issue by jocolamarco** [sdenec/tidy5e-sheet#372]
Request is for the ability to hide Currency Converter from Players.

Not sure how complex it is to be added to settings. Potential workaround would be to hide it via custom CSS - is that possible?

**Comment by sdenec** [comment]
Yeah, I would suggest using your workaround. While it isn immensely complicated to write a settings option it is something rarely used and I want to keep the already crowded settings somewhat contained^^

But it is quite easy to add a custom css rule with the custom css module!

Just add the following rule
´´´css
.tidy5e.sheet.actor .inventory-currency .currency-item.convert { display: none; }
´´´
to hide the convert button in all sheets!

If you want to exclude the GM and only want to hide the button from players write
´´´css
.tidy5e.sheet.actor .tidy5e-sheet:not(.isGM) .inventory-currency .currency-item.convert { display: none; }
´´´
instead!

Hope this helps :)
