### ISSUE TITLE
Bug:  Edit button is still available on text fields after MCEeditor is opened, but clicking it throws an error and prevents saving any edited text.

### ISSUE THREAD

**Issue by BadIdeasBureau** [sdenec/tidy5e-sheet#373]
Reproduction:

Create an item
Click the button to open the editor for the mechanics/flavour text.
Change anything in the text
Click the button to open the editor again
Attempt to save the text.

Errors (first one is triggered when clicking the edit button for the second time, second one is triggered when trying to save):
![image](https://user-images.githubusercontent.com/36359784/123832722-8f73f980-d8fd-11eb-9f71-46dfd628e5f9.png)

**Comment by BadIdeasBureau** [comment]
This doesn't seem to occur with the core sheet, as the edit button appears to be disabled while the editor is open.

**Comment by sdenec** [comment]
I checked, happens with the default sheet and tidy mod deactivated as well. Must have snuck in with the latest 5e update!
![default sheet](https://user-images.githubusercontent.com/8881200/123838543-6313a980-d90c-11eb-8c87-c03e891b9c94.jpg)

**Comment by sdenec** [comment]
ah, no. I see what you mean with "deactivated". Though I#m pretty sure the button being visible at all while editing is a core bug. I checked in 0.7.9 and there the button is completely invisible while in edit mode. Does make more sense from a usibility point of view as well.

**Comment by sdenec** [comment]
still a core bug it seems but I tried to somewhat circumvent it where i can. Fix will be applied in the next update, but only for tidy sheet. So anything that's based on the defaults will still have this issue.
