### ISSUE TITLE
Option: Death Saving Throws and overlay of successes and failures visible only to the GM

### ISSUE THREAD

**Issue by apoapostolov** [sdenec/tidy5e-sheet#374]
This is a great issue raised in the DM Lair video, starting at 3:15

https://youtu.be/7jrRZoJmTqY?t=196

To avoid metagaming among players, the option to make the death overlay roll death saving throws as secret GM rolls and information on successes and failures is added to the post and is not displayed to players (only to GM) in the Overlay on the Portrait.

**Comment by sdenec** [comment]
Will be a gm option in the next update! Though you need to roll hidden to keep the save results a secret. Currently it seems death saves are "broken" in that they don't put the "stable" or "died" message in the chat when either 3 results are collected. This is a core issue it seems. just fyi.
