### ISSUE TITLE
Feature Suggestion - Inverted Filter

### ISSUE THREAD

**Issue by oamsden** [sdenec/tidy5e-sheet#377]
When clicking on a filter for a tab, for example, the 'Action' filter on the 'Spellbook' tab, allow an option for enabling the inverse of that filter.  This would then show all things that are NOT Actions.  This would be the same for any filter, Ritual, Prepared, Equipped, etc...  This could probably be shown by marking it with a slight red tint.

Recommended way
Cycle through with left clicks. Disabled (0) -> Enabled (1) -> Inverse Enabled (2) -> Disabled (0)

Alternative, not quite as good way
Right click to inverse filter. Disabled (0) -(Lclick)-> Enabled (1) -(R/Lclick)-> Disabled (0) -(Rclick)-> Inverse Enabled (2) -(R/Lclick)-> Disabled (0)

**Comment by sdenec** [comment]
This should be a feature for the dnd5e core sheet - my filters are untouched and I don't plan on altering them. So my suggestion would be to head over to the dnd5e repo and open an issue there :)
