### ISSUE TITLE
Compatibility between dark theme and SIToolkit

### ISSUE THREAD

**Issue by dirusulixes** [sdenec/tidy5e-sheet#378]
When using the dark colour theme for the item sheet the content of the tab created by [SIFToolkit](https://github.com/bitkiller0/SIFToolkit) is not readable:

![image](https://user-images.githubusercontent.com/5693623/126525012-ae13f60c-e0fa-471d-bc2a-697c99fd5524.png)
![image](https://user-images.githubusercontent.com/5693623/126525113-77c1a66e-a7ed-4f53-8365-bfcb8a2cdd22.png)

**Comment by sdenec** [comment]
Tidy applies a class to the body of the whole foundry app when Dark mode is switched on

```html
<body class="vtt game system-dnd5e">
```
becomes
```html
<body class="vtt game system-dnd5e tidy5eDark">
```
I have set up my css accordingly and switch out colors stored in custom css-variables.

**Comment by sdenec** [comment]
here is a console excerpt regarding color changes - the default color properties aren't fully shown.
![excerpt](https://user-images.githubusercontent.com/8881200/135713223-5ca261c3-41e4-4b52-a406-3ad3128e548a.jpg)

**Comment by sdenec** [comment]
This issue should be resolved then. Thanks for looking into it on your end @bitkiller0 ! I'm closing this. If you have any more styling issues feel free to revive this post :)
