### ISSUE TITLE
[BUG] Ammunition dropdown field missing for NPCs

### ISSUE THREAD

**Issue by DarKDinDoN** [sdenec/tidy5e-sheet#379]
Hello,

In the PC sheet, there is a super handy dropdown to quickly change the ammunition type of a ranged weapon. But it's missing for the NPC sheet.

![pc](https://user-images.githubusercontent.com/1687854/126667487-87e919ba-f331-43c6-854c-1944aba355a1.jpg)
![npc](https://user-images.githubusercontent.com/1687854/126667492-8d829786-e110-45ab-9657-d76ed6d1735c.jpg)

**Comment by DarKDinDoN** [comment]
@sdenec should be fixed by this PR: https://github.com/sdenec/tidy5e-sheet/pull/383

**Comment by sdenec** [comment]
Again, you provided the feature yourself, so will definately be in the next update! Thanks :)
