### ISSUE TITLE
choose not to put the dead overlay.

### ISSUE THREAD

**Issue by rinnocenti** [sdenec/tidy5e-sheet#38]
it is a suggestion, because I use CUB and I prefer to use the lab, and I prefer to use the unconscious icon when a player fall with 0 HP.

**Comment by sdenec** [comment]
Do you mean the skull icon for saving throws? Well it is a death threat and it is called death saving throw. So in my opinion the skull is fitting and it would be a little to much work to build in an option to exchange icons as it is not derived from any token conditions. Sorry!

**Comment by sdenec** [comment]
technically if you wanted to simply hide the skull icon you can do that with the custom css module!
put this as a new rule and it should hide the icon:
.tidy5e.sheet.actor .death-save .fa-skull { opacity: 0; }
