### ISSUE TITLE
[BUG] items action/reaction/bonus action missing for NPCs

### ISSUE THREAD

**Issue by DarKDinDoN** [sdenec/tidy5e-sheet#381]
Hello,

Some items have actions/reactions/bonus action activation and uses. This important information is missing in the NPCs sheet

![image](https://user-images.githubusercontent.com/1687854/126871235-8c97d3e3-dd60-4538-958f-5b00f6682b50.png)

**Comment by DarKDinDoN** [comment]
@sdenec Hi,
Here is the PR: https://github.com/sdenec/tidy5e-sheet/pull/384/commits

More a feature that an issue, I reckon :)

**Comment by sdenec** [comment]
Well, you provided the feature yourself, so will definately be in the next update! Thanks :)
