### ISSUE TITLE
[BUG] Unresponsive Unlock

### ISSUE THREAD

**Issue by Scar851** [sdenec/tidy5e-sheet#382]
When going through the tidy sheet, some character's sheets have the ability to unlock the sheet and edit it as normal. However most of the sheets have a bug where when you click the unlock button, nothing happens; but if you close the sheet and re-open it the unlock button has indeed unlocked.

**Comment by sdenec** [comment]
Can you elaborate? I can't reproduce this. And from my point of view it shouldn't be an issue programmatically speaking. Do you get any errors in the console when you click the lock? Are multiple instances of the actor opened or any othe curiosities ... Have you checked if another module interferes maybe?

**Comment by Scar851** [comment]
Sure, I'll try; its a weird happenstance that seems to have just started up with the newest series of updates from Foundry. In most cases when using tidy sheet everything works as intended where you can click and drag basically everything onto the sheet and the sheet onto the maps etc. However just recently it seems that some tidy sheets don't want to unlock, well in a sense.
For example, I go into one of my players character sheets and I want to do some editing, maybe give them a new feature, item, etc. When I go to click on the lock icon to unlock the sheet allowing me to edit it, the icon doesn't show any feedback by changing to the unlock symbol. Though this isn't actually the case. When I close the sheet and bring it back up again, it shows that it is now unlocked and I can make some edits, though this strange error carries over to some features and items. Whenever I feel good about an item I press enter as if to finalize it and nothing happens, close out of it and boot it back up, it actually has taken the changes. Another example, I'm editing an item, change the name and press enter and it should automatically update, it doesn't, nothing changes until I close the entire sheet and boot it up again, then it displays the changes.
I'm not entirely sure if its a conflicting module issue since I haven't added any new modules, however maybe an update with one of them has caused issues, I'll look into it after I send this off to you, hoping its as easy as that because to be honest, I think your sheet is one of the best out there and would love to keep using it!
Thank you for your time, let me know if I can elaborate on anything more. 

    On Wednesday, July 28, 2021, 02:49:44 AM MST, sdenec ***@***.***> wrote:  
 
 


Can you elaborate? I can't reproduce this. And from my point of view it shouldn't be an issue programmatically speaking. Do you get any errors in the console when you click the lock? Are multiple instances of the actor opened or any othe curiosities ... Have you checked if another module interferes maybe?

**Comment by Scar851** [comment]
A quick disable of all modules, and things seem to work! Looks like its a conflicting module, when I find it I'll send the module name your way.
    On Thursday, July 29, 2021, 01:39:51 PM MST, Andrew Kofile ***@***.***> wrote:  
 
 Sure, I'll try; its a weird happenstance that seems to have just started up with the newest series of updates from Foundry. In most cases when using tidy sheet everything works as intended where you can click and drag basically everything onto the sheet and the sheet onto the maps etc. However just recently it seems that some tidy sheets don't want to unlock, well in a sense.
For example, I go into one of my players character sheets and I want to do some editing, maybe give them a new feature, item, etc. When I go to click on the lock icon to unlock the sheet allowing me to edit it, the icon doesn't show any feedback by changing to the unlock symbol. Though this isn't actually the case. When I close the sheet and bring it back up again, it shows that it is now unlocked and I can make some edits, though this strange error carries over to some features and items. Whenever I feel good about an item I press enter as if to finalize it and nothing happens, close out of it and boot it back up, it actually has taken the changes. Another example, I'm editing an item, change the name and press enter and it should automatically update, it doesn't, nothing changes until I close the entire sheet and boot it up again, then it displays the changes.
I'm not entirely sure if its a conflicting module issue since I haven't added any new modules, however maybe an update with one of them has caused issues, I'll look into it after I send this off to you, hoping its as easy as that because to be honest, I think your sheet is one of the best out there and would love to keep using it!
Thank you for your time, let me know if I can elaborate on anything more. 

    On Wednesday, July 28, 2021, 02:49:44 AM MST, sdenec ***@***.***> wrote:  
 
 


Can you elaborate? I can't reproduce this. And from my point of view it shouldn't be an issue programmatically speaking. Do you get any errors in the console when you click the lock? Are multiple instances of the actor opened or any othe curiosities ... Have you checked if another module interferes maybe?

**Comment by Scar851** [comment]
Dynamic Effects

    On Thursday, July 29, 2021, 01:42:42 PM MST, Andrew Kofile ***@***.***> wrote:  
 
 A quick disable of all modules, and things seem to work! Looks like its a conflicting module, when I find it I'll send the module name your way.
    On Thursday, July 29, 2021, 01:39:51 PM MST, Andrew Kofile ***@***.***> wrote:  
 
 Sure, I'll try; its a weird happenstance that seems to have just started up with the newest series of updates from Foundry. In most cases when using tidy sheet everything works as intended where you can click and drag basically everything onto the sheet and the sheet onto the maps etc. However just recently it seems that some tidy sheets don't want to unlock, well in a sense.
For example, I go into one of my players character sheets and I want to do some editing, maybe give them a new feature, item, etc. When I go to click on the lock icon to unlock the sheet allowing me to edit it, the icon doesn't show any feedback by changing to the unlock symbol. Though this isn't actually the case. When I close the sheet and bring it back up again, it shows that it is now unlocked and I can make some edits, though this strange error carries over to some features and items. Whenever I feel good about an item I press enter as if to finalize it and nothing happens, close out of it and boot it back up, it actually has taken the changes. Another example, I'm editing an item, change the name and press enter and it should automatically update, it doesn't, nothing changes until I close the entire sheet and boot it up again, then it displays the changes.
I'm not entirely sure if its a conflicting module issue since I haven't added any new modules, however maybe an update with one of them has caused issues, I'll look into it after I send this off to you, hoping its as easy as that because to be honest, I think your sheet is one of the best out there and would love to keep using it!
Thank you for your time, let me know if I can elaborate on anything more. 

    On Wednesday, July 28, 2021, 02:49:44 AM MST, sdenec ***@***.***> wrote:  
 
 


Can you elaborate? I can't reproduce this. And from my point of view it shouldn't be an issue programmatically speaking. Do you get any errors in the console when you click the lock? Are multiple instances of the actor opened or any othe curiosities ... Have you checked if another module interferes maybe?

**Comment by sdenec** [comment]
So, I have Dynamic Active Effects installed but I can't reproduce your error. Are you sure you have everything up to date? And that it isn't another module that interferes somehwo?

**Comment by Scar851** [comment]
Hmm yes I have everything up to date but that was the only one causing me issues so I just axed it, maybe a combination of modules with that one module but Im not sure.

**Comment by sdenec** [comment]
Well, I'm afraid I can't be of much help here. Also it seems a little odd that another mod would cause this behaviour. The only thing the button does is set an internal variable and refresh the sheet. So, since the variable is set any interfering module seems to prevent the sheet refresh. And that is out of my hands I guess ... sorry!
