### ISSUE TITLE
[BUG] Small CSS issue with 5e 1.4.1

### ISSUE THREAD

**Issue by DarKDinDoN** [sdenec/tidy5e-sheet#386]
Hello,

Since 1.4.1, rarity is now displayed in a dropdown.
That dropdown is off grid by a little

![image](https://user-images.githubusercontent.com/1687854/127352692-409fc021-cadb-40c7-b427-dccde8ad0962.png)

**Comment by unsoluble** [comment]
Gonna piggyback on this ticket to add: The stock 5e sheet is adding a `text-transform: capitalize;` to the rarity input in order to make the lowercase values appear correct in contex — should also add it here.

**Comment by sdenec** [comment]
Thanks guys! Will be fixed asap :)
