### ISSUE TITLE
Missing new proficiency options introduced in dnd5e 1.4.x 

### ISSUE THREAD

**Issue by Pjb518** [sdenec/tidy5e-sheet#387]
The latest version of the 5e system introduced the ability to select specific weapon, armor, and tool proficiencies, rather than just whole categories such as "Martial Weapons". These options are currently missing on the Tidy5e sheet.

You can see an example of these options below:

![image](https://user-images.githubusercontent.com/33249712/127371070-5c4eb0b7-05a4-4281-af03-1a0670c5cd7c.png)

**Comment by sdenec** [comment]
Check! Thanks for letting me know. Will be fixed asap!
