### ISSUE TITLE
D&D Beyond Importer compatibility

### ISSUE THREAD

**Issue by ravingdragoon** [sdenec/tidy5e-sheet#389]
Currently, importing a character with D&D Beyond Importer while using Tidy5e Sheet seems to work, however upon reloading the page all active effects are missing.

**Comment by sdenec** [comment]
have you tried with the default sheet? Is it the same. I don't use D&D beyond and can't really test it. But I find it strange that this would only happen with my sheet since the base for active effects is the same.
