### ISSUE TITLE
 [BUG] Player sheet stcuck with exhaustion level 1

### ISSUE THREAD

**Issue by chibiliplop** [sdenec/tidy5e-sheet#390]
![image](https://user-images.githubusercontent.com/2571334/127775628-13513b8e-56c4-4e51-a1d5-b2f4467418ad.png)

One of my players is stuck with exhaustion level 1. Clicking on any other level properly apply CUB Condition but the sheet still gives me exhaustion level 1.

**Comment by sdenec** [comment]
did you try to manually remove the effect? If you are using the cub option the exhaustion menu does nothing more that to apply the corresponding effect. What gets removed upon gaining another exhaustion level has to be handled by cub or macros.

**Comment by sdenec** [comment]
Ah, I got an idea why this might happen. I tested the CUB option and everything works fine. BUT it could have happened that the player already had 1 Level in exhaustion when you made the switch to the cub function. Try to switch to the default sheet and check if exhaustion is set to any other value than 0. Make sure it is 0 (when no active effects are applied).

**Comment by sdenec** [comment]
Also this: https://www.foundryvtt-hub.com/guide/under-the-hood-enhancing-exhaustion-condition/
is a really good guide how to automate the exhaustion levels aplied by cub. If you aren't using this already I highly recommend to take the time and set it up. It works with 0.8.x even though it says it doesn't. Just remember to give every exhaustion level one additional effect: data.attributes.exhaustion OVERRIDE CORRESPONDING_EXHAUSTION_LEVEL (so 1, 2, 3, 4, 5, 6)
Also create Exhaustion 6 to prevent getting errors if a character actually does reach level 6!

**Comment by chibiliplop** [comment]
Switching between tidi5e exhaustion allow me to remove the tracker stuck on 1 😄.
```If you are using the cub option the exhaustion menu does nothing more that to apply the corresponding effect```
Doest that mean the exhaustion tracket is not updated at all ( stuck at 0 )  ?

**Comment by sdenec** [comment]
Essentially yes. You have to add a new effect inside the cub condition. For example Exhaustion 1: create a new active effect, put "data.attributes.exhaustion" in OVERRIDE mode with "1" vor the value. Do the same for every other Exhaustion Condition (just with 2, 3, 4, 5, 6 as the value). Tah way when the effect is apllied the menu in the sheet will reflect this!

**Comment by chibiliplop** [comment]
Which makes sens. Thanks for your help @sdenec. 
Sorry for this false bug which is due to my incomprehension of the module.
It is now working like a charm
