### ISSUE TITLE
Vehicle AC is below the shield and resets to 10

### ISSUE THREAD

**Issue by UnoriginalDM** [sdenec/tidy5e-sheet#391]
Hey thank you for your hard work. On the last update when the new armor feature came out for dnd5e the AC on vehicles moved below the shield.

![image](https://user-images.githubusercontent.com/77896718/127866918-51216cb8-537c-4ef5-bb4b-7318be12ead5.png)

EDIT: Also, noticed that edits to vehicle sheet can reset the AC value to 10. Seems to happen if you adjust any of the ability scores/modifiers, threshold, HP, etc.

**Comment by sdenec** [comment]
Will be fixed with the next update!
