### ISSUE TITLE
Inline rolls are a bit hard to read in dark mode

### ISSUE THREAD

**Issue by cs96and** [sdenec/tidy5e-sheet#394]
If you have a feature that has inline rolls, they are a bit hard to read on the character sheet in dark mode.  E.g...

![image](https://user-images.githubusercontent.com/898086/128526310-ddc6ce51-571e-46f0-9297-299a096384ee.png)

However, if you edit that feature, the text is white and easy to read...

![image](https://user-images.githubusercontent.com/898086/128526674-a6fe89ec-e0e0-4039-bc8a-44403cf533ab.png)

Could the sheet version be changed to match the edit version please?  I.e. white text.

**Comment by sdenec** [comment]
hm, interesting. should be fixed in the next update! Thanks for the report :)
