### ISSUE TITLE
Implement popular "Illandril's Character Sheet Lockdown" features directly in Tidy5e Sheet

### ISSUE THREAD

**Issue by illandril** [sdenec/tidy5e-sheet#395]
Maintaining compatibility between Illandril's Character Sheet Lockdown and Tidy5e Sheet has taken up most of the time I spend on Illandril's Character Sheet Lockdown, and quite frankly the user experience of having both of these modules is terrible (two different lock/unlock buttons that do different, sometimes overlapping things, making it hard to know what is causing what to hide/show/lock/unlock). The best usability and long-term maintenance answer in my mind is to actually put all the flags people want from Illandril's Character Sheet Lockdown straight into Tidy5e Sheet. Both modules have the same goals of reducing user error and improving usability, but take different approaches, so it's only natural for them to not work well together.

The next time another time-consuming compatibility issue arises between Illandril's Character Sheet Lockdown and Tidy5e Sheet, I'm going to have to drop support for Tidy5e Sheet, because I don't have time or desire to keep the two modules working "nicely". It would be nice for our currently joint users if they didn't need both modules anymore and could just remove Illandril's Character Sheet Lockdown before this happens.

Settings in Illandril's Character Sheet Lockdown that I know people have enabled when using Tidy5e Sheets (because they've told me they used Tidy5e when requesting them, or there have been bugs related to Tidy5e compatibility and these settings):
- Hide Add and Delete Item Buttons
- Hide Edit Item Buttons
- Hide Empty Spellbooks
- Lock Max Spell Slots overrides
- Show Effects Tab to: Game Master only
- Lock Traits
- Lock Equip Item Toggles
- Hide Short and Long Rest Buttons

**Comment by sdenec** [comment]
Hi! Sorry for the (very) late reply. Understandable - I myself loathe supporting other modules ^^
I'll see what I can do. A few of the items already are or can be integrated right away into the default locking mechanism. 
- add/delete items
- lock max spell override
- lock traits

On the other items I wouldn't agree but to make them optional would require yet more setting options and I already have a but load of them ... I'll think about it - In the meantime maybe your module will continue to work for a while :)

Anyway, thanks for the suggedtions and heads up!
