### ISSUE TITLE
[Bug] Attunement lost upon module update

### ISSUE THREAD

**Issue by Havoclivekiller** [sdenec/tidy5e-sheet#396]
When I update my module, my players lose their attunements. Is it possible to fix this issue?

**Comment by sdenec** [comment]
Honestly, that seems unlikely. I wouldn't know what should cause this issue. If an item is attuned or not is stored inside the item itself, updating the sheet should not touch any of that data ...

**Comment by Havoclivekiller** [comment]
Made a test, it didn't remove the attunement (went to x.12 and updated to x.13). It might be a different module but it's not something I can test right now as there were over a dozen updated before the session. If I'll get more info, I'll inform you.
