### ISSUE TITLE
[Bug] Ability checks not rolling with correct card

### ISSUE THREAD

**Issue by PalaNolho** [sdenec/tidy5e-sheet#397]
I'm using BetterRoll5e to manage my rolls.
When I roll attacks and abilities from the sheet, they roll correctly using BeterRolls5e and showing the corresponding card.
However, when rolling ability checks directly from the sheet, they are rolled with foundry standard dice roller card.

![image](https://user-images.githubusercontent.com/6009914/129176705-fc27c6f7-be26-4649-a06d-e98b2587493d.png)

**Comment by sdenec** [comment]
Please check with the default sheet. I dont use BR but by quickly installing it it seems only attacks use the better roll flow, regardless if it's the default or tidy sheet.

**Comment by PalaNolho** [comment]
It seems the problem was with MidQol and has been already fixed. 👍
