### ISSUE TITLE
Large amount of deadspace on Attributes Page

### ISSUE THREAD

**Issue by AndrewKopczynski** [sdenec/tidy5e-sheet#399]
**Issue:** There's a lot of unused space on the Attributes Page / Tab

**Expected Behavior:** The space should be filled up with something. Previously, all of the senses and languages and stuff would fill that space up, but they're all listed below the Skills now.

**Additional Details:** Every other page (Inventory, Spellbook, Features, etc,) make a great use of space and look fantastic. It's just the Attributes page that sticks out.

**Versions:** Tidy5e Sheet 0.5.13, Foundry VTT 0.8.8 running on The Forge, Google Chrome 92.0.4515.131 64 bit (issue still occurs on Firefox as well).

Here's an image of the issue:
![image](https://user-images.githubusercontent.com/6044186/129406254-2f563adb-e1d2-4236-9de2-36a719eb18fe.png)

**Comment by sdenec** [comment]
Not an issue at all. First: You can add favorites to that section by going into your inventory or spellbook and use the right click option "add favorite" to place stuff on the front page for easy access. 
![favorites](https://user-images.githubusercontent.com/8881200/129438842-19c46eed-d3d9-4250-9494-978175440bfa.jpg)

If you don't have a use for favorites you can push the traits below the resources by going into the sheet settings and activate this option (per player option).
![trait-options](https://user-images.githubusercontent.com/8881200/129438855-10242ae8-ae06-4cdd-aa4a-ce3b4f25a61f.jpg)
![traits_below_resources](https://user-images.githubusercontent.com/8881200/129438858-b4ed15e9-cb64-4f35-a5c5-ef54524f071e.jpg)

**Comment by AndrewKopczynski** [comment]
My bad on the misunderstanding. Thank you for the clarification.

**Comment by sdenec** [comment]
No problem. Glad I could help :)
