### ISSUE TITLE
DndBeyond Integration Doesn't work

### ISSUE THREAD

**Issue by Jonwh25** [sdenec/tidy5e-sheet#4]
Not sure if this is your issue or VTA - Dndbeyond Integration...

If I import my character the only thing that isn't working is the Background / Traits / Personality Traits, Ideals, Bonds, Flaws, don't seem to go to the correct spot in the sheet.  Everything else is awesome.

**Comment by shawndibble** [comment]
that is vtta - they put it all in biography as the default sheet only has that option.

**Comment by sdenec** [comment]
But they also populate the default fields hidden in foundry. The sheet now uses these fields to correctly display this data (alongside the duplicated data in the background field - for sheets that do not offer multiple fields)!
