### ISSUE TITLE
[BUG] Empty description on item displays null when the description is visible

### ISSUE THREAD

**Issue by DarKDinDoN** [sdenec/tidy5e-sheet#400]
Hello,

On a npc sheet, when an item description is empty, the sheet displays "null".
![image](https://user-images.githubusercontent.com/1687854/129495833-431b608b-880c-4b99-95c5-95ccc73aac3d.png)

Exported item: https://we.tl/t-skOQLpUXn7

**Comment by sdenec** [comment]
It's not a  tidy bug. Happens with the default sheet as well. So more a core issue and better suited to bring up there. sorry!
