### ISSUE TITLE
Duplicate roll buttons on Attributes page when using Better 5e Rolls

### ISSUE THREAD

**Issue by malexherron** [sdenec/tidy5e-sheet#401]
Possible conflict with Better 5e Rolls' roll button feature. 
**Version info**
![Screen Shot 2021-08-15 at 11 55 58 PM](https://user-images.githubusercontent.com/81781423/129523336-e2388f97-0a03-4cab-8dc5-7a7ffde92936.png)
 Module Version: 0.5.13 (but issue has been present in previous versions)

As shown in Attributes tab screenshot, duplication of roll buttons only when displayed on Attributes tab, this does not occur on the Inventory tab, and does not occur when Tidy5e is disabled (because the core sheet does not have inventory on the attributes tab)

**Description on Attributes tab:**
![Screen Shot 2021-08-15 at 11 43 59 PM](https://user-images.githubusercontent.com/81781423/129522646-2738124d-f76f-4e9e-9b33-2305d88559bd.png)

**Description on Inventory tab:**
![Screen Shot 2021-08-15 at 11 44 07 PM](https://user-images.githubusercontent.com/81781423/129523141-990d3728-2659-41ea-9091-8e1aec463fb6.png)

**Comment by sdenec** [comment]
Hm, that might be better rolls territory. Not sure how I could influence this as I'm not adding the buttons, sorry. Maybe you could check with the BR mod dev?
