### ISSUE TITLE
Non-Clickable AC configuration if AC is empty

### ISSUE THREAD

**Issue by tagnullde** [sdenec/tidy5e-sheet#402]
dnd5e: 1.4.2
Foundry: 0.8.9
Tidy5e: 0.5.13

If the AC on an token / actor is empty, you can hover over the shield and see the empty AC. But you can't click the shield anymore to open the configuration menu. (I assume the text is actually the link to the config, which isn't present anymore.) 
You have to switch to the default 5e sheet to click the gear icon to fix the empty AC.

![grafik](https://user-images.githubusercontent.com/44159008/129861761-2444d488-5429-4cef-a5cf-8980917900bf.png)

**Comment by Mythano** [comment]
To add more and confirm, for tracking it. If you change calculation type to Flat, and erase the number and then save configuration it becomes not clickable to readjust.   Can revert back to default, to use gear.

**Comment by sdenec** [comment]
Whoops. You are correct. This was an oversight - didn't occur to me that it might potentially be empty. Will be fixed as soon as I can get to it! Thanks for the report!
