### ISSUE TITLE
Make Show Trait Labels a player setting

### ISSUE THREAD

**Issue by giogreymon** [sdenec/tidy5e-sheet#405]
If it's possible to have that option so I don't have to keep asking my DM to change it for me. Thanks for the awesome module!

**Comment by sdenec** [comment]
I guess I'm at a point where I can only make "wrong" decisions. One part wants all options to be GM-options, the other wants freedom of choice. It would be too much work to have both (as in overwrite the GM-presets). So for now I'd ask you to speak with the dm, sorry!
