### ISSUE TITLE
Death save tracker not displaying when PC HP < 0

### ISSUE THREAD

**Issue by dstein766** [sdenec/tidy5e-sheet#410]
FVTT 0.8.9, DND 1.4.2, TidySheet 0.5.14.  

When PC HP are 0, death save overlay appears.  When PC HP are < 0, no overlay.

**Comment by mesoraven** [comment]
Can confirm the same issue, running in 0.8.8 i as the DM have it but none of my players do

![](https://cdn.discordapp.com/attachments/846862948429594676/885274225303244920/unknown.png)

![](https://cdn.discordapp.com/attachments/846862948429594676/885273393857982515/unknown.png)

**Comment by sdenec** [comment]
this should be fixed.
