### ISSUE TITLE
No rest options on PC character sheets

### ISSUE THREAD

**Issue by Woodchip50** [sdenec/tidy5e-sheet#411]
Hi, 

Been using this a while and it's been great! 
However, while playing a session yesterday, my players found the rest button had disappeared from the character sheet (see Bat char sheet). Not sure exactly what's going on, but it is still there for my NPCs (see Kiwi char sheet). I went through the options for the module and there's nothing strange there I don't think. 

I'm using:
foundry version 0.8.8
5e version 1.4.2
tidy sheet version 0.5.14

Looking through the console, I'm not seeing any errors relating to tidy5e sheet (see console output).

Any help would be greatly appreciated! 

![norest](https://user-images.githubusercontent.com/70519637/132118721-4b2c8721-30f9-494e-9288-431d43957848.png)

![npcrest](https://user-images.githubusercontent.com/70519637/132118724-3485d022-c689-4414-a810-e69973f500ea.png)

![tidyerror](https://user-images.githubusercontent.com/70519637/132118782-c6f9c1d7-abdc-44f1-acaf-02c8b001179e.png)

**Comment by sdenec** [comment]
that is indeed a bit strange. There is no setting to disable the rest button and it only disappears if the actor is dead ... Is it only for said player? Have you tried to disable any other modules? It has to be some css interference that hides the button, no scripts are used to do this and the log is clean, so no errors. I'm a bit stumped aout this issue (that never occured before).

**Comment by Woodchip50** [comment]
Thanks for you insight! When you said it was something hiding the rest button it clicked! 

It was Illandril's character sheet lockdown - I think it updated because there was a new setting that locked away the ability to short and long rest. So not an error - just a new feature of a different module that I didn't know had come online.  

Cheers!
