### ISSUE TITLE
Thousands of errors during dnd5e system migration (game.actors.get(...) is undefined)

### ISSUE THREAD

**Issue by cs96and** [sdenec/tidy5e-sheet#413]
I just installed the dnd5e v1.4.3 update, and during the migration I got thousands of errors on the console, e.g...

![image](https://user-images.githubusercontent.com/898086/132495015-93203c36-e6e6-4236-8a52-eedfabfc8718.png)

**Comment by sdenec** [comment]
I have updated the 5e system with the sheet and lib-wrapper active without any issue. Twice. So I'm sorry to say that I don't have a clue what's going on there.

**Comment by sdenec** [comment]
Since this seems to have been an isolated issue that I can't replicate I guess it was something unique to your setup. I'm going to close this issue for now.

**Comment by sdenec** [comment]
Is this by any chance solved with the update - or maybe solved itself before that?

**Comment by cs96and** [comment]
I did not get these error on the dnd 2.1 migration, so I assume it is fixed.
