### ISSUE TITLE
[Bug] Negative Exhaustion

### ISSUE THREAD

**Issue by Ghostdesu** [sdenec/tidy5e-sheet#418]
Environment Details

    Foundry VTT Version: 0.8.9
    Operating System: Windows
    How Are You Using Foundry: Firefox
    Which Game System: dnd5e 1.4.3
    Modules Enabled: tidy5e-sheet 0.5.15

Issue Description
Long resting can result in negative exhaustion in the latest update.

To reproduce:
1) Set automatic exhaustion to tidy5e integrated: 
![settings](https://user-images.githubusercontent.com/31375910/133860610-53fc7317-a7f1-4b7d-b85c-a881e01ae8ca.png)

2) Use long rest function while at 0 exhaustion: 
![exhaustion](https://user-images.githubusercontent.com/31375910/133861140-7a3f22c7-24a1-4c60-8973-1427004358fc.gif)

**Comment by sdenec** [comment]
Whoops. Forgot to check the current exhaustion value. Will fix as soon as possible. Thanks!

**Comment by sdenec** [comment]
Should be fixed!
