### ISSUE TITLE
Suggestion: Option to show avatar image as portrait instead of actor image

### ISSUE THREAD

**Issue by NeV3rKilL** [sdenec/tidy5e-sheet#422]
Since avatars are usually rounded and actor image doesn't they fit much better on the tidys rounded design for the actor image I suggest to have a checkbox to use the avatar image on the PC Sheet instead the actor image.

**Comment by sdenec** [comment]
It shouldn't matter what dimension your actor image has. It will get masked and appear rounded on the sheet.

**Comment by NeV3rKilL** [comment]
I know, but is it really satisfactory?

!(https://i.imgur.com/H4AZYoV.png)

**Comment by sdenec** [comment]
It doesn't seem to be possible. I tried to find a solution but for some reason if you display the token image as actor image the actor image becomes the token image. I bet it is possible to achive this but I don't see the value in the neccessary effort. So my advise would be to simply cut the actor image in a way that suits your portrait needs.
