### ISSUE TITLE
Adopt custom skills and proficiencies

### ISSUE THREAD

**Issue by miromonti** [sdenec/tidy5e-sheet#423]
Is there a way to add custom skills and proficiencies? I'm using Sandy Petersen's Cthulhu Mythos and it has the Yog-Sothothery skill. I'd like to include it with the other skills.

Does such a feature already exist? If so, please let me know where or how to activate it. If not, then consider this a feature request.

**Comment by sdenec** [comment]
This feature does not exist for the sheet but I also do not plan to integrade it and would kindly ask you to try out other modules that add this feature - I'm sure there are some floating around.
