### ISSUE TITLE
Disable option to fill red token when losing hp

### ISSUE THREAD

**Issue by CapivaraTupiniquim** [sdenec/tidy5e-sheet#425]
(Google translator) I would like to disable the option to fill the token with red when you lose hp but I didn't find it in the configuration. A button to apply my settings to players would also be nice.

**Comment by sdenec** [comment]
You have "disable hit point overlay" under player options and - for some reason - "hide hit point overlay" under npcs. I'll have to fix the name of the option. For now it is a per player setting and everyone has to set it for themself. Or you have to log in for each player and make the adjustment.
