### ISSUE TITLE
Skills and abilities menus are not aware of settings via DAE

### ISSUE THREAD

**Issue by dirusulixes** [sdenec/tidy5e-sheet#427]
Not sure if this is a bug, indented behaviour, a feature suggestion or else. In any case, the new menus don't reflect settings set by DAE. The main sheet does it and rolls do account for proficiencies set via DAEs.

![image](https://user-images.githubusercontent.com/5693623/136654935-c8514f0c-597c-4296-b867-cdeb63d0205e.png)

**Comment by sdenec** [comment]
If it is the same behaviour it most likely is a DAE issue. I think I read that tposney hasn't updated his module for the new sheet features -  so that might what you are experiencing

**Comment by dirusulixes** [comment]
Good point. Default sheet does behave the same. Issue is on DAE.
