### ISSUE TITLE
[Feature Request] Proficiency Dice

### ISSUE THREAD

**Issue by BrunoLambert** [sdenec/tidy5e-sheet#428]
Hey! It'd be amazing if the sheet was adapted to accept proficiency dice as well.

The proficiency dice is a alternative to the bonus and it can be set on the DnD System Settings.

**Comment by sdenec** [comment]
Hi, using proficiency dice already works - it is just a display issue that the die used isn't shown on the sheet (instead the default bonus keeps showing). I will fix that in the next update - I wasn't aware that somewhere along the update line there was a change for the label that shows the bonus. Thanks for making me aware!

**Comment by sdenec** [comment]
Should display correct values in the coming update.
