### ISSUE TITLE
Suggestion: Add Ability to click stat bonus to trigger ablity/save throw

### ISSUE THREAD

**Issue by bsleys** [sdenec/tidy5e-sheet#43]
Above pretty much sums is up but take the char sheet in the readme and the con stat.  If the user clicks on the +2 of the con stat bonus skip the save/stat dialog and go directly to the stat roll dialog and if they click the +4 go directly to the save throw dialog. They can still click the Constitution label as normal this just give a short cut to eliminate one extra dialog box.

Bob

**Comment by sdenec** [comment]
Thanks for the sugestion. The new update has the modificators clickable to roll Ability Checks or Saving Throws!
