### ISSUE TITLE
[Localization] Add support for localized currency abbreviation keys

### ISSUE THREAD

**Issue by megahead11** [sdenec/tidy5e-sheet#430]
In a recent update to DND 5e, you can now set localization keys for the currencies. It would be nice to have support for these abbreviations.
The keys are:
```js
"DND5E.CurrencyAbbrCP": "cp",
"DND5E.CurrencyAbbrEP": "ep",
"DND5E.CurrencyAbbrGP": "gp",
"DND5E.CurrencyAbbrPP": "pp",
"DND5E.CurrencyAbbrSP": "sp",

**Comment by sdenec** [comment]
should be supported in the coming update!
