### ISSUE TITLE
[Localization] Add a localization key for "Ini" abbreviation

### ISSUE THREAD

**Issue by Phenomen** [sdenec/tidy5e-sheet#431]
PC Sheet: https://github.com/sdenec/tidy5e-sheet/blob/8b2d599c5222b9b6e410de0b31424a2e2d3c7821/src/templates/actors/tidy5e-sheet.html#L222

NPC Sheet: https://github.com/sdenec/tidy5e-sheet/blob/8b2d599c5222b9b6e410de0b31424a2e2d3c7821/src/templates/actors/tidy5e-npc.html#L154

**Comment by sdenec** [comment]
will be translatable in the upcoming update
