### ISSUE TITLE
[Feature Request] Allow "Toggle Info" pop up to be disabled

### ISSUE THREAD

**Issue by timartiny** [sdenec/tidy5e-sheet#432]
When hovering over an item on an Actor's Sheet there is a popup that says "Toggle Info (<Item Name>)" (or spell name etc). It disappears when pressing any button.

I'd love to have the ability to make that never show up at all! Using a Dice Tooltip module (which also makes a pop up showing the rolls associated with an item/skill/spell) results in conflicting popups. Usually this module ends up on top, blocking info from the Dice Tooltip module.

**Comment by sdenec** [comment]
Toggle popup will be removed in the coming update. It's kind useless anyways ;)
