### ISSUE TITLE
[Feature suggestion]: Add common actions such as Dodge, Dash, Overrun, Shove, Tumble, etc. 

### ISSUE THREAD

**Issue by ctbritt** [sdenec/tidy5e-sheet#434]
All actors can do them! Sort of like the automated actions module from Fantasy Grounds, populate part of the sheet with a section of the common combat actions: 

- Dodge
- Dash
- Grapple
- Help (maybe?)
- Hide
- Ready
- Shove
- Overrun (DMG optional)
- Tumble (DMG optional) 

And then you could attach either DF's convenient effects or run macros to adjudicate them. I already have separate features for Dodge (self-targeted DF's effect), Shove, Overrun and Tumble (using item macros against a targeted creature.) But would this be possible? Or maybe we just need a module that puts an "Actions!" button on the sheet that calls up a multiple-choice menu.

**Comment by sdenec** [comment]
I don't see this as part of the character sheet and more as a separate module. At least this isn'T something I will put into the sheet, soory. But maybe if you want more action abilties take a look at "Argon Combat Hud". I think it's a fantastic module that tries to replicate the action UI from the game solasta. As far as I  know you can select default abilities like dodge, dash and so on.
