### ISSUE TITLE
[Feature Request] Hide Resources

### ISSUE THREAD

**Issue by Larwck** [sdenec/tidy5e-sheet#435]
Love the sheet so much, great work!

A lot of classes don't use bonus resources, in fact I think most. There's a lot of options for hiding unnecessary things in the sheet already, I think it would be great if there was an option to hide the resources bar too (when unused). Would make a lot of extra room for favorited features, weapons, and spells in the attributes page.

Thanks!

**Comment by sdenec** [comment]
In the coming update resources will be hidden in "locked" mode when neither resource names or quantities are assigned.
