### ISSUE TITLE
[Bug] Item icons do not display when there is a space in the name

### ISSUE THREAD

**Issue by YugoNumachi** [sdenec/tidy5e-sheet#438]
When an item has a path containing spaces in the file or folder names, the image is not displayed as the path in "background-image: url(...)" is not put between quotes.

Solution: add quotes in the url(' ... ') part to make sure the path is taken as one string.

**Comment by sdenec** [comment]
Well, in my opinion neither should contain spaces but in any way thanks for the report and solution :) Should be fixed in the next update!

**Comment by YugoNumachi** [comment]
Agreed, but some importers generate file names with spaces, not much we can do about that unfortunately. Thanks for the fix!
