### ISSUE TITLE
Suggested Option: Show Exhaustion/Inspiration Icons on Portrait If > 0

### ISSUE THREAD

**Issue by Dumbhuman** [sdenec/tidy5e-sheet#44]
Rather than always being hidden or always being shown, it would also be nice to have an option for Exhaustion and Inspiration icons to be hidden if they have a value of 0 (Exhaustion level 0, Inspiration = false) but shown on the icon while they have a value of 1 or greater (Exhaustion 1-6, Inspiration = true).

edit: It would be a nice reminder for things that a character doesn't always have and might otherwise forget about while they're hidden away.

**Comment by sdenec** [comment]
Actually that is a good idea and probably could be the default for the "always show" standard setting!

**Comment by sdenec** [comment]
It's now integrated as an option to not confuse newcomers. Go to settings to find it!

**Comment by Dumbhuman** [comment]
This is working very well for me.  Many thanks!
