### ISSUE TITLE
Display Issue with Linked Compendium Entries

### ISSUE THREAD

**Issue by DivertedCircle** [sdenec/tidy5e-sheet#441]
Spells/Features/Etc display oddly when expanded in the character sheet if the entry contains a link to a compendium item. Each compendium link gets expanded to the full width of the character sheet.
![image](https://user-images.githubusercontent.com/26470570/143065871-9c539768-4eff-430d-bdaa-0ba989e6f201.png)

![image](https://user-images.githubusercontent.com/26470570/143065777-6c4b31cb-6513-44a2-8188-03800c147213.png)

**Comment by sdenec** [comment]
![compendium-link3](https://user-images.githubusercontent.com/8881200/143070180-426dc9eb-c7f6-4335-8733-12368910008d.jpg)

**Comment by DivertedCircle** [comment]
After playing around a bit, I've determined it only occurs when the Spellbook Assistant Manager module is also enabled. I see support for this module was already requested at https://github.com/sdenec/tidy5e-sheet/issues/437 so I'll close this issue.

**Comment by kandashi** [comment]
Note, I do not get this issue with both modules enabled, and I dont affect the css/stylings of those types of links anyway. 

I have added compatibility for Tidy5e anyway as a sidenote :)

**Comment by DivertedCircle** [comment]
The issue appears to be resolved regardless. Much appreciated.
