### ISSUE TITLE
[Feature Request] Hide only Death Save rolls

### ISSUE THREAD

**Issue by krysztalzg** [sdenec/tidy5e-sheet#442]
I like idea of hiding death saves from players, but currently the only option is to hide both button and result. Would it be possible to split this option into two? I'd love to let my players click the skull to initiate the roll, but keep the results for DM only.

**Comment by kaelad02** [comment]
While doable with some custom code, Tidy5e Sheet is just letting the core sheet functionality of triggering a death saving throw handle this. IMHO, it would be better to have the dnd5e system add this functionality instead of adding it to Tidy5e Sheet.
