### ISSUE TITLE
[Feature Request] Field for Title or Secondary Name

### ISSUE THREAD

**Issue by pesky-wobbit** [sdenec/tidy5e-sheet#443]
My players are adding titles and aliases - that's awesome, but clutters the chat cards. Would love to see a field on the Tidy 5e sheet for these. Probably just below the name.
Thanks!

**Comment by sdenec** [comment]
Hey, you might just use the "player name" option which adds a Textfield just below the character name. Go to sheet options under DM settings and activate "player name". It won't so anything else but to add the text field where you could enter Names or titles!

**Comment by pesky-wobbit** [comment]
Just what I was looking for. Thanks!
