### ISSUE TITLE
[Feature Request] Secret Block mindful formatting

### ISSUE THREAD

**Issue by susscribe** [sdenec/tidy5e-sheet#444]
Issue use case: When using the 'Secret' format on dark theme and a table the text becomes very hard to read due to being grey on grey as can be seen here:
![image](https://user-images.githubusercontent.com/87147923/144166924-6c44afcf-399a-423f-856e-d9a462caa845.png)

Request: would be great if for that specific case the letter colours were either a lighter shade of grey or another colour, like white.
Thank you for your time and the best sheet module.

**Comment by sdenec** [comment]
I checked and it already ist light text - see attached screenshot. Is the table maybe preformatted and pasted from a website, word document or imported with another tool? It may very well be that the table has integrated text styles that will override any styles I define.

![table_darkmode](https://user-images.githubusercontent.com/8881200/144892866-c7adc759-9229-4dfb-b3f2-287350785d4a.jpg)
