### ISSUE TITLE
[Feature Request] Image background

### ISSUE THREAD

**Issue by susscribe** [sdenec/tidy5e-sheet#445]
![image](https://user-images.githubusercontent.com/87147923/144182581-5a10c4ae-76b9-4d77-b5f8-32d589d559f9.png)
would be interesting if tidysheet let us use an image selected in the options as the sheet's background kinda like the screenshot above is going for in the paper sheet.

**Comment by sdenec** [comment]
I guess this could be possible technically but would also be very distracting as many fields are see through. Also the image sclaing is tricky sinde the sheet can be any size ... I don't think the sheet would really benefit from this and i'm going to pass on this suggestion. If you really wanted to you could change the sheets background yourself with the css module and target the window content for an actor e.g.

´´´css
#actor-Az938959ish .tidy5e.sheet .window-content {
  background: url('PATH_TO_YOUR_IMAGE') no-repeat;
  background-size: cover;
}
´´´
