### ISSUE TITLE
sheet not working

### ISSUE THREAD

**Issue by infias** [sdenec/tidy5e-sheet#448]
The last update made the sheet not usable on FoundryVTT 0.8.9 stable. Module shows active in module settings, but does not show on the sheet or in the configuration settings menu.

**Comment by sdenec** [comment]
Can't confirm. Works fine for me. Any error messages in the console? Are you self hosting or using any foundry hosting services? You could also try to reinstall the sheet.

**Comment by infias** [comment]
I am self-hosting, but I can send a link if needed to help troubleshoot. I
tried reinstalling the module as well as creating a new test world and
enabling just the sheet but to no avail. Here's a screenshot of all I'm
able to see with no errors, or even warnings, in the console.

[image: image.png]

**Comment by infias** [comment]
I manually rolled back to the previous version by installing the released module zip which worked. I then reupdated to the latest which seems to continue to work. Possible bug with the update process or something got the module folder into a bad state. Thanks for the help.
