### ISSUE TITLE
max number of prepared spells not being tracked

### ISSUE THREAD

**Issue by DukeOfSouls** [sdenec/tidy5e-sheet#451]
I have a question about the sheet, not sure whats going wrong.

In the spellbook tab at the bottom of the page you see prepared spells 0/0, the first 0 should be how many u have prepared this updates fine, but the second 0 which should automaticly show how many spells ur class can have prepared based on class level + wis for druid for example just always stays on 0.

even if i take a pre build actor that is correctly filled in from the compendium this always stays at 0, what do i need to do so the sheet tracks your max number of prepared spells properly?

**Comment by sdenec** [comment]
So, it is an input field and you could manually enter the value - and update it on any level up. I know, propably not what you desire. The other method though it seems currently broken (and I don't understand why) would be to create a passive effect and calculate the value like so
```js
data.details.maxPreparedSpells [custom] @details.level + @abilities.wis.mod
```
Strange thin is the wis.mod value won't show up - any other not-mod-value does. I'll have to investigate and I know it worked in the past.

**Comment by DukeOfSouls** [comment]
Yeah I don't mind putting it in manually thats what I did now, was just curious if I did something wrong somewhere as I tought it was automated.

**Comment by sdenec** [comment]
Sorry, no automation by default as it would be difficult to calculate with possible multi classing. The active effect seemed to be a good alternative. When I find out why it doesn't work and manage to fix it I'll let you know.

**Comment by sdenec** [comment]
Hey, should be working now if you create an new passive effect and enter the above formula to auto calculate the max spells.
You also could replace @details.level with a specific or multiple class levels like @classes.wizard.levels!
Hope this helps and makes spell slot management easier :)
