### ISSUE TITLE
[Feature Request] Visualize spells per class

### ISSUE THREAD

**Issue by Nysterian** [sdenec/tidy5e-sheet#452]
One of my players is currently multiclassing Cleric and Druid, and they keep complaining how it's hard to identify which spells are from the Cleric spell list and from the Druid spell list, since they have to prepare them separately.

Would it be possible at all to add a field that lets you "Color" spells differently, based off what classes they come from when multiclassing? I was thinking having them highlighted the same way as magical weapons are highlighted but with different colors.

**Comment by sdenec** [comment]
I'm pretty sure it would be possible but in my opinion this should be a core feature of the 5e system on which I then can build custom visualisation in line with my sheet. I'm not smart enough to devise this feature on my own and most times have to rely heavily on existing features or third party help. So sorry if I can't fulfill this request :(

**Comment by Nysterian** [comment]
No worries, thanks for considering it! You've done an amazing job as-is!

**Comment by gh7531** [comment]
I'm also looking for the feature, either through a module or in the core 5e system itself. There is already a [suggestion for this feature in the 5e issue tracker](https://gitlab.com/foundrynet/dnd5e/-/issues/1351). Maybe some activity there will improve the changes of getting this implemented in the core 5e system :+1:
