### ISSUE TITLE
[BUG] Exhaustion automation and CUB incompatibility

### ISSUE THREAD

**Issue by ZotyDev** [sdenec/tidy5e-sheet#455]
Hi, when a exhaustion level is first defined everything works fine, but after that a error appears everytime I try to change the exhaustion level. (the code is always the same, unless I refresh the page, then it changes and stays until another refresh)
![image](https://user-images.githubusercontent.com/34866157/145687160-15104da0-e4cb-4e56-b5f7-ab219c1dc475.png)
Also, the first effect of exhaustion applied is the only that works, all the others after aren't applied and after a page refresh the effects disappear.
![image](https://user-images.githubusercontent.com/34866157/145687236-a618c0b2-a134-44d6-9764-e923a013ee5a.png)
I should point that I'm using the compatibility with CUB, and this only happens with custom set effects. I'm trying to use [this](https://www.foundryvtt-hub.com/guide/under-the-hood-enhancing-exhaustion-condition/) guide.
My intuition says that the problem is related to removing or checking a effect that is already removed.

**Comment by sdenec** [comment]
So sorry for the late reply. I know it is about half a year late but did you solve this issue? On my latest try I didn't fin an issue with it.

**Comment by ZotyDev** [comment]
Hey, the issue got solved after I updated my module list a month later, might have been a bug with CUB. Now everything works as it should. Thanks for the reply.
