### ISSUE TITLE
Feature Request: Implement spell preparation sorting buttons for NPC sheet

### ISSUE THREAD

**Issue by archeresky** [sdenec/tidy5e-sheet#456]
I would like to request adding the buttons used for filtering spellbook spells by preparation mode to the NPC sheet, as it would make working with NPCs that have a lot of spells much easier. 
![image](https://user-images.githubusercontent.com/73297245/145722458-69b13675-969f-4065-a9dc-d1e37e16e2e4.png)
They could be added just above or below the Spellbook separator in the card
![image](https://user-images.githubusercontent.com/73297245/145722482-cd569a84-58e6-495f-822d-4bb78f8af116.png)

**Comment by p4535992** [comment]
This issue  seem already solved, we can close it.
