### ISSUE TITLE
Right-click -> Equip/Unequip for NPC sheets

### ISSUE THREAD

**Issue by Jyhnu** [sdenec/tidy5e-sheet#460]
I was wondering if it was possible to add a toggle to equip or unequip inventory items in NPC sheets. This would be especially great with the new AC calculation introduced in the last Foundry big update.

**Comment by sdenec** [comment]
Equipping can now be done via rightclick. NPCs items sadly aren't set up for attunement as Player items are though. I can't figure out how to make it accessable. For now attunement has to be done by editing the item directly. But I guess equipping is a mor frequent thing than attunement is.
