### ISSUE TITLE
Version 9 compatibility

### ISSUE THREAD

**Issue by treywatson** [sdenec/tidy5e-sheet#461]
I recently had to upgrade to _version 9 (Build 238)_ of Foundry VTT. Using _DnD5e - Fifth Edition System v. 1.5.6_ and am unable to load tidy5e-sheet due to incompatibility. I am sure that you are working on this but my players are heavily dependent on this AWESOME tool you have created and I am hoping that there will be an update soon. Could you provide any information on if and when we can expect an update to the module that will address it's compatibility with version 9?

Thanks!

**Comment by sdenec** [comment]
I don't see any incompatibilities for the sheet and foundry version 9.9 - I have updated two systems and it works fine.
![sheet](https://user-images.githubusercontent.com/8881200/147505505-4c416ed8-8b83-4d23-aa44-c88d28b041e8.jpg)

**Comment by treywatson** [comment]
Maybe update the manifest file? It's showing previous version as maximum
supported version.

**Comment by sdenec** [comment]
Manifest was updated. I hope it works now!

**Comment by treywatson** [comment]
Awesome, thanks! Working just fine now.
