### ISSUE TITLE
"Hide Death Saves from Players" not working

### ISSUE THREAD

**Issue by turboraton** [sdenec/tidy5e-sheet#464]
![image](https://user-images.githubusercontent.com/70917100/147687917-0e7fb0db-85dd-41a7-8015-1f4bd7cf67ec.png)

Hey there! Thanks for the amazing mod. The option that I'm attaching on the picture is not working, I tested it as a player, where I'm not availble to roll any death save roll and as a DM where it shows on the chat to everyone anyways.

**Comment by kaelad02** [comment]
The setting will hide the death save success/failures and the option to roll them from the player. It doesn't change the roll mode. This was also asked earlier in #442
