### ISSUE TITLE
Formatting Issues as Viewed by Players without Owner Permissions

### ISSUE THREAD

**Issue by Dumbhuman** [sdenec/tidy5e-sheet#47]
Currently the view that other players can see for player character sheets they don't own could use some tidying.

Here's the Tidy Sheet for a player character as viewed by someone with Limited permission:
![image](https://user-images.githubusercontent.com/63615591/85890023-69bf8c00-b7a1-11ea-8ac2-fa8aa410d27e.png)

I'm not sure what the empty section on the top is and at least for my purposes I'd prefer the biography next to the description field as opposed to under it.

I think the Alt5E Sheet layout as shown below in the same situation is a good layout to emulate (even if a little redundant on the name display):
![image](https://user-images.githubusercontent.com/63615591/85889586-9e7f1380-b7a0-11ea-9277-c1f72efe772e.png)

**Comment by sdenec** [comment]
Should look better now! Forgot to remove an effect for the image so it blended itself into the background. Arranged Textfields as columns.
