### ISSUE TITLE
V9 change to Roll()

### ISSUE THREAD

**Issue by szefo09** [sdenec/tidy5e-sheet#471]
https://github.com/sdenec/tidy5e-sheet/blob/104b6fd857b50475205baeba77711632c1d7bf34/src/scripts/tidy5e-sheet.js#L435
https://github.com/sdenec/tidy5e-sheet/blob/104b6fd857b50475205baeba77711632c1d7bf34/src/scripts/tidy5e-npc.js#L323

Those lines should be updated to support the V9 async Roll() method. Something like
`
const roll = await new Roll(formula).roll();
const result = roll.total
`

**Comment by sdenec** [comment]
Done, I hope. The console keeps showing a notice about the Roll() function becoming asynchronous, though.
