### ISSUE TITLE
Minor Issue: NPC Skills list not alphabetized if custom skills added. (dnd5e+dark matter)

### ISSUE THREAD

**Issue by Android8675** [sdenec/tidy5e-sheet#472]
Hey all, First all, love this character sheet, by far my favorite. I found a minor "thing", but wanted to put in a issue report because, it's beyond my ability to fix myself.

So I'm tinkering with a small add-on for [Dark Matter](https://gitlab.com/dark-matter1/dme) (Sci-fi setting) that adds 3 skills to Players/NPCs (Data, Pilot, Technology).

Usually the Skills list sorts in the 3 skills, but occasionally they are left at the end of the Skills list (unsorted). On Tidy the Player Skills list looks OK, but the NPC sheet does not.

Player:
![image](https://user-images.githubusercontent.com/440945/148798800-26bf4fbe-6081-4018-8740-578994fe3a33.png)

NPC:
![image](https://user-images.githubusercontent.com/440945/148798856-123ca040-b43d-4cbd-807f-5f095a497927.png)

Fix or no fix, up to you. We had a similar issue with the dnd5e game system and they fixed it.

Thanks for your work on this.
-A.

**Comment by sdenec** [comment]
Hi, little late response ... Is this still an issue? I actually don't sort abilities - neither for pcs nor npcs. So this must be something that is handled by the core system. That's why I'm a litlle bit puzzled why one sheet does it right and the other doesn't. Also I don't know how I could sort them myself ... so if this is still an issue I'm afraid I currently lack the ability to fix it. Sorry!

**Comment by arbron** [comment]
Not a dnd5e issue, you just need to modify how you are looping over the skills so you loop using the order in `CONFIG.DND5E` rather than the order in the character's data:

Old:
```handlebars
{{#each data.skills as |skill s|}}
```

New:
```handlebars
{{#each config.skills as |skill s|}}
```

That is the change we made in the core 5e sheets back in the day.

**Comment by sdenec** [comment]
I think that has sorted itself out with v10 and the 5e update? At least it seems skills are now alphabetically sorted for npcs.

**Comment by p4535992** [comment]
I confirm we can close the ticket.
