### ISSUE TITLE
v9

### ISSUE THREAD

**Issue by brunocalado** [sdenec/tidy5e-sheet#473]
Hi.

Please remove the foundry vtt warning.

Replace "compatibleCoreVersion":"0.9.0" by "compatibleCoreVersion":"9".

Docs: https://gitlab.com/foundrynet/foundryvtt/-/issues/5635

**Comment by zeel01** [comment]
The compatible version seems to currently be `0.9.9` which isn't a real version. The current core version is now simply `9`.

![image](https://user-images.githubusercontent.com/1721836/150163824-77059ab8-5a38-4f71-aff7-c96d2a2130eb.png)

Created PR #474

**Comment by CaosFR** [comment]
I'm agree please update your great mod :)

**Comment by sdenec** [comment]
done

**Comment by CaosFR** [comment]
Thanks for your work.

**Comment by sdenec** [comment]
Sorry it took so long!

**Comment by CaosFR** [comment]
No problem :)
