### ISSUE TITLE
GM ability to force client settings

### ISSUE THREAD

**Issue by M0nk3yy** [sdenec/tidy5e-sheet#475]
Suggestion:

Although it is great to have many elements be customisable per player - there are some settings I would like to be able to override as GM. For example I have players who are total noobs, and are able to be confused between the Journal character sheet tab, and Foundry's Journal Entries sidebar tab. This would also help me be able to minimise the number of tabs they see - simplifying the character sheet. Currently this is a client setting that I cannot change.

I'm not sure what the best way to implement this is, perhaps with some integration related to the "Force Client Settings" mod (https://foundryvtt.com/packages/force-client-settings). Whilst it works with ordinary mod settings, it is unable to reach inside mod submenus, such as Tidy5e's.

**Comment by kimitsu** [comment]
You can do it with [Force Client Client Settings](https://foundryvtt.com/packages/force-client-settings) now. Head to Configuration and find Force Client Settings editor, from there you can force these settings, just look them up by their name.

**Comment by M0nk3yy** [comment]
Sweet, thanks. I love Force Client Settings :D

**Comment by kaelad02** [comment]
Yeah, should probably just leave this functionality to that other module rather than build it into this

**Comment by sdenec** [comment]
I'd love to have a cleaner and maybe more approachable solution for all the different settings the sheet offers. I tried to build a one shoe fits all thing but having a global dm setting and player overwrites for every tiny thing would be really complicated i figured. So I always thought the dm could set up all sheets once and then a player could customize. I know this is not the best way especially when a dm has to manage many groups or players. I really struggled to get the current settings to work. If anyone wants to overhaul the system I'm very open to it :) Force client settings is the best solution until then I guess^^

**Comment by p4535992** [comment]
This ticket can be closed , the issue is resolved from other modules
