### ISSUE TITLE
inspiration support

### ISSUE THREAD

**Issue by zach-at-healthpilot** [sdenec/tidy5e-sheet#477]
Is there support (either in this module, or another) for:
- additive player inspiration (values higher than 1)
- bardic inspiration dice

**Comment by sdenec** [comment]
The foundry 5e system only allows to have a single inpiration (true or false) not a numbered value. Bardic inspiration is more like an effect and should propably be handled with an active effect. So I'm sorry but I can't add it to the sheet.
