### ISSUE TITLE
Option for Multiattack at the top of NPC sheet

### ISSUE THREAD

**Issue by xFaultx** [sdenec/tidy5e-sheet#478]
Hey I really like the Tidy5e sheets, but the thing I have the hardest time with is for NPCs is making sure I'm utilizing their multi attacks. It would be really helpful to have the 'Multiattack' listed at the top of the actions, much like it is in the standard DND stat block

**Comment by p4535992** [comment]
This go outside the scope of the module other modules like "Multiattack 5e" or "Mob Attacck " do the job
