### ISSUE TITLE
Font Size Spillovers

### ISSUE THREAD

**Issue by Dumbhuman** [sdenec/tidy5e-sheet#48]
I don't recall noticing this before, but currently the font size in certain places seems to be a bit too big to fit into certain boxes.  For example on a Player Character sheet, the ability scores show spillover, obscuring parts of the words Intelligence and Constitution and even shaving the side on some of the numbers:
![image](https://user-images.githubusercontent.com/63615591/85890580-7d1f2700-b7a2-11ea-876e-32857cc66056.png)

Also, the checkbox to set proficiency for Charisma isn't accessible because it's gone off the bottom.

On this NPC sheet, it's very noticeable for AC and the 6 in 16 is getting shaved on the side a bit under Dex:
![image](https://user-images.githubusercontent.com/63615591/85890846-00d91380-b7a3-11ea-84c1-f5b9b35728b3.png)

**Comment by sdenec** [comment]
That clearly is a font problem. You should see another font type - the "old fashioned" one. I'm not sure why it isn't showing up. Can you tell me what browser you are using?

**Comment by Dumbhuman** [comment]
Those screenshots were taken using the Foundry VTT application itself.  It looks the same using the latest verison of Firefox on Windows 10 to check what players see.  Admittedly I'm still on 6.2 of the Foundry application so perhaps that's part of the problem?

**Comment by sdenec** [comment]
yes, you are right. The font I used is new with 6.3 and when it isn't present it will fall back to the default font which renders as you have screenshotted!

**Comment by sdenec** [comment]
You can update the sheet. I switched back to the default font and it should render correct again!
