### ISSUE TITLE
Conflict with PopOut! Module

### ISSUE THREAD

**Issue by Dialectikal** [sdenec/tidy5e-sheet#482]
I've discovered a conflict with the PopOut! module. Whenever I edit an item on the sheet, the item options box stays open after closing the item window. It will do this for up to 3 items usually, before it will close.

![image](https://user-images.githubusercontent.com/31572084/151927651-685eed15-a994-4706-b49a-4a8b8aafe2ba.png)

This only occurs when the character sheet is popped out.

**Comment by Dialectikal** [comment]
Even when disabling the right-click options, this is still a problem.
![image](https://user-images.githubusercontent.com/31572084/151932382-fbe6f875-5648-42ad-b8da-5505f5209ecc.png)

**Comment by Dialectikal** [comment]
I presented this issue to tposney, who develops the PopOut module. He was able to uncover the issue and make a change on his side, but the following needs to be addressed within Tidy5e-sheet:

https://github.com/League-of-Foundry-Developers/fvtt-module-popout/issues/64#issuecomment-1059897403

**Comment by sdenec** [comment]
Thanks for your help! You don't have by any chance the code that would fix this issue? What should $(document) be replaced with in order to make it work with popOut! ?

**Comment by Dialectikal** [comment]
It seems as though there are a few possible solutions, and I'm not sure which is best. I asked Posnet if they know what code should be implemented, but it might also be something worth digging into since you probably have a better understanding of all the things Tidy5e interacts with.

**Comment by Dialectikal** [comment]
"The [getRootNode](https://developer.mozilla.org/en-US/docs/Web/API/Node/getRootNode) API will reliably get the correct document element from an arbitrary DOM node, regardless of which window it's in." - Posnet

**Comment by sdenec** [comment]
I think I got this fixed. Do me a favor and try it!

**Comment by Dialectikal** [comment]
Hey, thanks! I've messed around with it a bit and it looks like it's working. Nice job.
