### ISSUE TITLE
Renamed ability score abbreviations don't work

### ISSUE THREAD

**Issue by arbron** [sdenec/tidy5e-sheet#483]
Currently the localization for the ability score abbreviations is performed using hardcoded localization keys, not the value of the abbreviations available in `CONFIG.DND5E.abilityAbbreviations`. This makes it more difficult for modules to change the names of existing ability scores and have those changes reflected on TidySheet.

Looking through the codebase, I also noticed the same issue with currency abbreviations. A few versions ago `CONFIG.DND5E.currencies` was refactored to include abbreviations.

**Comment by sdenec** [comment]
After a few mess ups I think I got it now
