### ISSUE TITLE
Problem with abbreviations in latest version: 0.5.23

### ISSUE THREAD

**Issue by joevaughan** [sdenec/tidy5e-sheet#485]
Sheet is showing the CONFIG.DND5E.AbilityAbbreviations.x as the label for abilities instead of the variable substitution.
![tidy5esheet-error](https://user-images.githubusercontent.com/92576588/152325882-efe1d659-5872-4237-980d-f9e0bd40f743.png)

**Comment by sdenec** [comment]
Yeah, I messed up somewhere. In progress to fix. 0.5.24 should hit shortly

**Comment by sdenec** [comment]
Okay, seems to be fixed
