### ISSUE TITLE
Inventory Weight/Charge/Usage formatting off when Attunement Symbol present

### ISSUE THREAD

**Issue by GambetTV** [sdenec/tidy5e-sheet#489]
When an item requires attunement, the Sun Symbol pushes Weight/Charges/Usage to the left, making quickly reading these things (especially weights) a bit more difficult than it needs to be.

**Comment by sdenec** [comment]
Sorry for the late reply. I can't see anything beeing pushed by the attunement icon. Neither in list nor grid nor card view. Maybe you can attach a screenshot if this issue still persists?

**Comment by GambetTV** [comment]
Do you see how the inclusion of the little sun symbol on the Pearl of Power causes the 0.1 of the weight and 1/1 of the Item Uses to be shifted slightly to the left compared to the stats of the objects above and below it?

![image](https://user-images.githubusercontent.com/72000497/167770079-85f2a5cf-57cb-43d9-baef-a9d7e63f8f2b.png)

**Comment by sdenec** [comment]
Ah, you don't use the context menu. I didn't check the inline buttons. I'll have to check if I can fix that

**Comment by sdenec** [comment]
Hi. Ich checked the layout and I can't replicate your issue. All items are correctly aligned ...
![correct_layout](https://user-images.githubusercontent.com/8881200/168467766-db8e04f7-226d-4dd2-a6d4-5bde5333cb6e.png)

**Comment by GambetTV** [comment]
The issue occurs when you lock the character sheet. When the sheet is unlocked it looks like how you've got it.

**Comment by sdenec** [comment]
Should have send both states. But even in the locked state I can't see any issues ...
![correct_layout](https://user-images.githubusercontent.com/8881200/168539162-44f508d4-bf4c-49fb-91e1-2dd9ad8f53b5.png)

**Comment by sdenec** [comment]
Okay, now I figures it out. It's an issue with the gm option "gm can always edit"! because even in the locked state the trash can icon is present but the column width presumes it is not. At least now I know where to look to try and figure out if I can solve it :)
