### ISSUE TITLE
Suggested Option: Ability to Hide Spellcasting Section for NPCs that Don't Use It

### ISSUE THREAD

**Issue by Dumbhuman** [sdenec/tidy5e-sheet#49]
I very much appreciate the ability to add spellcasting on demand, but I would love the option to hide it for the many NPCs that will never cast a spell (just as we have the ability to hide unused traits/proficiencies).

**Comment by sdenec** [comment]
Good idea! Empty spellbook are now hidden - just the headline is visible so you are still able to toggle spellbooks if you want to add spells (or create new npcs). Good tradeoff in my opinion!
