### ISSUE TITLE
9.249 Incompatible - Which "Version 9" is good?

### ISSUE THREAD

**Issue by alltheusernamesaretaken0** [sdenec/tidy5e-sheet#491]
Apologies if this should have been self-evident. I finally updated Foundry to "Version 9" only to find that while this is the banner on the bottom, the full version number is 9.249. What is the latest build with which Tidy53Sheet is compatible?

**Comment by sdenec** [comment]
Hi. The latest release is compatible to foundry 9+ if I understand your question correctly
