### ISSUE TITLE
Unable to re-arrange favourites

### ISSUE THREAD

**Issue by Seamonster73** [sdenec/tidy5e-sheet#492]
This may be 'user error' so apologies in advance if that's the case...

In the past I thought it was possible to re-arrange items that had been marked as favourites, by dragging and dropping them. That no longer seems to be the case and the page throws an error to the console whenever I try to move the item.

To clarify: re-arranging items via drag and drop still works on the inventory tab. But it doesn't work for the 'favourited' version of the item on the front-page/attributes tab. This makes the sheet look a bit messy with weapons, equipment, and consumables all randomly mixed together.

The error that gets thrown is as follows:

```
tidy5e-favorites.js:436 Uncaught TypeError: app.actor.updateEmbeddedEntity is not a function
[Detected 1 package: tidy5e-sheet]
    at HTMLLIElement.<anonymous> (modules/tidy5e-sheet/scripts/app/tidy5e-favorites.js:436:25)
    at HTMLLIElement.dispatch (jquery.min.js:2:43064)
    at HTMLLIElement.v.handle (jquery.min.js:2:41048)
```

If it helps, I've attached a copy of a gif showing the issue occurring here:

![Tidy](https://user-images.githubusercontent.com/85457807/154032515-b2cc7f96-33d5-4130-8a5f-1ba035bc3e99.gif)

**Comment by sdenec** [comment]
Favorites in their tab can't be rearranged. In my opinion the favorites system is somewhat flawed but I'm not able to fix this - I'm not a skilled enough programmer and this part of the sheet was copied from another module a long while ago.

**Comment by Seamonster73** [comment]
Ah OK. Thanks for replying.

I'll close the ticket down in that case.
