### ISSUE TITLE
Feature sugestion "add new attributes"

### ISSUE THREAD

**Issue by altair984** [sdenec/tidy5e-sheet#493]
would it be possible to add the option to add new attributes like the obsidian module does? i ask this to be able to play with your character sheet to other D&D5e compatible games like carbon 2180, getfunk, lord of the rings 5e, which have different attributes like hacking, exploration and many other different attributes. Thank you very much

**Comment by sdenec** [comment]
It might certainly be possible but I sadly lack the skill (and time to learn) to implement this. Sorry! Maybe there is a compatible module that adds this feature?

**Comment by altair984** [comment]
Thank you very much for your answer, unfortunately there is no module compatible with this option. It's a shame because your character sheet is the best of all the ones in foundry for the D&D5e system (at least for me) and I wish I could still use it in Star wars 5e, carbon 5e and other compatible systems, but I also understand your point and I understand the situation, so sadly, I will have to use the alternative sheets for those compatible systems. As I said at the beginning I thank you very much for answering me so quickly.
My pleasure and thank you very much ¡¡¡¡
