### ISSUE TITLE
[Feature Request] Skills with Different Abilities

### ISSUE THREAD

**Issue by NdranC** [sdenec/tidy5e-sheet#496]
Would it be possible to add support for the variant rule "Skills with Different Abilities" PHB p. 175?

Seems to be very commonly used and it's a pain to deal with it in foundry. I'm actually not sure if this request is under the purview of sheet modules but I figured might as well ask. Thanks for your time.

**Comment by sdenec** [comment]
Hi, since it is a variant rule it should propably be something for the 5e Core module. Apart from that I'm not smart enough to implement that kind of functionality into my sheet. So sorry!
