### ISSUE TITLE
[Request] Custom skills/Sub-skills

### ISSUE THREAD

**Issue by Orionox** [sdenec/tidy5e-sheet#497]
I was just wondering if it would be possible to add the ability to create custom skills. Also, it would be nice to be able to create "sub-skills." I have started to play Advanced 5e by level-up and their system has sub-skills and two other base skills  "engineering" and "culture" and it would be lovely if I could add those along with some of the subskills to the tidy 5e character sheet in a well tidy way.

**Comment by sdenec** [comment]
Is it possible - pretty sure. Can I do it - I'm afraid not. I'm sorry but I'm not smart enough to implement custom skills or subskills. That calls for another mod - if there is one.
