### ISSUE TITLE
Modifiery not modifying for proficiency/half proficiency/expertise.

### ISSUE THREAD

**Issue by shawndibble** [sdenec/tidy5e-sheet#5]
In the character sheet. If I click the button for proficiency/half proficiency/expertise, the total value 14 =>16 changes instead of the modifier 2 => 3.

![image](https://user-images.githubusercontent.com/1980293/83319121-176e6800-a201-11ea-9f99-286b775c0bc1.png)

![image](https://user-images.githubusercontent.com/1980293/83319129-29500b00-a201-11ea-8de1-f8d378dba0d4.png)

**Comment by sdenec** [comment]
Now fixed in v0.1.5!
