### ISSUE TITLE
Module fails to initialize

### ISSUE THREAD

**Issue by EatsShootAndLeaves** [sdenec/tidy5e-sheet#501]
**Foundry Version**: V9 (live)
**Hosting provider**: The Forge
**DND5e System Version**: 1.5.7
**Tidy5e Version**: 0.5.25

**Issue**: Tidy5e fails to initialize upon launching a game, returning the following error at the very top of the console:
`Uncaught SyntaxError: Invalid or unexpected token (at settingsList.js:448:29)` 

This error persists even without any other modules enabled, including on a freshly-made test world. While Tidy5e appears in the module list, it doesn't have a section in module settings. Neither uninstalling/reinstalling DND5e or Tidy5e have had any effect.

**Comment by sdenec** [comment]
This must be an issue with The Forge. The sheet works fine on a local/self hosted environment. I also checked the file - there is no unusual character to be found ...

**Comment by EatsShootAndLeaves** [comment]
Reviewing it this morning, it looks like the sheet is working again, which leads me to think the same. I'm not really sure on the specifics of what might have been happening, but I can only guess that the Forge servers weren't properly loading the module.
