### ISSUE TITLE
Long values within source field result in layout issues

### ISSUE THREAD

**Issue by arbron** [sdenec/tidy5e-sheet#502]
A long value within the "Source" field at the top of NPC sheets results in the top of the sheet being spread out beyond the bounds of the application:

<img width="749" alt="Screen Shot 2022-04-08 at 16 07 09" src="https://user-images.githubusercontent.com/19979839/162545043-2e841d05-33ec-4fb8-ace0-d3f293dfacd2.png">

Here is the same NPC without the source value:

<img width="751" alt="Screen Shot 2022-04-08 at 16 07 18" src="https://user-images.githubusercontent.com/19979839/162545055-da6f06d3-004f-421c-a18d-6a8c67ca392d.png">

**Comment by sdenec** [comment]
The source field was not intended for long text. The text will be cut now to keep the layout intact. The actual text can be read when you hover over the source field. It's the best solution for now.
