### ISSUE TITLE
Localized currency does not work

### ISSUE THREAD

**Issue by Altrix1** [sdenec/tidy5e-sheet#503]
Localized currency does not work (always English version: PP GP EP SP CP)
I have to change for it to work:

files:  scripts\tidy5e-sheet.js

from:
let Id = id.charAt(0).toLowerCase() + id.slice(1);
data.data.abilities[id].abbr = CONFIG.DND5E.abilityAbbreviations[Id];

to:
let Id = id.charAt(0).toUpperCase() + id.slice(1);
data.data.abilities[id].abbr = game.i18n.localize(`DND5E.Ability${Id}Abbr`);

from:
let currency = $(this).data('denom').toLowerCase();
let abbr = CONFIG.DND5E.currencies[currency].abbreviation;
if(abbr == CONFIG.DND5E.currencies[currency].abbreviation){

to:
let currency = $(this).data('denom').toUpperCase();
let abbr = game.i18n.localize(`DND5E.CurrencyAbbr${currency}`);
if(abbr == `DND5E.CurrencyAbbr${currency}`){

**Comment by sdenec** [comment]
That actually is how it was before but then I got complaints that some other translations didn't work and ist had to be changed to this. So now I'm confused.

**Comment by Padhiver** [comment]
Hello',
I can confirm that for French the abbreviations don't work either, but using the method of the first post, it works again. 
Good luck with that ! 😅

**Comment by sdenec** [comment]
Reverted back to previous values
