### ISSUE TITLE
Double, bad looking "Actor On Use Macros" 

### ISSUE THREAD

**Issue by Altrix1** [sdenec/tidy5e-sheet#505]
Double, bad looking "Actor On Use Macros" on NPC and PC

maybe it could be hidden in "show / edit empty triats"?

![image](https://user-images.githubusercontent.com/86872105/163675972-e1bdcee8-0a2c-4c6b-a534-8b383348ab64.png)

**Comment by sdenec** [comment]
That's nothing I can influence. My bet is that it looks the same in the default sheet - At least the code is exactly the same. Maybe an issue with the module that genereates these entries?
