### ISSUE TITLE
Switch to using new 5e max attunement field

### ISSUE THREAD

**Issue by arbron** [sdenec/tidy5e-sheet#507]
With 1.6 the 5e system added a field to track max attunement: `attributes.attunement.max`. Tidy should migrate from its custom field to this core one for cross-compatibility with other sheets.

See 5e [issue #1311](https://gitlab.com/foundrynet/dnd5e/-/issues/1311)

**Comment by viewho** [comment]
+1

**Comment by sdenec** [comment]
replaced as suggested. Thanks!
