### ISSUE TITLE
Leveling drop-down not present after dnd5e system update to 1.6

### ISSUE THREAD

**Issue by TheFinalPerry** [sdenec/tidy5e-sheet#508]
After updating the dnd5e system to version 1.6 or later the drop-down for leveling does not appear on tidy sheets. There is no leveling option in details any longer. 

Tidy sheet: 
![tidylevel](https://user-images.githubusercontent.com/104395383/165591079-2f791701-7efd-422f-8896-99f02f725bfa.png)

Default sheet:
![defaultsheet](https://user-images.githubusercontent.com/104395383/165589979-c558813c-c30a-4377-aec1-ddf59bd3141c.png)

Details after update:
![leveldetails](https://user-images.githubusercontent.com/104395383/165591014-0b473edd-0e07-4a1d-a52e-0efdf64017e6.png)

**Comment by sdenec** [comment]
Should be fixed. Thanks!
