### ISSUE TITLE
Support Advancement Tab in Class Item

### ISSUE THREAD

**Issue by Sephalopod** [sdenec/tidy5e-sheet#512]
Class items have a new Advancement Tab that appears broken when using tidy5e for class items. Many of the graphics are duplicated and the page needs some structure to separate levels and features. Icons and linked items are hard to read in tidy5e's dark mode.

EDIT: Subclass items have been added in this update and are also affected.
![advcmttabbug](https://user-images.githubusercontent.com/60808544/166096818-6ee7ef5e-1945-4467-8740-2efc5e2107ef.png)
Compared to default:
![advcmttabdflt](https://user-images.githubusercontent.com/60808544/166096951-c8ff1021-665d-436f-be6c-e8e021f0fc6e.png)

**Comment by sdenec** [comment]
fixed
