### ISSUE TITLE
The text options block the entire persons of interest, locations of interest, quest, and misc box.

### ISSUE THREAD

**Issue by Orionox** [sdenec/tidy5e-sheet#513]
It makes it impossible to add or remove anything to or from the boxes

**Comment by sdenec** [comment]
Please clarify the issue. I can edit said fields without any porblem.
![edit](https://user-images.githubusercontent.com/8881200/165889691-e5117c18-26e0-45c9-b123-f5a684ce877c.png)

**Comment by sdenec** [comment]
Okay, then I'm afraid that's out of my scope, sorry.

**Comment by Orionox** [comment]
> Okay, then I'm afraid that's out of my scope, sorry.

Couldn't you make the field resizable? "journal entry" is resizable when I pull the character sheet out larger. I'd do it myself if I knew how.

**Comment by sdenec** [comment]
What you can do is install the "custom css" module and add this to your global or user style
```css
.tidy5e.sheet.actor .left-notes {
	width: 50%;
	max-width: 100%;
}
```
change width to the percentage that suits you or assign a fixed pc value (ie. 600px). But a fixed value might cause issues with the journal field if your window is to small.
I hope this helps!
