### ISSUE TITLE
No way to adjust font size?

### ISSUE THREAD

**Issue by Apockelipse** [sdenec/tidy5e-sheet#517]
Sheet seems unaffected by font size setting with no visible way of changing font sizes meaning hard of seeing are SOL.

**Comment by sdenec** [comment]
The font size settings only apply to the main UI. Sheets are excempt from the scaling. This is true for the default sheet aswell. Scaling the font would completely destroy the layout. Sorry.

**Comment by Apockelipse** [comment]
then perhaps adjust the font size slightly? from what I can tell right now its 12px which the default sheet is _not_ that small it makes it incredibly hard to read for anyone with sight difficulties.
