### ISSUE TITLE
Feature Request: Death Save Tracking

### ISSUE THREAD

**Issue by DivertedCircle** [sdenec/tidy5e-sheet#52]
Would love a section for tracking Death Saves, even if it's just a series of checkboxes or circles you can fill in. I feel like there is space for this under the Hit Points/Hit Dice/etc row, above the varies tabs.

**Comment by sdenec** [comment]
Well, since you can only have death saving throws when you are dying you will only get them if you have 0 hit point. they appear on your character portrait ;)
