### ISSUE TITLE
Features don't display uses when formula is used for max uses

### ISSUE THREAD

**Issue by DivertedCircle** [sdenec/tidy5e-sheet#521]
Setting a feature to have a number of Limited Uses that uses a formula instead of a set number, such as used equal to @attributes.int.mod, doesn't display the available number of uses on the sheet.

**Comment by kaelad02** [comment]
Not sure if it was fixed, but it's working for me with dnd5e v1.6.1 and Tidy5e Sheet v0.5.32. I created a test feature using `@abilities.cha.mod` as the max uses.

![image](https://user-images.githubusercontent.com/19502084/179130615-e88d8ef6-4bb2-4edd-8663-7efc7ba6e3c9.png)

Then on the character sheet's Features tab, it shows the correct number of uses:

![image](https://user-images.githubusercontent.com/19502084/179130697-ebfc2fbf-012f-497a-a952-5e8a4f652e9f.png)

**Comment by DivertedCircle** [comment]
I'm on the same module version but dnd5e v1.6.3 and the issue persists.
![image](https://user-images.githubusercontent.com/26470570/179298844-cc3681cd-941d-4e43-985c-f7a9eb2c10a2.png)
![image](https://user-images.githubusercontent.com/26470570/179298949-034d81dd-7831-4ac6-ae47-5df43649f881.png)

**Comment by SlimDante** [comment]
it would appear you have "attributes" not "abilities" in your test.

**Comment by DivertedCircle** [comment]
Right you are, my mistake. Closing this now. Thanks!
