### ISSUE TITLE
Feature Request: Collapsible Sections

### ISSUE THREAD

**Issue by DivertedCircle** [sdenec/tidy5e-sheet#522]
With the recent updates to the 5e system, the character sheet is now more crowded with the added Background and the expanded Class Levels sections. The option to click on the header of these sections and any others to collapse them would be appreciated.

**Comment by Shuggaloaf** [comment]
Hey @DivertedCircle I have a (now pretty old) open issue for this as well at #407. At the time these sections we'rent available but I agree to add them as well. 

I endorsed yours, would appreciate if you do the same for mine. Dev likely to close or combine these at some point. Thanks!

**Comment by DivertedCircle** [comment]
See above #407. Would love to see all this added.

**Comment by Shuggaloaf** [comment]
> See above #407. Would love to see all this added.

Haha, sorry for not being clear. I just meant go to mine and give it a thumbs up. But this is good too :)
