### ISSUE TITLE
NPC skills do not have the correct colour scheme on a translated card.

### ISSUE THREAD

**Issue by Padhiver** [sdenec/tidy5e-sheet#525]
Hello,
Like title say, NPC skills do not have the correct colour scheme on a translated card. Here are two screenshots, on the left in the skills section : 

Vanilla ; 
![2022-05-10 23_13_16-a • Foundry Virtual Tabletop](https://user-images.githubusercontent.com/80126915/167723154-446dc83e-a0d8-4efe-82aa-a28fcfc30775.png)

With translation ;
![2022-05-10 23_13_37-a • Foundry Virtual Tabletop](https://user-images.githubusercontent.com/80126915/167723198-3521fa79-d2fb-4e2b-9b4c-a39077baae5c.png)

I don't know if you can fix it, it's not a big deal but since it's probably not normal, I'm bringing it up. Knowing that for the player sheet, the problem doesn't exist. 😃 

Thank you for your hard work !

**Comment by sdenec** [comment]
Does the player sheet reorder the translated skill alphabetically? Seems to be the problem. Though I don't know why since just every other row is colored no a specific one ...

**Comment by Padhiver** [comment]
Yes she does, here a screenshot : 
![image](https://user-images.githubusercontent.com/80126915/167841514-3065f146-a28e-4c0a-8c0a-2e5eae74b3c2.png)

**Comment by sdenec** [comment]
should be fixed now!
