### ISSUE TITLE
One currency bug for french

### ISSUE THREAD

**Issue by Kariaudhanaur** [sdenec/tidy5e-sheet#526]
Sorry, a verrrryyyyyy minor bug, and I'm too noob to find the file to update to push to you this tiny bug.
On the sheet you see :
![image](https://user-images.githubusercontent.com/92259502/167949562-18c8a88f-4078-4757-b32c-838ac87238a1.png)

It should be "PO" and not "OR". 

Thank you.

**Comment by sdenec** [comment]
Hey, pretty sure that isn on me but a mistake in the french translation. Could you check if the default sheet display the same?

**Comment by Kariaudhanaur** [comment]
Hi !
On the standard sheet It only displays the type of coin, but not the french word "coins"
![image](https://user-images.githubusercontent.com/92259502/168152446-f53128fd-dded-4900-a526-b81dfdef9043.png)

As it is in english : 
![image](https://user-images.githubusercontent.com/92259502/168152611-4eddf6be-e6e7-4f63-9ba6-33e51e668db9.png)

TidySheet in english : 
![image](https://user-images.githubusercontent.com/92259502/168152708-7c31aa9e-d862-444e-ae55-103c8981cbeb.png)
I guess PP / GP (...) are for Platine Piece, Gold Piece, etc ...

So in french it should be "Pièce d'or" so "PO" and not "OR" which only means "Gold" ... :)

**Comment by sdenec** [comment]
So this is something the french translators decided to do - nothing I can change. It seems "PO" does make more sense and all other "Pieces" are translated this way while the currency itself has just the material name. Below is a screenshot of the french translation repo. You can rise the issue with them and propose to fix it!
![french_translation](https://user-images.githubusercontent.com/8881200/168154345-29c5e8f6-11d8-4726-9ca4-c0a39edf31ab.png)

**Comment by Kariaudhanaur** [comment]
Ahhh this is the thing I didn't found haha :) 
Sorry about the inconvenience... I thought it was on "your sheet", I didn't think about the whole translated module... Sorry.
