### ISSUE TITLE
Reaction Damaged/Manual show as undefined in favorites

### ISSUE THREAD

**Issue by hitokiri1337** [sdenec/tidy5e-sheet#527]
When you set Reaction Damaged or Reaction Manual as the activation cost on an item, and then favorite the item, it will show as undefined on the attributes page.

![image](https://user-images.githubusercontent.com/38703108/168458132-1f9e1f4b-2b7e-4cee-ab3c-49349e844596.png)

**Comment by sdenec** [comment]
How do you set these usages? There is only "Reaction" in the dropdown list.
![default_actions](https://user-images.githubusercontent.com/8881200/168466917-62607286-7a1e-49db-83ba-f3d59cfd6c4e.png)

**Comment by hitokiri1337** [comment]
I think it's part of Midi-QoL

![image](https://user-images.githubusercontent.com/38703108/168934631-834bfbc2-d1df-43fb-aca9-645bfb664851.png)

**Comment by sdenec** [comment]
action types should now be displayed.
