### ISSUE TITLE
[BUG] - Turning off Auto Exhaustion effects does not turn off exhaustion automation after finishing a long rest

### ISSUE THREAD

**Issue by Haxxer** [sdenec/tidy5e-sheet#528]
**Description:**
When finishing a long rest, Tidy 5e still subtracts exhaustion when finishing a long rest, even when turned off.

**Reproduction:**
1. Open a character sheet
2. Set exhaustion to 1
3. Set setting "Auto Exhaustion effects" to "No automatic exhaustion effects"
4. Finish a long rest
5. Exhaustion still gets set to 0

**Expected behavior**
Turning off exhaustion automation through the Tidy 5e setting should disable the automatic subtraction.

**Setup:**
 - Foundry Version: 9.255
 - System Version: DnD5e 1.6.1
 - Tidy 5e Version: 0.5.31
 - Browser & version: Chrome Chrome Version 101.0.4951.67 (Official Build) (64-bit)

**Active modules:**
- Only Tidy 5e sheet

**Comment by sdenec** [comment]
should be working now. Thanks for making me aware.
