### ISSUE TITLE
Unable to Increase Spell Slots Above Default Maximum

### ISSUE THREAD

**Issue by VoltCruelerz** [sdenec/tidy5e-sheet#53]
The user is prohibited from increasing a spell slot above its default maximum spell slots for your level.  For instance, you cannot give yourself a second 8th level spell slot, even if through some means (such as Dynamic Effects), an item grants you a second 8th level slot.

**Comment by sdenec** [comment]
Go to the spellbook, click the pen next to the maximum spell slot and enter a custom value to overwrite the default. Works for me and I didn't temper with these.

**Comment by sdenec** [comment]
Dynamic effects also works.
