### ISSUE TITLE
Feature Request: Add Hit / DC and Damage dice + modifiers columns 

### ISSUE THREAD

**Issue by leborat** [sdenec/tidy5e-sheet#530]
Good afternoon,

This character sheet is excellent and I believe to be the cleanest looking one so far for Foundry. 

One request I think would be very helpful would be to add an actions page or add columns to any items or spells that do damage and display the hit and damage rolls with modifiers. See example below:

https://imgur.com/a/rWKc5Xu

Currently there are other modules that add a feature like this but do not work well when an action contains more than 1 type of damage roll, causing both rolls to be cutoff as they dont fit in the text line. 

https://imgur.com/a/9BTiT8P

If there are other workarounds to this I am all ears. Great feature so far, looking forward to any updates for this module.

**Comment by p4535992** [comment]
This is already done from [Character Actions 5e](https://github.com/ElfFriend-DnD/foundryvtt-dnd5eCharacterActions)
