### ISSUE TITLE
In effects tab, when "Bonus Action" effect is added, there's no way to delete the effect. 

### ISSUE THREAD

**Issue by stevethibault** [sdenec/tidy5e-sheet#531]
Using foundry 9.269, and Tidy5E version 5.32.

A bonus action effect was added by using convenient effects Rage. But the DM didn't have a way delete the effect when using the Tidy5e sheet, but there was a trash icon using the default sheet. Can this be added/fixed so there is a way to delete effects?

**Comment by stevethibault** [comment]
This also seems to happen with the Rage Effect too. There's no delete on the right click on effects in the effects tab.

**Comment by sdenec** [comment]
I'm not familiar with convenient effects. Does the module add a new Effect Category "Bonus Action"? If so most likely the module does not support the sheet structure of the menu. Maybe you can post a screenshot for me to better visualize what's happening? Does this also happen with any other effect?

**Comment by stevethibault** [comment]
Oh sure. So Here is two screen shots, one trying to delete the rage effect, and another trying to delete the bonus action effect. 
![image](https://user-images.githubusercontent.com/2563836/170825199-2b6a53b0-6ff3-4384-a6bf-a8414a53891b.png)

![image](https://user-images.githubusercontent.com/2563836/170825210-c857b81e-dbdb-4b2c-aeda-9f05e9e099f4.png)

**Comment by stevethibault** [comment]
The effect are placed by MidiQOL, but I it uses Convenient Effects animate and interact when the feature like rage is used.

**Comment by sdenec** [comment]
Make sure to toggle the lock to "unlocken" (red unlocked icon) or have the dm enalbe the setting to always be ablet o edit sheets. If the sheet is locked the delete option won't show. My bet is tahts's the issue here :)

**Comment by stevethibault** [comment]
Ah, you are quite right! Thank you so much. :)
