### ISSUE TITLE
[Feature request] Limited uses columm on passive skilss

### ISSUE THREAD

**Issue by lucaspicerni** [sdenec/tidy5e-sheet#537]
Hi! Could you please implement the limited uses column, in traits tab, to show even on passive skills. Thank you!

![image](https://user-images.githubusercontent.com/95550238/176954301-5c363c1d-69c1-4d91-9d0f-7bb4d8b9d823.png)

**Comment by kaelad02** [comment]
Passive abilities don't have an Activation Cost so the Limited Uses fields aren't filled in. If you edit a passive feature, the Details tab doesn't even allow you to edit the Limited Uses fields.

Is there a particular feature that would need that? I'm trying to think of a use case, an example feature, and I cannot think of one.

**Comment by lucaspicerni** [comment]
When you select an activation cost, enter a usage limit, and then remove the activation cost, the usage limits are maintained and the system continues to make use of them correctly, even if the skill is a passive. So even though the tab doesn't allow you to edit informations for passives, they're still there. I personally don't like to use Resources on the character sheet, I prefer to set usage limits on the item itself.

The fighter's 'indomitable' skill, for example, I use this way, which goes very well with other modules like Midi QOL. And the skill is, in fact, a passive, as no action is required to use it, just a condition. And it has its own limit on uses between rests. I could register the skill as activation cost = none, but I prefer to leave it as passive.

Another example is skills with a pool of points, such as Ki, Sorcery Points or Channel Divinity. I chose to register the uses in an individual skill, and configure the other skills to consume them, instead of using a Resource for that. In this case, sometimes, the skill itself doesn't have an activation cost, it just represents the pool itself, but I'd like to be able to see that pool.

In addition, there are other abilities, both PCs and NPCs, that have limited uses, but do not cost any action to activate, such as: elemental affinity (Sorcerer 6), action surge (Fighter 2), and, of course, homebrew (which is also my case).

I would be very happy if the field was visible when it was filled! Thanks!

**Comment by M0nk3yy** [comment]
Although something like Action Surge doesn't cost an Action to use, it's still an "Active" ability as you have to elect to use it. For such abilities you can change the activation cost to "Special" or set it's value to 0 etc.

**Comment by LukasPrism** [comment]
In my opinion passive skills are by definition something that is always applied, not something that needs to be activated (eg. fighting styles)

**Comment by p4535992** [comment]
This ticket can be closed if something like this were to be integrated it would have to be integrated into the dnd5e system and not here .
