### ISSUE TITLE
Bug - Spellbook components table

### ISSUE THREAD

**Issue by juanxolina** [sdenec/tidy5e-sheet#538]
not sure if this is just me or is a general bug. In the spellbook section, the components column is empty, it doesn't show any component of any spell.
Strangely, if I put a spell as favorite, in the attributes section it does show the components in the proper column. So the spell is correctly configured but that column in the spellbook is not properly working.
Is it just my game? Is there a solution?
thank you in advance
______________________________________________________________________________________________________________________________________
Update: it was a bug in my part. Some weird interaction because a didn't had my "5e system" updated. This made everything work perfectly except that column, but it's already fixed and working. 
The bug surprised me so much I informed this community before trying the most basic thing to fix it xD. welp, who cares now, thanks for showing me my error.

**Comment by kaelad02** [comment]
I cannot reproduce this. I see the components column filled out.

![image](https://user-images.githubusercontent.com/19502084/179181446-3cedecca-37ea-4188-96d1-931247d4f220.png)

I'm using:

- Foundry 9.269
- dnd5e 1.6.1
- Tidy5e Sheet 0.5.32
