### ISSUE TITLE
Feature request: Filter favorites for NPC sheets

### ISSUE THREAD

**Issue by Fallayn** [sdenec/tidy5e-sheet#539]
I would love if the 'Favorite' feature would work for NPC sheets, i.e. simply having a toggle button to filter and only show items, features and spells that are favorited.

This would make running more complicated NPCs (especially spellcasters) way easier. It would allow me to just favorite the 2-3 things they'll likely use in combat, while still having full access for everything else for RP/outside combat/special circumstances.

**Comment by p4535992** [comment]
This feature is already carried out by [Character Actions 5e](https://github.com/ElfFriend-DnD/foundryvtt-dnd5eCharacterActions)
