### ISSUE TITLE
Error when updating sheet settings, old entities use

### ISSUE THREAD

**Issue by kaelad02** [sdenec/tidy5e-sheet#541]
I clicked on the Sheet Settings button in the module settings, then make a change (I changed Auto Exhaustion effects) and save. In the console there's an error:

```
foundry.js:3856 TypeError: Cannot read properties of undefined (reading 'filter')
    at Tidy5eUserSettings.redrawOpenSheets (settings.js:164)
    at Tidy5eUserSettings._updateObject (settings.js:183)
    at Tidy5eUserSettings._onSubmit (foundry.js:3853)
```

It's a leftover use of `entities` that's causing this. I'll file a PR for it, just a one-liner.

**Comment by kaelad02** [comment]
pr is #542

**Comment by sdenec** [comment]
thanks! PR is merged an will release asap
