### ISSUE TITLE
Character Sheet Visual Bug: Spell Attack Mod does not update properly

### ISSUE THREAD

**Issue by SlimDante** [sdenec/tidy5e-sheet#549]
![image](https://user-images.githubusercontent.com/25988077/183268131-58e94547-fc5d-48e8-b229-693a3e9ba197.png)

After some testing it would seem the Attack mod parses only the first bonus from data.bonuses.rsak.attack and ignores the rest of the bonuses that might be added when displaying on the bottom corner of the character sheet. They do however roll correctly in the game. The expected mod in this silly test was +25

**Comment by SlimDante** [comment]
it is not the first 2 characters, but the first bonus in the list.

**Comment by sdenec** [comment]
Try it know and see if I fixed it in the recent update (v10 only).

**Comment by MaxPat931** [comment]
The Attack Mod calculation seems to break if there is a roll formula in the ranged spell attack bonus (either with an AE or added in the Special Traits) such as with Bless

![image](https://user-images.githubusercontent.com/86370342/188342435-d61b157b-53ef-4dad-aec3-c069ff8c19fd.png)

**Comment by sdenec** [comment]
Should be fixed in the next update.

**Comment by sdenec** [comment]
Update is released. Please try it now :)

**Comment by MaxPat931** [comment]
The Attack mod does display now, and no errors are thrown, but humorously the sheet updates each time, "rolling" the d4 for the calculation.

https://user-images.githubusercontent.com/86370342/188745115-21336725-1ff6-44cf-98c7-f3c69474970f.mp4

**Comment by sdenec** [comment]
Yep, that's how it is. How else could it be. There is a random element in the bonus so each time the sheet is opened it is evaluated.  Because of that I put the label explaining where the value is coming from.
