### ISSUE TITLE
Download of the module is impossible

### ISSUE THREAD

**Issue by lefoudre** [sdenec/tidy5e-sheet#550]
Hello,
I tried to download this module on foundry vtt V10 testing 4 - Build 278 and I got an error with the message :

`[tidy5e-sheet] Metadata validation failed for module "tidy5e-sheet": The file "../fonts/modesto-condensed/modesto-condensed.css" included by module tidy5e-sheet does not exist`

**Comment by sdenec** [comment]
That's interesting. I never realized that there was a reference to this file still in the module. In any case there isn't a public release of the module for v10, yet. You can go into the 0.6.0 branch and install the module manually, though. The error was fixed there.

**Comment by lefoudre** [comment]
Thanks for your answer,
I tried to download manualy (on v10 still) and there is an error 
`Installation failed: Cannot read property 'id' of null`
V10 being not released, there is chances you don't care for now, but I thought it would be interesting to tell you anyways.

**Comment by benbarbour** [comment]
Happening on v10 right now.
