### ISSUE TITLE
TImeline for v10 release?

### ISSUE THREAD

**Issue by ctbritt** [sdenec/tidy5e-sheet#557]
Is there a timeline on when the v10 release will be available?

**Comment by sdenec** [comment]
soon™. One more issue to fix and I can push a release. Hopefully today.

**Comment by WThunderspirit** [comment]
looks like the main thing I'm seeing (saw this with libWrapper also) is changing author to authors.

the other thing I saw was flat-core compatibility being depricated in lieu of the compatibility object.

**Comment by sdenec** [comment]
v10 update released :)
