### ISSUE TITLE
Traits overlap Survival skill on Firefox

### ISSUE THREAD

**Issue by DivertedCircle** [sdenec/tidy5e-sheet#56]
The traits section overlaps the Survival skill when viewed via Firefox. Running Tidy5e 0.2.8. Seems to occur regardless of whether the Skill Customization for D&D 5e module is active or not. Occurs regardless of whether the traits toggle is on or not as well.
![image](https://user-images.githubusercontent.com/26470570/86063095-53c2fd00-ba27-11ea-864e-d6961625bd0a.png)
![image](https://user-images.githubusercontent.com/26470570/86063250-b7e5c100-ba27-11ea-9538-573817607581.png)

**Comment by sdenec** [comment]
As discussed via discord: Conflict with another module
