### ISSUE TITLE
Garcon, there's a "debugger" line in my code

### ISSUE THREAD

**Issue by wickermoon** [sdenec/tidy5e-sheet#561]
![image](https://user-images.githubusercontent.com/15907070/188217232-af4a8e3f-bca0-448b-b179-0c0b87f41417.png)

I'm pretty sure that doesn't belong here. :D

edit: It triggers when I close the character sheet AND I have to have the console (F12) open.

**Comment by sdenec** [comment]
ehm, what file? doesn't look familiar to be honest.

**Comment by wickermoon** [comment]
I just noticed, it only happens with tidy5e, but it is actually link-item-resource-5e that's f'ing up. So sorry, didn't look at the filepath!
