### ISSUE TITLE
v10 Version of Tidy5e-Sheet can be installed on v9 but breaks there

### ISSUE THREAD

**Issue by tagnullde** [sdenec/tidy5e-sheet#562]
Hi,

after updating modules tidy5e was also updated on my v9 install. However, this v10 version isn't working on v9 at all.
Maybe restrict this module to only v10 installs.

Is there also a way to downgrade again once I am ready to move towards v10?

Regards
x41

**Comment by sdenec** [comment]
the version should be restricted to v10. at least that's what it sais in the manifest and the foundry repo. strange. which version number do you got? 0.6.1?

**Comment by sdenec** [comment]
you should be able to download the latest v9 from the git repo. v0.5.33
https://github.com/sdenec/tidy5e-sheet/releases/tag/0.5.33

**Comment by tagnullde** [comment]
Yes. I've got. 0.6.1 on foundry v9.

![image](https://user-images.githubusercontent.com/44159008/188260191-2ef4a052-4eb5-4b5d-ae85-a2ba46bf5743.png)
![image](https://user-images.githubusercontent.com/44159008/188260202-26bf5ea2-ea35-41e0-a0ff-6426606c72b6.png)

How can I install it via github? Using the Manifest Json to install it? Or do I need to grab the code and drop it into my modules folder manually?

Regards
x41

**Comment by sdenec** [comment]
There is a new release. Please try to uninstall and reinstall. You should™ get 0.5.33 (v9) - the most recent would be 0.6.2 (v10). Be so kind and report back if it worked (aka. close this issue) :)

**Comment by tagnullde** [comment]
Uninstalling worked.
Re-Installing work - ie. got version 0.5.33 now.
Tidy5e overall is now loading as expected again.

Thank you and have a nice weekend. :)

Case closed.
