### ISSUE TITLE
Tidy5e throws several error-warnings, because it still uses the old .data paths

### ISSUE THREAD

**Issue by wickermoon** [sdenec/tidy5e-sheet#563]
tidy still uses x.data.xyz in a lot of places. I fixed that, so now it's fully v10 compatible. :)

**Comment by sdenec** [comment]
oh man, you are AWESOME! and did you just fix the show token art issue along the way? I always had the issue that when the token art differs from the master actor it would not show the correct one ...

**Comment by wickermoon** [comment]
I...maybe? I simply replaced all the data stuff. I noticed that one of these was accessing a value that didn't exist, so I guess? You're welcome. :)
