### ISSUE TITLE
Module does not load with Foundry v9.280 and dnd5e 1.6.2

### ISSUE THREAD

**Issue by adotor** [sdenec/tidy5e-sheet#567]
Foundry: 9.280
DnD5e: 1.6.2
Tidy5e: 0.6.2

The module does not load.

During initialization the module produces several errors, all related to the extended classes in `xxx-sheet.js` files, e.g.
```
tidy5e-sheet.js:16 Uncaught ReferenceError: dnd5e is not defined
[Detected 1 package: tidy5e-sheet]
    at tidy5e-sheet.js:16:34
(anonymous) @ tidy5e-sheet.js:16
15:44:44.124 
```

**Hint**
In this case the extended class `dnd5e.applications.actor.ActorSheet5eNPC` is undefined. As the changes to v10 included the switch from `ActorSheet5eNPC` to the qualified name, this might be the issues.

**Comment by sdenec** [comment]
tidy 0.6.2 is not v9 compatible and should not be available to install with v9. The latest version for v9 would be 0.5.33. Please try to uninstall and reinstall the sheet and check if you get the correct version number. Maybe you installed 0.6.1 which was missing the v9 incompatibility and somehow the 0.6.2 update was still available then.

**Comment by adotor** [comment]
I switched back to 0.5.33 manually (via manifest Link).

I didn‘t do that for 0.6.2 - it got installed via „Update All Modules“.

**Comment by kalak** [comment]
it upgraded for me onto the v10 version despite me being on v9. I had to manually replace the files. Just a friendly heads up, however you think you're preventing v9 installs, it isn't doing it.

**Comment by Here2makecomments** [comment]
> tidy 0.6.2 is not v9 compatible and should not be available to install with v9. The latest version for v9 would be 0.5.33. Please try to uninstall and reinstall the sheet and check if you get the correct version number. Maybe you installed 0.6.1 which was missing the v9 incompatibility and somehow the 0.6.2 update was still available then.

0.6.2 is not preventing V9 users from updating and breaking the module fyi.

**Comment by sdenec** [comment]
0.6.3 now prevents update from 0.5.33 - for real this time. So please do a reinstall to 0.5.33 (the only available version in v9). If you try to update it should say there is a new version but only vor v10.
