### ISSUE TITLE
Version 0.5.33 for Foundry v9

### ISSUE THREAD

**Issue by Kharmans** [sdenec/tidy5e-sheet#568]
This version for Foundry v9 show the bugs bellow.

![image](https://user-images.githubusercontent.com/112586547/188275661-485a3df1-a439-4715-9d54-bd9859a59924.png)

**Comment by sdenec** [comment]
have you checked with the default sheet? Pretty sure this is not tidy5e related. This are the translation strings in the item sheet. I did not touch the item sheet apart from a little visual styling. Maybe the strings are missing from you specific language?

**Comment by Kharmans** [comment]
You are right. This happen even with the normal sheet.
