### ISSUE TITLE
Dark theme input fields

### ISSUE THREAD

**Issue by 9ryex5** [sdenec/tidy5e-sheet#570]
Numeric input fields have dark text in dark theme, making it hard to read.
![image](https://user-images.githubusercontent.com/43207603/188293644-87dfe5ae-8053-453e-8327-854b36f92784.png)
![image](https://user-images.githubusercontent.com/43207603/188293647-da240454-f943-4c55-917c-3f4b87068d44.png)

**Comment by sdenec** [comment]
All right, got it fixed!
