### ISSUE TITLE
No longer able to drag-drop to link to other Items/Journal Entries/Actors

### ISSUE THREAD

**Issue by LukeUpThere** [sdenec/tidy5e-sheet#572]
When dragging and dropping into the 'Biography' or 'Journal' sections of the actor sheets, the saved entries look like this, unable to be clicked.
![image](https://user-images.githubusercontent.com/19293025/188330590-f25ec13d-8623-4e72-8b43-ce28450acf63.png)

The same action on the default 5e sheet saves as a link to the item/journal entry/actor
![image](https://user-images.githubusercontent.com/19293025/188330760-3758e313-d9a9-44cc-a97e-67997ea9b42a.png)

**Comment by sdenec** [comment]
Links should display correctly again (for the background field). Though I noticed you can't drop item links as they will be added to the inventory. That is for the default sheet and tidy5e - unless I miss some key you have to hold or something. Journal entries seem to work though. Please be so kind and confirm (and subsequently close the issue) :)

**Comment by LukeUpThere** [comment]
That seems to have fixed it. Thank you!
