### ISSUE TITLE
Version 0.6.4 Foundry v9

### ISSUE THREAD

**Issue by webmaster94** [sdenec/tidy5e-sheet#573]
It appears that Foundry v9 is allowing the downloading of the v10 version of Tidy5eSheet. This causes the module to no longer work. I had to revert back to 0.5.32 by manually downloading the files from Github.

**Comment by sdenec** [comment]
So, the last few updates where to battle the v9/v10 issue. Since 0.6.3 v9 ignores version numbers above 0.5.33 (the last one for v9). If you uninstall the module and install it through the module manager you should only get 0.5.33.
![v9_tidy5e](https://user-images.githubusercontent.com/8881200/188332013-7732879d-bd6c-4388-b67e-6b3ba190abdf.png)

If you then try to update you'll get notified that there is a newer version but only for v10.
![v9upd](https://user-images.githubusercontent.com/8881200/188332023-e7ed7794-b6ec-4a6f-a569-1c6a9ef6d2c5.png)

**Comment by YourDNDPleasesMe** [comment]
I've followed your steps and unfortunately I can't get Tidy5E Sheets to show up as an option any more. 
My 9.280 FVTT had updated to 0.6.2 Tidy5E, and I discovered this post. 
I unstalled Tidy5E, rebooted my server, reinstalled via the package manager, which installed Tidy5E Sheet v0.5.33. 
I enabled the module, but I get no options to use the module in any character sheet.

**Comment by sdenec** [comment]
Well that is strange. I can't say I can reproduce this. Any error messages in the console? 0.5.33 was the last working version for v9 so I'm pretty sure it's working fine (and is for my test environment) ...

**Comment by sdenec** [comment]
Thats strange. I can't reproduce this issue. I've tested it myself on v9 and can chose the sheet just fine.
![tidyv9](https://user-images.githubusercontent.com/8881200/189060588-65fc9e71-b7b1-47c9-b035-ef0d0ed5d670.png)

**Comment by Terrox** [comment]
I have v9 and TidySheet 0.6.2, I guess it's not working and I get this error on load which will help others googling if they get the same error - chrome console at least.

`tidy5e-sheet.js:16 Uncaught ReferenceError: dnd5e is not defined
[Detected 1 package: tidy5e-sheet]
    at tidy5e-sheet.js:16:34
(anonymous) @ tidy5e-sheet.js:16
tidy5e-npc.js:24 Uncaught ReferenceError: dnd5e is not defined
[Detected 1 package: tidy5e-sheet]
    at tidy5e-npc.js:24:40
(anonymous) @ tidy5e-npc.js:24
tidy5e-vehicle.js:7 Uncaught ReferenceError: dnd5e is not defined
[Detected 1 package: tidy5e-sheet]
    at tidy5e-vehicle.js:7:36
(anonymous) @ tidy5e-vehicle.js:7
tidy5e-item.js:1 Uncaught ReferenceError: dnd5e is not defined
[Detected 1 package: tidy5e-sheet]
    at tidy5e-item.js:1:38
`

**Comment by Terrox** [comment]
reverting to 0.5.33 fixed it. But I didn't work out why this was happening for a long time and had no idea it updated to a v10 version. Maybe can do a v9 version 0.6.2.1 with v9 compatibity and give it NO v10 compatibility to catch up all the v9 people who aren't ever going to work this out.
