### ISSUE TITLE
Dark Theme edit description

### ISSUE THREAD

**Issue by 9ryex5** [sdenec/tidy5e-sheet#574]
When editing the description of an item there is white text on light background making it hard to read.
![image](https://user-images.githubusercontent.com/43207603/188460114-f9aefcee-e926-45ee-9a38-e8109b87dc0d.png)

**Comment by MaxPat931** [comment]
Probably related: Content Links are also affected

![image](https://user-images.githubusercontent.com/86370342/188988618-f58d230d-7fb0-45eb-85ac-00a7efb0ba7a.png)

**Comment by sdenec** [comment]
should be fixed

**Comment by MaxPat931** [comment]
Looks like the darker background is applying to all drop downs, even sheets that arent (or cant be) in dark mode, in the core settings for example:
![image](https://user-images.githubusercontent.com/86370342/189373518-dd2b58a3-4915-435f-a42a-7f2c80c7fb20.png)
This one I dont actually mind

Editing an item not in tidy5e sheet the backgrounds are very dark, especially when highlighted:
![image](https://user-images.githubusercontent.com/86370342/189373921-5456b204-a649-4864-a2a4-e421ec0bc0d3.png)
(but of course the fix here is just to use the sheet, which I'm fine with)

**Comment by Nedrapter** [comment]
Can confirm this too. It makes editing journals (which have nothing to do with an actor sheet) particularly difficult, as the editing options are so dark.

**Comment by rdefendi** [comment]
I'm having this problem with journals as well. It's seems to be related to turning on the dark theme.
