### ISSUE TITLE
V10 bug: when updating a part of the char sheet, name duplicates in top bar

### ISSUE THREAD

**Issue by gris-x** [sdenec/tidy5e-sheet#577]
In V10, just update a sheet info (remove an item, a spell slot...)
Name is duplicated on the top bar of the character sheet, while the char sheet remains open.
it resets properly after closing and re-opening it.

**Comment by sdenec** [comment]
do you have any other mods installed? Crafting maybe?

**Comment by p4535992** [comment]
Without more information, the ticket should be closed
