### ISSUE TITLE
Can no longer do math in hp field

### ISSUE THREAD

**Issue by MelvinMcSnatch** [sdenec/tidy5e-sheet#578]
I don't think I'm crazy but I've used Tidy5e as my main sheet for a couple of version now and you used to be able to do math in the HP field. Suddenly it's broken. It still works in the default sheet just not Tidy5e.

So if my character has 23/23 hp, and I type '-5' into the current hp field, it now sets the hp as '-5'.

**Comment by sdenec** [comment]
Therr were some changes to the input field it seems. Neither the old one nor the new ones change the calculation abilties. When I try to do math operations in the default sheet it doesn't work either. And I believe you are right that it once worked! I don't know what changed there. Maybe a core system bug?

**Comment by sdenec** [comment]
Actually math doesn't seem to work in Token Health bars either!

**Comment by sdenec** [comment]
Okay, so it's an dnd5e issue. And it just affects sheets. You can substract but not add.
https://github.com/foundryvtt/dnd5e/issues/1806
I'll close this issue as I pretty much can't change it^^
