### ISSUE TITLE
[Question] CSS Variables

### ISSUE THREAD

**Issue by mouse0270** [sdenec/tidy5e-sheet#579]
Could I ask why you chose to attach the css variables for this module onto `.system-dnd5e` instead of `:root` ?

**Comment by sdenec** [comment]
Hm, I don't know exactly why I chose to put them there. Maybe to ensure they only affect the 5e-system, not Foundry in general or maybe I forgot that I could attach them to :root. I think when I introduced custom properties to the shee foundry itself didn't use them, yet. Honestly It's been so long ago that I can't remember my reasoning. But I don't see any problem with it either. Except that I maybe now should put a "t5e" or something in the properties to discern them from the default foundry ones and prevent overwriting values.

**Comment by mouse0270** [comment]
Its not really that important, I just asked as I am working on a theming library that I am getting ready to release and I noticed Tidy5e used variables so I was going to add support for it. But the variables declared at that level require special coding. So I figured I'd check in with you to see if hey could be moved or if there was a design choice for that.

![image](https://user-images.githubusercontent.com/564874/190294902-f7b0f17a-6b46-404f-b3a1-609df9c8457d.png)

**Comment by sdenec** [comment]
I'll check on my next update if there are any issues with moving them to :root. Should be an easy thing to do. In any case - with that I might adjust the naming to ensure tidy's variables are its own and don't cause issues elsewhere.

**Comment by mouse0270** [comment]
If you want to save time, I'd be happy to do this for you. As I'd love to include support. Honestly, it only seems fair as I am the one asking for the change for my module and it in no way benefits you. 

I can probably have it done later today/tomorrow

**Comment by sdenec** [comment]
Ahh! I just figured out why I didn't put the variables onto :root!

It's because of darkmode. I cant discern between the two color schemes when the variables are in root. If they are on .system-dnd5e I can attach another class (tidy5eDark) to it and simply overwrite the custom color properties. If I would switch to :root this would no longer work.

**Comment by mouse0270** [comment]
This could be solved by including the dark mode css variables in a stylesheet called `darkmode` and appending it to the head of the document when the variable is active and removing it when the variable is false. 

doing it this way, would also mean, the stylesheet wouldn't have to be loaded for those not using darkmode. I understand loading a stylesheet isn't a lot of resources.

**Comment by mouse0270** [comment]
```
document.querySelector('head link[href="modules/tidy5e-sheet/css/tidy5e.css"]').insertAdjacentHTML('afterend', `<link href="modules/tidy5e-sheet/css/tidy5e-dark.css" rel="stylesheet" type="text/css" media="all">`)
```
