### ISSUE TITLE
Feature Request: Make Initiative Label Clickable to Roll

### ISSUE THREAD

**Issue by DivertedCircle** [sdenec/tidy5e-sheet#58]
Adding the ability to click the 'Initiative' label so roll would be a small quality of life change. Most of my players are used to rolling Initiative this way from the Roll20 or Alt5e sheets and miss it on the Tidy5e sheet.

**Comment by sdenec** [comment]
It is actually CUB that does the clickable initiative. But I've changed my sheet so CUB recognized the initiative headline. In short - should be clickable now if you have CUB installed and active.
