### ISSUE TITLE
Favored equipment item can't be unequipped from favorites tab.

### ISSUE THREAD

**Issue by TiloBuechsenschuss** [sdenec/tidy5e-sheet#580]
As per title. An inventory item that's a favorite can be equipped in the favorite tab. But it then can't be unequipped.
Button appears, but clicking it does nothing.
Installed: Tidy5eSheet 0.6.6, DnD 2.0.2, Foundry 10.285

**Comment by roguedevjake** [comment]
Yeah, I wasn't sure if this was intended or not, but it does make things harder to get players to use the equip/unequip system.

**Comment by sdenec** [comment]
should be fixed
