### ISSUE TITLE
V10 Bug: Secret black is not hiding text from players who have "Limited" Permission

### ISSUE THREAD

**Issue by joshua-igor** [sdenec/tidy5e-sheet#581]
When creating a secret block for a character's Biography, all the players who have the "Limited" permission will be able to see everything from the secret block, regardless if it is set to "Reveal" or "Hide". Changing the character's sheet to the dnd5e default one, will make the secret block disappear from the player's view, changing back to using Tidy 5e Sheet, makes the secret block appear again.
This only happens when a player has the Limited permission, the "Observer" permission hides the secret block as expected.

Foundry: v10.285
Tidy5eSheet: 0.6.6

**Comment by krzykell** [comment]
Bug still there on Foundry v10.287

**Comment by alexdiste** [comment]
In addition limited permission do not guarantee the conversion of links.
