### ISSUE TITLE
Spell Components not displaying correctly

### ISSUE THREAD

**Issue by RedRoses88** [sdenec/tidy5e-sheet#584]
![image](https://user-images.githubusercontent.com/114310005/192113517-970af340-e8a1-48ba-963d-369b86f34fdc.png)

The spell components column has a bunch of things in there that make it illegible. This was captured with all other modules disabled.

**Comment by sdenec** [comment]
can't confirm this issue.
![t5e_comps](https://user-images.githubusercontent.com/8881200/192114013-735c6a18-18cf-4a9b-98b3-ec3531b2cf4f.png)
Foundry (10.286), 5e (2.0.3) and Tidy (0.6.6) are up to date?

**Comment by RedRoses88** [comment]
No, this is on v9. I havent updated yet

**Comment by sdenec** [comment]
Okay, but even on v9 everything looks fine ...
![t5-spellbook](https://user-images.githubusercontent.com/8881200/192459518-666540e4-850b-40bc-b77d-da58f8b0e5bf.png)
Foundry 9.280, 5e 1.6.3, Tidy 0.5.33 (last stable for v9) - Have you checked here if you are "up to date"?

**Comment by RedRoses88** [comment]
Problem resolved! For some reason it didn't update from Tidy 0.5.26 to Tidy 0.5.33 because it kept saying that the latest update wasn't compatible with v9. Had to delete module and reinstall, then it automatically did pick 0.5.33. Thanks for your help!

**Comment by sdenec** [comment]
Glad it worked out!
