### ISSUE TITLE
[Feature Request] show/edit to PC sheet as well (traits and proficiency)

### ISSUE THREAD

**Issue by roguedevjake** [sdenec/tidy5e-sheet#586]
The NPC sheets have handy "show edit not proficient" and "show edit empty traits" buttons under the skills and traits sections on the abilities tab. 

Having these be an option for the PC sheet would help tidy things up notably imo, even if it was an optional checkbox option in the settings.

**Comment by sdenec** [comment]
There is already an option to hide empty traits for players. I figured even unproficient skill are used frequently and shouldn't be hidden to not confuse players.
![toggle-traits](https://user-images.githubusercontent.com/8881200/192713411-00016287-bb6c-45de-b8d5-b7fc52ce4d88.png)

**Comment by roguedevjake** [comment]
> There is already an option to hide empty traits for players. I figured even unproficient skill are used frequently and shouldn't be hidden to not confuse players.

Regarding skills, in 5e the default assumption is rolling ability scores if something isn't proficient. 

`Without proficiency in the skill, the individual makes a normal ability check.`

and

`the DM might ask for a Strength (Athletics) check. If the character is proficient in Athletics, the character’s proficiency bonus is added to the Strength check. If the character lacks that proficiency, he or she just makes a Strength check.`

The reason this tends to matter outside of simple tidiness is because if a character gains a bonus to say Dexterity(Stealth) they do not gain a bonus to a Dexterity check to be stealthy if they aren't proficient in a skill RAW. Similar deal with things that say give advantage on strength athletics checks but not strength checks in general. 

So if it is possible to have as a similar checkbox option that would be great :)

Not sure how I missed the empty traits checkbox (I swear I looked, maybe I was thinking personality traits at the time)
