### ISSUE TITLE
[Feature] Allow cantrips to be 'prepared' via right-click

### ISSUE THREAD

**Issue by M0nk3yy** [sdenec/tidy5e-sheet#589]
The "cantrip formulas" optional rule from Tashas Cauldron of Everything allows Wizards to prepare their cantrips after a long rest in the same way that they do with leveled spells. I am currently setting the cantrips as prepared manually by editing the item, as the green highlight is helpful in making sure I know which cantrips I have that day. It would be convenient if this was available in the right-click menu as with other spells - even if the Prepared filter doesn't apply to them.

**Comment by sdenec** [comment]
Solved with a new option to be enabled through the module settings
