### ISSUE TITLE
Links to journals or other acotrs broken for a PC with limited permission

### ISSUE THREAD

**Issue by alexdiste** [sdenec/tidy5e-sheet#590]
V10: If a PC has limited permission for an ACTOR and try to see a biography of that actor that contains links to journals or other actors links are broken.

![image](https://user-images.githubusercontent.com/82694721/193883817-ca647bb1-f818-442f-b10f-7a6802c72630.png)

For master is ok
![image](https://user-images.githubusercontent.com/82694721/193883894-c3447600-5717-48ee-b2ba-5f1619dccac2.png)

**Comment by zero127** [comment]
Can also verify the other smaller info tab pieces don't seem to work, even for a GM permission. Links only work in the Background/Bio section, and nothing in Journal. Not the worst issue, but my players and I did make quite liberal use of this feature to add the various journal links to places.
