### ISSUE TITLE
Hit Points (HP) Subtraction Not Working In Sheet in v10

### ISSUE THREAD

**Issue by LeeMcKusick** [sdenec/tidy5e-sheet#594]
If you enter a relative value (i.e. "-5", "+6", etc) into the Current Hit Points field on the character sheet, it does not perform the arithmetic against the current value. Instead it sets it to that value. So entering "-4" will bring them to -4 HP.

Foundry Version: 10.288
Tidy5e Sheet: 0.6.6

**Repro Steps:**
1. Create a new world with Dnd5e.
2. Enable Tidy5e Sheet.
3. Create an actor.
4. Set their hit points (i.e. 10/10).
5. Using the Default sheet, enter "-4" into the current HP. Should drop to 6.
6. Reset current HP to 10.
7. Change to Tidy 5e sheet.
8. Enter -4 in current HP again. Actor will be set to -4.

**Comment by sdenec** [comment]
It's not a sheet issue but a 5e issue. You can try it in the default sheet should be the same.

**Comment by njharoon** [comment]
In core v10, only additions are broken. But with tidy5e sheet, subtraction is also broken

**Comment by LeeMcKusick** [comment]
Ah, you're right, njharoon. 
I found a discussion on this today on the Foundry Discord. Starts here: https://discord.com/channels/170995199584108546/670336046164213761/1031297686151901184

Positive deltas are a known issue in core, but negative ones should work.

**Comment by LeeMcKusick** [comment]
Did a little more digging. It's because the hp-min input field is type="text" instead of type="number".

**Comment by sdenec** [comment]
should be fixed
