### ISSUE TITLE
[Feature Request] Support for Spell Points

### ISSUE THREAD

**Issue by WhitThur** [sdenec/tidy5e-sheet#597]
Would love to have the ability - either via player settings or via an alternate sheet - to toggle use of the 'spell points' rule from the DMG  instead of spell slots. (http://dnd5e.wikidot.com/spell-points). Right now, we are just tracking them as a resource, but have no way of hiding the traditional slots.

**Comment by JamesMDenton** [comment]
I second this, especially if it could be compatible with this:

https://github.com/misthero/dnd5e-spellpoints
