### ISSUE TITLE
[Feature Request] 'Standard Roll' button in accordions for List View

### ISSUE THREAD

**Issue by WhitThur** [sdenec/tidy5e-sheet#598]
This issue inly impacts those who use modules that automate spells. For automated spell effects, simply clicking the die icon does not initiate use of a spell; you must use the 'Standard Roll' button, which is only found on info cards. Currently, you have to press your hotkey to interact with the card, then navigate to 'Standard Roll'. What would be helpful is an option to add the 'Standard Roll' to the collapsible info cards on the spell list.

Included an image of where it is in the standard sheet:
![image](https://user-images.githubusercontent.com/25377323/197400914-f0c38aed-e220-453a-a89f-2e4147bfb4e6.png)

**Comment by p4535992** [comment]
I cannot see the "Standard Roll" , "Damage and "Info" buttons on my actors can you specify the Foundry and Dnd5e system version are you using?
