### ISSUE TITLE
Vehicle Sheet Crew Bugged

### ISSUE THREAD

**Issue by KonteiKeisei** [sdenec/tidy5e-sheet#599]
When adding Crew/Passengers, the moment you add a new line, it erases all Crew/Passenger information.
Additionally, you cannot delete the new line.

![image](https://user-images.githubusercontent.com/49371326/199330835-ada02932-bfb2-47b1-9f83-a4107c31dc69.png)
![image](https://user-images.githubusercontent.com/49371326/199330877-5119db9b-3732-44f4-b211-1be3ed5f6ea2.png)

**Comment by sdenec** [comment]
should be fixed
