### ISSUE TITLE
Bug on function "+" or "-" in experience points and golds

### ISSUE THREAD

**Issue by arkangel85** [sdenec/tidy5e-sheet#601]
Hello! I report a bug where with tidy5e you cannot use the "add" and/or "subtract" function to increase or decrease experience points and gold

here is a Gif where i show the bug: https://gifyu.com/image/SEirU

**Comment by sdenec** [comment]
What version are you on? For me it's working in neither sheet (original or tidy) - v10.288 /5e 2.0.3/ tidy 0.6.6

Maybe it's a core 5e bug.

**Comment by sdenec** [comment]
In the default sheet I can only substract while tidy can't do that. So there is at least something that's missing from the sheet - core bug or not.

**Comment by arkangel85** [comment]
same of yours, v10.288 /5e 2.0.3/ tidy 0.6.6

but with the original sheet all works, no other module active

**Comment by cs96and** [comment]
I'm seeing this problem with hitpoints as well.  E.g. entering -5 in the HP box will set your HP to -5, instead of subtracting 5.  I don't see this problem with the core sheet.

**Comment by arkangel85** [comment]
The problem has been partially solved, the experience points work correctly while in gold only the "minus" function works

**Comment by sdenec** [comment]
this is a core issue. But you can activate "Lazy money" in the modules setting (module tab) and get all the benefits of this nifty feature, including addition :)
