### ISSUE TITLE
Can't unequip favored weapons/armor from attributes tab

### ISSUE THREAD

**Issue by blueacousticmusic** [sdenec/tidy5e-sheet#606]
**FoundryVTT v10, Build 291
Tidy5e Sheet 0.6.6**

There seems to be an issue with unequipping favored items from the attributes tab without giving an error message/warning in the F12 console. When you unequip from the inventory tab it's working fine. Also equipping favored items from the attributes tab is still working.

I've activated only the Tidy5e Sheet module and tried it on the previous Foundry build as well as with different browsers but it just stopped working for me and my players. I recently updated from v9 to v10 where this was not an issue. 
Would be nice to use this very handy feature in v10 as well since scrolling through the inventory is sometimes quite exhausting.

**Comment by sdenec** [comment]
should be fixed in the new version
