### ISSUE TITLE
Sheet seems to change max HPs after closing a sheet.

### ISSUE THREAD

**Issue by ghoulapool** [sdenec/tidy5e-sheet#609]
I have tested this on a world with only this module enabled.  If I take an actor and have attributes.hp showing on the token as a bar under the actor, and then open the sheet and simply close it, it resets the bar to look like the actor is almost dead.  Best I can tell, it isn't modifying the HPs or max HPs of the character.  As soon as I switch back to a default sheet and close it, the token's attributes.hp displays correctly.  Could this module be modifying the max HPs upon exit or something?

Notice here, I'm using a default one and notice the HPs.
![image](https://user-images.githubusercontent.com/36716334/209487748-b3078d30-7851-4588-9349-49b1e8b14049.png)

Here I am using tidySheets, notice the actor looks almost dead (no change other than changing the sheet)
![image](https://user-images.githubusercontent.com/36716334/209487769-5e8380b2-cc38-48d2-b314-e1584ee1859a.png)

![image](https://user-images.githubusercontent.com/36716334/209487710-744d6596-f9cb-40dc-a16e-06eeb4092806.png)

**Comment by krbz999** [comment]
The numeric fields (like hp and currency) are currently turned into strings. They need both of these properties in the templates:
```html
type="number" data-dtype="Number"
```
