### ISSUE TITLE
Currency is set to 0 when exiting sheet

### ISSUE THREAD

**Issue by DarkkingDraco** [sdenec/tidy5e-sheet#610]
With version 0.7.2, anytime the player sheet is closed all currency are set to 0. 

Using Find the Culprit, it seems to be an interaction between TidySheets and Link Item and Resources, which hasn't been updated since September.

I would like to keep using both, but I understand the issue might be Link Item and not TidySheet; however, is there a way to fix this on TidySheets end?

**Comment by Janner3D** [comment]
I'm having the exact same issue.
