### ISSUE TITLE
About the closed issue #601

### ISSUE THREAD

**Issue by arkangel85** [sdenec/tidy5e-sheet#616]
> Hello! I report a bug where with tidy5e you cannot use the "add" and/or "subtract" function to increase or decrease experience points and gold; here is a Gif where i show the bug: https://gifyu.com/image/SEirU

The problem has been partially solved, the experience points work correctly while in gold only the "minus" function works

**Comment by p4535992** [comment]
Just tested with '0.7.4' and seem to work with "=10", "+10"  and "-10"
