### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by MikeGPSand** [sdenec/tidy5e-sheet#621]
"NEW FEATURE : Add more colors for spellbook prepared, pact magic, innate, ecc. (really need this for not going crazy to check every spell)"

If we could choose the colors for the various preparations that would be greatly appreciated. Two of the colors are headache inducing for me. I like the idea just not the colors. Thanks for the great module otherwise though.

**Comment by p4535992** [comment]
Should be fixed on 0.8.14
