### ISSUE TITLE
Skill Names No Longer Showing on Attributes Tab

### ISSUE THREAD

**Issue by AlanDNelson** [sdenec/tidy5e-sheet#624]
Skill names no longer show up on the Tidy Player Character Sheet.

I think this was caused by the update to the D&D 5e system to 2.1.0.

Love your sheet!  I hope this helps!

![image](https://user-images.githubusercontent.com/36895037/211686951-5d282837-c784-4497-b024-e023a3a67bb6.png)

Foundry Virtual Tabletop: Version 10, 10.291
Game System: dnd5e, 2.1.0
Active Modules: 56
Performance Mode: 3

OS: Unknown
Client: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
GPU: ANGLE (NVIDIA, NVIDIA GeForce RTX 3080 Direct3D11 vs_5_0 ps_5_0, D3D11)
Max Texture Size: 16384

Scene: 2000 x 1124 | Grid Size: 100 | Padding Percentage: 0
Walls: 0 | Ambient Lights: 0 | Ambient Sounds: 0 | Tiles: 1 | Tokens: 6

Actors: 69 | Items: 46 | Journal: 32 | Rollable Tables: 0 |
Playlists: 4 | Compendium Packs: 58 | Chat Messages: 0

**Comment by mhoerter** [comment]
Having this issue too. Seeing this error when opening player sheets:
`tidy5e-favorites.js:187 Uncaught (in promise) TypeError: Cannot set property hasDamage of #<Item5e> which has only a getter
[Detected 1 package: tidy5e-sheet]
    at addFavorites (tidy5e-favorites.js:187:24)
    at Object.fn (tidy5e-sheet.js:815:3)
    at #call (foundry.js:724:20)
    at Hooks.callAll (foundry.js:681:17)
    at Tidy5eSheet._render (foundry.js:5153:13)
    at async Tidy5eSheet._render (foundry.js:5822:5)`

**Comment by mhoerter** [comment]
Possibly related, I'm unable to open NPC sheets that are assigned Tidy5eSheet as well, getting this error:
```

> foundry.js:747 Error: One of original or other are not Objects!
> [No packages detected]
>     at mergeObject (commons.js:2359:13)
>     at _mergeUpdate (commons.js:2423:14)
>     at mergeObject (commons.js:2380:41)
>     at _mergeUpdate (commons.js:2423:14)
>     at mergeObject (commons.js:2380:41)
>     at _mergeUpdate (commons.js:2423:14)
>     at Object.mergeObject (commons.js:2380:41)
>     at Tidy5eNPC._render (foundry.js:5104:19)
>     at Tidy5eNPC._render (foundry.js:5822:17)
>     at Tidy5eNPC.render (foundry.js:5067:10)
>     at Tidy5eNPC.render (foundry.js:6394:18)
>     at Token5e._onClickLeft2 (foundry.js:47378:16)
>     at MouseInteractionManager.callback (foundry.js:27813:45)
>     at MouseInteractionManager._handleClickLeft2 (foundry.js:28027:17)
>     at MouseInteractionManager._handleMouseDown (foundry.js:27989:66)
>     at a.emit (index.js:181:35)
>     at r.dispatchEvent (interaction.min.mjs:8:12235)
>     at r.processPointerDown (interaction.min.mjs:8:14214)
>     at t.recursiveFindHit (interaction.min.mjs:8:4098)
>     at t.recursiveFindHit (interaction.min.mjs:8:3882)
>     at t.recursiveFindHit (interaction.min.mjs:8:3882)
>     at t.recursiveFindHit (interaction.min.mjs:8:3882)
>     at t.recursiveFindHit (interaction.min.mjs:8:3882)
>     at t.recursiveFindHit (interaction.min.mjs:8:3882)
>     at t.findHit (interaction.min.mjs:8:4157)
>     at r.processInteractive (interaction.min.mjs:8:12841)
>     at r.onPointerDown (interaction.min.mjs:8:13543)

```

**Comment by AlanDNelson** [comment]
Just checked again with D&D 5e 2.1.1... problem still persists.

I caught the following error that seems like it could be related:

![image](https://user-images.githubusercontent.com/36895037/211689253-1c5f0b18-fc2a-413e-ba50-7440034db1ff.png)

**Comment by AlanDNelson** [comment]
I also get the problem with all modules disabled (except for TidySheet... of course).

**Comment by btbias** [comment]
I have the same issues listed above, including being unable to open an NPC actor that's been set to Tidy5e. However, this is ONLY for actors created prior to 2.1 (including ones on compendiums). Creating a new NPC actor does not have these issues.

![image](https://user-images.githubusercontent.com/114558351/211690882-a2c8e539-b6dd-4d25-964f-c77fcf70598c.png)

**Comment by AlanDNelson** [comment]
I also see the same problem with opening NPCs as btbias....

**Comment by ZoltanTheDM** [comment]
It seems both `label` and `icon` has been removed from the skills and saving throws.
I have not found a trivial solution. I have made a small edit in my local copy of my dnd5e system to at least get the skill names to appear. But this does not fix the issue of icons.

line 9205 of `Data/systems/dnd5e/dnd5e.mjs`
`skills[key].label = skill.label;`

**Comment by szefo09** [comment]
> It seems both `label` and `icon` has been removed from the skills and saving throws. I have not found a trivial solution. I have made a small edit in my local copy of my dnd5e system to at least get the skill names to appear. But this does not fix the issue of icons.
> 
> line 9205 of `Data/systems/dnd5e/dnd5e.mjs` `skills[key].label = skill.label;`
> 
> Edit: also noticed the label issue on spellcasting ability

You  can fix the Skill Names by changing those 2 lines:
https://github.com/sdenec/tidy5e-sheet/blob/6a214f4f48e72fc1029b5cd86ff715fd92e29018/src/templates/actors/tidy5e-sheet.html#L287-L288
to this: 
```            
{{#each config.skills as |obj s|}}
{{#with (lookup ../skills s) as |skill|}}
```

**Comment by szefo09** [comment]
> Edit: also noticed the label issue on spellcasting ability
Change:
https://github.com/sdenec/tidy5e-sheet/blob/6a214f4f48e72fc1029b5cd86ff715fd92e29018/src/templates/actors/parts/tidy5e-spellbook-footer.html#L12
to:
```
 {{#each abilities as |abl a|}} 
```

**Comment by Kharmans** [comment]
> {{#each config.skills as |obj s|}}
> {{#with (lookup ../skills s) as |skill|}}
> {{#each abilities as |abl a|}}

This all works, but only for the Player Sheet. You can help us with the same things for the NPC and Vehicle Sheets?

**Comment by Kharmans** [comment]
Oh, and this are still unable to use. Can you help with this too?

![image](https://user-images.githubusercontent.com/112586547/212073703-34cac080-1cf0-4d90-a584-731b419cbc38.png)

**Comment by szefo09** [comment]
> > {{#each config.skills as |obj s|}}
> > {{#with (lookup ../skills s) as |skill|}}
> > {{#each abilities as |abl a|}}
> 
> This all works, but only for the Player Sheet. You can help us with the same things for the NPC and Vehicle Sheets?

https://github.com/sdenec/tidy5e-sheet/blob/6a214f4f48e72fc1029b5cd86ff715fd92e29018/src/templates/actors/tidy5e-npc.html#L217
to
```
            {{#each skills as |skill s|}}
```

**Comment by Kharmans** [comment]
> {{#each skills as |skill s|}}

Works like charm!

**Comment by szefo09** [comment]
> Oh, and this are still unable to use. Can you help with this too?
> 
> ![image](https://user-images.githubusercontent.com/112586547/212073703-34cac080-1cf0-4d90-a584-731b419cbc38.png)

I redownloaded clean version of latest Tidy5e and can't reproduce. Possibly other module or some translation?
![image](https://user-images.githubusercontent.com/37833135/212074549-670caf2f-9bec-4ebb-8d4a-73e66743e06c.png)

also, Initiative Mod `NaN` fix:
https://github.com/sdenec/tidy5e-sheet/blob/6a214f4f48e72fc1029b5cd86ff715fd92e29018/src/templates/actors/tidy5e-npc.html#L162
https://github.com/sdenec/tidy5e-sheet/blob/6a214f4f48e72fc1029b5cd86ff715fd92e29018/src/templates/actors/tidy5e-sheet.html#L230

Change all  `system.attributes.init.value` to `system.attributes.init.bonus`

**Comment by Kharmans** [comment]
> Change all system.attributes.init.value to system.attributes.init.bonus

Works!

> I redownloaded clean version of latest Tidy5e and can't reproduce. Possibly other module or some translation?
> ![image](https://user-images.githubusercontent.com/37833135/212074549-670caf2f-9bec-4ebb-8d4a-73e66743e06c.png)

You just reproduce! Look in your print, there's no option to mark the saves.

**Comment by Kharmans** [comment]
You, sir, are a life-saver!
Works perfect, thanks!

**Comment by WThunderspirit** [comment]
I'm on forge - don't even know how to get into things to do fixes.  Any idea when an update will hit the system?

**Comment by Kharmans** [comment]
There's another issue I notice, @szefo09.
It's not possible to open the levels on classes. Can you help us?

![image](https://user-images.githubusercontent.com/112586547/212449107-ad152671-7b91-4f8c-a39e-461880ccd8ea.png)

**Comment by szefo09** [comment]
> There's another issue I notice, @szefo09. It's not possible to open the levels on classes. Can you help us?

Fix to this issue would require comparing https://github.com/sdenec/tidy5e-sheet/blob/master/src/templates/actors/parts/tidy5e-features.html
 with 
 https://github.com/foundryvtt/dnd5e/blob/master/templates/actors/parts/actor-features.hbs 
 for recent changes. 
Mostly around this line: https://github.com/foundryvtt/dnd5e/blob/b28a8680290ca47675fa86c28f1ec28843a2ac6d/templates/actors/parts/actor-features.hbs#L38
I haven't dug enough to provide working code.

**Comment by Kharmans** [comment]
I understand! You already help a lot!
Thanks!

**Comment by QuestionQuest117** [comment]
> > There's another issue I notice, @szefo09. It's not possible to open the levels on classes. Can you help us?
> 
> Fix to this issue would require comparing https://github.com/sdenec/tidy5e-sheet/blob/master/src/templates/actors/parts/tidy5e-features.html with https://github.com/foundryvtt/dnd5e/blob/master/templates/actors/parts/actor-features.hbs for recent changes. Mostly around this line: https://github.com/foundryvtt/dnd5e/blob/b28a8680290ca47675fa86c28f1ec28843a2ac6d/templates/actors/parts/actor-features.hbs#L38 I haven't dug enough to provide working code.

So I checked both files and they are identical. Problem seems to be elsewhere

**Comment by Regateiro** [comment]
It also seems like the Journal does not display or save any data entered there. A closer look seems to suggest that actor.system.details.notes is gone as well.

**Comment by sdenec** [comment]
ATTENTION! Tidy5e is now updated for the latest DND 5e release (2.1.x). When you have journal data in your sheet you WILL lose it when you transition from 2.0.3 to 2.1.x - In order to save it you have to execute the Macro in the readme https://github.com/sdenec/tidy5e-sheet#readme BEFORE you make the upgrade. If you do have a backup from before the switch you can recover your data this way. Sorry for any inconveniences.
