### ISSUE TITLE
Creature Sheet don't open in DnD5e 2.1.1

### ISSUE THREAD

**Issue by Kharmans** [sdenec/tidy5e-sheet#625]
After the update of DnD5e to 2.1.1, the creature sheet of old creatures (after the update) don't open, only new creatures. The error bellow is showed when I try to open the sheets.

![image](https://user-images.githubusercontent.com/112586547/211700901-02a65e96-89cd-4bc4-9009-e96fc45a5b69.png)

**Comment by ShannonMcG** [comment]
I see the same issue. As a temporary bandaid solution I disabled the Tidy5e Sheet module and the NPCs successfully opened using the default sheet.

**Comment by V3rotti** [comment]
Same Issue here. I can open the actors from the sidebar but that seems to partially fail too:
![image](https://user-images.githubusercontent.com/56869989/211779149-cf9780b5-b7c0-4c46-be34-f5cb1b6113ad.png)
In the console there is also an error:
![image](https://user-images.githubusercontent.com/56869989/211779313-d8256810-58f1-4f0e-8ebc-90ce8ddea517.png)

**Comment by Quercuas** [comment]
Same issue here as well!

![image](https://user-images.githubusercontent.com/96662470/211785409-c7565c44-d769-4f1c-9964-293848d1dc10.png)

**Comment by Janner3D** [comment]
Same issue here, too. The only so0lution right now seems to be disabling the module until this is fixed.

**Comment by ZoltanTheDM** [comment]
I was able to fix this issue by deleting the relevant lines:

https://github.com/sdenec/tidy5e-sheet/blob/0.7.6/src/scripts/tidy5e-npc.js#L117-L119

https://github.com/sdenec/tidy5e-sheet/blob/0.7.6/src/scripts/app/tidy5e-favorites.js#L180-L188

**Comment by Kharmans** [comment]
> 

Yeah, it work. Now only the Skills are broken.

![image](https://user-images.githubusercontent.com/112586547/211919572-89abcc36-2ef5-47c6-91e0-65dcd2ac90ae.png)

**Comment by Kharmans** [comment]
I just see that the Attribute Saves are broken too.

![image](https://user-images.githubusercontent.com/112586547/211921418-31715cb1-2648-4ce5-8e64-2f400a0befda.png)

**Comment by ZoltanTheDM** [comment]
That is a separate issue it seems https://github.com/sdenec/tidy5e-sheet/issues/624

**Comment by Sparicou** [comment]
I had the same issue except it wasn't solved until I uninstalled the module.

**Comment by rldorado** [comment]
I'm having the same issue with v2.1.2

**Comment by logoff** [comment]
Probably related with #634.

@Kharmans, @V3rotti, @Quercuas I would recommend posting the entire errors text, instead of image screenshots, to make searches easy and make other end up in the same issue :wink:.

**Comment by ravingdragoon** [comment]
I found that if you disable the module, set one of the monsters "this sheet" manually to use the default, re-enable the module, open the sheet of the monster you set to use the default 5e sheet, then you can change the default sheet back to the default 5e npc sheet instead of the tidy npc sheet.

**Comment by sdenec** [comment]
ATTENTION! Tidy5e is now updated for the latest DND 5e release (2.1.x). When you have journal data in your sheet you WILL lose it when you transition from 2.0.3 to 2.1.x - In order to save it you have to execute the Macro in the readme https://github.com/sdenec/tidy5e-sheet#readme BEFORE you make the upgrade. If you do have a backup from before the switch you can recover your data this way. Sorry for any inconveniences.
