### ISSUE TITLE
Character Data Document Update

### ISSUE THREAD

**Issue by Leondthurrell** [sdenec/tidy5e-sheet#629]
The way that the D&D 5e system interacts with the Actor documents has changes drastically which would be what is causing tidy5e to be broken right now.

>[D&D5e Game System ->⚠️ Breaking Changes](https://github.com/foundryvtt/dnd5e/releases/tag/release-2.1.0#:~:text=%E2%9A%A0%EF%B8%8F,Breaking%20Changes)
**Deprecated Methods & Classes Removed**
`SelectItemsPrompt`
`CONFIG.DND5E.classFeatures`
Non-namespaced `restCompleted` hook (use `dnd5e.restComplete` instead).
`Actor5e#addEmbeddedItems`
`Actor5e#getClassFeatures`
`Actor5e#loadClassFeatures`

### **Collected Related Issues:**
#628 #625 #624

**Comment by b2fram** [comment]
Where did the attribute names go?
![image](https://user-images.githubusercontent.com/122632938/212378540-ece4a23e-5c37-4c4b-87cc-66949892ee2a.png)

**Comment by denisbrandao** [comment]
> Where did the attribute names go? ![image](https://user-images.githubusercontent.com/122632938/212378540-ece4a23e-5c37-4c4b-87cc-66949892ee2a.png)

https://github.com/sdenec/tidy5e-sheet/issues/624#issuecomment-1380296133

**Comment by Leondthurrell** [comment]
#624 has a lot of fixes in it actually. Made this just to collect the issues that are found to provide one place to reference back to.
I love this module so, of the devs don't get to it first, I'll fork see what I can do to get it going again then merge it back in :)

**Comment by aquavitae** [comment]
@Leondthurrell I've made a start already (see #630). I'll give you access to my fork so you can contribute there rather than duplicating effort.

**Comment by logoff** [comment]
Probably related #634

**Comment by sdenec** [comment]
ATTENTION! Tidy5e is now updated for the latest DND 5e release (2.1.x). When you have journal data in your sheet you WILL lose it when you transition from 2.0.3 to 2.1.x - In order to save it you have to execute the Macro in the readme https://github.com/sdenec/tidy5e-sheet#readme BEFORE you make the upgrade. If you do have a backup from before the switch you can recover your data this way. Sorry for any inconveniences.
