### ISSUE TITLE
Actors sheets lost previous jornal entries and proficiencies are invisible. NPC sheets don't even open.

### ISSUE THREAD

**Issue by DanteMaximilion** [sdenec/tidy5e-sheet#637]
After I updated the module my players would not be able to access their previous Journal entries. Their proficiencies names also became invisible and unclickable. The same happens with new actors.
![image](https://user-images.githubusercontent.com/123312245/213923758-a2307e7f-88da-4197-97d9-4c58c3d9b73c.png)

Previous NPC sheets simply don't open. New NPC sheets do, but have the same proficiency problem.
![image](https://user-images.githubusercontent.com/123312245/213923817-4586bf12-7b04-4fe7-ad98-91af51f4039e.png)

I have both disabled all my other mods and installed/uninstalled this one and it still occours.

**Comment by p4535992** [comment]
Sadly without a backup the journal data is now lost, we are working on the next release here the link to the beta:
https://github.com/p4535992/tidy5e-sheet/releases/download/v0.8.3/module.json

there still some issue follow up the progress here: https://github.com/sdenec/tidy5e-sheet/pull/622

**Comment by DanteMaximilion** [comment]
Thanks for the response. The proficiency problem has been solved, but sadly even with backup i was not able to restore de journals.
If you could kindly send me the version before the current stable one for me to test it in the backup i would apreciate it very much, one of my players had some very important things in there.

**Comment by funwithfondue** [comment]
Wanted to chime in here and say that I too am unable to open NPC sheets with this module activated after upgrading from Foundry V9 to V10 and updating to the latest version of the module. Below you can see a screenshot of my console with the error message associated with the issue.

![image](https://user-images.githubusercontent.com/86520580/214005409-f0cca46a-ff84-4aee-9049-6d221caae3d1.png)

**Comment by webmaster94** [comment]
> Thanks for the response. The proficiency problem has been solved, but sadly even with backup i was not able to restore the journals. If you could kindly send me the version before the current stable one for me to test it in the backup i would apreciate it very much, one of my players had some very important things in there.

I can assist you with restoring your data if you have a backup. It isn't too hard if you know what to do.

**Comment by webmaster94** [comment]
> Wanted to chime in here and say that I too am unable to open NPC sheets with this module activated after upgrading from Foundry V9 to V10 and updating to the latest version of the module. Below you can see a screenshot of my console with the error message associated with the issue.
> 
> ![image](https://user-images.githubusercontent.com/86520580/214005409-f0cca46a-ff84-4aee-9049-6d221caae3d1.png)

This isn't a v10 issue. It has to do with the most recent version of D&D 5e System. You will want to downgrade the system to v2.03. If you do that, the module will work properly.

**Comment by p4535992** [comment]
If you still have the backup of 2.0.3 you can run this macro:
```
//Update old tidy5e data
game.actors.updateAll((actor)=>{
    return {
        "flags.tidy5e-sheet":{
            gender:actor.system.details?.gender ?? "",
            age:actor.system.details?.age ?? "",
            height:actor.system.details?.height ?? "",
            weight:actor.system.details?.weight ?? "",
            eyes:actor.system.details?.eyes ?? "",
            skin:actor.system.details?.skin ?? "",
            hair:actor.system.details?.hair ?? "",
	    notes: {
			 "value": actor.system.details?.notes  ?? ""
	    },
            notes1:{
			"name": actor.system.details.notes1name ?? "",
			"value": actor.system.details?.notes1  ?? ""
	    },
	    notes2:{
			"name": actor.system.details.notes2name ?? "",
			"value": actor.system.details?.notes2  ?? ""
	   },
	   notes3:{
			"name": actor.system.details.notes3name  ?? "",
			"value": actor.system.details?.notes3  ?? ""
	    },
            notes4:{
			"name": actor.system.details.notes4name  ?? "",
			"value": actor.system.details?.notes4  ?? ""
	    }
        }
    }
})
```

**Comment by webmaster94** [comment]
> If you still have the backup of 2.0.3 you can run this macro:
> 
> DO A BACKUP BEFORE LAUNCH THIS JUST TO BE SAFE
> 
> ```
> //Update old tidy5e data
> game.actors.updateAll((actor)=>{
>     return {
>         "flags.tidy5e-sheet":{
>             gender:actor.system.details?.gender ?? "",
>             age:actor.system.details?.age ?? "",
>             height:actor.system.details?.height ?? "",
>             weight:actor.system.details?.weight ?? "",
>             eyes:actor.system.details?.eyes ?? "",
>             skin:actor.system.details?.skin ?? "",
>             hair:actor.system.details?.hair ?? "",
> 	    notes: {
> 			 "value": actor.system.details?.notes  ?? ""
> 	    },
>             notes1:{
> 			"name": actor.system.details.notes1name ?? "",
> 			"value": actor.system.details?.notes1  ?? ""
> 	    },
> 	    notes2:{
> 			"name": actor.system.details.notes2name ?? "",
> 			"value": actor.system.details?.notes2  ?? ""
> 	   },
> 	   notes3:{
> 			"name": actor.system.details.notes3name  ?? "",
> 			"value": actor.system.details?.notes3  ?? ""
> 	    },
>             notes4:{
> 			"name": actor.system.details.notes4name  ?? "",
> 			"value": actor.system.details?.notes4  ?? ""
> 	    }
>         }
>     }
> })
> ```

That is very helpful. I just grabbed the data manually from my backup actors.db. I did this before you guys had anything lol. Hopefully that will help @DanteMaximilion.

**Comment by funwithfondue** [comment]
> > Wanted to chime in here and say that I too am unable to open NPC sheets with this module activated after upgrading from Foundry V9 to V10 and updating to the latest version of the module. Below you can see a screenshot of my console with the error message associated with the issue.
> > ![image](https://user-images.githubusercontent.com/86520580/214005409-f0cca46a-ff84-4aee-9049-6d221caae3d1.png)
> 
> This isn't a v10 issue. It has to do with the most recent version of D&D 5e System. You will want to downgrade the system to v2.03. If you do that, the module will work properly.

Ah I see, thank you for clarifying! Do you know if this will be fixed in the next version of the D&D 5e System?

**Comment by p4535992** [comment]
for avoid this kind of problem i have asked some hook on the migration tool https://github.com/foundryvtt/dnd5e/issues/2068 you can upvote the feature

**Comment by p4535992** [comment]
UPDATE OF THE MACRO  (i have made a mistake..)

FOR ANYONE STILL HAVING THE 2.0.3 BACKUP HERE THE "MIGRATION MACRO" FOR 2.1.X: 

DO A BACKUP BEFORE LAUNCH THIS JUST TO BE SAFE

```
//Update old tidy5e data
game.actors.updateAll((actor)=>{
    return {
        "flags.tidy5e-sheet":{
            gender:actor.system.details?.gender ?? "",
            age:actor.system.details?.age ?? "",
            height:actor.system.details?.height ?? "",
            weight:actor.system.details?.weight ?? "",
            eyes:actor.system.details?.eyes ?? "",
            skin:actor.system.details?.skin ?? "",
            hair:actor.system.details?.hair ?? "",
	    notes: {
			 "value": actor.system.details?.notes?.value  ?? ""
	    },
            notes1:{
			"name": actor.system.details?.notes1name ?? "",
			"value": actor.system.details?.notes1  ?? ""
	    },
	    notes2:{
			"name": actor.system.details?.notes2name ?? "",
			"value": actor.system.details?.notes2  ?? ""
	   },
	   notes3:{
			"name": actor.system.details?.notes3name  ?? "",
			"value": actor.system.details?.notes3  ?? ""
	    },
            notes4:{
			"name": actor.system.details?.notes4name  ?? "",
			"value": actor.system.details?.notes4  ?? ""
	    }
        }
    }
})
```

**Comment by logoff** [comment]
Probably related with #622.

**Comment by sdenec** [comment]
ATTENTION! Tidy5e is now updated for the latest DND 5e release (2.1.x). When you have journal data in your sheet you WILL lose it when you transition from 2.0.3 to 2.1.x - In order to save it you have to execute the Macro in the readme https://github.com/sdenec/tidy5e-sheet#readme BEFORE you make the upgrade. If you do have a backup from before the switch you can recover your data this way. Sorry for any inconveniences.
