### ISSUE TITLE
This module is not working properly with the new release of the system 5e

### ISSUE THREAD

**Issue by spitfire1081** [sdenec/tidy5e-sheet#639]
We are having several issues with this module since the upgrade of ths system 5e.
NPC's sheets won't open, player's sheets are a mess.
I tried to reinstall everything from scratch, and still is not working.

**Comment by p4535992** [comment]
We are working on the next release but there still some issue follow up the progress here: https://github.com/sdenec/tidy5e-sheet/pull/622 (you can find a link to the beta too).

BEWARE if you already upgrade from 2.0.3 to 2.1.X sadly without a backup othe journal data is now lost, 
FOR ANYONE STILL HAVING THE 2.0.3 BACKUP HERE THE "MIGRATION MACRO" FOR 2.1.X, YOU MUST LAUNCH THIS ON YOUR WORLDS BEFORE UPGRADE THE WORLD.  

DO A BACKUP BEFORE LAUNCH THIS JUST TO BE SAFE

```
//Update old tidy5e data
game.actors.updateAll((actor)=>{
    return {
        "flags.tidy5e-sheet":{
            gender:actor.system.details?.gender ?? "",
            age:actor.system.details?.age ?? "",
            height:actor.system.details?.height ?? "",
            weight:actor.system.details?.weight ?? "",
            eyes:actor.system.details?.eyes ?? "",
            skin:actor.system.details?.skin ?? "",
            hair:actor.system.details?.hair ?? "",
	    notes: {
			 "value": actor.system.details?.notes?.value  ?? ""
	    },
            notes1:{
			"name": actor.system.details?.notes1name ?? "",
			"value": actor.system.details?.notes1?.value  ?? ""
	    },
	    notes2:{
			"name": actor.system.details?.notes2name ?? "",
			"value": actor.system.details?.notes2?.value  ?? ""
	   },
	   notes3:{
			"name": actor.system.details?.notes3name  ?? "",
			"value": actor.system.details?.notes3?.value  ?? ""
	    },
            notes4:{
			"name": actor.system.details?.notes4name  ?? "",
			"value": actor.system.details?.notes4?.value  ?? ""
	    }
        }
    }
})
```

**Comment by sdenec** [comment]
ATTENTION! Tidy5e is now updated for the latest DND 5e release (2.1.x). When you have journal data in your sheet you WILL lose it when you transition from 2.0.3 to 2.1.x - In order to save it you have to execute the Macro in the readme https://github.com/sdenec/tidy5e-sheet#readme BEFORE you make the upgrade. If you do have a backup from before the switch you can recover your data this way. Sorry for any inconveniences.
