### ISSUE TITLE
'Secret' Text Spacing

### ISSUE THREAD

**Issue by DivertedCircle** [sdenec/tidy5e-sheet#64]
The spacing between the top bar of the 'Secret' text styling does not match the bottom spacing. It displays properly when editing the text, but the spacing changes when viewing the result.

Editing
![image](https://user-images.githubusercontent.com/26470570/87214863-c5376100-c2ed-11ea-802e-6e3ca1ffe27e.png)
Viewing
![image](https://user-images.githubusercontent.com/26470570/87214876-d3857d00-c2ed-11ea-8e03-79bfa0a6bb93.png)

**Comment by sdenec** [comment]
should be fixed now.
