### ISSUE TITLE
players cant see "classic items controls"

### ISSUE THREAD

**Issue by Ghosts2045** [sdenec/tidy5e-sheet#646]
I enabled classic controls so the little buttons are there for ease but they dont appear for my players, just me. I have all the permissions set right, and refreshed but nada. Please help. Thanks!

**Comment by p4535992** [comment]
should be fixed with 0.8.11 (please specifiy the module version next time )

**Comment by Ghosts2045** [comment]
Foundry says 0.8.3

**Comment by Ghosts2045** [comment]
Is there an ETA on the release of 0.8.11? Thanks again
