### ISSUE TITLE
[BUG] Middle Click to Edit no longer works

### ISSUE THREAD

**Issue by Brimcon** [sdenec/tidy5e-sheet#650]
Foundry: 10.291
D&D5e: 2.1.4
TidySheet: 0.8.14
LibColors: 2.9.0
No other Modules Enabled

Tidy's Middle click function no longer works for editing items. While not a huge issue, is weird to see it there in the side card and have it not work.

**Comment by p4535992** [comment]
just tested is working what browser are you using ?

**Comment by Brimcon** [comment]
Testing on Chrome myself, No luck.

**Comment by p4535992** [comment]
can you pass to me the actor ? or on PM discord or here on github by renaming the file json to txt

**Comment by Brimcon** [comment]
Clearing my browser cache seems to have fixed the issue. Not sure why it does that but Chrome be Chrome. Apologies for the bug report.
