### ISSUE TITLE
maxPreparedSpells not updating with DAE

### ISSUE THREAD

**Issue by Ehill05** [sdenec/tidy5e-sheet#651]
I'm attempting to have the Prepared Spells section on the character sheet automatically populate with the max prepared spells, but nothing seems to be happening when using the system.details.maxPreparedSpells(*) with an override to add class level to the wisdom modifier.

**Comment by p4535992** [comment]
i prepared a fix beware for avoid collisions with the dnd5e system the field `system.details.maxPreparedSpells` is been replaced with `flags.tidy5e-sheet.maxPreparedSpells`
