### ISSUE TITLE
No longer working after last update

### ISSUE THREAD

**Issue by geoidesic** [sdenec/tidy5e-sheet#652]
manifest can't be found.

**Comment by p4535992** [comment]
if you have installed the beta uninstall and reinstall the module from the standard library

**Comment by geoidesic** [comment]
I have not installed the beta.

**Comment by p4535992** [comment]
just tested is working, try to uninstall the module and reinstall.

**Comment by jporto89** [comment]
Not running the beta, running DND5e version 2.0.3. Foundry on latest stable version. After the update, I am also no longer seeing the module. It is not listed as a module that can be turned on or in the sheet options for the players. Reinstalled the module, same thing.

**Comment by p4535992** [comment]
@sdenec  we need to modify the release 0.7.6 to point to :
https://github.com/sdenec/tidy5e-sheet/releases/download/0.7.6/module.json
instead 
https://github.com/sdenec/tidy5e-sheet/releases/latest/download/module.json

and the module.json in the module.zip too.

**Comment by p4535992** [comment]
Should be fixed, let me know it.

**Comment by geoidesic** [comment]
Nope. No change.
