### ISSUE TITLE
[bug] Special Traits and Actor On Use Macros configuration buttons missing

### ISSUE THREAD

**Issue by cgplayer2000** [sdenec/tidy5e-sheet#655]
Nice work on fixing this sheet for v2.1.2.  

However, the attributes tab no longer provides access to the Special Traits or Actor On Use Macros configuration buttons.  I regularly use the Special Traits configuration and would love to have access to it with my favorite sheet.  

![image](https://user-images.githubusercontent.com/10798879/215356568-9f2542c6-d780-44bb-9ff4-888793d7b964.png)

**Comment by p4535992** [comment]
Cannot replicate the issue have you tried to reset the module settings ?

**Comment by cgplayer2000** [comment]
Okay, yes – I went into settings and reset it back to system defaults and  there they are.  Good to know!

Thanks!



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by p4535992** [comment]
This ticket can be closed
