### ISSUE TITLE
[Bug] Mouse Scroll Wheel Key not working since merge 

### ISSUE THREAD

**Issue by RaylaTheBrave** [sdenec/tidy5e-sheet#656]
**Issue:**
The issue I'm having is that the middle mouse key (the scroll wheel or mouse button 3) doesn't directly open the edit window of the item clicked with it like it used to, I noticed the issue since the pull request from p4535992 was merged into the module.
 
**Versions:**
- Foundry Version: 10 - Build 291, Desktop App.
- Tidy5e Sheet Version: 0.8.15.
- DnD5e Version: 2.1.4.

**Comment by p4535992** [comment]
some people found out some strange behaviour with the cache . try to clean up the cache and try again,

**Comment by OxTailSafu** [comment]
Can confirm this same issue even after clearing my cache. I tested it by going back to version 0.7.6 and the mouse wheel opened the features just like before.

If it makes any difference, I'm launching Foundry using Forge.

**Comment by OxTailSafu** [comment]
Would like to make an update on this issue. It actually DOES work...however you have to enable the classic item controls in list view option as seen here.

![image](https://user-images.githubusercontent.com/123988485/215975014-df52b6b2-9fe5-41f7-be3c-ee76f058a9af.png)

Once I enabled this feature then my mouse wheel was able to open the sheets on the various features, however disabling it once again causes the bug.

**Comment by p4535992** [comment]
is already solved, i made a PR about it
