### ISSUE TITLE
BUG: PC Character Sheet Hit Points drop to 0 if you don't put something in the override.

### ISSUE THREAD

**Issue by GambetTV** [sdenec/tidy5e-sheet#659]
When you click on the Cog Wheel beneath Hit Points it opens "Configure Hit Points." You can enter something in the big field, and it will work. However, if you do not enter anything, the Hit Points are supposed to drop to the default amount of hit points as configured by your Class/Level Advancement. The override is meant to be blank for most characters, unless there's a special reason you need to override this. It will show the default number as it's supposed to, but when you click Save it will drop the HP down to 0, and when you re-open the configuration it shows it like 0 has been entered in. Deleting this number shows you the default value again, but once again saving it will cause the HP to drop to 0.

For whatever reason when this happens, the current HP is increased by the default value, even though Max HP is reduced to 0. So if I have 25 HP, my current HP will increase to 50, while my max HP decreases to 0. If I go back in and hit Save again my Current HP will bump up to 75, while the Max HP stays at 0.

**Comment by MaxPat931** [comment]
Related video, copied from my previous post in the closed PR to here as it's more relevant

https://user-images.githubusercontent.com/86370342/215358520-0f335476-bd3d-49cc-8a0f-4b83e3392b89.mp4

**Comment by GambetTV** [comment]
This bug has returned. If you don't put anything in the override, it drops Max HP to 0.
