### ISSUE TITLE
BUG: Gear Icon to configure ability checks and saving throws covers the actor's saving throw bonus

### ISSUE THREAD

**Issue by OxTailSafu** [sdenec/tidy5e-sheet#662]
Hey there, really thankful for the update recently. I noticed a small issue where the gear icon to edit the actor's global bonus for saving throws and ability checks appears to cover the saving throw bonus on the sheet. Normally not the biggest deal, however given how hard it can be sometimes to see the values and the fact that the gear icon underneath the initiative value is formatted correctly really sticks out.

![image](https://user-images.githubusercontent.com/123988485/215970065-b42d3499-5f91-458b-87ea-07feb9d3d82a.png)

It also causes an issue where sometimes when you try to roll a saving throw you may accidently click on that configure button, and vice versa. This occurs on both npc sheets as well as pc sheets.

I have attempted to reshape the sheet to see if that was the cause, but no matter how small or large I resized it, it still resulted in the icon covering the bonus.

**Comment by p4535992** [comment]
@OxTailSafu i cannot replicate the issue,  have you tried to disable all other modules ?

**Comment by OxTailSafu** [comment]
Ah you're absolutely right, there's a conflict with the 5e Custom Abilities and Skills module. Thank you!
