### ISSUE TITLE
Bug: Prepared Spells Display Issue

### ISSUE THREAD

**Issue by DivertedCircle** [sdenec/tidy5e-sheet#664]
Referencing back to #657 , I do not see ```flags.tidy5e-sheet.maxPreparedSpells``` as an option in the dropdown list of active effect flags. I tried entering it anyway and while it seemed to work last night, it is no longer doing so as of today after updating to the new sheet.

**Comment by p4535992** [comment]
You're asking in the wrong place I think the hints in the dropdown of choosing the key of the effect are from another module and anyway the default flags are not visulized.

**Comment by DivertedCircle** [comment]
What seems to be happening is that the active effect is recognized, but then no longer recognized on a game reload. Entering the following active effect correctly display the proper number of max prepared spells. Reloading the game however resets the value back to 0, until the active effect is edited and resaved.

![image](https://user-images.githubusercontent.com/26470570/216774446-de524c94-393b-4928-aebc-cdde5154b74e.png)

**Comment by SirGarhi** [comment]
My experience with this issue is that it works fine if I put a single number in the Effect Value field, such as 9. But if I put any sort of formula, even one that doesn't use referenced fields, such as "5+3+2" it doesn't work and remains a 0 on the spellbook tab.

**Comment by p4535992** [comment]
Try out 0.8.18

**Comment by DivertedCircle** [comment]
I am not able to download 0.8.18 (using Molten Hosting). I had previously been on 0.8.17 but checking for updates did not find 0.8.18. Uninstalling and trying to reinstall revealed that 0.8.16 shows as the latest version available, and trying to install it gave this error.

![image](https://user-images.githubusercontent.com/26470570/217686694-6b44d197-4741-46a6-a4b5-47099ff786bf.png)

**Comment by DivertedCircle** [comment]
Appears to be fixed in 0.8.19. Initially I didn't think it was, but after disabling the effect I was able to see the warning message indicating the effect couldn't be set to Override. Once changing the effect to Custom it worked and continued to work after reloading.

**Comment by p4535992** [comment]
Yea it a strange bug not sure why the override mode reset to 0 every time... i even add a note on the tooltip

**Comment by cs96and** [comment]
It seems you can still edit the max prepared spells box, even with an Active Effect in place, unless the mode is set to Add.  when the mode is set to Add, then you get a tooltip saying it can't be modified.  If its set to anything else, then you can just type over the top of what the Active Effect thinks it should be.

Also, the field does not update if changes are made to your character.  E.g. If I set the `flags.tidy5e-sheet.maxPreparedSpells` to `CUSTOM` `@classes.druid.levels + @abilities.wis.mod` and then increase my WIS mod, then the max number of prepared spells does not increase

**Comment by treautea** [comment]
Hello. I just checked the latest version with Foundry V11 build 300. Unfortunately, custom mode doesn't work at all on my side and add doesn't recognize formula (checked @abilities.cha.mod). Putting any digit works only in add mode.
