### ISSUE TITLE
How do I use the macro for updating

### ISSUE THREAD

**Issue by SuicidalWeeaboo** [sdenec/tidy5e-sheet#665]
So I rarely update my foundry but I want to update to 2.1 Ive updated my world to 2.0.3 Like the macro says to but I dont know how to use said macro I tryed just throwing it in chat and putting it in the macro button area but I dont think thats right so how do I use the macro

**Comment by p4535992** [comment]
there many tutorial on youtube and many documentation on foundrysite for accomplish this,.
