### ISSUE TITLE
BUG: Features cannot be favorited and don't show up on favorited list.

### ISSUE THREAD

**Issue by GambetTV** [sdenec/tidy5e-sheet#666]
As of the latest update items on the Feature tab cannot be favorited. There's also no delete button, edit button, duplicate button, or Favorite button listed, though you can still access them by right clicking them. However even if you Right Click to Favorite, they won't show up on the Favorite list.

**Comment by p4535992** [comment]
Did you enabled the "Classic Control view" ?

**Comment by GambetTV** [comment]
Disabling "Use classic item controls in list view" fixed the issue, and actually re-enabling it I'm not having the same issues anymore. Although it's very strange to me that "Features" does not work the same as Spells and Inventory.

With "Use classic item controls in list view" ENABLED, Features cannot be edited, copied, favorited, or deleted without right clicking on them, yet Spells and Inventory items can be used from the right side of the screen.

With "Use classic item controls in list view" DISABLED, Features can be edited, copied, favorited, and deleted from the right hand side of the screen, but Spellbook and Inventory can only be right clicked on.

Why is there no option for all of these things to work exactly the same as each other?

**Comment by GambetTV** [comment]
Also for some reason NPC sheets don't have the option to be edited except through right clicking.

**Comment by p4535992** [comment]
k i replicate issue i'll try to fix on the next release
