### ISSUE TITLE
BUG: Spell Attack Mod Incorrectly Including Temporary Dice Roll Bonuses

### ISSUE THREAD

**Issue by Dialectikal** [sdenec/tidy5e-sheet#668]
![image](https://user-images.githubusercontent.com/31572084/216178366-9a690d3e-7c9c-4da0-9e6b-fc562c905e23.png)

This should be +11. Whenever the Bless spell is applied, or something similar, the attack mod includes it as a flat value increase.

**Comment by p4535992** [comment]
Did you have the same value with default character sheet ? or is +11 ?

**Comment by Dialectikal** [comment]
I believe this is a unique info feature to Tidy5e. The default sheet only shows spell attack modifier on individual attack spells. In those cases, it is calculated correctly.

![image](https://user-images.githubusercontent.com/31572084/216188994-0d9b74c6-715d-40e2-b61a-42b644b163dd.png)

**Comment by p4535992** [comment]
A ok i see on the old version on 2.0.3 is the same, so is not a bug , but a feature, maybe you want a different label ?
For example:
_Spell DC 19  /Attack Mod: +12 ( + 11 base)_ 

or perhaps a module setting for show the bonus or not ?

**Comment by Dialectikal** [comment]
It might have been there before. I'm not sure. But it is definitely a bug. It shouldn't show +12 at all.
I could see maybe including +1d4 somewhere, but I don't think that is even necessary.

To clarify, the player's Spell Attack Modifier is actually +11. Bless grants an additional 1d4 to be rolled for any attack rolls and saving throws. It doesn't actually increase a player's Spell Attack Modifier. If it were not a bug, or even intended, I imagine the saving throw bonuses would all be incremented as well.

**Comment by p4535992** [comment]
It's just a visual interface thing, I don't know why it was done that way at the time, but I can't know in advance whether people would prefer to see +12 or +11 for now I'll just update the label to show both values.

**Comment by Dialectikal** [comment]
Ok. I suppose that's fine. The +12 just doesn't represent anything at all.
There is no sense in which the character has a +12, so I'm not sure why
anyone would prefer that.

Just so you understand what I'm saying, the bonus added is +1d4 in this
example, not +1. So going from 11 to 12 never makes sense. I think it was
just an error.
