### ISSUE TITLE
BUG: Sheet periodically stops working/updating, especially when adding/deleting items from inventory, requires Refresh to fix

### ISSUE THREAD

**Issue by GambetTV** [sdenec/tidy5e-sheet#670]
This is a hard one to duplicate quickly, but is pretty catastrophic when it occurs. It's happened to me 3 times today, and twice to my players today. It seems to occur if I add an item to someone's inventory, or delete an item from someone's inventory. I suspect it would work the same for Spells/Features, but I haven't tested this.

It does not happen 100% of the time. It seems to take a little time before it starts to come up. I don't know if there's such a thing as a memory leak with a TidySheet module, but that's the vibe it gives me. At some point I'll delete an object from the inventory and nothing happens. Then I close the sheet and I can't open it again. I can open other character's sheets, but the one I added/deleted an item from just won't open unless I refresh.

When adding an object it works the same way, it just doesn't show up. The funny thing is, the object IS being added. Just like when I delete an object, it doesn't show it's being deleted, but it is. It just doesn't show up until I refresh. I wound up adding the same object 3 times to a character sheet because I couldn't figure out why drag and drop wasn't working. Then the sheet wouldn't re-open and when I refreshed it suddenly had multiple items.

I can say that it might not happen for a while, maybe 30 minutes to an hour into a session, but once it starts, it'll happen pretty consistently across multiple character sheets from what I can tell.

I've only tried this in PC sheets so far, not NPC sheets.

**Comment by p4535992** [comment]
1) No exception on the web console ?
2) Did you use some other module ?
3) What system and foundry version are you using ?

**Comment by GambetTV** [comment]
1. I didn't look. Next time it happens I will, and I'll post it here. I'm having a session tonight, so it most likely will happen then.
2. I use a lot of other modules, but the problem is that because this bug doesn't rear it's ugly head for 30-60 minutes of using Foundry, there's just no way I can test this out in a live session with only one module running.
3. Foundry 10, Build 291, and DnD5e 2.3.4.

**Comment by p4535992** [comment]
If you update the system to 2.1.X (i guess 2.3.4 is 2.1.4 XD) many module need to be updated... so even if you do not update any other module that doesn't mean they are not the cause of the problem.

I still  can't replicate the problem.

**Comment by GambetTV** [comment]
Yeah, apologies, I meant 2.1.4.

And I don't think so. I updated to 2.1.4 the day it was released, and had to disable TidySheet ever since, and never had this specific issue. That said, I get that it's hard to duplicate, so I'll just make sure to get the console error next time it happens and report back on it.

**Comment by ForbiddenArcana** [comment]
I'm also getting this issue, but it seems to be a dnd5e system bug. It happens reliably every time I delete an item while it's expanded in the inventory (collapsed items are deleted fine without triggering the bug), on character sheets created on dnd5e 2.1.4, regardless of whether it's a Tidy5e sheet or even if no modules (including Tidy5e) are activated.

Foundry: 10.291
dnd5e: 2.1.4
Tidy5e: 0.8.20

I've opened an issue for the dnd5e system [here](https://github.com/foundryvtt/dnd5e/issues/2183) which you can follow, but I don't know if anything can be done on the Tidy5e side.

**Comment by ForbiddenArcana** [comment]
Ah I didn't see an open issue for it on dnd5e because a previous issue reporting it had already been closed. Looks like it's targeted to be fixed on dnd5e 2.2.0.

**Comment by GambetTV** [comment]
Yeah, I can confirm what Forbidden says here, it's not a Tidy5e problem, it's a core DnD5e problem. We can happily close this one!
