### ISSUE TITLE
Sheet style breaking with long entries in <ul class="origin summary">

### ISSUE THREAD

**Issue by thatlonelybugbear** [sdenec/tidy5e-sheet#673]
It probably won't be triggered quite that often, but still its something worth mentioning I guess!

![image](https://user-images.githubusercontent.com/7237090/216339703-00a0dd8d-01c5-401c-8070-176225bdc3fa.png)

**Comment by p4535992** [comment]
For solve this i just truncate the value on the sheet, but let you read the full value on the tooltip
