### ISSUE TITLE
BUG: NPC sheet column issue with Uses/Usage not showing up in the right spot

### ISSUE THREAD

**Issue by GambetTV** [sdenec/tidy5e-sheet#674]
Uses and Usage columns don't line up with the actual items in the list. If you look at the screenshot below, the ability "Children of the Night" has the 1/1 uses under the Usage Column, and the action cost is showing up under nothing.

![image](https://user-images.githubusercontent.com/72000497/216400184-bd55d0f2-2a7c-44fc-8087-0108cc581fa9.png)

**Comment by p4535992** [comment]
Try out 0.8.17 and let me know if the issue persist and what module setting you are using

**Comment by GambetTV** [comment]
It's fixed! Thank you for this and all the other bug fixes you addressed!
