### ISSUE TITLE
Version 0.8.16 not working properly

### ISSUE THREAD

**Issue by KxngSonic** [sdenec/tidy5e-sheet#676]
I am currently running Foundry 0.10.285 and I just updated Tidy 5e Sheet and now it's not showing up on my modules list, and I'm a little afraid to update my foundry cause I don't want to lose my 5e Importer.

**Comment by p4535992** [comment]
DO NOT SAY THE P WORD PLEASE (remove from the comment please).

Try to uninstall and reinstall the module if you hvae update the dnd5e system to 2.1.x or else use the direct manifest.json  https://github.com/sdenec/tidy5e-sheet/releases/download/0.7.6/module.json for system 2.0.3

**Comment by KxngSonic** [comment]
Thank you it works again, and I should have said I didn't want to lose the ability to click and drag tokens.

**Comment by p4535992** [comment]
This ticke can be closed
