### ISSUE TITLE
Bug: Unattuned Item Icon Color

### ISSUE THREAD

**Issue by DivertedCircle** [sdenec/tidy5e-sheet#678]
Unattuned magic items in player inventory used to have a red sunburst icon showing that they weren't attuned. In the latest updates the icon has remained, but it not longer displays in red, now showing in black like the regular attuned icon.

**Comment by GambetTV** [comment]
To add to this, you used to be able to attune to an item with this module by clicking on the attunement icon. Now you have to right click the item to do it. Not a huge deal, but just one of those quality of life features that made this module so great.
