### ISSUE TITLE
Missing localization strings

### ISSUE THREAD

**Issue by BrotherSharper** [sdenec/tidy5e-sheet#682]
The ability scores besides the skills do not translate.
The abbreviation for these are in the system's i18n but I did not find any derivatives in the latest en.json so I am putting this up as an issue.

![image](https://user-images.githubusercontent.com/41280723/216818153-773f36c9-4de1-48db-be43-c02024aea2a5.png)

**Comment by p4535992** [comment]
Those labels are generated at the system level, I could also "patch" them on the module side, but it would be more correct for them to be fixed on the system itself.

**Comment by BrotherSharper** [comment]
It's weird because they are picked up correctly when I use the default sheet (taken from the localization module of the system) but turn to english when using tidy5e sheet.
I double checked the localization string on the 5e module and everything seems to be fine (and loads well on past versions)

Could it be that tidy5e somehow missed those and hard coded them in?

**Comment by p4535992** [comment]
k i see it, not sure why i used the `skill.ability` instead of `skill.abbreviation` on the template... but i see many changes on the skills template from 2.1.0 to 2.1.4 so maybe it was a fix on the system ?
