### ISSUE TITLE
[BUG]Visual bug with Character Actions List for dnd5e

### ISSUE THREAD

**Issue by OxTailSafu** [sdenec/tidy5e-sheet#688]
Module Version: Tidy5e Sheet: v0.8.17 (Has been occuring since version v0.8.14)
Character Actions List dnd5e: Version 6.0.2.

Describe the bug
Crossposting this issue from here https://github.com/p4535992/foundryvtt-character-actions-dnd5e/issues/1. The character actions tab on the sheet appears to have issues regarding alignment which makes it difficult to see everything unless you expand the window. It does not fully rectify the issue however as seen in the screenshots below.

To Reproduce

Open the character sheet.
Go to the action section of the sheet.

Expected behavior
To have the range, hit/dc and damage fields align with its list elements.

Screenshots
![image](https://user-images.githubusercontent.com/123988485/217340671-467b8ac9-5b6a-4c5b-8a9a-debf36c902e1.png)
This is how the sheet looks when you first open it.

![image](https://user-images.githubusercontent.com/123988485/217340812-670915c7-beb2-4a00-8354-a9a96a13515b.png)
When you widen the window however, you can clearly see that the values for damage aren't being aligned, which is likely pushing everything else to the left as seen here where it's blank.

**Comment by gambit07** [comment]
Seeing the exact same issue

**Comment by p4535992** [comment]
Made some css tweak on my fork 
https://github.com/p4535992/foundryvtt-character-actions-dnd5e/releases/latest/download/module.json 
for anyone interested

**Comment by gambit07** [comment]
> Made some css tweak on my fork https://github.com/p4535992/foundryvtt-character-actions-dnd5e/releases/latest/download/module.json for anyone interested

Works awesome, tks
