### ISSUE TITLE
Why burden my game with unneeded add-ons.

### ISSUE THREAD

**Issue by BillPitcher** [sdenec/tidy5e-sheet#689]
There is no need for me or my players to use VTTColorSettings but now I've got to have it so you don't need to add a little code to your module. Every new module is a break point in this never ending update / out of date Foundry add-on cycle. Ahhhh, make it stop.

**Comment by p4535992** [comment]
If you are concerned about integration and management between modules then FoundryVTT is not the VTT for you. Tidy itself is a "useless" module if you ask me, but people can't seem to do without it.

"VTTcolorSettings" is also used by the "LibThemer" library that I hope to integrate later, so at least that is module I can't avoid using.

**Comment by p4535992** [comment]
looking at the code again I changed my mind, in hindsight I could put the dependency as optional, the only thing is that for color customization to generate the hex code you will have to rely on some online tool.

**Comment by p4535992** [comment]
k removed on 0.8.18
