### ISSUE TITLE
Needless Favourite icon Showing, confusing to Players

### ISSUE THREAD

**Issue by BillPitcher** [sdenec/tidy5e-sheet#691]
When Classic Item Controls enabled shows 2 Favourite icons
<img width="635" alt="Screenshot 2023-02-08 at 7 06 30 pm" src="https://user-images.githubusercontent.com/4987108/217488651-e06fc66d-6bdd-4222-8c24-7fac9732383b.png">
<img width="403" alt="Screenshot 2023-02-08 at 7 02 18 pm" src="https://user-images.githubusercontent.com/4987108/217488684-5dcf83cb-90be-45db-a767-e2d09323d0ed.png">

**Comment by p4535992** [comment]
Add a module setting on 0.8.18
