### ISSUE TITLE
Player Name not being saved [BUG]

### ISSUE THREAD

**Issue by systemeth** [sdenec/tidy5e-sheet#692]
**Module Version:** v0.8.17

Currently, it is not saving player names on a given character sheet.  I am currently assuming it's the same problem as when it wasn't saving the Journal tab or character description on the Biography tab. It looks to me like a slight oversight in that y'all simply forgot to get that entry as well when updating things so the Journal and such could be kept (the Macro for doing that worked just fine btw, was very pleased about that).

**To Reproduce**
1. Go to any PC's character sheet
2. Click on "Player name" and put anything in there
3. Close the sheet when you're done, then reopen it
4. The entry is now gone and back to being empty.

**Comment by sdenec** [comment]
Can't confirm this behavior. Character names are saved as they should be. Any error messages in the console or maybe conflicting modules?

**Comment by p4535992** [comment]
a k yes i see it. If i update the player name is not saved on the sheet probably some flags i forgot

**Comment by systemeth** [comment]
> Character names are saved as they should be.

Not _character_ name, **player** name. The much smaller entry that's directly under the character name.

**Comment by p4535992** [comment]
Try out 0.8.20 should be fixed

**Comment by systemeth** [comment]
Just checked it, and yes this seems to be fixed in 0.8.20. Great job. (y)
