### ISSUE TITLE
[BUG] Ammo Dropdown Missing from weapons

### ISSUE THREAD

**Issue by Brimcon** [sdenec/tidy5e-sheet#693]
**Module Version:** v0.8.17

**Describe the bug**
Ammunition selection is missing from ranged weapons.

**To Reproduce**
1. Import a character from 5e SRD with a ranged weapon (Dragonborn Cleric, Elf Ranger)
2. Open the Character sheet
3. Observe lack of dropdown for equipped Ammunition

**Expected behavior**
Expected to see a dropdown for ammunition.

**Screenshots**
![image](https://user-images.githubusercontent.com/7198283/217641633-33738b0e-8242-4e9a-90bf-2ed09c53c971.png)

**Browser:**
Chrome

**Foundry Version:** 
10.291

**Game System:** 
dnd5e 2.1.4

**Additional context**
No console log.
No other modules enabled.

**Comment by GambetTV** [comment]
Yep, I came here to report the same thing. Occurring for me too in the same version, but I'm using the Foundry App.

**Comment by GambetTV** [comment]
As of 0.8.19, this is still not fixed.

**Comment by p4535992** [comment]
i fixed i just don't made the release yet , just wait fro me to ask to try out the new version

**Comment by p4535992** [comment]
Try out 0.8.20 should be fixed

**Comment by BillPitcher** [comment]
Gone again in 8.21

**Comment by p4535992** [comment]
Just tested is working checkout the itemif is enabled to use ammunition
