### ISSUE TITLE
[BUG] Player Race does not output correctly if Parenthesis are added and manage long string text

### ISSUE THREAD

**Issue by GambetTV** [sdenec/tidy5e-sheet#694]
It's quite common for races to have subraces in Parenthesis, such as: Elf (High Elf) or Bugbear (Goblinoid). For whatever reason formatting it this way in Tidy5e Sheet causes it to output really badly, and it doesn't even make sense how or why. I've attached a screenshot.

![image](https://user-images.githubusercontent.com/72000497/217674388-39f37b20-69ed-4af2-bc9d-6a49ba33ff2d.png)

**Comment by OxTailSafu** [comment]
Can also confirm that this occurs even when you don't put parenthesis. From what I can gather, when the entry is too long (about 15 characters long), it glitches out. This occurs on all 3 fields from what I can tell.

**Comment by p4535992** [comment]
The long string are problematic (https://github.com/sdenec/tidy5e-sheet/issues/673) i decide to truncate the long strings on sheet and show up the full name on the tooltip... alterative can be multline text or window with more width, but that require to much work just for a string to read some time.

**Comment by p4535992** [comment]
Try out 0.8.20 and the tooltip work around for long names

**Comment by OxTailSafu** [comment]
Sure thing! I'll report back once it lets me update. At the moment when I try to update it's still saying the previous version is the most current release, but that's likely to change in a few minutes.

**Comment by OxTailSafu** [comment]
Okay so I was able to update. It DOES fix the issue and though it looks a little odd with some of the spaces, I do think I prefer this over before where it would glitch out.

![image](https://user-images.githubusercontent.com/123988485/217950871-1ab225b6-7cab-48c6-958c-ef7c42202243.png)

**Comment by The-Forge-Master** [comment]
I'd argue the edge case mentioned above is one that must occur on purpose, has minimal impact other than a giggle for the person testing, and should be left as it was, as 15 characters is too short for even many official races and backgrounds.

**Comment by p4535992** [comment]
I'll move the config button on the left and try to give more default space to the labels and put some css to try to made a little  prettier

**Comment by p4535992** [comment]
Try out 0.8.21 i have made it prettier, BUT long text will be truncate anyway and the full text will show up on the tooltip unless you know some better workaround

**Comment by p4535992** [comment]
Wait for this pr to be merged for remove the truncate function https://github.com/foundryvtt/dnd5e/pull/2186/files

**Comment by p4535992** [comment]
Made some better css tweak...still need a css expert
