### ISSUE TITLE
Can't install version 0.8.18 in app

### ISSUE THREAD

**Issue by aojengineering** [sdenec/tidy5e-sheet#695]
I am getting this error when I try to install the module, same happened when I tried to update it so I uninstalled.  Manual Manifest URL does the same thing.  I can download the file manually from git, so not sure why it is having this problem.  Other mods updated fine.

setup.js:292 Error: An unexpected error occurred when downloading file https://github.com/sdenec/tidy5e-sheet/releases/download/v0.8.18/module.zip: Not Found
    at fetchWithTimeout (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/common/utils/http.mjs:42:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/files/downloader.mjs:1:616

**Comment by ice11691** [comment]
How did you download the file manually from git?  I uninstalled and tried to copy the manifest but that did not work and now I am without it entirely.

**Comment by aojengineering** [comment]
Under Code you can download the zip, and you can go to the address listed in the error message, but I don't know how to install that zip file personally.

**Comment by DivertedCircle** [comment]
Having the same problem, and not seeing 0.8.17 available where you would expect.
https://github.com/sdenec/tidy5e-sheet/issues/664#issuecomment-1423452899

**Comment by ndstumme** [comment]
The url in the manifest has an extra character. There's a 'v' before the version number that shouldn't be there.
It links to https://github.com/sdenec/tidy5e-sheet/releases/download/v0.8.18/module.json but it should link to https://github.com/sdenec/tidy5e-sheet/releases/download/0.8.18/module.json

**Comment by sdenec** [comment]
Please try again. Should be working now

**Comment by aojengineering** [comment]
it did, thanks for the quick fix!
