### ISSUE TITLE
[BUG] PC Character Sheet Hit Points drop to 0 if you don't put something in the override.

### ISSUE THREAD

**Issue by GambetTV** [sdenec/tidy5e-sheet#696]
Latest version of everything. 0.8.18. I reported this before, I think it was fixed, but I can't remember anymore. At the very least the old ticket was closed, and it's broken again.

When you click on the Cog Wheel beneath Hit Points it opens "Configure Hit Points." You can enter something in the big field, and it will work. However, if you do not enter anything, the Hit Points are supposed to drop to the default amount of hit points as configured by your Class/Level Advancement. The override is meant to be blank for most characters, unless there's a special reason you need to override this. It will show the default number as it's supposed to, but when you click Save it will drop the HP down to 0, and when you re-open the configuration it shows it like 0 has been entered in. Deleting this number shows you the default value again, but once again saving it will cause the HP to drop to 0.

For whatever reason when this happens, the current HP is increased by the default value, even though Max HP is reduced to 0. So if I have 25 HP, my current HP will increase to 50, while my max HP decreases to 0. If I go back in and hit Save again my Current HP will bump up to 75, while the Max HP stays at 0.

**Comment by p4535992** [comment]
Try out 0.8.19 and make sure the module setting "Allow Max Hp Override on the Character" is enabled.

**Comment by GambetTV** [comment]
This setting fixes one aspect of the problem, however I think you're missing the core problem. Realistically you should probably just have HP behave how it would by default in the core DnD5e system, because changing that core functionality is really what's causing all these bugs to crop up, and I don't really see what the changes add. I mean it's fine to let us override the Max HP directly in the character sheet, but beyond that I'm just not sure what the point is.

By default, DnD5e has the Cog next to the HP that opens up a configuration screen. 

![image](https://user-images.githubusercontent.com/72000497/217920986-25844719-0243-4e71-8892-57b426c095a1.png)

TidySheet also has this.

![image](https://user-images.githubusercontent.com/72000497/217920119-9742c8a0-0196-4ffc-85f8-a1311d795bf8.png)

In Default DnD5e (no TidySheet), the HP number will be grayed out, but will display the number. In the picture below, the left version shows it grayed out, the right one I've manually entered in the same number showing that it's more bold/black. It's a subtle difference but it's important.

![image](https://user-images.githubusercontent.com/72000497/217921423-a8ba66a9-56e4-4ea8-ac13-c8a1bfd61848.png)

If I leave this number blank, and therefore grayed out, it's going to default to exactly how many HP I should have as configured by my character's Level Up/Advancement Wizard, pulling from my Class, and Constitution bonus per level. However if my character is a Hill Dwarf and gets an extra +1 HP per level, you can enter this in the "Per Level Bonus" area and it will automatically calculate it out.

From here on out, if I level up, it will automatically level up my Current HP and my Max HP to what it should be.

![image](https://user-images.githubusercontent.com/72000497/217923917-442788c1-b384-4fb7-9f91-040f247d45c0.png)


However, if instead of just leaving the Configuration window blank, if I input a number, this will override that automatic calculation, and the behavior will be pretty glitchy and weird by comparison.

![image](https://user-images.githubusercontent.com/72000497/217924900-df475f5b-2d31-46e1-b8fd-ddd8d40bf3a2.png)

As you can see in the image above, simply by entering a number in the Configuration menu instead of leaving it blank, when the character levels up, it doesn't do what it did before, instead it only boosts the Current HP, but leaves the Max HP the same. This behavior essentially strips the automation out of the system and requires the GM to manually adjust things every time they level. This is GOOD that they allow for this, but I don't think it's useful for 99% of users or use cases, and the vast majority of players will simply want to use the default behavior and leave the Configuration grayed out.

All of that was default DnD5e, with TidySheet disabled.

When TidySheet is enabled, it makes all that finnicky manual configuration requirements the DEFAULT mode, and there is NO WAY TO FIX IT.

With "Allow Max HP Override on the Character Sheet" DISABLED, The default behavior is to have the HP Configuration not be grayed out, but instead have the number filled in.

![image](https://user-images.githubusercontent.com/72000497/217926610-71a59ac8-f692-4c2b-9776-1720c05728e4.png)

If I delete that number, it still uses the DnD5e default of making the grayed out number be the CORRECT number, however once I click SAVE, it  drops my max HP to 0, while leaving my Current HP alone.

![image](https://user-images.githubusercontent.com/72000497/217927199-25f203ca-5002-4474-9493-d8b2eef29f40.png)

The next time I go into the Configuration box, it will have a 0 entered in, not grayed out. If I delete this 0, something nonsensically buggy occurs, even though it shows what my max HP should be with the normal calculations of Class/CON, as a grayed out number, when I hit Save it will still drop my Max HP to 0, but now for no reason whatsoever my current HP jumps up by this amount. This is 100% a bug that should not be occuring.

![image](https://user-images.githubusercontent.com/72000497/217928392-f1d47ee4-52ff-455f-bf80-c56fdfd2b0d4.png)

So, okay, you created a new setting, which is not active by default. "Allow Hp Max override on Character" which as far as I can tell is designed to do two things.

1. It allows us to change the Max HP without having to hit the Cog and opening the Configuration screen. We can simply click on the HP bar in the character sheet and change it there.
2. It reinitializes the default DnD5e behavior of, when you delete the number in the Configuration screen, and it shows what the normal calculation should be, when you hit Save it will actually plug in that number into your HP.

#1 is fine. Letting people change the Max HP through the HP bar instead of the configuration menu is a fine quality of life feature for GMs who want to get fiddly with manual changes of HP. This is what that setting is there for, I think, and it makes sense to me that it is OFF by default, so that GMs who don't care about automation can essentially turn it off but gain access to a new feature.

However, this is not my use case, I do not especially care about manually changing HP, and I suspect most GMs don't either, or at least don't need to do it so quickly that they need this functionality. It's still very cool and a useful feature that I'm glad you added, but I'm just trying to explain that I think this is more of a niche functionality for a small group of GMs.

#2 however is far more important, as it essentially brings the core DnD5e default automation back into the module, which I imagine MOST GMs are going to want to use. Because of this, I would highly recommend that this functionality NOT be something GMs have to enable in the settings, but instead should be DEFAULT behavior. Furthermore, there should NEVER be a use case where deleting the number from the configuration window shows us an HP value (of say 39 as in my examples above) but then drops it to 0. This is completely unintuitive, and buggy, and is going to lead to a lot more people putting in bug tickets.

That said, even with "Allow Hp Max override on Character" enabled, this does not even solve the core issues. It bandaids one particular symptom, but doesn't cure the core disease. Because now when you open the HP Configuration and delete the number, it will use the automatic calculations to figure out what your HP should be, but then it simply throws the new number into the configuration, and there is effectively no way to delete it and get it to always automatically configure it.

![image](https://user-images.githubusercontent.com/72000497/217933213-8b5c528b-d7a4-402f-bac3-9aa1b52125cd.png)

This matters, because effectively Tidy5e now ALWAYS OVERRIDES Foundry's default automation. It simply allows you to, through a very finnicky workflow, briefly reinitialize the automation for one token at a time. This is most easily displayed via the level up system.

![image](https://user-images.githubusercontent.com/72000497/217935731-811e708e-a3bb-40ab-8b95-700b3340fdb6.png)

As you can see from the above, because of the way you've configured this, so that effectively Tidy5e always operates as if Max HP has been overridden with a specific value, and automatic HP calculations are always disabled, when you level up it keeps your HP the same. This means EVERY TIME someone levels up, no matter how the DM has TidySheet configured, HP will be wrong, and will require the GM to take the extra step of either calculating HP themselves, or going back into the HP Configuration window, and delete the value there to reset the automation.

Hopefully you can see the problem with this.

Personally I think what makes the most sense is to just have TidySheet act the way core DnD5e has it work, where it assumes automation of HP calculation is on by default, and nothing overrides this unless you very intentionally manually configure it yourself. This automation should always be assumed to be on, should be default, should not require us to enable a new setting. It should just work.

An extra setting to allow us to override this through the HP bar is completely fine for the GMs who don't care about the automation, but because I suspect the vast majority of GMs will just want to stick to the very useful automation, this makes sense to turn off by default.

Hopefully this all makes sense, and clarifies what the core issue is.

**Comment by p4535992** [comment]
> This setting fixes one aspect of the problem, however I think you're missing the core problem. Realistically you should probably just have HP behave how it would by default in the core DnD5e system, because changing that core functionality is really what's causing all these bugs to crop up, and I don't really see what the changes add. I mean it's fine to let us override the Max HP directly in the character sheet, but beyond that I'm just not sure what the point is.
> 
> By default, DnD5e has the Cog next to the HP that opens up a configuration screen.
> 
> ![image](https://user-images.githubusercontent.com/72000497/217920986-25844719-0243-4e71-8892-57b426c095a1.png)
> 
> TidySheet also has this.
> 
> ![image](https://user-images.githubusercontent.com/72000497/217920119-9742c8a0-0196-4ffc-85f8-a1311d795bf8.png)
> 
> In Default DnD5e (no TidySheet), the HP number will be grayed out, but will display the number. In the picture below, the left version shows it grayed out, the right one I've manually entered in the same number showing that it's more bold/black. It's a subtle difference but it's important.
> 
> ![image](https://user-images.githubusercontent.com/72000497/217921423-a8ba66a9-56e4-4ea8-ac13-c8a1bfd61848.png)
> 
> If I leave this number blank, and therefore grayed out, it's going to default to exactly how many HP I should have as configured by my character's Level Up/Advancement Wizard, pulling from my Class, and Constitution bonus per level. However if my character is a Hill Dwarf and gets an extra +1 HP per level, you can enter this in the "Per Level Bonus" area and it will automatically calculate it out.
> 
> From here on out, if I level up, it will automatically level up my Current HP and my Max HP to what it should be.
> 
> ![image](https://user-images.githubusercontent.com/72000497/217923917-442788c1-b384-4fb7-9f91-040f247d45c0.png)
> 
> However, if instead of just leaving the Configuration window blank, if I input a number, this will override that automatic calculation, and the behavior will be pretty glitchy and weird by comparison.
> 
> ![image](https://user-images.githubusercontent.com/72000497/217924900-df475f5b-2d31-46e1-b8fd-ddd8d40bf3a2.png)
> 
> As you can see in the image above, simply by entering a number in the Configuration menu instead of leaving it blank, when the character levels up, it doesn't do what it did before, instead it only boosts the Current HP, but leaves the Max HP the same. This behavior essentially strips the automation out of the system and requires the GM to manually adjust things every time they level. This is GOOD that they allow for this, but I don't think it's useful for 99% of users or use cases, and the vast majority of players will simply want to use the default behavior and leave the Configuration grayed out.
> 
> All of that was default DnD5e, with TidySheet disabled.
> 
> When TidySheet is enabled, it makes all that finnicky manual configuration requirements the DEFAULT mode, and there is NO WAY TO FIX IT.
> 
> With "Allow Max HP Override on the Character Sheet" DISABLED, The default behavior is to have the HP Configuration not be grayed out, but instead have the number filled in.
> 
> ![image](https://user-images.githubusercontent.com/72000497/217926610-71a59ac8-f692-4c2b-9776-1720c05728e4.png)
> 
> If I delete that number, it still uses the DnD5e default of making the grayed out number be the CORRECT number, however once I click SAVE, it drops my max HP to 0, while leaving my Current HP alone.
> 
> ![image](https://user-images.githubusercontent.com/72000497/217927199-25f203ca-5002-4474-9493-d8b2eef29f40.png)
> 
> The next time I go into the Configuration box, it will have a 0 entered in, not grayed out. If I delete this 0, something nonsensically buggy occurs, even though it shows what my max HP should be with the normal calculations of Class/CON, as a grayed out number, when I hit Save it will still drop my Max HP to 0, but now for no reason whatsoever my current HP jumps up by this amount. This is 100% a bug that should not be occuring.
> 
> ![image](https://user-images.githubusercontent.com/72000497/217928392-f1d47ee4-52ff-455f-bf80-c56fdfd2b0d4.png)
> 
> So, okay, you created a new setting, which is not active by default. "Allow Hp Max override on Character" which as far as I can tell is designed to do two things.
> 
> 1. It allows us to change the Max HP without having to hit the Cog and opening the Configuration screen. We can simply click on the HP bar in the character sheet and change it there.
> 2. It reinitializes the default DnD5e behavior of, when you delete the number in the Configuration screen, and it shows what the normal calculation should be, when you hit Save it will actually plug in that number into your HP.
> 
> #1 is fine. Letting people change the Max HP through the HP bar instead of the configuration menu is a fine quality of life feature for GMs who want to get fiddly with manual changes of HP. This is what that setting is there for, I think, and it makes sense to me that it is OFF by default, so that GMs who don't care about automation can essentially turn it off but gain access to a new feature.
> 
> However, this is not my use case, I do not especially care about manually changing HP, and I suspect most GMs don't either, or at least don't need to do it so quickly that they need this functionality. It's still very cool and a useful feature that I'm glad you added, but I'm just trying to explain that I think this is more of a niche functionality for a small group of GMs.
> 
> #2 however is far more important, as it essentially brings the core DnD5e default automation back into the module, which I imagine MOST GMs are going to want to use. Because of this, I would highly recommend that this functionality NOT be something GMs have to enable in the settings, but instead should be DEFAULT behavior. Furthermore, there should NEVER be a use case where deleting the number from the configuration window shows us an HP value (of say 39 as in my examples above) but then drops it to 0. This is completely unintuitive, and buggy, and is going to lead to a lot more people putting in bug tickets.
> 
> That said, even with "Allow Hp Max override on Character" enabled, this does not even solve the core issues. It bandaids one particular symptom, but doesn't cure the core disease. Because now when you open the HP Configuration and delete the number, it will use the automatic calculations to figure out what your HP should be, but then it simply throws the new number into the configuration, and there is effectively no way to delete it and get it to always automatically configure it.
> 
> ![image](https://user-images.githubusercontent.com/72000497/217933213-8b5c528b-d7a4-402f-bac3-9aa1b52125cd.png)
> 
> This matters, because effectively Tidy5e now ALWAYS OVERRIDES Foundry's default automation. It simply allows you to, through a very finnicky workflow, briefly reinitialize the automation for one token at a time. This is most easily displayed via the level up system.
> 
> ![image](https://user-images.githubusercontent.com/72000497/217935731-811e708e-a3bb-40ab-8b95-700b3340fdb6.png)
> 
> As you can see from the above, because of the way you've configured this, so that effectively Tidy5e always operates as if Max HP has been overridden with a specific value, and automatic HP calculations are always disabled, when you level up it keeps your HP the same. This means EVERY TIME someone levels up, no matter how the DM has TidySheet configured, HP will be wrong, and will require the GM to take the extra step of either calculating HP themselves, or going back into the HP Configuration window, and delete the value there to reset the automation.
> 
> Hopefully you can see the problem with this.
> 
> Personally I think what makes the most sense is to just have TidySheet act the way core DnD5e has it work, where it assumes automation of HP calculation is on by default, and nothing overrides this unless you very intentionally manually configure it yourself. This automation should always be assumed to be on, should be default, should not require us to enable a new setting. It should just work.
> 
> An extra setting to allow us to override this through the HP bar is completely fine for the GMs who don't care about the automation, but because I suspect the vast majority of GMs will just want to stick to the very useful automation, this makes sense to turn off by default.
> 
> Hopefully this all makes sense, and clarifies what the core issue is.

If you don't enable the module setting "Allow Max Hp Override on the Character"  IS IT THE DEFAULT CODE OF THE SYSTEM, i touch only the input change made on sheet side so i don't touch the code behind the dialog configuration of default of the system

```
  THIS IS THE TIDY PATCH
      {{#if @root.allowHpMaxOverride}}
      <a class="config-button hit-points-tidy" data-tooltip="{{localize 'DND5E.HitPointsConfig'}}">
		<i class="fas fa-cog"></i>
	</a>
      {{else}}
  THIS IS THE SYSTEM DEFAULT
      <a class="config-button" data-action="hit-points" data-tooltip="{{localize 'DND5E.HitPointsConfig'}}">
		<i class="fas fa-cog"></i>
	</a>
      {{/if}}
```
so i'm not sure what did you want from me ... i give up... i'm not waste anymore time on this issue, maybe is something simple or maybe is  some other module collision i haven't this problem of yours

**Comment by GambetTV** [comment]
I apologize, I'm not trying to frustrate you. I was hoping the long post would clarify the issues and make it easier to troubleshoot. I have tested this in a variety of ways, with all of my modules activated, with all of them activated except Tidy5e, with all of them disabled, with all of them disabled except Tidy5e. In every single case things work when Tidy5e is disabled, and it doesn't work when Tidy5e is enabled. I don't know what specific line of code is causing the issue, I only know that something in Tidy5e is causing the issue.

When you say you haven't had this problem, are you saying that when you level a PC up, the Maximum Hit Points automatically increase and don't require you to manually adjust it or play with it at all? It simply levels it up fully?

If so, then my guess is there's some other setting in Tidy5e messing with it. I'd be willing to look around and see if I can figure out what setting that might be, but first I'd like confirmation from you that you are able to level up a character on your system and both the Current Hit Points AND the Maximum Hit Points automatically increase according to the Automated Advancement System in DnD5e. When I do it, ONLY the Current HP increases, while Maximum HP remains the same as it was from the previous level.

**Comment by MaxPat931** [comment]
FWIW it seems it was working at least in 8.16

**Comment by GambetTV** [comment]
I figured out the problem, I think. I'm not a coder, so I can't explain it whatsoever, but there seems to be some kind of weird issue with the "Lazy Hp and Exp" setting. I believe this setting is enabled by default. Disabling it completely fixed the issue for me, and my HP no longer went to 0. However, even stranger, when I re-enabled Lazy Hp and Exp, the problem was still gone. Not only was it gone, but it was gone for ALL of my worlds, without me having to disable/re-enable. I don't know what the hell to make of that, but there must be some kind of issue with this module when using it with worlds that existed prior to the 2.1.x DnD5e update. Disabling and re-enabling Lazy Hp and Exp seems to reboot it, and the problem has just flat out gone away for me. I'm going to post this in the other thread too, to hopefully help out other people fix their games.

**Comment by MaxPat931** [comment]
Can confirm disabling Lazy HP and EXP fixed it for me too, although reenabling it did return the issue for me
Thanks @GambetTV !

**Comment by p4535992** [comment]
Add some logs and better code for manage this on 0.8.27 if the problem persist let me know it and disable th setting  "laxzy hp"
