### ISSUE TITLE
Ammo Selection Dropdown on Favourite

### ISSUE THREAD

**Issue by BillPitcher** [sdenec/tidy5e-sheet#697]
Thanks for putting the menu back on Inventory, it would be really great if it was on the Attributes/Favourite list too.

cheers
Bill

**Comment by p4535992** [comment]
Try out 0.8.21

**Comment by BillPitcher** [comment]
Not seeing the selector menu in 0.8.21

**Comment by p4535992** [comment]
Just tested, are you sure the item is setted to use ammunitions ?
