### ISSUE TITLE
[BUG] Weird dot on the left side of character sheets.

### ISSUE THREAD

**Issue by GambetTV** [sdenec/tidy5e-sheet#698]
**Module Version:** v0.8.20

There's a weird dot on the left side of the character sheets in v0.8.20, about midway down. It's there for NPC and PC sheets, but the PC sheet has two dots, the second of which pokes off the edge of the character sheet.

**Comment by Brimcon** [comment]
Doing some investigation on my end with Inspect Element, it is refering to a span::after as a 3x3 black pixel at `tidy5e.css:1450`
```js
.tidy5e.sheet.actor .origin-summary li span::after {
    content: "";
    display: block;
    width: 3px;
    height: 3px;
    border-radius: 50%;
    background: var(--t5e-primary-color);
    position: absolute;
    top: 50%;
    left: 0px;
    -webkit-transform: translateY(-50%);
    transform: translateY(-50%);
}
```

**Comment by GambetTV** [comment]
Deleting that gets rid of the one inside the sheet, but not the one that randomly sticks out from the PC tokens.

**Comment by p4535992** [comment]
is already solved (some strange css style) wait for next release

**Comment by p4535992** [comment]
Try out 0.8.21 should be fixed
