### ISSUE TITLE
[BUG] Character sheet Error Opening/editing

### ISSUE THREAD

**Issue by CharlesWynne** [sdenec/tidy5e-sheet#699]
**Module Version:** v0.8.21

**Describe the bug**
Periodically when deleting/adding things to a tidy5e sheet (both NPC and player sheets) I get the following error
![image](https://user-images.githubusercontent.com/125153677/218276793-48e6a4de-c294-49da-9aad-fb79428ee69b.png)

Restarting the foundry game resolves the issue for a time until I start deleting spells/items and adding them back in. Any changes I make while the bug is happening only shows after a restart.

**Comment by p4535992** [comment]
PLEASE DO NOT POST ANYTHING WHIT REFERENCE TO THE "P" MODULE, REMOVE THE SCREENSHOT AND RE-EDIT THE TICKET

Anyway it's seem to be connect to a problem on the core system more detail here: https://github.com/sdenec/tidy5e-sheet/issues/670

**Comment by p4535992** [comment]
Should be solved with 2.1.5 of the system ?
