### ISSUE TITLE
[BUG] Stray Console Log in async function spellAttackMod(app, html, data) {

### ISSUE THREAD

**Issue by BillPitcher** [sdenec/tidy5e-sheet#700]
**Module Version:** v0.8.20

console.log('Prof: '+prof+ '/ Spell Ability: '+spellAbility+ '/ ability Mod: '+abilityMod+'/ Spell Attack Mod:'+spellAttackMod+'/ Spell Bonus :'+spellBonus);

**Comment by p4535992** [comment]
Try out 0.8.21
