### ISSUE TITLE
Usage Field when in Edit mode doesn't apply changes to listed item.

### ISSUE THREAD

**Issue by BillPitcher** [sdenec/tidy5e-sheet#701]
Not sure if Bug or Feature not working yet.
<img width="336" alt="Screenshot 2023-02-12 at 5 27 16 am" src="https://user-images.githubusercontent.com/4987108/218287078-be3e8ea8-cf36-4963-b40b-6ff72bf0dd15.png">

**Comment by p4535992** [comment]
Fixed in 0.8.22

**Comment by Xijiks** [comment]
In 0.8.22 the issue still persists.

**Comment by BillPitcher** [comment]
It may be that you're setting Available Usage above Maximum Usages. It will change Available Usage to Maximum Usages if it's greater.
