### ISSUE TITLE
[BUG]Editing an Item Quantity in both Favourites and Inventory does not update the Items Quantity.

### ISSUE THREAD

**Issue by BillPitcher** [sdenec/tidy5e-sheet#702]
**Module Version:** v0.8.22

**Describe the bug**
Editing an Item Quantity in both Favourites and Inventory does not update the Items Quantity.
<img width="340" alt="Screenshot 2023-02-15 at 8 04 05 am" src="https://user-images.githubusercontent.com/4987108/218874564-f8ab831b-4356-4d1e-8c52-bc0798782d14.png">
![Uploading Screenshot 2023-02-15 at 8.09.05 am.png…]()

**Comment by BillPitcher** [comment]
<img width="616" alt="Screenshot 2023-02-15 at 8 09 05 am" src="https://user-images.githubusercontent.com/4987108/218875053-af78315e-db6f-4bdc-9f3c-53cd49620ef6.png">

**Comment by p4535992** [comment]
Should be fixed on 0.8.25

**Comment by GambetTV** [comment]
Fixed! Thank you!
