### ISSUE TITLE
Error: Failed to inject currency icon onto character sheet. on Tidy5eSheet #43

### ISSUE THREAD

**Issue by BillPitcher** [sdenec/tidy5e-sheet#703]
From [lets-trade-5e](https://github.com/KageJittai/lets-trade-5e)

**Hi,
When I open actor sheets I get the following Error in F12: Let's Trade 5e | Failed to inject currency icon onto character sheet.

I am using tidySheet5e, but when switching to default sheet the currency icon appears and I get no errors.

Here is the Expanded error:

main.js:48 Let's Trade 5e | Failed to inject currency icon onto character sheet.
 	renderInjectionHook	@	main.js:48
 	#call	@	foundry.js:724
 	callAll	@	foundry.js:681
 	_render	@	foundry.js:5153
 	await in _render (async)	 	 
 	_render	@	foundry.js:5822
 	render	@	foundry.js:5067
 	render	@	foundry.js:6394
 	_onClickDocumentName	@	foundry.js:60848
 	🎁call_wrapped	@	libWrapper-wrapper.js:507
 	checkClickDocumentName	@	monks-active-tiles.js:1922
 	🎁call_wrapper	@	libWrapper-wrapper.js:616
 	🎁SidebarDirectory.prototype._onClickDocumentName#0	@	libWrapper-wrapper.js:189
 	🎁call_wrapped	@	libWrapper-wrapper.js:507
 	clickDocumentName	@	monks-active-tiles.js:1870
 	🎁call_wrapper	@	libWrapper-wrapper.js:616
 	🎁ActorDirectory.prototype._onClickDocumentName#0	@	libWrapper-wrapper.js:189
 	dispatch	@	jquery.min.js:2
 	y.handle	@	jquery.min.js:2**

**Comment by BillPitcher** [comment]
> function currencyTidySheet(element, actorId, callback) {
    let currencyIcon = $(`<a class="currency-control currency-trade" title="${game.i18n.localize("LetsTrade5E.Send")}">
        <i class="fas fa-balance-scale-right"></i>
    </a>`)[0];
    currencyIcon.dataset.actorId = actorId;
    currencyIcon.addEventListener("click", callback);

    let insertPoint = $("ul.currency li.currency-header", element)[0];
    let insert = $(`<li class="currency-header flexrow"></li>`).append(currencyIcon);
    insertPoint.before(insert[0]);
}

Looking at the lets trade compatibility.js I'd guess Tidy has removed "ul.currency li.currency-header" :-(

**Comment by p4535992** [comment]
should be fixed now
