### ISSUE TITLE
[BUG] Hovering over AC does not reveal calculation popup.

### ISSUE THREAD

**Issue by GambetTV** [sdenec/tidy5e-sheet#705]
**Module Version:** v0.8.23

When you hover your mouse over your AC, you should see the calculation that shows how you have the AC you have. Such as "16 Chainmail + 2 Shield + 1 Fighting Style: Defense. 19 Total". This popup still occurs, however, the shield symbol seems to cover up the area that registers the mouseover. When you hover over the AC number, or anywhere on the shield icon, you only see "Configure Armor" popup. To see the calculation you have to hover your mouse somewhere in the 4 pixels that's in the AC area but not covered up by the shield symbol. It seems to have to be either to the left or right of the symbol too, anywhere beneath it doesn't work.

**Comment by GambetTV** [comment]
And while we're at it, the alignment on the AC number is off too. There's 27 pixels between the bottom of the shield icon and the bottom of the number, but only 14 pixels between the top of the number and the top of the shield.

**Comment by p4535992** [comment]
Try ou 0.8.25

**Comment by GambetTV** [comment]
Fixed!
