### ISSUE TITLE
[BUG] Right click popup menu doesn't pop over the character sheet, gets stuck beneath it

### ISSUE THREAD

**Issue by GambetTV** [sdenec/tidy5e-sheet#706]
**Module Version:** v0.8.24

When right clicking an item in the Inventory/Spellbook/Features, NPC sheet, etc. the menu that pops up letting you Add/Remove Favorite, Edit Item, Duplicate, Delete, Equip/Unequip for items, etc. gets stuck beneath the character sheet, whereas in the old days it would pop up over it. This basically means you have to scroll down to see the entire menu for items at the bottom of the list.

How it used to be:
![image](https://user-images.githubusercontent.com/72000497/219286398-293814e0-4bbd-429d-be57-b41abf716f63.png)

How it is now:
![image](https://user-images.githubusercontent.com/72000497/219286322-c601f145-3f60-4ea5-847c-74e6630afe23.png)

**Comment by p4535992** [comment]
Before the context menu was built from scratch, now it "leans" on the default foundry and system menu. I replicated the issue even with the deault character sheet, the problem should be inidirizzo to the foundryvtt project where the "ContextMenu" class is allocated

**Comment by GambetTV** [comment]
Ah, yeah. I see that now. Okay no problem!
