### ISSUE TITLE
[BUG] Max HP does not auto increment during level up

### ISSUE THREAD

**Issue by BrotherSharper** [sdenec/tidy5e-sheet#707]
*I am aware there is another issue with this, but since it has sadly spiraled out, I am trying to get proper steps to reproduce this and my own take on it.

**Module Version:** v0.8.24

**Describe the bug**
If a character has had the max HP configuration changed to something manual even once while tidy5e is turned on, henceforth the max HP will drop to zero if the field is left empty. Here's what happens with each setting and default settings.
All this has been tested using "Find the culprit" module while determining that it only happens with Tidy5e only.

I and others in the Japanese community have faced this and would like to provide genuine feedback in hopes to get this fixed. I am sorry if at any point whoever reads this would feel stressed or confronted, this is not my intention.

**Case A (default, no modules)**
New character: created with HP set to 0/0 and nothing inside the max HP configuration window. If a class is dropped, the max and current HP goes up accordingly.

Existing character: HP set to 10/10 due to previous level ups. If a class levels up, the HP is increased accordingly. I can manually change this by using the hp configuration window. If I decide I want to go back to automatic I delete the value inside the window and it goes back to what it would have been when calculated automatically.

**Case B (tidy5e, Allow Max Hp Override on the Character turned off)**
New character: created with HP set to 0/0 and nothing inside the max HP configuration window. If a class is dropped, the max and current HP goes up accordingly.

Existing character (never manually changed max HP): HP set to 10/10 due to previous level ups. If a class levels up, the HP is increased accordingly. I can manually change this by using the hp configuration window. If I decide I want to go back to automatic I delete the value inside the window and it is set to 0. **I believe this is a bug**.

Existing character (migrated from 0.8.14 tidy5e): HP set to 10/10 due to previous level ups and also set a manual value in the configuration window. If a class levels up, HP is not increased because it is using manual override but the current HP does increase. If the HP is deleted from the HP configuration window, the max HP is set to 0. If I try to level up from here it sill remains 0.
If I switch to the default sheet and do the same, it still remains at 0. **I believe this is a bug**.

**Case C (tidy5e, Allow Max Hp Override on the Character turned on)**
New character: created with HP set to 0/0 and nothing inside the max HP configuration window. If a class is dropped, the max and current HP goes up accordingly.

Existing character (never manually changed max HP): HP set to 10/10 due to previous level ups. If a class levels up, the HP is set to 0. I can manually change this by using the hp configuration window. If I decide I want to go back to automatic I delete the value inside the window and it is set to the automatically calculated value. **I believe that the HP going to 0 during level up is a bug**.

Existing character (migrated from 0.8.14 tidy5e): HP set to 10/10 due to previous level ups and also set a manual value in the configuration window. If a class levels up, HP is not increased because it is using manual override but the current HP does increase. If the HP is deleted from the HP configuration window, the max HP is set to the correct value. If I try to level up from here it does not change because it has saved the automatic value as the manual override. **I think this part is behaving accordingly**.

**To Reproduce**
As above.

**Expected behavior**
New character: should keep increasing HP automatically with their respective class levels.
Existing character (never used manual override): should keep increasing HP automatically with their respective class levels. However during migration all character max HP is set as manually overridden.
Existing character (manual override used): should be able to return back to automatic calculation. 

There seems to be something that causes tidy5e to drop the automatic HP calculation to 0. Unless this was an intended feature of tidy5e sheet I suspect this may be a bug.

Allow Max Hp Override on the Character only fixes the problem on existing characters that have previously used manual override, but newly created characters still face the bug of having HP set to 0 during automatic level up.
This would need the GM to switch in and out of settings which is kind of hard to do.

**Browser:**
foundry app (electron) 

**Foundry Version:** 
V10 build 291
**Game System:** 

**Additional context**
All other modules have been turned off.

**Comment by GambetTV** [comment]
I figured out the problem, I think. I'm not a coder, so I can't explain it whatsoever, but there seems to be some kind of weird issue with the "Lazy Hp and Exp" setting. I believe this setting is enabled by default. Disabling it completely fixed the issue for me, and my HP no longer went to 0. However, even stranger, when I re-enabled Lazy Hp and Exp, the problem was still gone. Not only was it gone, but it was gone for ALL of my worlds, without me having to disable/re-enable. I don't know what the hell to make of that, but there must be some kind of issue with this module when using it with worlds that existed prior to the 2.1.x DnD5e update. Disabling and re-enabling Lazy Hp and Exp seems to reboot it, and the problem has just flat out gone away for me.

**Comment by p4535992** [comment]
Add some logs and better code for manage this on 0.8.27 if the problem persist let me know it and disable th setting  "laxzy hp"
