### ISSUE TITLE
Labels always on

### ISSUE THREAD

**Issue by Kharmans** [sdenec/tidy5e-sheet#709]
The labels that appear when you keep the mouse pointer are appearing very fasta and when you move the mouse, they will instantly show other labels that the mouse go through. And sometimes the labels just stays forever on the screen, even if you change the window.

![image](https://user-images.githubusercontent.com/112586547/219879381-d74bfc55-62dc-48ea-a3ac-3145fbe53fe6.png)

And when you put the mouse pointer on the AC, it not show the AC details.

![image](https://user-images.githubusercontent.com/112586547/219879520-41ba1683-8540-49a6-a245-5b54f8e9c246.png)

**Comment by p4535992** [comment]
What module version are you using ?

**Comment by Kharmans** [comment]
Version 0.8.21. But I notice that there's a 0.8.25 version, but this version don't show in the Configuration and Setup from Foundry. The last version of the module there is 0.8.18.

![image](https://user-images.githubusercontent.com/112586547/219956590-29a6d8bb-f27f-4332-949e-347c2a55ee36.png)

**Comment by Kharmans** [comment]
Well, I manual update to 0.8.25 and the first problem are still there, but I can see the AC details now.

**Comment by GambetTV** [comment]
I will say that probably every update for the last half dozen updates or so I've had to delete this module and manually reinstall it to get the latest version. Simply clicking update on it does nothing.

**Comment by p4535992** [comment]
@Kharmans 
_The labels that appear when you keep the mouse pointer are appearing very fasta and when you move the mouse, they will instantly show other labels that the mouse go through. And sometimes the labels just stays forever on the screen, even if you change the window._

Sorry maybe it's me who don't understand the behavior seems to me the same as the default item sheet or am I wrong ?

**Comment by GambetTV** [comment]
I think this issue is fixed in the latest version. In previous versions the pop-up would come up almost instantly, and would stay up forever sometimes. I even saw it stay up after I closed the character sheet a few times. But in the latest version it takes half a second of mouse hovering or so to pop up, and goes away about half a second after moving the cursor away, which seems reasonable to me.
