### ISSUE TITLE
Support for narrow displays

### ISSUE THREAD

**Issue by acd-jake** [sdenec/tidy5e-sheet#71]
On very narrow displays - and when using the "Simple-Mobile" module - the range for the attributes is not high enough, so the value for Charisma disappears. 

Simply increasing the height for the css class ".tidy5e.sheet.actor .ability-scores" in line 963 of the file "tidy5e-sheet.css" to 373px would fix this.

This change would allow the character sheet to be displayed and used on a smaller tablet.

![2020-07-27 08_38_43-Foundry Virtual Tabletop • A Standalone Virtual Tabletop Application](https://user-images.githubusercontent.com/67855941/88511529-40cf2880-cfe5-11ea-9b17-187c27c91771.png)

**Comment by sdenec** [comment]
should look better now :)
