### ISSUE TITLE
Add item trading in right-click menu

### ISSUE THREAD

**Issue by The-Forge-Master** [sdenec/tidy5e-sheet#711]
It is currently only available in classic controls, which means it is unavailable if that is disabled. It should be in both that and right-click.

**Comment by p4535992** [comment]
Please try to give better informations-- like version of the modue , system ,ecc., i can "guess" you mean the "Let's trade" module integration... this is something already asked to the developer.

https://github.com/KageJittai/lets-trade-5e/issues/41

**Comment by p4535992** [comment]
should be fixed now
