### ISSUE TITLE
[BUG] Can't install (I think there is a case issue in source control)

### ISSUE THREAD

**Issue by gitscosh** [sdenec/tidy5e-sheet#715]
**Module Version:** v0.8.27

**Describe the bug**
Module won't install. It's looking for "scripts/app/tidy5e-hb-upcast-free-spell.js" but in source, it's named "scripts/app/tidy5e-hb-upcast-free-Spell.js" with a capital S and both linux and Github are case sensitive.

It was introduced in this commit: https://github.com/sdenec/tidy5e-sheet/commit/205e6f6b5ad279181f6820cf9bc1dbd0ee434d4f

Previous versions install just fine.

**Comment by p4535992** [comment]
try this https://github.com/sdenec/tidy5e-sheet/releases/download/0.8.28/module.json

**Comment by gitscosh** [comment]
That worked. Thanks! My Foundry install is saying I have 0.8.31 installed now.
