### ISSUE TITLE
Error When Trying to Install

### ISSUE THREAD

**Issue by kibaruzo** [sdenec/tidy5e-sheet#716]
Module Version: v0.8.18

![image](https://user-images.githubusercontent.com/121198870/220804027-978d7564-5a9e-4943-811e-9e7e988611a8.png)

**Describe the bug**
After I click on install for the module, I got the error message.

**To Reproduce**
1. Go to the Install Module browser
2. Click on Install
4. Error is shown

**Expected behavior**
Module to install with no errors

**Browser:**
Chrome 

**Foundry Version:** 
V10 Build 291

**Game System:** 

**Additional context**

**Comment by p4535992** [comment]
try this https://github.com/sdenec/tidy5e-sheet/releases/download/0.8.29/module.json

**Comment by kibaruzo** [comment]
I went back to reinstall and no errors. Thanks for the quick fix.
