### ISSUE TITLE
[BUG] 0.8.30 Level display bugs out.

### ISSUE THREAD

**Issue by GambetTV** [sdenec/tidy5e-sheet#717]
**Module Version:** v0.8.30

Level display bugs out in the latest version. 

![image](https://user-images.githubusercontent.com/72000497/220939361-8ac1ddd2-cc34-4592-80d2-7bde79edb085.png)

**Comment by GambetTV** [comment]
Went back and checked, the bug was introduced in 0.8.26. It works fine in 0.8.25.

**Comment by p4535992** [comment]
Should be fixed with 0.8.31

**Comment by GambetTV** [comment]
Fixed!
