### ISSUE TITLE
Request: Responsive format/ Simple Mobile support

### ISSUE THREAD

**Issue by shawndibble** [sdenec/tidy5e-sheet#72]
I would like to request that tidy5e be responsive or support simple mobile.

When using simple mobile:
on landscape, the top section is a fixed height and thus you can't really see anything inside the sheet.
on portrait, things are better, however the top section still gets cut off on the sides. The content is usable, but very smushed together or floats weirdly.

![Screenshot_20200730-104736](https://user-images.githubusercontent.com/1980293/88944941-fd79f180-d252-11ea-9960-ba3ab019b178.png)
![Screenshot_20200730-104703](https://user-images.githubusercontent.com/1980293/88945028-15ea0c00-d253-11ea-9e4b-f75f29db12f8.png)

**Comment by sdenec** [comment]
That's open for a while now. The sheet never was and most likely never will be developed with mobile support in mind. While I can understand that some people have the need to use foundry on mobile devices that is not something I will explicily support with this sheet. In my opinion there should be a sheet specifically crafted to suit mobile needs. I'm sorry.
