### ISSUE TITLE
[BUG] Features that consume resources cannot be manually edited

### ISSUE THREAD

**Issue by mcabel** [sdenec/tidy5e-sheet#720]
**Module Version:** v0.8.25
LOG:
[localhost-1677633885585.log](https://github.com/sdenec/tidy5e-sheet/files/10856147/localhost-1677633885585.log)

**Describe the bug**
Features that consume resources (example necrotic shroud, Divine Sense, etc.) can not be manually edited by the Dungeon Master, or in cases where they can be edited, they report having "0 uses available."

**To Reproduce**
1. Go to a paladin character sheet. 
2. Click on Features.
3. Scroll down to Active Abilities.
4. Click on Divine sense until you spend all your uses. (It was also tested with Aasimar necrotic Shroud, Healing hands, as well as Paladin "channel divinity")
5. Try to manually override the amount of uses. (it will not let you; or in some abilities it will let you with no immediate error)
6. Click on the ability which amount of uses was edited.
7. See error "No available uses remaining", even though you have 1/1.

**Expected behavior**
Tested on core, with no other modules: on the Features tab, one can manually edit the value of spent abilities. This is important for case players made a mistake, for example.

**Screenshots**

**Browser:**
 - 

**Foundry Version:** 
10 build 291
**Game System:** 
2.1.5
![Screenshot 2023-02-28 202248](https://user-images.githubusercontent.com/10392829/222026713-075e7f79-b918-488f-a5b3-f529c17d0bac.png)
![Screenshot 2023-02-28 211946](https://user-images.githubusercontent.com/10392829/222028452-da288cdb-f047-4321-bacd-4990b4de3132.png)

**Additional context**
Add any other context (like other modules installed) about the problem here.

Ways I found to bypass this behavior:

+Entering to the ability and editing the value of the uses internally.
+Disabling tidy 5 sheets :(
+Installing "Link item Resource" module (although only works if the resource is edited on the attributes tab)

**Comment by p4535992** [comment]
Cannot replicate this behaviour
