### ISSUE TITLE
[BUG] Tidy5e-sheet not operating

### ISSUE THREAD

**Issue by mikaelkhristov** [sdenec/tidy5e-sheet#721]
**Module Version:** v0.8.33

**Before open any issue**

1) Enable the module setting _"Enable debugging"_
2) Click F12 go to the _console_ tab 
3) make the test you want and replicate the error
4) Go to the tab console open on point 2) and just right click and click 'Save as' and 'Save' or send a screenshot of the exception on the console.
5) Attach the text file on the github issue with all the logs related tot he module, or send a screenshot of the messages on the console.

[localhost-1678035057752.log](https://github.com/sdenec/tidy5e-sheet/files/10892341/localhost-1678035057752.log)

**Describe the bug**
Tidy5e-sheet not appearing as an option for character sheets nor in the "manage modules" settings.

**To Reproduce**
1. Install the module, following the installation instructions.
2. Launch any world
3. Open any character sheet
4. Click on "Sheet" option
5. Only option available is Default 5e Character Sheet
6. Open "Manage Modules" from the Options tab
7. Tidy5e-sheet does not appear

**Expected behavior**
I expect tidy5e-sheet to appear in either the "Sheet" option from character sheets or in the "Manage Modules" options

**Screenshots**
![image](https://user-images.githubusercontent.com/51464761/222974609-46d25eac-13b6-46e0-886a-17f713d5ce43.png)
![image](https://user-images.githubusercontent.com/51464761/222974635-a49c273c-8391-48b1-af40-bd179b710dd8.png)

**Browser:**
 - Foundry VTT executable

**Foundry Version:** 
Version 10 - Build 291

**Game System:** 
DnD5e - Fifth Edition System ver. 2.0.3

**Additional context**
Tidysheet has been working fine until today, there have been no updates installed to either this module, other modules, the system, or Foundry. I have done nothing with the root files since I last launched Foundry. I have run Foundry normally and as Administrator, I have checked for updates, I have uninstalled and reinstalled Foundry, the DnD5e system and the Tidysheet Module. I have tried this with my ongoing worlds and with a fresh world. I HAVE TURNED THE COMPUTER OFF AND ON AGAIN. It is STILL not working and I have absolutely no ideas how this has happened or how to fix it. Please help.

**Comment by p4535992** [comment]
For system 2.0.3 you must used this json reference :  https://github.com/sdenec/tidy5e-sheet/releases/download/0.7.6/module.json

Unistall and reinstall the module with this json : https://github.com/sdenec/tidy5e-sheet/releases/download/0.7.6/module.json

**Comment by mikaelkhristov** [comment]
> For system 2.0.3 you must use this json reference : https://github.com/sdenec/tidy5e-sheet/releases/download/0.7.6/module.json
> 
> Uninstall and reinstall the module with this json : https://github.com/sdenec/tidy5e-sheet/releases/download/0.7.6/module.json

Wodnerful, that worked. Thank you so much.
