### ISSUE TITLE
Width of origin summary and PC/NPC sheets

### ISSUE THREAD

**Issue by gurgugnao** [sdenec/tidy5e-sheet#722]
Hello, since the introduction of origin summary configuration, the width of each field does not adapt with the width of the PC/NPC sheet.
In PC sheets, race and alignment fields have a limited number of letters (20) after which the field reach its maximum width and the text is always abbreviated with "..." although you modify the width of the PC sheet (see examples 1 below).
On the other hand, NPC sheets have the same problem (always abbreviate) with source field whereas they never abbreviate race and alignment fields, thus obliging to expand a lot the sheet if the text introduced in these 2 fields is long (see examples 2 below).
I think the correct functioning is to abbreviate all these field depending on the width of the sheets.
Thanks!

Example 1, PC sheet.
 Race and alignment field are at their limit (20 letters). PC sheet is the tightest.
![Origin (1)](https://user-images.githubusercontent.com/122090327/223076724-44ae0cfa-af83-4753-b91e-d92d0b56e335.JPG)
 Race and alignment field are abbreviated (23 letters). PC sheet is the tightest.
![Origin (3)](https://user-images.githubusercontent.com/122090327/223079750-526c9bd1-8d6a-4ef0-b16d-1b4503c35b2a.JPG)
Race and alignment field are still abbreviated (23 letters) even if the PC sheet is widened.
![Origin (4)](https://user-images.githubusercontent.com/122090327/223076757-10842047-8e02-43e2-b89d-cee5ff79fa46.JPG)

Example 2, NPC sheet.
Source field is abbreviated. NPC sheet is the tightest.
![Origin (5)](https://user-images.githubusercontent.com/122090327/223083188-bc6d8777-1d79-4846-9f71-a6774529544d.JPG)
Source field is still abbreviated even if NPC sheet is widened.
![Origin (6)](https://user-images.githubusercontent.com/122090327/223083281-f366e6cd-4b55-4ddd-b2c9-6f6fbf2726f4.JPG)
Alignment field is not abbreviated even if NPC sheet is the tightest.
![Origin (7)](https://user-images.githubusercontent.com/122090327/223083295-557086cc-d741-447e-a04c-3f9caac9b450.JPG)
Source field is still abbreviated even if NPC sheet is widened.
![Origin (8)](https://user-images.githubusercontent.com/122090327/223083310-4b92b70d-3af2-49b7-aa7c-173caf97c6f8.JPG)

**Comment by p4535992** [comment]
Made some css tweak on 0.8.36, but still need a css exeprt for this...
