### ISSUE TITLE
[BUG] Issue with 5e - Custom Abilities & Skills

### ISSUE THREAD

**Issue by OxTailSafu** [sdenec/tidy5e-sheet#723]
**Module Version:** 

D&D 5e: v2.1.5

Tidy5e-sheet: v0.8.35

5e - Custom Abilities & Skills: v1.1.7

**Describe the bug**
Going to reference this previous issue here where a similar occurrence is happening.

https://github.com/sdenec/tidy5e-sheet/issues/662

It looks as though the most recent update may have misaligned the saving throw gear icon and fillable space.

**To Reproduce**
1. Activate both modules

There doesn't appear to be any sort of error on the console.

**Expected behavior**
For the markers to be aligned properly.

**Screenshots**
![image](https://user-images.githubusercontent.com/123988485/224135761-7cdba5f6-de2f-4112-ad14-78c5d970e269.png)

With both modules activated.

![image](https://user-images.githubusercontent.com/123988485/224136042-4550a399-8836-42e6-a0f2-8c48b6fac59a.png)

With only Tidysheet activated.

**Browser:**
Google Chrome

**Foundry Version:** 

Version 10, Build 291

**Game System:** 

D&D 5e: v2.1.5

**Comment by mmacgibbon** [comment]
i mentioned this in another ticket. its two very small CSS changes.

**Comment by mmacgibbon** [comment]
in fact its been fixed by custom abilities.  they put it to the top.  (i like it better that way). You can prob close this ticket.

![image](https://user-images.githubusercontent.com/2736379/224506221-7f48bbdf-32b7-486f-8e98-f2db8cb9dd0c.png)

**Comment by OxTailSafu** [comment]
Yup it definitely has been fixed, thanks for that! I didn't realize that a ticket was submitted on there module as well.
