### ISSUE TITLE
Multiclass Spellbook Filter

### ISSUE THREAD

**Issue by setite80** [sdenec/tidy5e-sheet#725]
Hello sorry for bothering you. My players dont seem to have the dropdown menu that sorts spells for different classes. i have the menu as a dm. i populated data for all spells they have in their sheets and chose spells classes but still no dropdown menu (in their side). also they dont have the option to choose spells class when they edit their spells in their sheets.

**Comment by p4535992** [comment]
Did you activate the module setting ?

**Comment by setite80** [comment]
> Did you activate the module setting ? By default is set to false

if you mean the box in gm options tab yes its active

**Comment by p4535992** [comment]
Should be fixed on 0.8.36, now the setting is on the player side for let the single user customize this.
