### ISSUE TITLE
Referencing #398 Attributes Tab Favorites for Transformed Actors

### ISSUE THREAD

**Issue by KonteiKeisei** [sdenec/tidy5e-sheet#726]
In Issue #368  it was mentioned that NPC favorites was implemented, however I cannot find a way to enable this, or mark items as favorite so they are all on the main attributes page upon transformation.

**Comment by p4535992** [comment]
It's been removed a while ago, because it was confusing and because it was agreed that the [Character Actions 5e](https://github.com/ElfFriend-DnD/foundryvtt-dnd5eCharacterActions) form was a much better option.
