### ISSUE TITLE
[BUG] Feature items' `Limited Uses` cannot be updated from NPC/PC sheet, only from the Feature items' details tab

### ISSUE THREAD

**Issue by skyhammer1995** [sdenec/tidy5e-sheet#729]
**Module Version:** v0.8.25

**Before open any issue**

1) Enable the module setting _"Enable debugging"_
2) Click F12 go to the _console_ tab 
3) make the test you want and replicate the error
4) Go to the tab console open on point 2) and just right click and click 'Save as' and 'Save' or send a screenshot of the exception on the console.
5) Attach the text file on the github issue with all the logs related to  the module, or send a screenshot of the messages on the console.

**Log**
[localhost-1678559832781.log](https://github.com/sdenec/tidy5e-sheet/files/10949184/localhost-1678559832781.log)
When running the `test` of updating these items, no logs were observed when making changes to a `Feature` item's `Uses`

**Describe the bug**
When updating a Feature's `Uses` from a PC/NPC sheet, it does not update the Item card, and will not change after re-opening the character sheet. E.g. Update `Font of Magic` from 2/2 to 0/2; close sheet; re-open sheet; see that `Font of Magic` uses still show 2/2.

**To Reproduce**
1. Go to any character sheet
2. Click on `Features` tab
3. Add a Feature/copy over feature
4. Ensure that feature has `Limited Uses` (any number of any number, charges/Day/short rest/etc.)
5. Update number of used `Uses` 
6. Close and re-open sheet --OR-- Edit item and navigate to details tab, observe no change in `Limited Uses`
7. Observe no change to number of available uses 

**Expected behavior**
I and my players should be able to update available uses of a Feature from the character sheet, without having to open the item->details tab, and updating there.

**Screenshots**

![image](https://user-images.githubusercontent.com/39307121/224505699-976bed8c-6eaf-4fc6-8229-3b5965535c88.png)

![image](https://user-images.githubusercontent.com/39307121/224505702-dcd704e4-eecf-448b-a6f3-f50f11197e73.png)

**Browser:**
 - Agnostic, but observed on Chrome, Firefox, and the Electron Client

**Foundry Version:** 
V10 Build 291
**Game System:** 
DND5e 2.1.5
**Additional context**
This problem seems to only happen with `Features` under the `Uses` field on the sheet. When updating an item in Inventory, the number of `Limited Uses` correctly updates the Item. I have shown pictures of the fields I'm meaning above with the `Dispel Magic` being an example of where the value will not update, whereas the Item `Shrouds Strike` can have its `Charges` field updated and correctly reflected on the item sheet.

**Comment by p4535992** [comment]
@skyhammer1995 cannot replicate this issue on my actors, can you pass to me the json actor ?

**Comment by skyhammer1995** [comment]
@p4535992 sure, but could you please provide instructions on how to do so?

**Comment by p4535992** [comment]
@skyhammer1995 
1) Right Click on the actor on the sidebar (is a core feature)
2) Click on  Export to json
3) Rename the file "xxx.json" in "xxx.txt"
4) Drag and drop the "xx.txt" file here

**Comment by skyhammer1995** [comment]
@p4535992  Let me know if there's anything else I can provide, thanks.
[fvtt-Actor-fredrick-von-glen.txt](https://github.com/sdenec/tidy5e-sheet/files/11013224/fvtt-Actor-fredrick-von-glen.txt)

**Comment by 9ryex5** [comment]
I was having this problem after updating this module to 0.8.35, clearing cache solved it.

**Comment by fylson** [comment]
I got the same issue, event on a freshly created testworld with only one actor and only this module active. Its not only at limited uses, it evens seems on item counts. 

I change the count / uses and after reopen the sheet, the old count is back. Even if i open the item/feat after the change, it is still the old.


How can i clear the cache?

**Comment by skyhammer1995** [comment]
Well, @fylson's comment made me realize there are newer releases, and my instance wasn't updating. Uninstalled and re-installed. Everything seems to be working now.
