### ISSUE TITLE
[BUG] Issue with feature usage resets in 5e.

### ISSUE THREAD

**Issue by kurikyoma** [sdenec/tidy5e-sheet#733]
**Module Version:** v0.0.0

**Before open any issue**

This is all I get from the console:

Foundry VTT | Rendering Tidy5eSheet [foundry.js:5099:15](https://127.0.0.1:30000/scripts/foundry.js)
Foundry VTT | Registered callback for dnd5e.getActiveEffectContextOptions hook [foundry.js:610:13](https://127.0.0.1:30000/scripts/foundry.js)
Foundry VTT | Registered callback for dnd5e.getItemContextOptions hook [foundry.js:610:13](https://127.0.0.1:30000/scripts/foundry.js)
Foundry VTT | Registered callback for dnd5e.getItemAdvancementContext hook

**Describe the bug**
The issue is abilities don't keep the changed values properly. In 5e, when I change the number of "Lay on Hands" points my paladin has, it resets when I reopen the page. However, when I click to use the ability and leave the checkbox checked that says "Consume available usage?" checked then the ability does decrement.

**To Reproduce**
1. Open character sheet.
2. Find a Feature that says you have X/Y usages.
3. Change X manually by clicking on the numerator.
4. Close the sheet.
5. Reopen it.
6. Observe that the value has not changed.

**Expected behavior**
The changed values will persist after I close the character sheet.

**Screenshots**
I've attached a short video demonstrating the issue.

**Browser:**
Firefox
 - 
[video_of_issue.zip](https://github.com/sdenec/tidy5e-sheet/files/10998014/video_of_issue.zip)

**Foundry Version:** 
Version 10 - Build 291

**Game System:** 
DnD 5e - Fifth Edition System

**Additional context**
Monk's Combat Details
Monk's Enhanced Journal
lib-wrapper

Just disabling Tidy5eSheet fixes the issue.

**Comment by p4535992** [comment]
@kurikyoma cannot replicate on my actors,, can you pass to me the json actor ?

**Comment by kurikyoma** [comment]
I managed to resolve this issue by reinstalling the add-on, so I can no longer recreate.
