### ISSUE TITLE
[BUG] Player Name not saving

### ISSUE THREAD

**Issue by 9ryex5** [sdenec/tidy5e-sheet#735]
**Module Version:** v0.8.19

The player name doesn't save
![image](https://user-images.githubusercontent.com/43207603/226651951-60d96f58-f480-407e-9fd2-3d9ab5b1640d.png)
![image](https://user-images.githubusercontent.com/43207603/226652100-d384521c-99c5-46b8-b510-1e79783dfbf5.png)

**Comment by p4535992** [comment]
uninstall the module and use this json: https://github.com/sdenec/tidy5e-sheet/releases/latest/download/module.json

**Comment by 9ryex5** [comment]
It is indeed fixed in this version. Thanks
