### ISSUE TITLE
Vehicle sheet support

### ISSUE THREAD

**Issue by LuxuriaU** [sdenec/tidy5e-sheet#74]
Hi, love this module, adds a lot more functionality to the sheets, and is just a whole lot more aesthetically pleasing with its minimalist design. Do you plan on bringing this module to the new vehicle sheets? They are rather handy, but it would be so much easier to use provided this module was compatible. 

Just a few suggestions/requests (mostly requests) if and when you:

- more than one place for speed or easily changeable speed, vehicles usually have more than one, and you seem to add to fit needed functionality.

- More obvious layout for stations, the current equipment page is rather lackluster for the case of crew stations, maybe they could have their own tab, so that they can be more opened, and have kinda dedicated mini-sheets within that tab.

At the end of the day whatever you do will be grand, hope you can get to this sheet one day.

**Comment by sdenec** [comment]
It has been a very long time and I'm sorry that I haven't replied to you sooner. I honestly had no intention to bother with the vehicle sheet but finally have started adapting it to the rest of the sheet. So you can look forward to see a "tidy" vehicle sheet in the near future :)

**Comment by sdenec** [comment]
Out of curiositiy - and I'm not sure if I can actually do this - what would a crew entry contain? I'm not familiar with vehicle rules and needed data. For speed there is a text field where you can enter text freely like "60 ft fly / 40 ft swim" for an airship or something fancy - vehicles don't seem to have support for the new speed settings (yet)

**Comment by akrigline** [comment]
Here's a sample vehicle for you from [Ghosts of Saltmarsh](https://www.dndbeyond.com/vehicles/keelboat) (I think this is visible to all though).

Poking around in the "Crew" area of Cargo & Crew, it looks like Crew is just a text field and a number. I suspect it can play into things like the "Actions" on the main tab, where Actions Threshold is the basis for this kind of rule:

> On its turn, the keelboat can take 2 actions, choosing from the options below. It can take only 1 action if it has only one crew. It can't take these actions if it has no crew.


> vehicles don't seem to have support for the new speed settings (yet)

Good find, [opened an issue for this](https://gitlab.com/foundrynet/dnd5e/-/issues/899)

**Comment by akrigline** [comment]
FYI @sdenec the changes to the 5e system for vehicle speed configuration have been merged, next release will probably change things. Would recommend setting your vehicle sheet up for future compatibility if you plan on releasing soon.

**Comment by sdenec** [comment]
Vehicle sheets are finally supported by tidy5e with the latest update!
