### ISSUE TITLE
[Feature Request] OneDnD exhaustion

### ISSUE THREAD

**Issue by Orionox** [sdenec/tidy5e-sheet#740]
wizards of the coast awhile ago released a revamp of the exhaustion system where instead of the 5 levels we currently have, there are 10 levels and each level reduced all rolls by +1 and all spell dc by +1. it would be cool if we got that as an option.

**Comment by p4535992** [comment]
I'll close the issue because you already asked this https://github.com/sdenec/tidy5e-sheet/issues/596.

it is in my todo list , but i'll probably try to open a pr to "DFreds Convenient Effects" before integrate this on the sheet.

**Comment by Orionox** [comment]
Oops! Sorry about that
