### ISSUE TITLE
[BUG] Incorrect Calculation on PC Sheets

### ISSUE THREAD

**Issue by KellethDregar** [sdenec/tidy5e-sheet#741]
**Module Version:** v0.0.0

**Before open any issue**

1) Enable the module setting _"Enable debugging"_
2) Click F12 go to the _console_ tab 
3) make the test you want and replicate the error
4) Go to the tab console open on point 2) and just right click and click 'Save as' and 'Save' or send a screenshot of the exception on the console.
5) Attach the text file on the github issue with all the logs related tot he module, or send a screenshot of the messages on the console.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Browser:**
 - 

**Foundry Version:** 

**Game System:** 

**Additional context**
Add any other context (like other modules installed) about the problem here.

**Comment by p4535992** [comment]
Incorrect Calculation of what ? I'll close the ticket . You can reopen with more info about the issue.

**Comment by KellethDregar** [comment]
Sorry not sure why this also got posted? I only made one post and it was https://github.com/sdenec/tidy5e-sheet/issues/742 (you can check creation time) and for some reason it created that one and an empty one.
