### ISSUE TITLE
[BUG] Incorrect Currency Calculation on PC Sheets

### ISSUE THREAD

**Issue by KellethDregar** [sdenec/tidy5e-sheet#742]
**Module Version:** v0.8.39

**Describe the bug**
Using the lazy money module toggle, when calculating the amount added or subtracted the final value will usually result in a zero. Sometimes when adding if the added amount is higher than the current amount it will simply replace the current amount with the added amount (5+50=50). It's notable it works fine on NPC sheets just not PC sheets.

**To Reproduce**
1. Select a Coin type
2. Click it and replace the value with +X or -X and hit enter
3. Value will either result in 0 or add

**Expected behavior**
The value will be increased or decreased to a new value.

**Screenshots**
![image](https://user-images.githubusercontent.com/79947702/229427740-f0c14db9-a110-4385-b068-4aebb36d8c1b.png)
![image](https://user-images.githubusercontent.com/79947702/229427764-9d9ae5d1-94d5-4e97-9636-2d74201d4397.png)
![image](https://user-images.githubusercontent.com/79947702/229427774-929b4063-be8e-435e-837b-63ff50ca7a8a.png)
![image](https://user-images.githubusercontent.com/79947702/229427793-96ad45a4-00cc-4fc8-8fe9-a2d13f378ab7.png)

**Browser:**
 -Chrome OS

**Foundry Version:** 
10.291

**Game System:** 
2.1.5

**Additional context**
I am also using lazymoney. I'm unsure if this is an issue on that module or this module but it occurs when only one is active too.

**Comment by KellethDregar** [comment]
Still seems to be overriding the amount with the newly entered amount instead of the calculation result.

![image](https://user-images.githubusercontent.com/79947702/230802527-d8a0502d-d753-4026-b805-02ce5f1fea5a.png)
![image](https://user-images.githubusercontent.com/79947702/230802552-206a16b9-60b5-4a86-ba60-0a45916569aa.png)
![image](https://user-images.githubusercontent.com/79947702/230802556-db1db858-95be-4fd8-b732-26dc6b808a60.png)

**Comment by p4535992** [comment]
It's working on my actors, try to clean up the cache of the browser, if the isue still persist enable the debug and pass to me the web console logs.

**Comment by KellethDregar** [comment]
Can confirm its working after that!
