### ISSUE TITLE
[BUG] Updating item quantity in character sheet not working

### ISSUE THREAD

**Issue by F1rewind** [sdenec/tidy5e-sheet#744]
How to reproduce:
1. Open a character sheet that has some items in the inventory
2. Click in the parentheses next to the item name and change the value from 1 to anything else
3. Update the character sheet (close and reopen)
4. The item is still at 1 in the parentheses and in the "quantity" field if the item is edited. Players will confirm that it has stayed at 1 for them too.

**Note** that editing the item and changing the value in the "Quantity" field directly will successfully update the number both there and in the parentheses, in the character sheet inventory.

**Comment by p4535992** [comment]
what version of the module are you using ?

**Comment by p4535992** [comment]
uninstall the module and install this https://github.com/sdenec/tidy5e-sheet/releases/download/0.8.39/module.json

**Comment by cs96and** [comment]
> uninstall the module and install this https://github.com/sdenec/tidy5e-sheet/releases/download/0.8.39/module.json

Out of interest, why is foundry no longer offering the latest version?  Are there plans to get it back up to date, or is manually installing going to be the only way to get the latest version going forward?

**Comment by p4535992** [comment]
it's not foundry it's just that sdenec who is the owner of the module should make a new version on the foundryvtt site for every github release I generate and I can't bother him all the time... as a trick I make the module json point from version 0.8.35 to the latest github release so that the update button on foundry downloads the latest github release.

**Comment by cs96and** [comment]
You can ask the Foundry team to transfer the module over to you.

**Comment by F1rewind** [comment]
Just cause I noticed this is marked "probably fixed", updating to 0.8.39 indeed fixed the item update bug for me
