### ISSUE TITLE
Request: allow dice to be used in the initiative mod field

### ISSUE THREAD

**Issue by kgrnt** [sdenec/tidy5e-sheet#75]
One of my players has a magic item that gives them +1d10 to their initiative rolls. We'd love the ability to automate that.

**Comment by sdenec** [comment]
Hi, the initiative mod input field is from the default dnd5e core sheet and does not support dice rolls as far as I know. Maybe you could set up your item with an initiative bonus via the "dynamic effects" module. I tried it and technically it works but there seems to be a little problem with rerolling the bonus die. Right now only the first roll will generate a random number every roll after that will take this bonus result. That's propably something for @tposney to work out though.

**Comment by kgrnt** [comment]
Aha, thanks for the clarification! I'll take a loot at dynamic effects and see if we can figure it out.
