### ISSUE TITLE
[BUG] Cannot roll skill checks from either Player or NPC sheet

### ISSUE THREAD

**Issue by tnarv** [sdenec/tidy5e-sheet#752]
**Module Version:** v0.8.41

**Describe the bug**
Clicking on a skill in the character sheet doesn't roll the associated skill. 

**To Reproduce**

1. Open any actor's sheet that is using the Tidy 5e sheet
     1a. A warning appears in the console about deprecated use of attributes.
3. Click on any skill.
4. Nothing happens on the client.
5. Error appears in console (see image below) that indicates the culprit is Tidy5e Sheets

**Expected behavior**
Clicking on a skill in the character sheet does roll the associated skill. 

**Screenshots**

![image](https://github.com/sdenec/tidy5e-sheet/assets/75012229/5db132a1-2f8d-4bff-8112-c42e813b08e4)

**Browser:**
Any 

**Foundry Version:** 
version 10 build 291

**Game System:** 
DnD5e - Fifth Edition System v2.2.1

**Additional context**
Judging by the warning when opening the character sheet and the fact this only started occurring after installing v2.2.1 of the DnD 5e system, it seems the error is likely caused by a change in the way abilities are stored in DnD 5e's newest release.

**Comment by kiligir** [comment]
Same here, though my specific error is:

```javascript
Uncaught TypeError: event.currentTarget.closest(...) is null
[Detected 1 package: system:dnd5e]
    _onRollSkillCheck base-sheet.mjs:1355
    jQuery 2
base-sheet.mjs:1355:38
    _onRollSkillCheck base-sheet.mjs:1355
    jQuery 2
```

**Comment by tnarv** [comment]
Similar console errors appear when trying to configure a skill or cycle its proficiency level.

Making the following change to the list element for a skill fixes the issue.

Change this:

`<li class="skill" data-skill="acr">...</li>`

to this

`<li class="skill **proficiency-row** proficient" **data-property="skills"** data-**key**="acr">...</li>`

Looks like the base sheet is now looking for `data-key` instead of `data-skill` when attempting to roll and attempting to configure a skill. That change fixes those two issues.

Cycling the proficiency is looking for the closest list item with the class `proficiency-row` in order to find the element with the current level of proficiency. This should be the list item for this skill but since its not set, it errors out attempting to querySelector on a null object.

Don't know if `data-property` is necessary. Didn't seem to be when I was messing with it but I'm very much a novice at this stuff and it was included in the base sheet from the system.

No idea if simply adding those missing things is the best way to handle it but figured the information was nonetheless (possibly) useful.

**Comment by TyrasNistru** [comment]
Looks like some fields changed on the latest version of the DnD 5e system. These problems started to happen when I updated the system.

**Comment by Yofukasi** [comment]
Been having this Issue too, temporarily bypassed it by using Token Action Hud 5e, thought still can't edit proficiencies and such, but still able to roll skill checks.

**Comment by DiceAndEasy** [comment]
I'm also having this issue.

**Comment by marcelbrode** [comment]
> Similar console errors appear when trying to configure a skill or cycle its proficiency level.
> 
> Making the following change to the list element for a skill fixes the issue.
> 
> Change this:
> 
> `<li class="skill" data-skill="acr">...</li>`
> 
> to this
> 
> `<li class="skill **proficiency-row** proficient" **data-property="skills"** data-**key**="acr">...</li>`
> 
> Looks like the base sheet is now looking for `data-key` instead of `data-skill` when attempting to roll and attempting to configure a skill. That change fixes those two issues.
> 
> Cycling the proficiency is looking for the closest list item with the class `proficiency-row` in order to find the element with the current level of proficiency. This should be the list item for this skill but since its not set, it errors out attempting to querySelector on a null object.
> 
> Don't know if `data-property` is necessary. Didn't seem to be when I was messing with it but I'm very much a novice at this stuff and it was included in the base sheet from the system.
> 
> No idea if simply adding those missing things is the best way to handle it but figured the information was nonetheless (possibly) useful.

Couldn't you do a pull request for this? Would be great to see this issue corrected early!

**Comment by friction1** [comment]
I have this issue too 
<img width="1070" alt="Screenshot 2023-05-27 at 8 00 15 PM" src="https://github.com/sdenec/tidy5e-sheet/assets/11384891/7c56a46d-9499-4b77-9268-e51c5ae7b21b">

**Comment by friction1** [comment]
> Similar console errors appear when trying to configure a skill or cycle its proficiency level.
> 
> Making the following change to the list element for a skill fixes the issue.
> 
> Change this:
> 
> `<li class="skill" data-skill="acr">...</li>`
> 
> to this
> 
> `<li class="skill **proficiency-row** proficient" **data-property="skills"** data-**key**="acr">...</li>`
> 
> Looks like the base sheet is now looking for `data-key` instead of `data-skill` when attempting to roll and attempting to configure a skill. That change fixes those two issues.
> 
> Cycling the proficiency is looking for the closest list item with the class `proficiency-row` in order to find the element with the current level of proficiency. This should be the list item for this skill but since its not set, it errors out attempting to querySelector on a null object.
> 
> Don't know if `data-property` is necessary. Didn't seem to be when I was messing with it but I'm very much a novice at this stuff and it was included in the base sheet from the system.
> 
> No idea if simply adding those missing things is the best way to handle it but figured the information was nonetheless (possibly) useful.

What files do you need to change this in?

**Comment by MsVella** [comment]
Not sure if this will help but I'm also having this issue with these errors on trying to roll skills or modify proficiencies respectively:
![Bug3](https://github.com/sdenec/tidy5e-sheet/assets/88259742/a6c125ea-b1fa-485b-b9a0-955ba6a5cfe8)

**Comment by SirAron111** [comment]
Yep, happened to me too, can't even set skills to be proficient anymore and the like.

**Comment by SugarSheikh** [comment]
Having the same issue, using Forge VTT (Foundry ver. 10.291) for D&D 5e (ver. 2.2.1) 
Do you know if there is a fix in the works?

![image](https://github.com/sdenec/tidy5e-sheet/assets/71370353/8eaf1b54-89b7-42a3-9f56-eb7802290390)

**Comment by marcelbrode** [comment]
> Having the same issue, using Forge VTT (Foundry ver. 10.291) for D&D 5e (ver. 2.2.1) Do you know if there is a fix in the works?
> 
> EDIT: I'll add in that i'm also using the [Action Pack module](https://foundryvtt.com/packages/action-pack) and rolling is fine through that. Not sure if that information helps 👍
> 
> ![image](https://user-images.githubusercontent.com/71370353/241763670-8eaf1b54-89b7-42a3-9f56-eb7802290390.png)

The "Quick fix" is just to not use tidy5e. Guess we have to wait until they release an update

**Comment by Kharmans** [comment]
Same here. It's not possible even add proficience.

![image](https://github.com/sdenec/tidy5e-sheet/assets/112586547/e123dffb-9f02-4664-aa4f-2025aa351c28)

**Comment by tposney** [comment]
I've had a quick play (and this is me just pattern matching dnd5e and tidy5e) if you change line 536 of tidy5e-sheet.html to
```
<li class="skill {{#if skill.value}}proficient{{/if}}" data-skill="{{s}}" data-key="{{s}}">
```
instead of 
```
<li class="skill {{#if skill.value}}proficient{{/if}}" data-skill="{{s}}">
```
then skill rolls work again.

**Comment by Kharmans** [comment]
@tposney there's no line 536 on tidy5e-sheet.html. It ends in line 501.

![image](https://github.com/sdenec/tidy5e-sheet/assets/112586547/6a0a2f66-ceaf-4023-b404-fce6af296740)

**Comment by chrisk123999** [comment]
Should be line 316 in tidy5e-sheet.html and line 301 in tidy5e-npc.html

**Comment by tposney** [comment]
I hate having fat fingers - yes line 316 and I did not check the npc sheet but 301 looks good.

**Comment by Kharmans** [comment]
Yeah, the lines 316 and 301 checks out. I change and works. Now is just find the lines that add the proficiency and it's good to go!

**Comment by marcelbrode** [comment]
> Yeah, the lines 316 and 301 checks out. I change and works. Now is just find the lines that add the proficiency and it's good to go!

Can you private a Pull Request for that? Maybe that speed it up :)

**Comment by Kharmans** [comment]
> Can you private a Pull Request for that? Maybe that speed it up :)

I have no idea what are you talking about. I'm not a dev, I'm here just to see if anyone found any solutions. Sorry =/

**Comment by marcelbrode** [comment]
> > Can you private a Pull Request for that? Maybe that speed it up :)
> 
> I have no idea what are you talking about. I'm not a dev, I'm here just to see if anyone found any solutions. Sorry =/

My Bad. A short explaination of what I meant: Github is there for people to check repositories out (= download them), like the exact code the devs use in most cases. And the beautify of Github is that you as an external guy could fix it and upload the changes into something called a "Pull Request" or short PR. Then the owners of the project repository can review it (see the link I posted) and say "Yup. That's nice, merge into our product".

But if you're not really into that, which is of course fine, it would be great if someone else could do it to speed up the fix release!

My Question would be: Is the link of the release everything necessary for the fix? Then we already have our fix-PR :D

**Comment by marcelbrode** [comment]
https://github.com/sdenec/tidy5e-sheet/pull/756

This got merged, so this is issue is probably closable. Let's hope for the next update

**Comment by KonteiKeisei** [comment]
> I've had a quick play (and this is me just pattern matching dnd5e and tidy5e) if you change line 536 of tidy5e-sheet.html to
> 
> ```
> <li class="skill {{#if skill.value}}proficient{{/if}}" data-skill="{{s}}" data-key="{{s}}">
> ```
> 
> instead of
> 
> ```
> <li class="skill {{#if skill.value}}proficient{{/if}}" data-skill="{{s}}">
> ```
> 
> then skill rolls work again.
> 
> I would guess there are other places where the same change is needed.

Would the fix for proficiency toggling start here:

<li class="ability {{#if ability.proficient}}proficient{{/if}}" data-ability="{{id}}">

Line 262 of tidy5e-sheet.html

**Comment by whitemage12380** [comment]
Hello! It looks like a lovely PR got issued and merged 3 days ago. Does there still have to be some testing for this issue to be closed? Would love to a release soon; Most of my players disabled TidySheet until this can be resolved.

**Comment by marcelbrode** [comment]
The mentioned issue seems fixed!
