### ISSUE TITLE
[BUG] Compatibility with DnD 5e System 2.2

### ISSUE THREAD

**Issue by TyrasNistru** [sdenec/tidy5e-sheet#753]
**Module Version:** v0.8.41

**Describe the bug**
The skill rolls doesn't work due to the DnD5e System update to v2.2.x

**To Reproduce**
Update DnD5e System to 2.2.x
Open a sheet
Click on any Skill

**Expected behavior**
To open the window to roll the skill

**Browser:**
Any

**Foundry Version:** 
V10 b291

**Game System:** 
DnD5e 2.2.x

**Additional context**
Add any other context (like other modules installed) about the problem here.
[localhost-1685200078701.log](https://github.com/sdenec/tidy5e-sheet/files/11582294/localhost-1685200078701.log)

**Comment by TyrasNistru** [comment]
Duplicated, sorry.

**Comment by geoidesic** [comment]
I updated modules yesterday and this problem has not gone away.
