### ISSUE TITLE
I can't add in attacks properly because they all default to 'feats'

### ISSUE THREAD

**Issue by PupperooX** [sdenec/tidy5e-sheet#76]
![image](https://user-images.githubusercontent.com/67825695/90134553-40ff5000-dd69-11ea-9a4d-0e00593aad81.png)
![image](https://user-images.githubusercontent.com/67825695/90134637-5d9b8800-dd69-11ea-8357-ae3fc1e07e99.png)
![image](https://user-images.githubusercontent.com/67825695/90134792-9e939c80-dd69-11ea-9b37-9825de3306a7.png)

**Comment by PupperooX** [comment]
![image](https://user-images.githubusercontent.com/67825695/90134928-cdaa0e00-dd69-11ea-9921-63d12629ee20.png)
The regular sheet allows the addition of feats and attacks

**Comment by sdenec** [comment]
I reverted attacks back to be listed in its seperate category. So adding attacks directly from the sheet should be possible again!
