### ISSUE TITLE
[Maybe bug] GM cannot edit fields if locked.

### ISSUE THREAD

**Issue by Nedrapter** [sdenec/tidy5e-sheet#764]
Not sure if it's a bug or a missing feature: Shouldn't the GM be able to edit NPC sheets even when locked? If it's not a bug then is it possible to have NPC sheets unlocked by default? Having to unlocked NPC sheets to just delete active effects or items every time has become tedious... Maybe I'm missing something here, idk.. this definitely feels more work when Tidy Sheets is enabled.

**Comment by p4535992** [comment]
Add some module settings in the "GM Options" for this

**Comment by Nedrapter** [comment]
Do you mean this?
![image](https://github.com/sdenec/tidy5e-sheet/assets/74311190/2a6a004f-2f14-4009-9f7c-0a1c393d2531)
I have it enabled, but it doesn't allow me still.
