### ISSUE TITLE
[BUG]Dragging Spells to Inventory no longer creates spell scrolls

### ISSUE THREAD

**Issue by Avitale34** [sdenec/tidy5e-sheet#765]
It is a minor issue but was super convenient in the past. You could drag a spell into a characters inventory and it would generate a spell scroll of that spell.

**Comment by MythicalRollers** [comment]
This works for me in V10 and V11 dnd5e 2.2.1.  Do you get any errors?

**Comment by mhilbrunner** [comment]
I likewise can't reproduce this with the most current versions of Foundry V11, D&D 5E 2.2.2 and Tidy 5E 0.9.16.
