### ISSUE TITLE
Tidy5e issue with active auras[BUG]

### ISSUE THREAD

**Issue by Dyrnwyrm** [sdenec/tidy5e-sheet#773]
**Module Version:** v0.9.2- v0.9.3

How to replicate the bug:

Enable active auras and dependencies
Enable Tidy5e
Move actor inside and out of the aura
Error will pop up on the screen and on the console

**Describe the bug**
The auras stacks and it fills the console with this error, disabling tidy makes the module active auras works like it should

**Foundry Version:** 
v11.305
**Game System:** 
5e 2.2.2

![Captura](https://github.com/sdenec/tidy5e-sheet/assets/129613553/df979288-a270-46fb-b921-b271adc34dc1)
![imagen_2023-07-16_150914750](https://github.com/sdenec/tidy5e-sheet/assets/129613553/02a3b3fa-e8ac-4c27-b081-fa908ac2664e)

**Comment by szefo09** [comment]
I have no words for what just happened in the last release.

**Comment by p4535992** [comment]
I don't see any error related to tidy and in the list of active modules you showed on the other ticket https://github.com/kandashi/Active-Auras/issues/285 I don't see Tidy5e on the list.

i add some debug message on version 0.9.5 enable the debug module setting and show to me the web console.

**Comment by p4535992** [comment]
K i see i misstype a variable try out 0.9.6 and let me know it if the issue persist.

**Comment by p4535992** [comment]
Forgot  to commit ..... try out 0.9.7

**Comment by Dyrnwyrm** [comment]
No issues here so far, thanks for the fix
