### ISSUE TITLE
[BUG] Hooked function bug

### ISSUE THREAD

**Issue by Dyrnwyrm** [sdenec/tidy5e-sheet#775]
0.9.6-0.9.10

The issue is again on Tidy, i tried to rollback to 0.9.6 but now the issue persist even if the version is different, disabling tidy removes the console errors

**Screenshots**
![image](https://github.com/sdenec/tidy5e-sheet/assets/129613553/698dae4d-2b95-4500-b489-9270c1ede52e)
![image](https://github.com/sdenec/tidy5e-sheet/assets/129613553/13d631dc-209e-4eef-807b-905940e6b5fe)

**Additional context**
Downgrading or deleting the module and reinstalling doesnt work at all

**Comment by p4535992** [comment]
I don't understand why you have this strange problem I have tested and retested it .... I added the forcing in the 0.9.11 version of the control, but if it doesn't work for you even that way I really don't know why it keeps giving you this problem.

**Comment by Dyrnwyrm** [comment]
I dont understand either, and the worst part if that im still getting this error after downgrading

**Comment by p4535992** [comment]
add a orrible try-catch on 0.9.12 try out and let me know it

**Comment by Dyrnwyrm** [comment]
![image](https://github.com/sdenec/tidy5e-sheet/assets/129613553/a460f112-9d67-42c0-bcf6-a3b67ddb024b)

Sadly is not fixed yet

**Comment by p4535992** [comment]
What version of fvtt are you using.... in the bug template i explicitily asking for put the fvtt version , maybe you are still on v10 ?

**Comment by Dyrnwyrm** [comment]
Foundry v11.305
Dnd 5e v2.2.2

**Comment by p4535992** [comment]
Try out 0.9.13

**Comment by Dyrnwyrm** [comment]
There it worked, dunno what was the issue but no errors on console, thanks for all your help

**Comment by p4535992** [comment]
good to know cheers
