### ISSUE TITLE
[BUG] Roll evaluate is deprecated on v11

### ISSUE THREAD

**Issue by Zarhog** [sdenec/tidy5e-sheet#776]
**Module Version:** v0.9.11
The modual is spamming console with this error, how to fix?????
![Screenshot 2023-07-18 144720](https://github.com/sdenec/tidy5e-sheet/assets/76391362/5c39733d-0106-4427-a906-4d2bddc6bce3)

**Comment by M0nk3yy** [comment]
![image](https://github.com/sdenec/tidy5e-sheet/assets/66137312/81054526-8fe4-4174-ab61-6b840d40018a)
