### ISSUE TITLE
Damage Resist/Immune/Vuln Edit Not Functioning

### ISSUE THREAD

**Issue by Phorsayken** [sdenec/tidy5e-sheet#78]
Hello,

As of the most recent update (version 0.2.18), when attempting to edit the Damage Immunities, Damage Resistances, and Damage Vulnerabilities on the PC and NPC sheets, it does not function.  Normally clicking on the edit icon pops up a small window that allows you to modify the contents, this is not happening.

The other entries in the Traits section are still working as normal.

Thank you for your work, the sheets are great.

**Comment by sdenec** [comment]
Hi, there was a dnd5e system update (0.95). Make sure to update that as it changed some things regarding immunitites/vulnerabilities!
