### ISSUE TITLE
[BUG] Tool proficiencies rendering incorrectly.

### ISSUE THREAD

**Issue by ctbritt** [sdenec/tidy5e-sheet#781]
**Module Version:** v0.9.15

**Before open any issue**

1) Enable the module setting _"Enable debugging"_
2) Click F12 go to the _console_ tab 
3) make the test you want and replicate the error
4) Go to the tab console open on point 2) and just right click and click 'Save as' and 'Save' or send a screenshot of the exception on the console.
5) Attach the text file on the github issue with all the logs related tot he module, or send a screenshot of the messages on the console.

![CleanShot 2023-07-24 at 15 29 08@2x](https://github.com/sdenec/tidy5e-sheet/assets/4516034/143548ba-6855-4cc5-8a02-b6f11fa25245)

**Describe the bug**
Tool proficiencies rendering incorrectly.

**To Reproduce**
1. Enable Tidy Sheet
2. open a character sheer
3. view widely rendered tools 

**Expected behavior**
clean tool rendering.

**Screenshots**
![CleanShot 2023-07-24 at 09 47 36@2x](https://github.com/sdenec/tidy5e-sheet/assets/4516034/0aaab08e-cd63-4ef6-9307-378422249acb)

**Browser:**
Chromium engine - 115.0.5790.98

**Foundry Version:** 
11.306
**Game System:** 
DnD5e 2.2.2.

**Comment by p4535992** [comment]
ty for the info i will checkout

**Comment by mhilbrunner** [comment]
Can reproduce on the latest version (on latest DND5E and Foundry v11 as well), just by adding tool profs on any PC actor.

**Comment by mhilbrunner** [comment]
Submitted a fix in https://github.com/sdenec/tidy5e-sheet/pull/786.
