### ISSUE TITLE
Request: Option to Favorite by Type

### ISSUE THREAD

**Issue by shinkei13** [sdenec/tidy5e-sheet#79]
If possible, I'd like to request the ability to favorite by item/spell type. For example: when playing, I will always favorite any equipped weapons, so that I can easily have my attacks ready. If I could favorite all weapons, I wouldn't need to track and manually favorite whatever I pick up (much like how D&D Beyond has it's Attack/Actions section). The same goes for any prepared spells or cantrips.

I feel like this would add great compatibility with modules that frequently change your items or spells, like VTTA-Beyond or Pick-Up-Stix.

**Comment by sdenec** [comment]
Well, first of I  didn't wrote the fav-mod. It's more or less a conversion from Felix's Favorites Tab, so making extensive changes isn't exactly my cup of tea^^ Secondly - you  have all your weapons one click away - in the inventory tab and every weapon get's added there! So I feel it would kind of defeat the purpose of favorites. Also I don't think it's unbearable to click one icon on a newly picked up item to move it to the fav tab. Long story short - I don't think I will change the current fav system, from a technical or practical viewpoint - sorry!
