### ISSUE TITLE
[BUG] "fonts" directory not included in 

### ISSUE THREAD

**Issue by Javalar** [sdenec/tidy5e-sheet#805]
**Module Version:** v0.10.0

`styles/tidy-icons.css` refers to files in path `fonts`. This path and the corresponding files can indeed be found in the repository under `src/fonts`, but these are nowhere to be found when the module is installed in Foundry. In fact, opening the `module.zip` file from the release page reveals that the files are missing.

This does not seem to be causing any problems with the sheet. But if you have the `Custom Fonts` and `Dice So Nice` modules installed, and you enable Dice So Nice integration in Custom Fonts, it does show an annoying warning.

**Comment by kgar** [comment]
The Tidy rewrite is almost complete and will take over the Foundry package as version 1.0.
The new version is here: https://github.com/kgar/foundry-vtt-tidy-5e-sheets
You can currently pull down the beta via direct URL installation. Also, it will appear as Tidy 5e Sheets version 1.0 on Foundry in another week or so, replacing the original.

If this problem persists in the new version, can you forward this issue to the rewrite's repo and close here?

**Comment by Javalar** [comment]
Seems very unlikely that the problem is also in the new version. Will simply close for now.
