### ISSUE TITLE
[BUG] Vehicle Sheet does not have an effects tab

### ISSUE THREAD

**Issue by XXDarrienX** [sdenec/tidy5e-sheet#807]
**Module Version:** v0.10.0

**Describe the bug**
The tidy Vehicle sheet in 5E does not have a Effects tab, it is for the default 5E Vehicle Sheet

**To Reproduce**
1. Create a Vehicle actor
2. No Effects Tab
3. Switch to Default 5E Vehicle Sheet and you have an effects tab

**Expected behavior**
The Effects tab should be visible

**Screenshots**

**Browser:**
 - Opera GX but I am not loading Foundry in the browser, I am running the application locally.

**Foundry Version:**  11.315

**Game System:** DND 5E

![image](https://github.com/sdenec/tidy5e-sheet/assets/28017703/5c7c64bd-5733-4ee1-bbfb-16c68e6f7c44)
![image](https://github.com/sdenec/tidy5e-sheet/assets/28017703/d159b635-7350-4920-91c5-310419a3a736)

**Comment by kgar** [comment]
This has been corrected in Tidy rewrite.
The new version is here: https://github.com/kgar/foundry-vtt-tidy-5e-sheets
You can currently pull down the beta via direct URL installation. Also, it will appear as Tidy 5e Sheets version 1.0 on Foundry in another week or so, replacing the original.

If you have any additional issues or if this one is not fully resovled, please feel free to issue them to the rewrite's repo.

**Comment by XXDarrienX** [comment]
Alright thanks for that
