### ISSUE TITLE
Charges not saving properly

### ISSUE THREAD

**Issue by Avitale34** [sdenec/tidy5e-sheet#83]
If you update the number charges on the character sheet using the quick way in the column next to the item it does not save. You have to go all the way into details to get the charges to change properly.

![Usage Error](https://user-images.githubusercontent.com/65961637/91481230-138aca00-e872-11ea-9605-5d671256cef8.png)

**Comment by sdenec** [comment]
Thanks for the bug report. Should be fixed now!
