### ISSUE TITLE
Allow selection of the standard 5e item sheet and styles

### ISSUE THREAD

**Issue by akrigline** [sdenec/tidy5e-sheet#88]
It seems that installing and activating the Tidy5e Sheet module changes the 5e Item sheet without any way for the GM to select the normal item sheet (or any other item sheet). 

To piggyback off of this, all of the styles in `tidy5e-items.css` are applied globally rather than restricted to a module-specific scope.

It would be more bulletproof and would prevent module conflicts if Tidy5e would register a new Item sheet and restrict its style changes to only be within that sheet.

**Comment by sdenec** [comment]
This is a great comment and totally justified. Big thanks for your code contribution! You have missed the darkmode item stylesheet but that was a quick adjustement. I'll implement this imediately!

**Comment by sdenec** [comment]
I'm going to mark this issue as resolved :)
