### ISSUE TITLE
Manual skills modifiers for NPCs

### ISSUE THREAD

**Issue by konstantin-kiriushyn** [sdenec/tidy5e-sheet#93]
Some NPCs can have a bigger skills modifiers than Ability + Proficiency combination. 
Would be great we have a way to edit skills manually

**Comment by sdenec** [comment]
You can use the module https://github.com/schultzcole/FVTT-Skill-Customization-5e to modify skills for pcs and npc beyond what the base 5e system offers and add custom modifiers! I hope that's what you are searching for :)

**Comment by sdenec** [comment]
closing this issue as resolved :)
