### ISSUE TITLE
Better Rolls tab not supported by new item sheets

### ISSUE THREAD

**Issue by joshjlewis93** [sdenec/tidy5e-sheet#94]
Writing this in both modules just in case:

The Better Rolls tab and other functions no longer appear on the new Tidy5e item sheets as of the latest update, presumably because it is its own item sheet now where BR was modifying the default item sheet only (you can still see the tab if you swap back to the default). 

Edit: Relevant comment from RedReign if it helps - "it is possible to add your own hooks to support your own individual sheet. If a sheet wants to support Better Rolls it can do so using the hooks in scripts/hooks.js"

**Comment by joshjlewis93** [comment]
Also relevant to this, the Magic Items module does not appear either.

**Comment by akrigline** [comment]
Taking a look, I caused this so I'll see if I can fix it.

**Comment by sdenec** [comment]
Thanks akrigline, your commit seems to have solved this! Update Tidy5e to 0.2.22 to get the better rolls tab back :)
